### ISSUE TITLE
PCDM shows '(disconnected)' long after connection of a PersonaCrypt device, and '(ok)' long after disconnection

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#105]
1. Have one PersonaCrypt device
2. start one notebook with the device connected
3. start a second notebook
4. log out from the first
5. disconnect the device
6. connect the device to the second notebook.

**Expected**
- Where the PersonaCrypt device is disconnected, PCDM should no longer say _(OK)_ **and**
- where the device is connected, PCDM should no longer say _(disconnected)_.

**Actual result**
- At both machines, PCDM appears outdated
- where the device is connected, the user can ignore the outdated appearance; it _is OK_ to log in.

**Workaround**

Refresh PCDM. 

Please note that a refresh of the list of users (the green clockwise arrow in that part of PCDM) does _not_ workaround the bug.

**Comment by pkgdemon** [comment]
Just an update I took the time to confirm this behavior.  @beanpole135 asked me to assign his to him last week.
