### ISSUE TITLE
Where PCDM uses the phrase 'OK' it should be uppercase (not ok)

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#106]
Observed whilst reporting #105

For example: if a PersonaCrypt device is connected before a start of TrueOS Desktop, then PCDM will show, alongside the name of the user of the device: 

> ' (ok)'

Grammatically it's probably better to use uppercase, _OK_

**Comment by grahamperrin** [comment]
AFAIR the wording has changed. Maybe _(ready)_ 

Thanks

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/pcdm/commit/45324e4dc01a0291710990ef63c464cdbc5b55f8
