### ISSUE TITLE
SysAdm: AppCafe: 'Uninstall Selected Packages' applies to items that are checked/ticked, not to the selected package

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#108]
1. check boxes for two or more packages
2. select a package that is not checked
3. point at the trash icon
4. observe the hint, Uninstall Selected Packages
5. click

![uninstall selected packages](https://cloud.githubusercontent.com/assets/192271/19416020/c7f25426-937c-11e6-9e48-642110720fc3.png)

**Expected**

If the hint is believed: uninstallation of the selected package.

**Actual result**

The selected package remains installed: 

![still selected still installed](https://cloud.githubusercontent.com/assets/192271/19416021/ceca221a-937c-11e6-91c0-cac804abd026.png)

**Suggested resolution**

A change of wording to the hint. 

Plain English, I should probably use: 
- neither _selected_ nor _checked_
- _ticked_

**Comment by beanpole135** [comment]
Done!

https://github.com/trueos/sysadm-ui-qt/commit/936de3dbad925246667ede8d8b6dd7d161bfde0b
