### ISSUE TITLE
 Finished installation fails to present menu of options with TrueOS-Desktop-12.0-CURRENT-08-01-2016-x64-USB.img on Intel GM45

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#11]
**From IRC**

2016-08-02 22:36:25`<grahamperrin>`	Ergo Vista 621 with AUGUST: installation reportedly completed but when I click 'Finish', there's a quarter screen of red followed by a quarter screen of blue and failure to present the menu of options. Photograph added to https://goo.gl/photos/K85oQAkXEb8U1xvp9
2016-08-02 22:36:48`*	grahamperrin` presses the power button

**Comment by grahamperrin** [comment]
As far as I call the red quarter-screen remained after I pressed the power button. 

After a while, I pressed and held the power button to force a stop.

**Comment by pkgdemon** [comment]
So just to confirm it looks like this one is using EFI boot?

**Comment by grahamperrin** [comment]
Confirmed, UEFI is not an option on this circa 2007 notebook.

**Comment by grahamperrin** [comment]
From https://goo.gl/photos/K85oQAkXEb8U1xvp9 here's the relevant photograph: 

![img_20160802_223338](https://cloud.githubusercontent.com/assets/192271/17464602/6aa27d4c-5cda-11e6-8154-a709ad2c7559.jpg)

**Comment by pkgdemon** [comment]
Can you try the "Legacy Intel" option in the installer to see if it makes a difference?

**Comment by grahamperrin** [comment]
There's an unexpected restart (a kernel panic, I guess) before the suggested option can appear. 

TrueOS-Desktop-2016-08-31-x64-USB.img

**Comment by pkgdemon** [comment]
We have received confirmation that older chipsets pre SB are known not to be supported by drm-next-4.7. The reason given is "the AGP bits need to be updated to sync up with DRM changes". For an ETA "it's just not that big a priority compared to making SB+ work reasonably well".
