### ISSUE TITLE
GELI BTX Halted

### ISSUE THREAD

**Issue by ppumkin** [trueos/trueos-core#110]
Fresh Install using USB Install Image.
Boot from USB on Dell Latitude E6220 
Used entire disk for a single ZFS Volume
No other Logging or anything enabled. All Default
Enable GELI during setup.

Run Setup......
Reboot.. Reboot... nope. need to power cycle :(

OK Rebooting.
Asks for Geli passphrase. I input my passphrase

CRASH. Please view screenshot. I have no idea what that means.

![Imgur](http://i.imgur.com/fqcEpZu.jpg)

**Comment by kmoore134** [comment]
Ok, looks like this is a known bug in FreeBSD that is being worked on: 
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213491

Keep and eye on it over there, once its fixed we'll be grabbing that change as well.
