### ISSUE TITLE
Shutdown hangs

### ISSUE THREAD

**Issue by ppumkin** [trueos/trueos-core#112]
Since installing TrueOS from the first time today. When I got to the reboot stage, my Dell E6220 just hangs after Uptime. It will not reboot.

Doing the same, Restart from Lumina, it does a few things and then hangs again.

![Imgur](http://i.imgur.com/QNy5o2Zh.jpg)

Pressing the power button, or using Shutdown command to shut down , works fine.

Sorry I do not know how to provide you with more information?

**Comment by kmoore134** [comment]
The X1 carbon has a similar issue with ACPI, it'll shutdown but not "reboot" properly, without hitting the power-button. Its an issue with upstream FreeBSD right now, so I would recommend opening a ticket up here with your hardware information: https://bugs.freebsd.org/bugzilla/

**Comment by ppumkin** [comment]
Thanks, to follow up the bug is here.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213654
