### ISSUE TITLE
Intel WiFi hangs

### ISSUE THREAD

**Issue by ppumkin** [trueos/trueos-core#113]
OK SO i had a Broacom WiFi installed during install and post install. It didnt show up anywhere to be configured. So I went rumaging and found a 

Intel WiFi Link 4965AGN (Originally slapped with an HP spare part junk sticker) Its Intel.. Its gonna work.

After install, boot and then this?? :(

![Imgur](http://i.imgur.com/9caStAPh.jpg)

Sorry guys.. but its been nearly 2 hours I have been trying to get WiFi to work... I mean, just follow the trail of bug reports ;(

PS Before you blame my hardware... all these WiFi MiniPCIe work under Winblows laptops I am swapping them out with.
PSS Seems like a very older and rarer Intel 5121AN seems to be working... finallllly

PSSS I put the 4965AGN back in the same slot as the 5121AN to make sure it was not a dodgey connection or whatever.. **and it was a dogey connection**

Sorry :( Can be closed was getting really upset.

And then finally after closing up the laptop.. it failed again with error 22, could not configure device, reading firmware setting failed, failed to set RX.. etc etc. Not sure? Works on Windows machine. I reverted to the slightly older Intel WiFi.

**Comment by kmoore134** [comment]
Ok, thanks for the update on this! I'll close it out :)

**Comment by ppumkin** [comment]
Just updated the bug ticket name to include 4965AGN in the title.
Is this a supported WiFi in BSD? I was still having problem with it but now using the 5100 series, working really smooth.

**Comment by kmoore134** [comment]
Yea, the manpage for the "iwn" driver shows  that it supports "Intel Centrino Wireless-N 4965". Glad the other one is working though!
