### ISSUE TITLE
GTK Applications Have Text Corruption

### ISSUE THREAD

**Issue by nomadlogic** [trueos/trueos-core#115]
```

$ uname -ar
FreeBSD boomers.nomadlogic.org 12.0-CURRENT FreeBSD 12.0-CURRENT #12 8b8c812(drm-next-4.7): Wed Oct  5 19:36:49 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
$ sysctl hw.model
hw.model: Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz

```

Xorg.conf device section:
```
Section "Device"
        Identifier      "Card0"
        Driver          "modesetting"
        Option          "SWcursor" "on"
EndSection

```
I am noticing that GTK dialogs and applications are suffering from font rendering corruption.  For example, all text in thunderbird is unreadable as per the attached image.  I am not seeing anything relevant in Xorg.0.log or other files, so please let me know if you all need additional information or would like me to test anything.

**Comment by nomadlogic** [comment]
![screenshot-2016 10 22-10 30 47](https://cloud.githubusercontent.com/assets/8356819/19621262/e4f45bee-9842-11e6-8d81-af537483ebbf.png)

**Comment by grahamperrin** [comment]
Corresponding chat: https://gitter.im/trueos/lumina?at=580c6462278cc54c6f5e6ce7

**Comment by nomadlogic** [comment]
Just spoke with Matt Macy regarding this.  It is a known issue with Glamor+modesetting on the i915kms/linuxkpi work.  I'll close this issue and re-test when his branch is updated and ready for more testing.

For posterity - the fix is to run the intel Xorg driver, which actually does full GPU acceleration and may provide better perf in X.
