### ISSUE TITLE
sysutils/firstboot-growfs

### ISSUE THREAD

**Issue by pkgdemon** [trueos/trueos-core#1153]

**Comment by ZackaryWelch** [comment]
https://github.com/trueos/freebsd-ports/commit/0999871859cc52677afdda28aadad48d8507e014
Might not work. As with the other firstboots, has no command, is not a daemon.

**Comment by ZackaryWelch** [comment]
Firstboot not an OpenRC keyword. Not a proper OpenRC script.
https://github.com/trueos/freebsd-ports/commit/69034b3753211d72db5c43a8ce8ed0e9a6ed888a
