### ISSUE TITLE
There are no localisations option  for specific country settings for the English language

### ISSUE THREAD

**Issue by Mystified1234** [trueos/trueos-core#116]
I'm from down under. 
Under localisation, there is no option for "en_au.utf-8" Nor is there options for other English speaking countries other than UK, USA & south Africa. 
Is there likely to be a fix in the near future or is there a work around, by using an editor .

Thanks, 
Mystified.

Ps. love the work you guys are doing !

Kris suggested I post this here !
https://discourse.trueos.org/t/localisations-option-does-not-allow-for-specific-country-settings-in-english-language/73
Most likely it's just that nobody has specifically requested it before :slight_smile:
Go ahead and open a ticket and we'll get it added in the near future.

**Comment by RodMyers** [comment]
still a valid ticket

**Comment by Mrt134** [comment]
Confirmed still valid.

**Comment by ZackaryWelch** [comment]
Translation files for en_AU are being added.
