### ISSUE TITLE
sysutils/firstboot-freebsd-update

### ISSUE THREAD

**Issue by pkgdemon** [trueos/trueos-core#1188]

**Comment by ZackaryWelch** [comment]
https://github.com/trueos/freebsd-ports/commit/abad17ad106b1870defe458dbf380c7df238861c
Might not work. Less of an OpenRC service and more of a shellscript.

**Comment by ZackaryWelch** [comment]
Firstboot not an OpenRC keyword. Not a proper OpenRC script.
https://github.com/trueos/freebsd-ports/commit/69034b3753211d72db5c43a8ce8ed0e9a6ed888a
