### ISSUE TITLE
Boot to console (Disable X) no longer an option

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#12]
http://web.pcbsd.org/doc/11/html/introduction.html states: 

> The “Boot to console (Disable X)” option has been added to the graphical boot menu.

No such option with the TrueOS-branded BSD loader that was installed by TrueOS-Desktop-12.0-CURRENT-08-01-2016-x64-USB.img

**Comment by dlavigne** [comment]
That is the wrong Handbook to be showing on that website (it should be the 10.3 static HTML). It is also the wrong handbook to be showing on the upcoming TrueOS website (which should be pulling the correct src from trueos/trueos-docs). In either case, the doc src is correct for 10.3, it is also correct for 12.0 (does not show this option), it is the website that is pulling the wrong HTML. Reassigning to Josh so websites can be corrected.

**Comment by grahamperrin** [comment]
Thanks, will TrueOS Desktop never gain the option to boot to console?

**Comment by pkgdemon** [comment]
Technically we do have the option to boot to console if you press 3 for single user mode.

**Comment by grahamperrin** [comment]
I'm familiar with single user mode from Mac OS X. 

I tried it a few weeks ago with TrueOS Desktop; it's **no substitute** for  boot to console.

**Comment by pkgdemon** [comment]
Can you elaborate further with a particular use case?

**Comment by grahamperrin** [comment]
Let's assume that at some point in the future, X will not work (or not work properly) with someone's hardware. In such cases: 

- boot to console may be relatively user-friendly
- single user mode may be relatively less friendly (requirement to mount multiple file systems, start networking and so on). 

A more personal example, which does not involve troubleshooting: 

1. boot to console
2. pc-updatemanager pkgcheck

– and so on; sometimes it's simply quicker and convenient to not use X.

**Comment by pkgdemon** [comment]
Good points.  I think we should certainly consider this.

**Comment by grahamperrin** [comment]
Food for thought: the `>console` user approach that was or is possible [with some installations of Mac OS X](http://apple.stackexchange.com/q/119027/8546). So for TrueOS Desktop there may be a notion of `console` in the list (maybe first or last) of users  …

… although that alone would be not good if PCDM is bugged in some way. So I still prefer the idea of offering 'to console' _at boot time_.

**Comment by dlavigne** [comment]
How did you get to the webpage in the first place? eg was it linked anywhere on the website or did you happen to stumble across it?

Josh, you can safely remove the /doc/11/ dir as it will never get used. The /doc/10 directory is correct and referred to on the website.

**Comment by grahamperrin** [comment]
@dlavigne probably found with Google; I often use it to find what can't be found with the search that's integral to the guides. 

https://www.google.co.uk/search?q=%22boot+to+console%22+site%3Aweb.pcbsd.org

**Comment by kmoore134** [comment]
FreeBSD is currently working to add a "Boot to Console" option for the Beastie menu. I'm going to close this, because the plan is to just use theirs when it lands.

**Comment by uweiner** [comment]
Well, its TrueOS 18.03 now. Can you tell how to boot to Console? I have a problem updating the X system with vmware driviers while X is running.
I tried to stop the PCDM service, by 'sudo rc-service PCDM stop'. it says it is stoppoing, but in actuallyity, it doesn't.
