### ISSUE TITLE
Menus may be invisible within the pre-PCDM display wizard

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#120]
Before log on to a desktop envirionment, 

`sudo touch /var/.runxsetup`

– then refresh PCDM and click to present any menu. 

**Expected**

A visible menu. 

**Actual result**

An invisible menu. Educated guesses may allow the user to click the required invisible menu item :-)

**Environment**

HP EliteBook 850 G2 notebook, Intel driver for graphics, using an external display. 

**Cross reference**

https://discourse.trueos.org/t/display-settings-wizard-how-to-make-it-show-up/128/2?u=grahamperrin

> If you're unlucky, …

**Comment by grahamperrin** [comment]
From what I have seen with the Intel driver on this hardware _after_ log in to desktop environments, I wonder whether it will be safer to default to modesetting for the _Display Settings_ GUI of `pc-xgui`.

----

From the linked topic: 

> If a menu does not appear, click where you imagine the required item to be.

There's an alternative workaround that requires less imagination. If you know the first few letters of the menu item: when the menu is invisible, rapidly blindly type the first few letters of the item, then blindly key Return/Enter. 

Also: to have the content of the window drawn or refreshed, shake the window.

**Comment by grahamperrin** [comment]
> to have the content of the window drawn or refreshed, shake the window.

When I last encountered this bug, that workaround was **not** effective. 

The broken GUI for what's normally a post-installation wizard did not feel wizardly ;-)

**Comment by pkgdemon** [comment]
The display wizard will remove /etc/X11/xorg.conf.  This is a problem for 2 reasons.

**1**
For intel video most or parts of the screen windows may be un-viewable when 3d acceleration is enabled.

**2**
Nvidia requires a preconfigured xorg or X will not even come up.

True autodetect is not an option right now until the above issues can be resolved.  Since this tool relies on autodetect before it can provide the selection I see it as essentially worthless for those two use cases.  It would be better to copy the relevant file from ```/usr/local/share/trueos/cardDetect``` to ```/etc/X11/xorg.conf``` to try a different driver until the above issues can be resolved.

**Comment by pkgdemon** [comment]
I am marking 3rd party to resolve in reference to number 1 at minimum which would have to be resolved before we can pursue a fix.

**Comment by grahamperrin** [comment]
Thanks. (I imagined that KMS would be good for the 'essence' of the wizard (its GUI at times when not testing whatever is selected by the user), didn't realise that KMS could be unreliable for Intel and Nvidia.)

**Comment by pkgdemon** [comment]
We do this.  

https://github.com/trueos/trueos-core/blob/master/overlays/install-overlay/etc/trueos-video.sh

The during install we copy xorg.conf to the installed system.  The display wizard removes those fixes.  Ultimatley it would be nice just to startx with no xorg as linux does.  That is kind of what I was refferring to.  When that works we would not have issues 1, and 2 which cause the graphical display wizard to break a system.

**Comment by grahamperrin** [comment]
As a partial fix/enhancement, would it be more reliable to use VESA for the periods when the wizard is inviting the user to select things?
