### ISSUE TITLE
WPA2-PSK network is identified as WEP

### ISSUE THREAD

**Issue by wblock** [trueos/trueos-core#121]
When the installer asked for my PSK, it identified the network as WEP rather than WPA.

**Comment by grahamperrin** [comment]
https://github.com/trueos/trueos-core/issues/69

**Comment by grahamperrin** [comment]
This issue is described as _odd_ in the review that's linked from https://discourse.trueos.org/t/-/182/9?u=grahamperrin

**Comment by RodMyers** [comment]
are you still having this issue?

was given the task of looking over older issues

thanks
