### ISSUE TITLE
Installer modifies bootcode when installed in unused part of Windows UEFI disk

### ISSUE THREAD

**Issue by wblock** [trueos/trueos-core#122]
Installing TrueOS-497 into the unused space on a Windows UEFI disk and leaving the boot loader option at the default of "BSD" does not give the user any way to boot back into the Windows install.

This needs to be explained on that screen.  Better yet if it would detect a multiboot installation and set it up.  Recovering from this situation to a plain Windows-only boot should also be documented.

**Comment by mheily** [comment]
I had a different experience when installing into unused space with an existing Windows UEFI partition. The installer did not appear overwrite the Windows boot loader, so I was unable to boot into TrueOS. The machine continued to boot into Windows after TrueOS was installed.

**Comment by RodMyers** [comment]
@wblock can I assume, with the latest release, and the using of rEFInd Boot Manager, that this has become a non-issue?

**Comment by wblock** [comment]
I don't know, have not tested this lately.  In any case, I've started to wonder if this is a security feature in Dell's UEFI implementation.  If you delete and recreate a partition, the boot settings referring to the old one don't work on the new one.  But recreate the same boot entry in the Dell setup, and it works again.

**Comment by RodMyers** [comment]
i'm going to close this, since we rEFInd. if it is still an issue, it can always be reopened
