### ISSUE TITLE
HTML5 AV playback neither audible nor visible in some browsers for some user accounts

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#123]
Spun off from discussion at https://discourse.trueos.org/t/125

https://www.youtube.com/watch?v=aoHX2AyWj2Q for example: 

- is problematic in Chromium and Firefox for UIDs 1001 (an operator account that I rarely use) and 1003 (a non-operator account that I created after opening this issue)
- is **not** a problem in Chromium, Firefox, Qupzilla or Web 3.16.3 for UID 1002 (an operator and a PersonaCrypt user)
- is **not** a problem in Qupzilla or Konqueror for UID 1001. 

![uid 1003](https://cloud.githubusercontent.com/assets/192271/19878528/88959bc8-9fe1-11e6-97e0-b60943045dd8.png)

Maybe worth mentioning: with initial use of Konqueror at the given YouTube page, if each security-related issue is dismissed for one session only, then playback becomes audible and visible whilst the user continues to dismiss multiple issues. 

All tests were performed with Lumina.

**Comment by RodMyers** [comment]
affected by this as well

**Comment by pkgdemon** [comment]
We imported a fix to force pulse to use the correct sound output FreeBSD uses.

https://github.com/trueos/freebsd-ports/commit/0fc977557b776db4de8462de8d0886a062a0bd21

Please let me know if this persists with the edge packages for new users, and I will reopen.

**Comment by grahamperrin** [comment]
> **HTML5 AV playback neither audible nor visible …**

That pair of symptoms continued to bug Firefox, frequently, but I chose to not reopen this bug because my test environments are pleasantly messy (to catch other things in the wild). Within that mess, https://gitter.im/trueos/Lobby?at=58471a5803554185047a7485 (2016-12-06, Firefox 50.0 on TrueOS Desktop UNSTABLE) was memorable for its relative cleanliness: 

> No better with a new profile for Firefox.

From this morning's https://gitter.im/trueos/troubleshooting?at=5856763296a565f84405d52b, with additional emphasis: 

> _AFAIR_ the workaround involved opening an affected page in a separate instance of Firefox, using **KDE Volume Control** to do something basic that was not possible with PulseAudio Volume Control, closing the second instance and now I can playback in the first instance of Firefox. 
> 
> Time to restart Firefox and tell whether the workaround is persistent.

Success, touch wood :+1: 

----

If anyone else reports comparable symptoms, I can treat this morning's scribble as a point of reference and then take a more methodical approach to understanding the problem.
