### ISSUE TITLE
I am not a number, I am a free man …

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#124]
… unless I am created and named with SysAdm in TrueOS Desktop with the set of updates that was pushed on 2016-10-28. I and my group are prisoner _1003_. 

```
$ sudo su
Password:
[root@momh167-gjp4-hpelitebook850g2-trueos] /usr/home/gjp4# whoami
root
[root@momh167-gjp4-hpelitebook850g2-trueos] /usr/home/gjp4# cd /usr/home
[root@momh167-gjp4-hpelitebook850g2-trueos] /usr/home# ls -l
total 33
drwxr-xr-x  25 bbsadmin-l  bbsadmin-l   54  1 Nov 02:30 bbsadmin-l
drwxr-xr-x  75 gjp4        gjp4        127  1 Nov 02:43 gjp4
drwxr-xr-x  19 1003        1003         43  1 Nov 02:37 test
[root@momh167-gjp4-hpelitebook850g2-trueos] /usr/home# ls -ln
total 33
drwxr-xr-x  25 1001  1001   54  1 Nov 02:30 bbsadmin-l
drwxr-xr-x  75 1002  1002  127  1 Nov 02:43 gjp4
drwxr-xr-x  19 1003  1003   43  1 Nov 02:37 test
[root@momh167-gjp4-hpelitebook850g2-trueos] exit
exit
$ date ; uptime ; freebsd-version ; uname -a
Tue  1 Nov 2016 02:54:29 GMT
 2:54a.m.  up 15 mins, 2 users, load averages: 1.12, 0.86, 0.49
12.0-CURRENT
FreeBSD momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #14 1717ae3(drm-next-4.7): Fri Oct 28 13:49:49 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
$ 
```

**Comment by beanpole135** [comment]
While I enjoy the reference to the "Prisoner" TV show, there is not really a problem here. The UID for the "test" user was automatically assigned to 1003 since UID's 1001 and 1002 were already taken by the bbsadmin-1 and gjp4 users. The reason the "human readable" owner/group returns 1003 is because your shell caches the user/group data when it starts up and it did not refresh that cache after you changed the user database on the system with SysAdm. Once you close that shell session and/or launch a different one, it will show the owner/group as "test" for you again.

**Comment by grahamperrin** [comment]
> … Once you close that shell session and/or launch a different one, it will show the owner/group as "test" for you again.

Nope, the system has been restarted twice and still I see: 

```
$ ls -l /usr/home
total 65
drwxr-xr-x  25 bbsadmin-l  bbsadmin-l   54  1 Nov 02:30 bbsadmin-l
drwxr-xr-x  75 gjp4        gjp4        127  1 Nov 17:42 gjp4
drwxr-xr-x  19 1003        1003         43  1 Nov 02:37 test
$ 
```

A SysAdm view of users shows only two (not the third user, which I named _test_). At the time of creation of that user I was bugged by the 'non-Standard DPI' issue, my workaround for which was preferring a different boot environment, almost certainly an earlier BE. 

With my limited understanding of the scope of BEs, I half-expect a user account created with the most recent BE to be available when booting an earlier environment. True or false?

**Comment by kithrup** [comment]
False.  BEs are fairly self-contained for configuration information, and that includes local users and groups.  Configuration changes made to one BE will not show up in any other boot environments unless a new one is created from said BE.

**Comment by grahamperrin** [comment]
Thanks for the clarification. Two learning points from an invalid bug report (works as expected)!
