### ISSUE TITLE
sysadm-client sometimes makes excessive use of memory, risk of bringing the OS to a halt

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#126]
This bugged me on various occasions and I'd like to make it reproducible for you but Murphy's Law, the hardware that I normally use for FreeNAS died a few days ago. On at least one occasion, all attempts to kill the client failed and so it was necessary to force off the computer (press and hold the power button). 

I have a hunch that the client becomes hungry in some Life Preserver replication failure situations. 

### 2016-10-18 21:41, hungry sysadm-client

![2016-10-18 21-41 hungry sysadm-client](https://cloud.githubusercontent.com/assets/192271/19902581/431d4e24-a063-11e6-8541-90eababe7faf.png)

### The client as it _probably_ was before the hunger was observed

![2016-10-18 21-44 the client as it probably was](https://cloud.githubusercontent.com/assets/192271/19902587/49a21d10-a063-11e6-8c73-c3913b93d565.png)

### 2016-10-19 05:36, around ten minutes after boot

![2016-10-19 05-36 around ten minutes after boot](https://cloud.githubusercontent.com/assets/192271/19902593/4e621cec-a063-11e6-8c6a-19b26692e673.png)

### 2016-10-19 05:41, around fifteen minutes after boot

![2016-10-19 05-41 around fifteen minutes after boot](https://cloud.githubusercontent.com/assets/192271/19902598/52a2c9f0-a063-11e6-9203-0819ceda8a1e.png)

### 2016-10-19 around 07:51

![2016-10-19 07-51 sysadm-client](https://cloud.githubusercontent.com/assets/192271/19902601/565d68ca-a063-11e6-8fec-6fac134541fd.png)

### 2016-10-22 14:48, nearly all swap space used

![2016-10-22 14-49 nearly all swap space used](https://cloud.githubusercontent.com/assets/192271/19902613/5bb84a1a-a063-11e6-93c3-1a295a572fa3.png)

### 2016-10-22 around 14:50, processes

![2016-10-22 14-50 processes](https://cloud.githubusercontent.com/assets/192271/19902618/60a97c74-a063-11e6-92a4-ce0b2d7c464a.png)

### 2016-10-22 around 14:50

![2016-10-22 14-50 sysadm-client](https://cloud.githubusercontent.com/assets/192271/19902622/649aea66-a063-11e6-95b9-750aebd8f4e3.png)

### 2016-10-22 around 14:52, after using System Monitor to kill the client

AFAIR other approaches to killing, probably with htop, did not succeed. 

![2016-10-22 14-52 client would not close killed by system monitor](https://cloud.githubusercontent.com/assets/192271/19902626/67d430f2-a063-11e6-8389-fb4e927d48a4.png)

### 2016-10-22 around 14:57, a view of Life Preserver schedules

![2016-10-22 14-57 life preserver schedules](https://cloud.githubusercontent.com/assets/192271/19902633/6b0b62a4-a063-11e6-96d3-eade745360d1.png)

**Comment by grahamperrin** [comment]
Above: > … I'd like to make it reproducible for you but Murphy's Law, the hardware that I normally use for FreeNAS died … a hunch that the client becomes hungry in some Life Preserver replication failure situations. …

I removed the one and only replication schedule after that failure of the NAS. 

The hogging persists, so it's probably safe to ignore my first hunch and instead, revisit the notion from #128: 

> … message presentation issue might somehow contribute to the memory-hogging aspect of #126, …

Yesterday (2016-11-05) at 01:01: 

![sysadm-client 3.7 GB memory after 01:00 whilst presenting outdated messages](https://cloud.githubusercontent.com/assets/192271/20036730/44d36bb0-a408-11e6-85a8-eb11ef7191dc.png)

![no replication tasks hourly snapshots](https://cloud.githubusercontent.com/assets/192271/20036745/c5d51844-a408-11e6-9a5e-767d6873dc5d.png)

15:16, 1.5 GB virtual memory used by the client: 

![sysadm-client 1.5 GB virtual memory](https://cloud.githubusercontent.com/assets/192271/20036768/3b86c948-a409-11e6-93f5-a92eb3080a55.png)

Today: 

```
$ last | less
gjp4       pts/1    :0                     Sun  6 Nov 09:49   still logged in
gjp4       pts/0    :0                     Sat  5 Nov 15:33   still logged in
boot time                                  Sat  5 Nov 15:23
shutdown time                              Sat  5 Nov 15:21
gjp4       pts/0    :0                     Sat  5 Nov 15:21 - 15:21  (00:00)
gjp4       pts/1    :0                     Sat  5 Nov 15:02 - 15:17  (00:15)
gjp4       pts/1    :0                     Sat  5 Nov 14:58 - 15:01  (00:02)
gjp4       pts/0    :0                     Sat  5 Nov 14:44 - 15:17  (00:33)
gjp4       pts/0    :0                     Sat  5 Nov 14:06 - 14:43  (00:36)
boot time                                  Sat  5 Nov 14:03
```

– after leaving the machine overnight (I left the house around 19:00), this morning I arrived home and found the client using … AFAIR either more than 9 GB or more than 11 GB virtual memory.

**Comment by grahamperrin** [comment]
(This issue is probably ready for reassignment to a developer; read alongside https://github.com/trueos/trueos-core/issues/128#issuecomment-258767269 where the problem may be reproducible with multiple desktop environments.)

**Comment by grahamperrin** [comment]
## Reproducibility

I started the OS and used: 

- Lumina alone. 

Half-expecting leaps in usage of memory at hourly intervals, shortly after 21:00 I observed a leap. 

Around twenty minutes later, no remarkable increase (below) but I half-expect leaps to continue. I'll review usage after 22:00 and/or maybe tomorrow morning. 

```
$ date ; freebsd-version ; uname -a ; htop
Sat 12 Nov 2016 21:22:43 GMT
12.0-CURRENT
FreeBSD momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #14 1717ae3(drm-next-4.7): Fri Oct 28 13:49:49 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64










  1  [                                                    0.0%]   Tasks: 92, 0 thr; 3 running
  2  [                                                    0.0%]   Load average: 0.44 0.55 0.60 
  3  [                                                    0.0%]   Uptime: 00:33:35
  4  [                                                    0.0%]
  Mem[||||||||||||||                               2.95G/15.8G]
  Swp[                                                0K/8.00G]

  PID USER      PRI  NI  VIRT   RES S CPU% MEM%   TIME+  Command
 2509 gjp4       83   0 2722M 2230M R 45.7 13.8 17:49.42 /usr/local/bin/firefox
 1716 gjp4       30  10 1494M  979M S  0.0  6.1  1:20.25 /usr/local/bin/sysadm-client
 1654 gjp4       20   0  789M  190M S  0.1  1.2  0:40.81 lumina-desktop
 1531 root      -21 -21  469M  118M S  0.7  0.7  0:29.23 X :0 -auth /var/tmp/.PCDMAuth-0ea04e26e8f074e8ee3e -nolisten tcp
 1695 gjp4       30  10  433M 53192 S  0.0  0.3  0:00.72 /usr/local/bin/python2.7 /usr/local/bin/hp-systray -x
 1840 gjp4       20   0  400M 49680 S  0.9  0.3  0:12.15 /usr/local/bin/konsole
$ 
```

**Comment by grahamperrin** [comment]
> … half-expect leaps to continue. I'll review usage after 22:00 …

Lumina alone. One screenshot three seconds before 22:00, three shots soon afterwards. 

![21-59-57](https://cloud.githubusercontent.com/assets/192271/20242563/37153ea0-a92a-11e6-8dc4-a42801cbc963.png)

22:00:41, a remarkable increase in use of memory:

![22-00-41](https://cloud.githubusercontent.com/assets/192271/20242564/3e690100-a92a-11e6-82bc-a0e303f0e408.png)

22:02:32, usage still increasing and the September messages in November are exemplary of #128:

![22-02-32](https://cloud.githubusercontent.com/assets/192271/20242565/4249054a-a92a-11e6-9c83-7342fd15840f.png)

22:03:51, the surge of activity has ceased but the memory footprint of sysadm-client remains much larger than is desirable: 

![22-03-51](https://cloud.githubusercontent.com/assets/192271/20242566/45f479f4-a92a-11e6-8156-045eb2f6bba4.png)

If I had left the computer on with sysadm-client running, then almost certainly I would have found the system effectively useless (swap space exhausted) some time on Sunday. 

To avoid that exhaustion I logged out (ending my Lumina test session), logged in to KDE, closed the icon of the secondary SysAdm client ([discussion](https://discourse.trueos.org/t/multiple-sysadm-icons-in-some-desktop-environments/194)), then used the one remaining SysAdm icon to close the client. 

----

Side note: whilst the closure was effective – there's no longer a sysadm-client process – the icon persists in the System Tray of KDE. This seems to be a rare, negligible, cosmetic bug.

**Comment by grahamperrin** [comment]
On one hand: no recent incidents of this bug. 

On the other hand: I have not recently used PersonaCrypt from a USB flash drive. So I'll not rush to close this issue.

**Comment by pkgdemon** [comment]
I have a personacrypt usb install.  I have not been able to reproduce this issue for some time.
