### ISSUE TITLE
IXsystems: Ruben having issues

### ISSUE THREAD

**Issue by b4** [trueos/trueos-core#1262]
Ruben is having issues with:

1). Random freezes (I have witnesses this - it is a hard system lock)
2). sj-storage not mounting at boot automatically, despite backup attempts being in /etc/rc.local - are special parameters required for this in fstab on TrueOS?
3). He is no longer able to open .ods - seems libreoffice "disappeared"

He is running KDE.

**Comment by kmoore134** [comment]
1) The random freezes are most likely kernel panics. Can you provide some details on the type of hardware being used? Video card?

2) It should mount if listed in /etc/fstab. Can you provide examples of what you have tried?

3) That is odd, but using KDE will become hard to debug. I assume pkg info libreoffice still shows it installed? In KDE's control pannel there is a file-associations tool that may be used to re-associate with .ods files if so.

**Comment by Mrt134** [comment]
Closed for inactivity/lack of response. Please comment or respond if the ticket needs to be reopened. Thanks!
