### ISSUE TITLE
SysAdm client wastes time presenting outdated messages

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#128]
Consider some of the October screenshots in #126; messages from August and September. 

There's sometimes a long wait – more than a quarter of an hour – before relevant messages are presented. 

I toyed with the idea that this message presentation issue might somehow contribute to the memory-hogging aspect of #126, but my gut tells me that there's no direct relationship. Just coincidence.

**Comment by grahamperrin** [comment]
On closer inspection, the problem may be recurrent (but most easily noticeable after boot), maybe periodic and triggered by something. 

Here's a shot taken more than four hours after boot. August messages in November: 

![again](https://cloud.githubusercontent.com/assets/192271/20025251/89924aa2-a2e4-11e6-93ef-74a9ed5de91d.png)

----

Side note: the overlapping of messages, seen in that shot, seems to occur when the GUI can't 'cope' with the rate at which messages are presented. Flooding of sorts. Should I raise a separate issue for the overlaps? (I have seen them many times, and off the top of my head I can't imagine any situation other than this (128) that might cause the flooding.)

**Comment by grahamperrin** [comment]
## Remarkable this morning

A) three (3) messages counted, less than two are displayed, both are from September and (contrasting with the 'flood' effect) there's no progress beyond that date: 

![two not three](https://cloud.githubusercontent.com/assets/192271/20049331/50896ca4-a4ba-11e6-8d38-a4611cf3f4f0.png)

B) after observing the mismatch (2 is not 3) I used the menu (probably not the contextual menu) of the icon to close the client and: 

- the client is closed – no matching process
- its icon persists – amber, but not pulsing – in the system tray (of KDE)
- it is possible to get the contextual menu but not the menu
- in this situation (no process) none of the contextual menu items work as expected (no surprise). 

![client](https://cloud.githubusercontent.com/assets/192271/20049338/568e35bc-a4ba-11e6-8464-ee6903b65af7.png)

Wonder points (A) and (B) are symptomatic of a separate but overlpapping issue. 

Rewind a few hours …

----

I began to wonder whether issues such as this would be reproducible in desktop environments other than KDE. For what it's worth, at the weekend I performed very brief experiments with Lumina, MATE and GNOME. 

With the first screenshot below taken at 21:06, I'm almost certain that I had begun the MATE session shortly before 21:00 (I have learnt to expect the flood-like symptoms on an hourly basis). 

![2016-11-06-21-06-07](https://cloud.githubusercontent.com/assets/192271/20049875/cc5e1afc-a4bd-11e6-8f08-b751b4dcc57a.png)

I wondered whether the on-screen position of the icon is contributory to problems so here, I experimented with the icon as close as possible to the foot: 

[2016-11-06-21-12-14](https://cloud.githubusercontent.com/assets/192271/20049876/d00a5ab2-a4bd-11e6-81d8-6529fde16afd.png)

At first glance I found nothing wrong with the first of those two shots. Then I realised: 

- the first (lowest) of the two messages is outdated; there have been numerous daily snapshots since October.

**Comment by grahamperrin** [comment]
## Reproducibility

> … very brief experiments with Lumina, … (I have learnt to expect the flood-like symptoms on an hourly basis). …

I started the OS and used Lumina alone. Shortly after 21:00, with the icon for SysAdm in just one panel at the top of screen, I observed the 'flood' of messages. 

```
$ date ; uptime ; freebsd-version ; uname -a ; last
Sat 12 Nov 2016 21:03:49 GMT
 9:03p.m.  up 15 mins, 2 users, load averages: 1.28, 1.15, 0.66
12.0-CURRENT
FreeBSD momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #14 1717ae3(drm-next-4.7): Fri Oct 28 13:49:49 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
gjp4       pts/1    :0                     Sat 12 Nov 21:03   still logged in
gjp4       pts/0    :0                     Sat 12 Nov 20:51   still logged in
boot time                                  Sat 12 Nov 20:49
…
```

**Comment by grahamperrin** [comment]
Symptoms were observed at least twice in recent days but – with a relatively fast computer – the incidents were _probably_ not long-lasting (not _certain_ because I did not pay attention to the clock, to tell how close things were to the hour). 

I suggest https://github.com/trueos/trueos-core/labels/priority%3Alow for this issue.

**Comment by pkgdemon** [comment]
I was going to try to confirm this next week by swtting up life preserver.

**Comment by pkgdemon** [comment]
Fixed in https://github.com/trueos/sysadm-ui-qt/commit/82cd018ffc795e0725eb177acf0afdbc8de0478e

**Comment by pkgdemon** [comment]
Also here more cleanup was done https://github.com/trueos/sysadm-ui-qt/commit/92edaeaca85de360a20e3a18ad60f7e16b6190ba
