### ISSUE TITLE
sysutils/firstboot-pkgs

### ISSUE THREAD

**Issue by pkgdemon** [trueos/trueos-core#1283]

**Comment by ZackaryWelch** [comment]
https://github.com/trueos/freebsd-ports/commit/d5b30dcda0b49737d7c2f7b6dc3474f979d8ba9a

**Comment by ZackaryWelch** [comment]
Progress made, but more work needs to be done.

**Comment by ZackaryWelch** [comment]
Firstboot not an OpenRC keyword. Not a proper OpenRC script.
https://github.com/trueos/freebsd-ports/commit/69034b3753211d72db5c43a8ce8ed0e9a6ed888a
