### ISSUE TITLE
Control-Alt-F1 and Control-Alt-F2 no longer work

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#13]
TrueOS-Desktop-12.0-CURRENT-08-01-2016-x64-USB.img installed to an Ergo Vista 621 notebook. 

**Expected**

System console (ttyv0), first virtual console (ttyv1).

**Actual results**

A very dark grey full screen with a momentary quarter screen of flashing colours (predominantly blue and red, as far as I can tell), then a non-blinking mid-grey underscore cursor on the very dark grey background. 

In some cases there's no cursor. 

Control-Alt-F9 returns me to the GUI that's severely bugged by #10

**Thoughts**

Given the size, shape, position and colours of the flashes, this issue is comparable to #11

**Side note**

Those Control-Alt- combinations differ from the Alt- combinations that are documented at https://www.freebsd.org/doc/handbook/consoles.html for FreeBSD.

**Comment by pkgdemon** [comment]
It sounds like this laptop has NVIDIA graphics?  

https://forums.pcbsd.org/thread-20235.html

If not using EFI boot it is known that the nvidia driver has broken VT, and this would explain the side effects you are seeing when trying to switch to virtual terminals after X has started.

I am going to keep this ticket open for now because I have some additional ideas to look into next week which may be able to resolve this issue.

**Comment by grahamperrin** [comment]
No, not NVIDIA. The linked topic included a mention of NVIDIA by DJ9; https://forums.pcbsd.org/thread-20235-post-112854.html#pid112854 clarified, 

> (No NVIDIA in the technical specification.)

**Comment by pkgdemon** [comment]
Is this system boot EFI, or BIOS?  I am wondering if it is missing newcons which would be required for VT switching.

**Comment by grahamperrin** [comment]
From https://github.com/trueos/trueos-core/issues/11#issuecomment-238085978 for the same notebook: 

> UEFI is not an option on this circa 2007 notebook.

**Comment by pkgdemon** [comment]
Can you try this below:

Press 3 to escape to loader prompt at the boot menu
set  kern.vty=vt (press enter)
boot (press enter)

**Comment by grahamperrin** [comment]
From IRC – 

> not a fix AFAICT.

– and from Joe: 

>  i have reproduced that issue in the office.  i can work on a fix / test further for sure.

**Comment by pkgdemon** [comment]
From IRC - 

<itaylor57> what does sysctl -a | grep vty return?

<grahamperrin> OK, I see 'kern.vty: vt'.

**Comment by kmoore134** [comment]
Issue with the DRM stack and using intel. Please open ticket here: https://github.com/FreeBSDDesktop/freebsd-base-graphics
