### ISSUE TITLE
www/squid-devel

### ISSUE THREAD

**Issue by pkgdemon** [trueos/trueos-core#1333]

**Comment by ZackaryWelch** [comment]
https://github.com/trueos/freebsd-ports/pull/67/commits/54b47c08a46aeb8dd7c17d6dc2fdfe1055ddddb8

**Comment by ZackaryWelch** [comment]
https://github.com/trueos/freebsd-ports/pull/67/commits/54b47c08a46aeb8dd7c17d6dc2fdfe1055ddddb8
