### ISSUE TITLE
PersonaCrypt device usable on one machine but not another

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#137]
The device that I normally use with an HP EliteBook 850 G2 seems to not work with installations of TrueOS Desktop on other machines. AFAIR I first noticed this a few weeks ago. 

At an HP EliteBook 8540p with the most recent version of the OS: I create the user account with both (a) the required UID number and (b) import of the required key file. When I introduce the PersonaCrypt device to the OS where the new account was created, the OS behaves as if I'm using an incorrect password. 

----

At an Ergo Vista 621, the device _does_ work with a build from 2016-10-05 (`#12 8b8c812(drm-next-4.7)`). Here the OS was fresh on 2016-10-03, updated on 2016-10-16.

**Comment by pkgdemon** [comment]
Did you make sure to set the same user id on each system?  The user id has to match exactly.  You can run `id nameofyouruser` to get the id, or inspect it with user manager.

**Comment by grahamperrin** [comment]
At the system that works with the device: 

```
$ uname -n
momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk
$ id gjp4
uid=1002(gjp4) gid=1002(gjp4) groups=1002(gjp4),0(wheel),5(operator),920(vboxusers)
$ 
```

At the system that does _not_ work with the device: 

```
$ id gjp4
uid=1002(gjp4) gid=1002(gjp4) groups=1002(gjp4),5(operator)
$ 
```

**Comment by pkgdemon** [comment]
Would it make any difference to add user on the system that does not work to the wheel group?

**Comment by grahamperrin** [comment]
Hmm, after re-entering (in SysAdm) the password for gjp4, the system works as expected with the device. 

On one hand: I'd like to dismiss this as PEBKAM and close this issue. 

On the other hand: when I created the account, I was _extremely_ careful with entry of the password (careful, because of past problems). So I doubt that there was a typo. 

I'll perform a fresh installation to tell whether the problem is reproducible. I wonder whether the problem involves some sequence of switching between tabs, and so on …

**Comment by pkgdemon** [comment]
Also.  Try creating a user first, and not importing the personacrypt key.  Then try logging in as the user, make sure the password works.  Then import the personacrypt key.  It may be if you are creating the user, and trying to import the personacrypt key in one step that is not working.

**Comment by grahamperrin** [comment]
Good thinking. I'm almost certain that a past workaround to a different bug (maybe unreported, or reported then disappeared) required an abnormal number of steps to a usable account. 

I assume that it's OK for SysAdm to default to /home (the symlink) as the prefix to the path for the home for a new user. 

----

Side note: the machine that I'd normally use to test a fresh installation is not compatible with the most recent installer for TrueOS Desktop, and that machine is currently used in connection with https://discourse.trueos.org/t/153 so I might not revisit this issue (137) until after more recent installers are pushed.

**Comment by pkgdemon** [comment]
Let us know if we need to reopen when you can retest with newer images.
