### ISSUE TITLE
GELI encrytpion should set grub by default

### ISSUE THREAD

**Issue by narkisr** [trueos/trueos-core#138]
If grub isn't selected as the bootloader during the installation advanced partitioning then the system isn't prompting for GELI password and no OS is found.

Thanks

**Comment by kmoore134** [comment]
Just an update: I'm working on this now. There is code floating around which enabled GELI support for EFI + ZFS, which is why I've left this option open in the installer :)

**Comment by orangecms** [comment]
Awesome, I also just came across this yesterday when I installed the system 3 times on my new laptop before having the idea to use GRUB instead of BTX. :D Could you for now add a remark to the installation guide @kmoore134 until you're done with the implementation? :)

**Comment by pkgdemon** [comment]
Just an update as of the 12-27-16 images this was still broken.

**Comment by grahamperrin** [comment]
> … add a remark to the installation guide …

https://github.com/trueos/trueos-docs/issues/25 led to https://github.com/trueos/trueos-docs/commit/21a737ce06373ea4dd66db58cb72fec736b3d5bf

**Comment by pkgdemon** [comment]
Grub removed from upcoming STABLE, and replaced with refind.
