### ISSUE TITLE
Quarter screen of red at shutdown – no text – with TrueOS-Desktop-12.0-CURRENT-08-01-2016-x64-USB.img on Intel GM45

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#14]
The installed system, with or without a verbose boot: 

- shutdown progresses from a part screen of grey (compare with #10) to a quarter screen of red (compare with #11) with a non-blinking mid-grey underscore cursor at top left. 

Then that cursor disappears, then shutdown completes. 

No text.

**Comment by pkgdemon** [comment]
Are you booting this system with EFI or bios?

**Comment by grahamperrin** [comment]
UEFI is not an option on this circa 2007 notebook – Ergo Vista 621, in the first three of the screen shots at https://goo.gl/photos/K85oQAkXEb8U1xvp9 (I aim to rationalise that collection in due course, for now the priority is to report issues). 

Thanks

**Comment by pkgdemon** [comment]
Can you try the "Legacy Intel" option in the installer to see if it makes a difference?

**Comment by grahamperrin** [comment]
There's an unexpected restart (a kernel panic, I guess) before the suggested option can appear. 

TrueOS-Desktop-2016-08-31-x64-USB.img

**Comment by pkgdemon** [comment]
We have received confirmation that older chipsets pre SB are known not to be supported by drm-next-4.7.  The reason given is "the AGP bits need to be updated to sync up with DRM changes".  For an ETA "it's just not that big a priority compared to making SB+ work reasonably well".
