### ISSUE TITLE
'Start graphical install (Legacy Intel)' not effective with build 111

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#141]
Tested with an Ergo Vista 621. Selecting the option appears to have no effect; the selection changes to the topmost item (xorg).

**Comment by pkgdemon** [comment]
Was this option useful?  I was considering removing it since it seemed to have no effect.

**Comment by pkgdemon** [comment]
@grahamperrin Also if this issue is with our internal images we know about this.  They are not ready yet.
