### ISSUE TITLE
Text Reworks for TrueOS installer screens

### ISSUE THREAD

**Issue by Mrt134** [trueos/trueos-core#1413]
These are suggestions to replace text throughout the TrueOS 

1. **Tooltip for Keyboard layout (Icon with key and US + Brazilian flags):** Adjust the TrueOS keyboard layout.

2. **TrueOS Keyboard Configuration popup:** (Type in the white space below to test the chosen settings.)

3. **Screen 1 (Language Select):** Welcome to TrueOS! Please select your language and click "Next" to continue. You can also restore a saved TrueOS configuration from a MSDOSFS or FAT32 formatted USB drive with "Load config from USB".

4. **Screen 1 pop-up (Load config from USB):** Load an installation configuration file from a MSDOSFS/FAT32 formatted USB stick?

5. **Screen 1 Help pop-up:** Choose your desired installation language. Elements not fully translated display in English. You can also load a saved TrueOS configuration from a USB drive. The drive must be formatted with MSDOSFS or FAT32.

6. **Screen 2 (Install Type):** Choose the installation type.

7. **Screen 2 Help (pop-up):** Choose what kind of TrueOS installation to install to your system:

 "TrueOS Desktop" is the full graphical experience for the home or light office user. The Lumina Desktop Environment is installed with TrueOS, providing a full graphical experience.

 "TrueOS Server" installs a FreeBSD based command-line server operating system. There is no graphical desktop operating system with this option. The SysAdm client and API is included to assist with managing the server either locally or remotely.

 "Restore from Life-Preserver backup" is used to restore a TrueOS system from ZFS snapshots that have been replicated to a remote backup server. The network interface **must** be configured for this option to work properly. The installer attempts to automatically configure networking, but you can click the "blue orb" icon on the bottom of this screen to manually configure the network interface.

8. **Screen 3 Summary box (Disk Selection):** The disk will initialize with this configuration:

9. **Screen 3 "Save Config to USB" (pop-up):** Save the installation configuration to a MSDOSFS/FAT32 formatted USB stick?

10. **Screen 3 "Help" text:** This screen displays the currently selected disk options. Click "Customize Disk Settings" to open a wizard to adjust the installation partition or disk, alter the partition scheme, use a custom ZFS pool name, or force a ZFS 4k block size. Click "Save Config to USB" to save your TrueOS installation configuration to a MSDOSFS or FAT32 formatted USB drive.

11. **Screen 3 Customize Disk Settings menu:** This wizard walks you through the disk setup process. Choose a setup mode and press "Next" to continue.

12. **Screen 3 Customize Disk settings, basic mode:** Select the install disk or partition. **Drop menus:** Remove "Selected" from "Disk" and "Partition". **Summary screen:** Review this summary and press "Finish" to save your settings. Press "Back" to change any options. **Summary window:** The disk will initialize with this configuration:

13. **Screen 3 Customize Disk settings, advanced mode:** Select the install disk or partition.  
 **Drop menus:** Remove "Selected" from "Disk" and ****"Partition".
 **ZFS config screen:** Click "Next" if this is a single disk ZFS install. Otherwise, select the mirror/raid mode and disks here:
 **Encryption Screen:** TrueOS can encrypt your disks using the GELI framework. This is full-disk encryption, requiring a password at startup.
 **File-system mount points screen:** Here are the default file-system mount points. While these are best for most users, you can customize the points using the buttons on this screen or right-clicking an entry.
 **Summary screen:** Here is a summary of the disk configuration. Click "Finish" to save your choices or "Back" to adjust them.

14. **Install progress screen:** Your system is installing! This process can take some time, depending on the installations options and system speed.

15. **Install finished screen:** Your system is now installed!
 Click "Finish" to reboot the system.
 After rebooting, you may need to eject the install media to ensure the system boots from the local disk.

16. **Install finished help popup:** The installation is complete. You can save your system configuration to a MSDOSFS or FAT32 formatted USB drive by clicking "Save Config to USB". Pressing "Finish" immediately reboots the system. Once the monitor screen goes dark, remove the installation medium to ensure the system boots from the freshly installed local drive.
**Save config to USB popup:** Save your installation configuration to a MSDOSFS or FAT32 formatted USB drive?

**Comment by q5sys** [comment]
7) Is there a point to having a popup over a text field which says the same thing?  I did it, but it just seems odd.
10) I'm not sure what you mean by 'help text'  Do you want a new text field or something else?
12) "Summary window"? 
13) Is there a reason you want the summary screen text here to be different than in #12? 
(I've left it the same as what you had for #12 right now) FYI: there is only one summary screen from what I can tell.  Both Basic and Expert mode will end up there.
16) I've added this but why are we having a popup that says virtually the same thing as the text that is then obscured by the popup?
Shouldn't we just have this as the actual text... or only have information that's not in the text field in the mouse over popup?

**Comment by Mrt134** [comment]
7. The "light bulb" icon is described as help for options on this screen, which is currently in a minimal state ("This screen allows you to pick the language"). I tried to follow the descriptive nature of the help text, but add more details directly from the handbook ("Choose a language on this screen. Elements that remain untranslated in your chosen language display in English."). The idea is that people who are confused about how to proceed with the options on the screen can click the light bulb icon and get more information. Another pass with more details may be useful in this case.

8.(did you mean 7?) "Help text" refers to the window that appears when the user clicks the "light bulb" icon in the various installer screens.

9.(did you mean 8?) "Summary window" refers to the disk selection screen, which has an embedded scrollable window summarizing the disk layout. Currently, the embedded window has text beginning with: "The disk will be setup with the following configuration:"

10. Summary screen text should be the same - that was my mistake (there's a good 30 min or so between suggestions, and I didn't review the old suggestion to keep them the same). 

11. I'm not entirely sure which element you're asking about (I think the numbering associations got out of whack). There should probably be some room for redundancy with help text, as we're expanding/explaining the text in the main screen for users who are confused or need more information. Since the "help" button is optional to the user, some critical elements will have to be visible in multiple areas. For example, the Help box for "Install finished screen" says you can plug in a msdosfs or fat32 USB stick to save your install config (clarified/expanded info), while the popup that appears after clicking "save config to USB" on the "Install finished screen" also mentions the USB must be msdosfs or fat32 formatted (required for operation to work).

**Comment by Mrt134** [comment]
Adding a few more suggestions/reworks now that I'm going through the Server installation Wizard screens:

S1. TrueOS Server Wizard (TSW) 1st screen: [ This wizard will walk you through the setup of your new server. Click next to begin. -> This wizard guides you with configuring a new TrueOS server. Click "Next" to begin. ]

S2. TSW 2nd screen (create root password): [ Please enter the root password for this server -> Create a root password for this server: ], [ Password (Repeat) -> Repeat Password ].

S3. TSW 3rd screen (create user): [ Please create a user for this server -> Create a new user: ], [ Password (Repeat) -> [ Repeat Password ]

S4. TSW 4th screen (system hostname): [ Please enter a system hostname and remote login preference -> Enter a system hostname and enable/disable remote logins: ]

S5. TSW 5th screen (network device): [ Please select a network device to configure for this system. -> Configure a network device for this system: ]

S6. TSW 6th screen (optional features): [Please select any optional features to install. -> Choose any additional features to install: ], [Install ports tree (/usr/ports) -> Install FreeBSD ports tree (/usr/ports) ]

**Comment by q5sys** [comment]
I think I've got all these taken care of now.  If I missed one, yell at me with another ticket. ;)
