### ISSUE TITLE
TrueOS installer: Remove disabled "Abort" button

### ISSUE THREAD

**Issue by Mrt134** [trueos/trueos-core#1414]
The current (4/21/17) TrueOS installer has an "Abort" button with no functionality on the "Installation Finished" screen. It should probably be removed. Added a screenshot.

![install14c](https://cloud.githubusercontent.com/assets/17933320/25865202/25393f84-34c0-11e7-9fa0-973a2e33856d.png)

**Comment by q5sys** [comment]
This was already disabled, but I added a setVisible(false) function as well since it wasn't working.
https://github.com/trueos/trueos-utils-qt5/commit/b900b5f547d19b09f7224e322371bdfc115084e2
