### ISSUE TITLE
Remove obsolete "fixgrub" option from TrueOS Utility Menu (installer)

### ISSUE THREAD

**Issue by Mrt134** [trueos/trueos-core#1415]
GRUB utilities are apparently removed from the installer as of 4/17, so we should remove the entry to "fixgrub" from the utility menu. Added screenshot:
![util1a](https://cloud.githubusercontent.com/assets/17933320/25866264/dbb5a114-34c3-11e7-80ac-15f0daa7fbdd.png)

**Comment by Mrt134** [comment]
Instead of removing the entry, what about replacing with "fixrEFInd", restamping rEFInd on the disk?

**Comment by beanpole135** [comment]
Done!

https://github.com/trueos/trueos-core/commit/71123e7a5d7354cc8bb2950d8f24bb465a05d28e
