### ISSUE TITLE
TrueOS Installer: Restore from Life-Preserver backup text reworks

### ISSUE THREAD

**Issue by Mrt134** [trueos/trueos-core#1416]
Text replacement suggestions for the screens after choosing "Restore from Life-Preserver backup" and pressing "Next":

1. **Installation type screen:** Remove hyphen ("-") from "Life Preserver".

2. **Wizard initial screen:** This wizard guides you through a system restoration from a Life Preserver backup. Click "Next" to begin. You can click "Cancel" at any time in the process to return to the installation type menu.

3. **SSH restore screen:** Select the type of backup to use for a system restoration.

(EDIT: Added wblock's suggestions)

**Comment by q5sys** [comment]
updated: 
https://github.com/trueos/trueos-utils-qt5/commit/7f7368850f2d7f833bdcbe2d45faee4a3843ac17
