### ISSUE TITLE
Life Preserver: Cannot replicate two pools from the same host

### ISSUE THREAD

**Issue by VulcanRidr** [trueos/trueos-core#1417]
I have, what I suspect, is a weird corner case. I have a TrueOS desktop with two pools that I would like to replicate to my FreeNAS box. The problem is that it will only replicate one pool at a time. My workstation defiant has pool 1, NX74205, which is on a mirrored pair of SSDs and contains the core system. The second pool, NCC1764, is on a pair of 1TB spinning drives, and is used for large datasets, like jails, ports, VMs, and the like.

I find that I am unable to run a ZFS send to my FreeNAS from both pools, either via the sysadm client or the lpreserver script. The first send works, but the second one says 

> Failed creating remote dataset!
> cannot create 'NX80101/archive/defiant.sonsofthunder.nanobit.org': dataset already exists

I am looking at the code, trying to see if I can work around it by any other method than creating a separate dataset on the FreeNAS machine for that specific pool.

On  the subject of lpreserver, since there is a limit on the character length of the directory structure for ZFS sends. So instead of doing hName=`hostname`, perhaps provide the option to use hName=`hostname -s`?

**Comment by VulcanRidr** [comment]
Might also have to take this into account in the installer too.

**Comment by grahamperrin** [comment]
#194

**Comment by Mrt134** [comment]
Sorry about the inactivity on this issue! Is this still an issue on the current STABLE/UNSTABLE builds?

**Comment by kmoore134** [comment]
I think having unique dataset names included in the target path may help here. Have you considered adding another dataset on the remote to differentiate between the two as well? The tricky part is that making a change like that to the code here will be non-backwards compatible. I'll have to think on it to see how it can be done
