### ISSUE TITLE
Server Installation: make root password viewable

### ISSUE THREAD

**Issue by Mrt134** [trueos/trueos-core#1418]
When installing a TrueOS server, the wizard asks for a root password for the server, but the typed characters are always hidden. Could we add a toggle to make the characters visible?

![tswrpinvisible](https://cloud.githubusercontent.com/assets/17933320/26118086/99f77c48-3a36-11e7-84fd-6777714d4cbd.png)

**Comment by beanpole135** [comment]
q5sys forgot to close this ticket after he fixed this.... :-)
