### ISSUE TITLE
Server install

### ISSUE THREAD

**Issue by Mrt134** [trueos/trueos-core#1419]
After doing a server installation settings dialogue, the disk installation options aren't displaying properly.

**Comment by Mrt134** [comment]
Update: checked with 7/4/2017 .iso and it is still an issue:
![serverconfigmissinfo](https://user-images.githubusercontent.com/17933320/28717300-3002a1e2-736f-11e7-8b3d-058ab0bbcd20.png)

The ZFS Pool Drop down is blank, and neither "Install to disk" nor "Install into Boot Environment" is checked.

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/trueos-utils-qt5/commit/c50c3a54179abce0db126aed589b979f6b1c48d1
