### ISSUE TITLE
SysAdm: inexplicable black alert (no messages)

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#142]
![black alert](https://cloud.githubusercontent.com/assets/192271/20030981/41b8e9c8-a368-11e6-883d-8b87a6aaca4a.png)

After a reasonable waiting period (below), no change. The alert persists, with no message to explain it. 
```
$ date ; uptime ; freebsd-version ; uname -a
Sat  5 Nov 2016 14:58:55 GMT
 2:58p.m.  up 56 mins, 2 users, load averages: 0.63, 0.67, 0.69
12.0-CURRENT
FreeBSD momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #14 1717ae3(drm-next-4.7): Fri Oct 28 13:49:49 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
$ 
```
----
Above, I spoke too soon. Amusingly, the messages began appearing after around an hour. I got this uptime within a few seconds of observing the amber pulse: 

```
[gjp4@momh167-gjp4-hpelitebook850g2-trueos ~]$ uptime
 3:02p.m.  up 1 hr, 2 users, load averages: 0.72, 0.73, 0.71
[gjp4@momh167-gjp4-hpelitebook850g2-trueos ~]$ 
```

As the amber pulse began, so (half-expected) I observed recurrence of https://github.com/trueos/trueos-core/issues/128

----

Around five minutes later, 

```
[gjp4@momh167-gjp4-hpelitebook850g2-trueos ~]$ uptime
 3:07p.m.  up  1:05, 2 users, load averages: 0.57, 0.64, 0.66
[gjp4@momh167-gjp4-hpelitebook850g2-trueos ~]$ 
```
– after the 'flood' had ended (more rapidly than I might expect with #128) I hid all messages and there remains a black alert. Clicking the alert simply opens a SysAdm window.

**Comment by grahamperrin** [comment]
I restarted the OS, with an uptime of eleven minutes there's the black alert and not yet any message. 

Does the black alert for SysAdm client mean the same (security vulnerability) as the black alert in the AppCafe part of the client?I restarted the OS, with an uptime of eleven minutes there's the black alert and not yet any message. 

Does the black alert for SysAdm client mean the same (security vulnerability) as the black alert in the AppCafe part of the client?

**Comment by pkgdemon** [comment]
Are you still seeing this anywhere @grahamperrin.  I have not yet encountered this.

**Comment by grahamperrin** [comment]
To be honest, I while ago I removed SysAdm Client from my lists of things (at various machines) that open at startup. For a variety of reasons, I learnt to not pay attention to it (that's not a dig – just saying). 

It's now a startup item at the HP EliteBook 850 that's used for my everyday work, I'll keep an eye on it.

**Comment by grahamperrin** [comment]
Re https://gitter.im/trueos/troubleshooting?at=588584b296a565f84409d71e sorry, I had to stop the client. 

Please make this issue 142 low priority until after a fix for other issues that bug the client. Thanks.

**Comment by grahamperrin** [comment]
Observed at a different computer. 

![desktop](https://cloud.githubusercontent.com/assets/192271/23330193/e948db2e-fb3f-11e6-8c08-27ee6f0b943f.png)

```text
$ about

===================
General information
===================

boot environment now (N) … 12.0-CURRENT-up-20170225_091154 NR 2017-02-25
       after restart (R) … 12.0-CURRENT-up-20170225_091154 NR 2017-02-25
boot loader …………………………………… BSD
            type ……………………… BIOS
CPU ………………………………………………………… Intel(R) Core(TM)2 Duo CPU     T7700  @ 2.40GHz
    number of cores ……………… 2
host ……………………………………………………… momh167-gjp4-ergovista621-trueos.university.brighton.ac.uk
memory ………………………………………………… 4096 MB available, 1472 MB free
OS git branch ……………………………………………………………………………………… drm-next
OS git revision ………………………………………………………………………………… 2dc2a76
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… CUSTOM
TrueOS version …………………………… TrueOS-Desktop-201702250619
uptime ………………………………………………… 34 mins
user  …………………………………………………… grahamperrin

More (TrueOS Desktop):

    desktop environment …… KDE
    sound card driver ………… pcm0: <Realtek ALC660-VD (Analog 2.0+HP/2.0)> (play/rec) default
    wireless driver ……………… wpi0
    X11 drivers ………………………… modesetting_drv.so 

$ uname -v
FreeBSD 12.0-CURRENT #38 2dc2a76(drm-next): Sat Feb 25 05:22:57 UTC 2017     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
$ sudo pc-updatemanager pkgcheck
Boot-strapping updater...OK
Updating trueos-base repository catalogue...
trueos-base repository is up-to-date.
Updating trueos-major repository catalogue...
trueos-major repository is up-to-date.
All repositories are up-to-date.
All packages are up to date!
$ rc-status | grep -v tarted
Runlevel: default
 bsdstats                                                          [  crashed  ]
Dynamic Runlevel: hotplugged
Dynamic Runlevel: needed/wanted
Dynamic Runlevel: manual
$ beadm list
BE                              Active Mountpoint  Space Created
initial                         -      -            2.6G 2016-12-18 14:11
12.0-CURRENT-up-20170123_051228 -      -            2.2G 2017-01-23 05:09
12.0-CURRENT-up-20170128_030454 -      -            2.2G 2017-01-28 03:01
12.0-CURRENT-up-20170202_182316 -      -            3.5G 2017-02-02 18:00
12.0-CURRENT-up-20170225_060551 -      -          680.3M 2017-02-25 05:29
12.0-CURRENT-up-20170225_091154 NR     /           19.8G 2017-02-25 09:09
$ 
```

**Comment by grahamperrin** [comment]
At host momh167-gjp4-ergovista621-trueos.university.brighton.ac.uk the black alert is also visible: 

- when logged in to Lumina instead of KDE
- when logged in as a different user (UID 1001).
