### ISSUE TITLE
Readme.md Trueos handbook wording, order of links

### ISSUE THREAD

**Issue by darkfiberiru** [trueos/trueos-core#1425]
Should the trueos handbook section be worded closer to the lumina handbook section so that the handbook link is first and then the website second. If I'm looking for documentation the Lumina section is less confusing while with trueos I opened both pages on accident.

"TrueOS documentation is hosted on the [TrueOS website](). The[ TrueOS User Guide ](url)is a comprehensive guide to install"
"The Lumina Desktop Environment has its [own handbook, ](url)hosted on the[ Lumina Website](url)."

**Comment by Mrt134** [comment]
Good point - I'll switch it around.
