### ISSUE TITLE
login/display manager delay

### ISSUE THREAD

**Issue by danboid** [trueos/trueos-core#1427]
I'm running the latest TrueOS and there seems to be a bug in the login manager. If I log out of MATE or Lumina to the default TrueOS login manager (sorry, I don't know its name?) then enter my username and password and hit ENTER, the cursor becomes ye olde Xorg 'X' cursor and there is a delay of approx 2 minutes before you get logged into your chosen DE/WM.

Could this be related to my previous bug re gmtp and its laggy GUI?

**Comment by danboid** [comment]
This is on a i7 laptop with SATA3 SSD etc so logging into MATE should be almost instant. It seems Lumina has a progress bar when you log into it now so that I don't expect to but as snappy but not a two minute wait.

**Comment by danboid** [comment]
Clarification:

I should've said that this delay doesn't occur the first time I login, immediately after boot. It only occurs when logging back in after having logged out of X at least once.

**Comment by nielsk** [comment]
I've seen this with xfce as well and already wondered what is going on

**Comment by q-pa** [comment]
This also happens on my STABLE installation.

**Comment by beanpole135** [comment]
I have not seen this on UNSTABLE for the last couple months or so.
Can anybody verify if this is still an issue with the latest UNSTABLE updates?

**Comment by q-pa** [comment]
Cannot verify, seems to be resolved (latest UNSTABLE).
