### ISSUE TITLE
February ISO is OK, but later ISOs won't boot

### ISSUE THREAD

**Issue by HutchSails** [trueos/trueos-core#1428]
The february 22 ISO works fine.  I like it.  But everything since then does not boot (neither the ISO nor the USB image will boot) on my ASUS N68/AMD64.  Manifests itself as:

```
trying to mount root from cd9660: /dev/iso9660/TRUEOS_INSTALL [] ...
ada0:ata5:0:0:0): READ_DMA48 ACB ec:00:00:00:00:40:00:00:00:00:00
ada0:ata5:0:0:0): CAM status: Command Timout
This, and similar errors repeat indefinitely, with no successful booting.

```
The USB image boot attempts do  something similar.  I could go retry the USB boot and get some exact error examples, I suppose.  The ASUS motherboard is about 6 years old. Here is devlist (without USB plugged into machine):

```
[ron@trueos-5071] /usr/home/ron# camcontrol devlist
<ATAPI iHAS324   Y BL1W>           at scbus4 target 0 lun 0 (pass0,cd0)
<WDC WD5000AAKS-00Z7B0 01.03B01>   at scbus5 target 0 lun 0 (ada0,pass1)

```

**Comment by HutchSails** [comment]
It doesn't look like KDB is enabled? Otherwise could provide additional info if requested.

**Comment by beanpole135** [comment]
Please try out the newest ISO/IMG for TrueOS (June 1 or later). That has all the installer/firstboot improvements specifically to fix a number of these "non-bootable-system" issues, and so far the updates have fixed it for most people that were having trouble.
