### ISSUE TITLE
pc-netmanager 'Public servers' GUI lists servers but the selected server is not used

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#143]
1. Select a server
2. click 'OK'.

## Expected

The address of the server in the DNS field. 

## Actual result

No change to the field. 

----

Maybe read this alongside [Bug #16117: PC-BSD Network Manager fails to cease using custom DNS - PCBSD - Bug Tracking System](https://bugs.pcbsd.org/issues/16117)

**Comment by pkgdemon** [comment]
Working for me with latest internal build after dhcpcd changes.  I selected an OpenDNS server, and selected OK.  The server was entered into the field automatically.

**Comment by grahamperrin** [comment]
Thanks, double-click does not yet work as expected in the list of servers. Do you see the same? If so I can raise a new issue for low priority attention at a later date.
