### ISSUE TITLE
Handbook: Dual-booting clarification

### ISSUE THREAD

**Issue by danboid** [trueos/trueos-core#1430]
https://www.trueos.org/handbook/install.html#dual-booting

The dual-booting chapter of the handbook is all a bit vague and I expect outdated too.

From my recent resarch into this I THINK dual-booting TrueOS with Linux should be possible once tsoom's chainloading patch for the FreeBSD bootloader is merged. He tells me it works and is ready to go, pretty much.  He just needs to check the licensing IIRC.

Would dualbooting with Windows be possible on a single drive machine? I'm not sure it would as I think both TrueOS and Windows want to control the bootsector. Maybe dual-booting with Windows will be possible on machines with multiple drives?

**Comment by Mrt134** [comment]
This issue was moved to trueos/trueos-docs#35
