### ISSUE TITLE
Latest (20170526) update removes KDE

### ISSUE THREAD

**Issue by VulcanRidr** [trueos/trueos-core#1432]
I am running on the unstable repository, and both my latop and my desktop were running KDE. After the update, I found that my only options in PCDM were Fluxbox and Lumina, as KDE appears to have been uninstalled. I was able to pkg install kde and all was back to the way I had it.

Request the running desktop be installed during the upgrade.

Thanks,
--b

**Comment by Mrt134** [comment]
Thanks for reporting this!

**Comment by darkfiberiru** [comment]
@VulcanRidr  Unstable had a relatively major leap as new DRM(direct rendering manager for graphics) version and ino64 was brought in. These abi changes broke the tail end of the upgrade process.  Updates have been made/are being made to fix this upgrade issue before it ever hits a stable version. The work being done should also stop this from happening in the future during major changes of kernel abi.

Definitely appreciate the  additional reporting and info. I was personally quite surprised when I all of a sudden had no web browser post upgrade.

Also we are making sure that it's easier to compare installed software prior and post update.

**Comment by Mrt134** [comment]
Update: we're working on this and getting close to finishing it up!

**Comment by Mrt134** [comment]
Ok, this one is complete - discovered KDE had breakage that kept it from building for an UNSTABLE release. Looks like @kmoore134 and @beanpole135 have since resolved the build issue.
