### ISSUE TITLE
Wrong wireless signal power % in Network Manager

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/trueos-core#1436]
TrueOS image from 1st june 2017. MikroTik HAP Lite WiFi router.

FreeBSD trueos4278.local 12.0-CURRENT FreeBSD 12.0-CURRENT #61 d7b9fac18(trueos-stable)-dirty: Mon May 29 20:21:45 UTC 2017     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64

1. Intel NUC5PPYH. WiFi Card: Intel AC-3165. TrueOS Network Manager Wireless signal power is 60%. All OK because in this NUC some problems with WiFi  antenna connector.

![5ppyh](https://cloud.githubusercontent.com/assets/20837310/26750341/60743cfc-4839-11e7-81a0-a88e7a033fd9.png)

2. Intel NUC DN2820FYKH. Wifi Card: Intel 7260BN. TrueOS Network Manager Wireless signal power is 0%. This is the bug. This value must be 100%, because all OK with NUC DN2820FYKH antenna connector and with MikroTik HAP Lite router (be located near NUCs). In Linux Network Manager WiFi signal power is 100%.

![dn2820fykh](https://cloud.githubusercontent.com/assets/20837310/26750421/36508a32-483b-11e7-80ba-f967e527ff21.png)

**Comment by beanpole135** [comment]
This as been fixed.
Right before the STABLE release, I found a bug in FreeBSD where the signal/noise values reported by `ifconfig` were occasionally getting reversed - resulting in a 0% signal strength to be calculated. I put a couple quick commits into the source tree which allow our calculation routine to detect/fix the reversal, but those commits did not make it into the STABLE packages that were pushed out. They *will* be in the next round of updates that we push out to the STABLE branch though.

You can double check that it is the same bug by running the following command:
`ifconfig wlan0 list scan`
If you look at the "S:N" column, the noise *should* be hanging out around -159dB while a good-quality signal will be around -130dB or higher.
