### ISSUE TITLE
cannot re-install trueos

### ISSUE THREAD

**Issue by billpetheram** [trueos/trueos-core#1437]
My system wouldn't boot. It hangs after running Sysadm. It seems zfs doesn't start, however because the text disappears off the screen, i can't see what the problem is.

So I thought I would try to re-install trueos. Howeer that doesvn't work as deleting the gpt partitions fails. I tried using dd to zero over the start of the drive but it seemed to make no difference.

I have attached the log file from the install.

[trueos-install-debug-log.txt](https://github.com/trueos/trueos-core/files/1050695/trueos-install-debug-log.txt)

**Comment by darkfiberiru** [comment]
If you want to restart from scratch you need to 

 zpool import -fN $OLD_POOL

**Comment by Mrt134** [comment]
Workaround is functional and no one has anything else to add. Closing this ticket for inactivity.
