### ISSUE TITLE
Lumina: Time delay hiding panel reappearing

### ISSUE THREAD

**Issue by q-pa** [trueos/trueos-core#1438]
Fresh install of TrueOS-2017-06-01-x64 on Lenovo Thinkpad T520, using integrated graphics with intel driver.

There is a significant delay when the hiding panel should reappear. First, there is a more or less empty field, then between one and two seconds later the panel comes into view (see screenshots attached). 
![panel_1](https://cloud.githubusercontent.com/assets/3322553/26800393/72d85034-4a39-11e7-949a-0588cfae8702.png)
![panel_2](https://cloud.githubusercontent.com/assets/3322553/26800392/72cf8d8c-4a39-11e7-823a-02996068d3db.png)

I did not have that problem with PCBSD 10.3 installed on the same laptop.

**Comment by q-pa** [comment]
Sorry, I just now realised that there is a dedicated Lumina repository, of course. Could you move this issue there or should I file a new ticket?

**Comment by q5sys** [comment]
Github does not allow us to move tickets between repos.  You will have to close this ticket and re-create it there.
