### ISSUE TITLE
Lumina: many settings not persistent

### ISSUE THREAD

**Issue by q-pa** [trueos/trueos-core#1439]
Fresh install of TrueOS-2017-06-01-x64 STABLE on Lenovo Thinkpad T520, using integrated graphics with intel driver, localisation Germany.

1. lumina-fm.conf's owner was root (group: user). That is why I could not make any changes like e.g. bookmarks permanent until I used `chown` to change the user.

2. Question for favorite browser keeps reappearing, although this is set in Desktop Settings.

3. I changed my favorite program for opening images in Desktop Settings but it was not  persistent before I changed the line lumina-mimeapps.list (although I am not supposed to...) 

I could not find any more config files with the owner set to root but something seems wrong here.

**Comment by q-pa** [comment]
Sorry, I just now realised that there is a dedicated Lumina repository, of course. Could you move this issue there or should I file a new ticket?

**Comment by q5sys** [comment]
Github does not allow us to move tickets between repos.  You will have to close this ticket and re-create it there.

**Comment by q-pa** [comment]
I switched to UNSTABLE yesterday. Now this issue has re-appeared. I can chown back the files lumina-fm.conf and lumina-fm_root.conf to my user (although the latter should be root as far as I understand). But after launching lumina-fm with sudo the file owner of both(!) files is root again.

**Comment by ZackaryWelch** [comment]
I looked at this with the latest UNSTABLE and I am unsure what the issue is. I ran lumina-fm as root, which causes a new configuration file to be created and owned by root, lumina-fm_root.conf. The default lumina_fm.conf did not change owners. If you chown lumina-fm_root.conf, you can make changes to it, and those changes will stick after running lumina-fm as root again. I have not been able to reproduce lumina-fm causing the default lumina-fm.conf to change ownership to root.

**Comment by q5sys** [comment]
I have used Lumina-fm as both a normal user and as root for a very long time and i have never gotten the behavior that you are referring to.  I do this so much I've been planning to add in a 'relaunch Insight as root' menu option, but I have some other things I want to tackle first. I will do some investigation on this later, to see if there has been a change in code that would cause running lumina-fm as root to change your user level conf file.

Also, as mentioned in the message when this ticket was closed, please recreate this ticket under the lumina-fm repo.  Ken and myself look there far more often for lumina issues than we do here.  Making tickets about lumina issues in this repo is a good way for it to split past us. Help us help you. :)

**Comment by q-pa** [comment]
I will re-test and re-open lumina issue #426 if necessary.

**Comment by q-pa** [comment]
I just commented issue https://github.com/trueos/lumina/issues/426 with some new information but I cannot reopen that issue.

**Comment by Mrt134** [comment]
Ok, thanks for updating - I'll reopen the issue.
