### ISSUE TITLE
pc-netmanager fails to run from launcher menu

### ISSUE THREAD

**Issue by ethoms** [trueos/trueos-core#144]
The Network Manager tool will not start from the launcher menu. It needs root privileges, but does not try to elevate (ask for password). It does open from the pc-nettray though.

So, it should either be hidden from the launcher menu, or the same elevation mechanism that pc-nettray uses should be used from the .desktop file.

Minor issue, but leaves user with bad impression.

I'm curious what pc-nettray does to gain privileges to run pc-netmanager?

**Comment by ethoms** [comment]
I notice that if the .desktop file is changed on below line, it launches fine from launcher menu:

    Exec=sudo pc-netmanager

**Comment by grahamperrin** [comment]
> … what pc-nettray does to gain privileges to run pc-netmanager?

@kmoore134 or @beanpole135 I recall a great privileges-related answer in Stack Exchange but http://stackexchange.com/search?q=%22pc-su%22 does not find it. Can either of you remind me? Thanks.

**Comment by beanpole135** [comment]
Fixed!
It just needs to be launched through sudo...

https://github.com/trueos/pc-networkmanager/commit/c47cf945c1d0071bb74ac44cc761c5c9a9cc3f0f
