### ISSUE TITLE
Lumina-FM / Insight shortcuts not shown in menu

### ISSUE THREAD

**Issue by q-pa** [trueos/trueos-core#1440]
Fresh install of TrueOS-2017-06-01-x64 STABLE on Lenovo Thinkpad T520, using integrated graphics with intel driver.

With localisation set to Germany there are no shortcuts shown in the menus of Insight (see screenshot).
![shortscuts_menu](https://cloud.githubusercontent.com/assets/3322553/26801410/1a779126-4a3d-11e7-8d7a-5c90780ea5cd.png)

**Comment by q-pa** [comment]
Sorry, I just now realised that there is a dedicated Lumina repository, of course. Could you move this issue there or should I file a new ticket?

**Comment by q5sys** [comment]
Github does not allow us to move tickets between repos.  You will have to close this ticket and re-create it there.

**Comment by q-pa** [comment]
re-created in Lumina repository.
