### ISSUE TITLE
Feature request: incorporate Lumina Archiver in Lumina like Ark is in KDE

### ISSUE THREAD

**Issue by q-pa** [trueos/trueos-core#1441]
It would be nice to have options in the right-click menu like different types of compression, compress and send to... etc. like KDE offers with Ark.

**Comment by q-pa** [comment]
Sorry, I just now realised that there is a dedicated Lumina repository, of course. Could you move this issue there or should I file a new ticket?

**Comment by q5sys** [comment]
Github does not allow us to move tickets between repos.  You will have to close this ticket and re-create it there.

**Comment by q-pa** [comment]
Re-created in Lumina repository.
