### ISSUE TITLE
DHCP running on statically configure interfaces

### ISSUE THREAD

**Issue by mremski** [trueos/trueos-core#1442]
After the June update, statically configured ethernet interfaces wind up with 2 IPV4 addresses and IPV6 addresses when IPV6 is disabled.  
Root cause is the wrong init.d script is installed in /usr/local/etc/init.d/dhcp on an OpenRC system.  The base FreeBSD gets installed instead of the openrc one.  I'm guessing that the package build is not quite correct (I know that the team is working on allowing either OpenRC or base FreeBSD init scripts).
If you have all your interfaces using dhcp it's not an issue, only static IP config has problems.

**Comment by kmoore134** [comment]
https://github.com/trueos/freebsd-ports/commit/d26bf8ef88f363a1e39fcc009fea7a3415ef2902
