### ISSUE TITLE
kernel panic during advanced install of TrueOS

### ISSUE THREAD

**Issue by danboid** [trueos/trueos-core#1444]
I am trying to dual boot TrueOS with Arch Linux on a single drive (SSD), BIOS-based machine - in my case a system76 i7 GazellePro w/ 8GB RAM and 250GB Samsung SSD. I have already proved this should be technically possible as I have FreeBSD 11 (installed using ZFS) happily dual-booting with Arch Linux so I should be able to keep the same (or similar) partitioning but, using the advanced mode of the TrueOS installer, install TrueOS on top of my FreeBSD partition as a drop-in replacement.

I've just tried doing that but the result was that the TrueOS kernel panicked when I clicked 'Next' on the button that should've started the advanced install, after telling it to install into/over my existing FreeBSD ZFS partition. I would expect TrueOS to format and install to the ZFS partition and replace the existing FreeBSD bootloader but NOT TOUCH the Linux partition.

My FreeBSD partition got trashed and no longer booted after this kernel panic (see attached screenshot) but thankfully my Linux partition was untouched and still booted.

My drives partitioning looks like:

disk0p1 - FreeBSD bootloader
disk0p2 - Arch Linux ext4 partition
disk0p3 - FreeBSD ZFS partition

All three are GPT partitions.

How I achieved a working FreeBSD ZFS / Linux BIOS dual boot config:

First I used the FreeBSD installer to install FreeBSD 11 amd64. I used the guided ZFS install mode and accepted all the defaults except for the swap partition size which I adjusted to 111GB - the size I wanted for my Linux partition.

After installing FreeBSD and checking I could boot into it fine, I disabled the FreeBSD swap partition in fstab then rebooted into sysemrescuecd off a USB stick. I used gparted to delete the FreeBSD swap partition and make a ext4 partition in its place.

I then booted the Arch installer off USB and when it came to installing GRUB, I used a command like

grub-install --force /dev/sda2

grub requires you use --force to install into a partition boot record rather than the MBR but it works fine actually. At that point, I could boot into arch successfully by using the GRUB commandline chainload command but I went the extra step and patched the FreeBSD bootloader to include a chainload option which works just great using this patch:

https://reviews.freebsd.org/D59925

It is configured via adding a line to loader.conf like:

chain_disk=“disk0p2:"

Note the colon after the partition number. Chainloading will fail if you don't include the trailing colon! On the next boot you just have to push the 8 key when the FreeBSD bootloader menu appears to chainload into GRUB.

![trueos-advanced-install-panic](https://user-images.githubusercontent.com/1429783/27252483-6394a2ca-534f-11e7-8cb9-51a74549c0c2.jpg)

**Comment by danboid** [comment]
I don't bother with swap partitions under Linux - if I really needed it I'd create a swap file, but I don't.

Can TrueOS be installed without a dedicated swap partition? I'd say most people with 16GB+ RAM don't really need it.

Can True OS use a swap file stored on its root partition instead of a swap partition? I get the impression it supports this already.

**Comment by danboid** [comment]
I realise I could've installed trueOS into a boot environment but I had decided against using FreeBSD on this laptop because I want my 4K monitor working properly. It works under TrueOS but not FreeBSD, even after upgrading to 12.

I'm hoping you can get the installer to work as I want but otherwise, I will go down the bootenv route and just remove the FreeBSD related BE. I presume that would be safe and doable?

**Comment by danboid** [comment]
Seeing as my failed advanced TrueOS install failed but the FreeBSD bootloader (and Linux) remained intact, I thought I'd try running the installer again but try installing into a bootenv instead. That failed with the error:

cannot import 'zroot': invalid vdev config

That is most likely due to the fact that my FreeBSD partition became unbootable after the advanced  install failed. I expect that if I had tried installing to a BE first (when FreeBSD was booting), it would've worked.

**Comment by danboid** [comment]
I was using the TrueOS installer from either last month or early this month. I've just noticed there is a newer installer iso from a few days ago so I'm downloading that now to try again on the off-chance it behaves better. I think I'll be lucky but my ZFS partition is unusable right now so I've got nothing to lose.

**Comment by danboid** [comment]
I've just tried installing again with TrueOS-2017-06-14-x64-USB.img and it has failed again but this time there was no kernel panic and instead it printed:

BIOS: unexpected operator

In / just above the installation progress bar area at the time of starting the install ie immediately after clicking 'Yes' after being asked "Start the Customized-Disk installation now?"

Also, I should clarify the 'Advanced' in the title of this issue. I am referring to the 'Advanced Install' mode of the 'Customize Disk Settings' options when using the 'Install to disk' mode of the TrueOS installer. I am using the default pool name and not forcing the 4K block size.

**Comment by danboid** [comment]
I re-installed both FreeBSD and Linux, checked I could boot into them both and then tried installing TrueOS-2017-06-14 again but into a boot env this time.

Install worked, mostly, except for me having to forcefully power down my laptop right at the end after clicking 'Finish' on the screen that says install was successful. TrueOS has replaced/updated the bootloader and my laptop now boots into the TrueOS setup wizard thing, and my Linux partition has survived. It asks me which video driver I want to use, but every option fails by producing a static screenful of garbage which forces you to reboot.

I expect you are already aware of this pos install video driver prob with the latest installer? I can make a separate ticket for that if is unreported.

**Comment by danboid** [comment]
I have now got TrueOS to install into a FreeBSD 11 bootenv but in order for both the initial install to  complete without a crash and to get past the new video driver selection screen (the first screen of the first run helper) I had to install from TrueOS-2017-04-21-x64-USB.img because both TrueOS-2017-06-14-x64-USB.img and TrueOS-2017-06-01-x64-USB.img would just show a load of pseudo  characters on the screen after I click on 'Finish' on the "Installation successful" screen and after choosing any valid driver and clicking Apply OR when clicking 'Skip' on the first run driver selection screen hence I never get to see Lumina with the June images.

Intel HD 4600 Haswell GPU.

**Comment by RodMyers** [comment]
can you attempt with the Beb 2018 UNSTABLE release?

**Comment by q5sys** [comment]
I'm going to go ahead and close this ticket.  I have personally done several dozen installs of our ISOs since Jan 18 and have not had any experiences of this.  Also, Since our stable release in December, we've had no additional reports of this from thousands of downloads.  @danboid if you do experience this again, please make a new ticket.

**Comment by RJVB** [comment]
I'm seeing something similar with the current installer, when trying to install TrueOS in a VirtualBox VM that has a rawdisk access to the target partition on my internal harddisk (and 4Gb of RAM). From the install log:

```
vm_fault: pager read error, pid 15878 (pkg)
pid 15878 (pkg), uid 0: exited on signal 11
vm_fault: pager read error, pid 15882 (pkg)
[...]
pid 3835 (zfs), uid 0: exited on signal 6
pid 3938 (zfs), uid 0: exited on signal 6
pid 4041 (zfs), uid 0: exited on signal 6
pid 4102 (sh), uid 0, was killed: out of swap space

# DISK INFO ada0 
/dev/ada0
/dev/ada0p1
/dev/ada0p2
/dev/ada0p3
/dev/ada0p4
=>       40  976773088  ada0  GPT  (466G)
         40     204800     1  efi  (100M)
     204840  909195264     2  freebsd-zfs  (434G)
  909400104   33554432     4  freebsd-swap  (16G)
  942954536     235520        - free -  (115M)
  943190056   33552384     3  freebsd-swap  (16G)
  976742440      30688        - free -  (15M)


# MOUNT OUTPUT 
/dev/iso9660/TRUEOS_INSTALL on / (cd9660, local, read-only)
devfs on /dev (devfs, local, multilabel)
tmpfs on /tmp (tmpfs, local)
/dev/md2 on /memfs (ufs, local)
/dev/md0.uzip on /usr (ufs, local, read-only)
/dev/md10 on /etc (ufs, local)
/dev/md9 on /var (ufs, local)
/dev/md8 on /root (ufs, local)
tmpfs on /libexec/rc/init.d (tmpfs, local, noexec, nosuid)
bolaTrOS/ROOT/initial on /mnt (zfs, local, noatime, nfsv4acls)
bolaTrOS/tmp on /mnt/tmp (zfs, local, nosuid, nfsv4acls)
bolaTrOS/usr/home on /mnt/usr/home (zfs, local, nfsv4acls)
bolaTrOS/usr/jails on /mnt/usr/jails (zfs, local, nfsv4acls)
bolaTrOS/usr/local/share/doc on /mnt/usr/local/share/doc (zfs, local, nfsv4acls)
bolaTrOS/usr/obj on /mnt/usr/obj (zfs, local, nfsv4acls)
bolaTrOS/usr/ports on /mnt/usr/ports (zfs, local, nfsv4acls)
bolaTrOS/usr/src on /mnt/usr/src (zfs, local, nfsv4acls)
bolaTrOS/var/audit on /mnt/var/audit (zfs, local, nfsv4acls)
bolaTrOS/var/log on /mnt/var/log (zfs, local, noexec, nosuid, nfsv4acls)
bolaTrOS/var/mail on /mnt/var/mail (zfs, local, nfsv4acls)
bolaTrOS/var/tmp on /mnt/var/tmp (zfs, local, noexec, nosuid, nfsv4acls)
devfs on /mnt/dev (devfs, local, multilabel)
```

Is that the same issue, should I open a new ticket?
