### ISSUE TITLE
Feature request: Incorporate libdvdcss by default

### ISSUE THREAD

**Issue by q-pa** [trueos/trueos-core#1445]
It took me some time to find out why most DVDs would not play on my fresh install of 2017-06-01-STABLE release. I just needed to install libdvdcss. I am pretty sure PCBSD came with that preinstalled. Things like not being able to play media could easily frustrate new users enough to ditch this great OS.

**Comment by beanpole135** [comment]
Done!

https://github.com/trueos/trueos-utils-qt5/commit/25ffafa53c0d668b60dcc3d19a2e123c1f5bc8d9
https://github.com/trueos/trueos-core/commit/033cd1e0566ba40ad1424457d722752c1883ba8f
