### ISSUE TITLE
system updates don't get installed

### ISSUE THREAD

**Issue by danboid** [trueos/trueos-core#1446]
I have just reinstalled trueos using an install image from May because  the June images (the ones that introduce the extra video options) don't work for me. I installed it into a FreeBSD 11 bootenv. The initial installation and the first run setup went without any errors.

I have now tried three times to update using the system update tool - each time it downloaded and installed 800+ updates with no errors then asked me to reboot so I do and the update tool pops up asking if I want to install the updates  to which I reply 'Yes'. It seems to update without error then reboot but if I go to update manager I sill the same set of updates are available and thus it goes on...

Here's a snippet from pc-updatemanager.log.prev

pc-updatemanager: Thu Jun 22 19:37:07 BST 2017
Checking for updates to ports-mgmt/pkg..
Updating the package repo database...
Cleaning old pkg upgrade cache...
Verifying / fetching packages for ports-mgmt/pkg - pkg-1.10.1.txz
Verifying / fetching packages for misc/trueos-desktop - trueos-desktop-201706210948.txz
Verifying / fetching packages for graphics/phototonic - phototonic-1.7.20_1.txz
Verifying / fetching packages for mail/trojita - trojita-0.7_1.txz
Verifying / fetching packages for misc/trueos-meta-hunspell - trueos-meta-hunspell-20160701,1.txz
Verifying / fetching packages for multimedia/openh264 - openh264-1.5.0,2.txz
Verifying / fetching packages for multimedia/vlc - vlc-2.2.5.1,4.txz
Verifying / fetching packages for print/cups-pdf - cups-pdf-2.6.1_4.txz
Verifying / fetching packages for print/gutenprint-cups - gutenprint-cups-5.2.10_3.txz
Verifying / fetching packages for print/qpdfview - qpdfview-0.4.16_7.txz
Verifying / fetching packages for sysutils/fusefs-ntfs - fusefs-ntfs-2017.3.23.txz
Verifying / fetching packages for www/qupzilla-qt5 - qupzilla-qt5-1.8.9_2.txz
Verifying / fetching packages for x11-fonts/droid-fonts-ttf - droid-fonts-ttf-20131024_3.txz
Verifying / fetching packages for x11-fonts/noto-lite - noto-lite-1.0.5.txz
Verifying / fetching packages for x11-themes/cursor-jimmac-theme - cursor-jimmac-theme-0.1_2.txz
Verifying / fetching packages for x11/qterminal - qterminal-0.7.0_1.txz
Verifying / fetching packages for FreeBSD Base
-----------------------------------------------
Your update is ready to install. Please shutdown to finish the update process.
Creating stage BE...
Created successfully
Mounting the stage BE...
Running: cp /var/db/pc-updatemanager/.newPkgUpdateList /.updateStage/install-pkg-list
Running: mount -t devfs devfs /.updateStage/dev
Running: cp /var/log/Xorg.0.log /.updateStage/var/log/Xorg.0.log
Can't locate FreeBSD-Runtime-development package: FreeBSD-runtime-development-12.0.s20170621011908.txz
Failed incremental pkg upgrade! Doing full package upgrade now.
Installing packages to stage BE... (This may take a while)
Running: chroot /.updateStage sh /.doPkgUp.sh
chroot: sh: No such file or directory
Destroyed successfully
Error 1: chroot /.updateStage sh /.doPkgUp.sh
ERROR: Error 1: chroot /.updateStage sh /.doPkgUp.sh
Unmounting stage BE...
Copy upgrade.log to new BE...
Running: cp /var/db/pc-updatemanager/.pkgUpdateLog /.updateStage/usr/local/log/pc-updatemanager/upgrade.log
Determine new BE name...
Cleanup mounts...
Update file failed verification...

**Comment by RodMyers** [comment]
premature anticipation.

the cdn network was still trying to sync STABLE & UNSTABLE

You're download was no complete. Your computer never downloaded the FreeBSD packages

**Comment by danboid** [comment]
pc-updatemanager pkgupdate has just worked and installed its updates but:

pc-updatemanager check                                                                                                                                         
Boot-strapping updater...OK                                                                                                                                                                   
Update file failed verification...                                                                                                                                                            
ERROR: Update file failed verification...     

Doesn't look so promising. Surely the CDNs can't still be syncing 10 hours later?

It'd be nice if pc-updatemanager was aware when the CDN syncs are taking place and prevent you from updating if it will fail.
