### ISSUE TITLE
Haswell GPU machine - cannot complete installation

### ISSUE THREAD

**Issue by danboid** [trueos/trueos-core#1447]
I have tried and failed to install every TrueOS release that came out in June, the latest being TrueOS-2017-06-23-x64-USB.img. They have all failed the same way - the bulk of the installation goes without a hitch until the very last screen that tells you the installation is complete, then as soon as I click 'Finish' I get a garbled display like in the attached screenshot and I'm forced into power cyclng my laptop.

TrueOS then boots into the first run setup program but I am unable to progress past the first screen which asks you to select a graphics driver. Regardless of if I click 'Skip' or I select one of the valid drivers for my GPU (intel, modesetting, VESA or scfb) then agree to testing it, I always get the same result - the same garbled mess of junk gets displayed on the screen and I have no other option than to poweroff.

I'm trying to install into a FreeBSD bootenv on a Haswell i7 with a HD4600 GPU. The most recent TrueOS install image that installs without issue that I have tried is from April, before the new GPU driver options were added.

![barf](https://user-images.githubusercontent.com/1429783/27520551-8c233616-59fd-11e7-9091-be96d36bad8e.jpg)

**Comment by Mrt134** [comment]
Thanks for reporting this!

**Comment by danboid** [comment]
I believe my probs installing recent releases of TrueOS are related to this ticket:

https://github.com/trueos/trueos-core/issues/1457

Newer versions of the TrueOS installer (since about May) seem to enforce the running of the Change Video Driver helper on first boot and I've just borked X on what was a perfectly running install by trying to use Change Video Driver from within PCDM.

**Comment by Mrt134** [comment]
It appears this has since been fixed, but please update if this still an issue on latest UNSTABLE and I'll reopen. Thanks!
