### ISSUE TITLE
installer crashes when trying to reinstall in a dual-boot setup

### ISSUE THREAD

**Issue by mheily** [trueos/trueos-core#145]
*Synopsis*

When TrueOS is installed as the second OS in a dual-boot setup, if you try to reinstall TrueOS, the installer will crash.

*Steps to reproduce*

Given a new laptop with a factory Windows installation:
1. Shrink the Windows partition
2. Install TrueOS into the unused space on the drive
1. Attempt to reinstall TrueOS by selecting the same partition as you did the first time around

*What happens*

The installer crashes with a message saying "no more free space"

*Workaround*

I was able to workaround this by dropping to an emergency shell and using gpart to delete both TrueOS partitions. The commands were:

gpart delete -i 5 nvd0
gpart delete -i 6 nvd0

After deleting the partitions, the reinstall was successful.

*Comments*

I believe this is caused by the mishandling of the swap space partition. During the initial TrueOS install, a small swap partition was automatically created. During the second install, it appears the installer does not detect the existing swap partition, and tries to create a new one instead. Since there is no space left on the device, it fails.

**Comment by mheily** [comment]
Another quirk I discovered is that after reinstalling, the ZFS pool will be named "tank1" instead of the default "tank". I think that to avoid this, the pool needs to be destroyed before the partitions are deleted; e.g: 
```
zpool destroy tank
gpart delete -i 5 nvd0
gpart delete -i 6 nvd0
```

**Comment by patryk-s** [comment]
I think the default is "tank1", it's in the handbook and on my fresh install.

**Comment by grahamperrin** [comment]
> … "tank1" instead of the default "tank" …

Enhancement request: #146

**Comment by pkgdemon** [comment]
This seems to be working in the upcoming images.  The tank, and tank1 alternating is expected, and required to work around another issue.  Alternativley dozer the other matrix character could be used for alternating.  It just cannot be the same for a reinstall without destroying the entire partition table from my understanding.
