### ISSUE TITLE
sysadm: auto-populate BE clone name with name of BE being cloned

### ISSUE THREAD

**Issue by danboid** [trueos/trueos-core#1454]
When you clone a boot environment with sysadm currently, you get presented with an empty text entry box. It would be nicer if it auto-populated it with the name of the BE being cloned so the user can easily add a prefix or suffix.

**Comment by Mrt134** [comment]
Thanks for the suggestion!

**Comment by beanpole135** [comment]
Done!

https://github.com/trueos/sysadm-ui-qt/commit/7a7466df55dd3f43af208aab63cd53689bec1eb1
