### ISSUE TITLE
Bittorrent files: Web seeds are not built with correct URLs

### ISSUE THREAD

**Issue by baitisj** [trueos/trueos-core#1456]
Currently the web seeds are built with the following URL:
http://download.trueos.org/**master**/amd64/TrueOS-2017-07-14-x64-USB.img

This used to be correct, but has changed. Now, the correct web seed URL should be:
http://download.trueos.org/**unstable**/amd64/TrueOS-2017-07-14-x64-USB.img

As a result, the files cannot be downloaded by BitTorrent as there is no original seed available.

**Comment by Mrt134** [comment]
This appears to be fixed now, thanks for reporting it!
