### ISSUE TITLE
Screenshot in installer

### ISSUE THREAD

**Issue by cconrad** [trueos/trueos-core#1459]
Hi

I'm not sure if this is the right place to report this, because technically nothing is broken, but... from a marketing perspective, I think the screenshot below (displayed within the installer) should be improved. 

This screenshot of the Discourse forum has a topic called "Tried to install TrueOS today - no luck" at the top. While this is refreshingly honest, I feel it could unnecessarily worry some new users. Also, the resolution of the screenshot is quite bad.

![image](https://user-images.githubusercontent.com/584491/28720595-f209cc82-73ad-11e7-856d-14debf7c141f.png)

Best regards,
Claus

**Comment by Mrt134** [comment]
Agreed. I've been planning on updating/changing that one for some time, but it keeps getting lost amidst all the other stuff that needs to be done. I'll make sure it gets updated. :)

**Comment by Mrt134** [comment]
Updated in commit f1203c645bb28f785723d6a25d0b1055819a1caf - thanks for the report!
