### ISSUE TITLE
Allow the name of the pool to be set predictably at time of installation; so (for example) 'tank' should not become 'tank1'

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#146]
Enhancement request. 

https://diigo.com/091q56 for an annotated view of [Destroy GPT partition scheme absolutely, how?](https://lists.freebsd.org/pipermail/freebsd-current/2016-October/063501.html) (2016-10-04). 

## Background

From [note 1](https://bugs.pcbsd.org/issues/11363#note-1) under _Bug #11363: CURRENT, MBR, installation stuck at 'Clearing partition data...' (dd, 3880k) - PCBSD - Bug Tracking System_ (2015-09-11), with added emphasis:

> … patch (kludge) that we put in the latest PC-BSD images to make sure all ZFS backup data is erased from the drive on **re**-installation. We found a bug in the way that some disk managers (i.e. windows) handle deleting partitions and leaving data remnants behind. We are working on a better way going forward that won't take so much time during installation to complete, but it is entirely dependent on FreeBSD support from the maintainers. …

If I recall/understand correctly: 

- _backup_ there refers to _backup GPT data structures_ (probably not specific to ZFS, but affecting TrueOS (and PC-BSD) use of ZFS)
- the naming inconsistency is a side-effect of a more recent approach to dealing with those data structures

– and of the two approaches, the more recent is debatably more palatable (less likely to be misconstrued as a _stuck_ installation).

**Comment by pkgdemon** [comment]
I just reinstalled to a system which had "tank" previously setup, and under advanced I set the name "tank.  Afterwords the system booted fine so this is working now.  I do not want to change the installer to always set tank again in case it proves to cause an issue again in the future.  We tried that previously, and it caused more trouble than it was worth.
