### ISSUE TITLE
login screen: display more WM/DE options?

### ISSUE THREAD

**Issue by jungle-boogie** [trueos/trueos-core#1460]
Hi All,

I installed cwm via pkg:
https://www.freshports.org/x11-wm/cwm

However, I can't exactly start this while I'm in Lumia, and I'm not quite sure how to start it at all.
When I am at the login screen, I noticed I can select fluxbox or Lumina. I'm assuming Fluxbox is listed because for now, Lumina needs it. 

How would I start cwm and is it possible to have it listed in the drop down box?

If any of the above isn't accurate, please forgive me. I'm not real knowledgeable with window managers and desktop environments. You're more than welcome to direct me to some documentation to understand these two things better, though.

Thanks!

**Comment by beanpole135** [comment]
WM and DE registration is typically done by the relevant package or project, but PCDM does have a small collection of registration files for smaller WM's that it pre-registers (ones that are known to not follow the specs). If you like, you could add one for cwm to the list. https://github.com/trueos/pcdm/tree/master/src-qt5/xsessions

**Comment by beanpole135** [comment]
Oh, the .desktop files are installed in /usr/local/share/xsessions FYI. You can put one there on your system to try it out and get it working before sending it in... 😉
