### ISSUE TITLE
VM Ware guest option during installation

### ISSUE THREAD

**Issue by Passaita** [trueos/trueos-core#1461]
I am installing TrueOS under ESXi environment and selecting WM Ware guest option during installation didn't install open-vm-tools. Is this my wrong expectation or a system bug? What does this option is affecting then?

**Comment by beanpole135** [comment]
The VMWare video driver option was only installing the xf86-video-vmware graphics driver. I just changed this to also install the open-vm-tools when that option is checked.

https://github.com/trueos/trueos-utils-qt5/commit/d0df7b36540cbad2ca3a34913663efeab7934a59
