### ISSUE TITLE
can't find iocage?

### ISSUE THREAD

**Issue by jungle-boogie** [trueos/trueos-core#1464]
Hi All,

I would really prefer to install `iocage` from its github src, but there's an outstanding issue with one of the dependencies on trueOS.

That means I'll use pkg for this - no problem!

I often use freshports for my pkg/port reference:
https://www.freshports.org/sysutils/py3-iocage/

```
% sudo pkg install py36-iocage
Updating trueos-base repository catalogue...
trueos-base repository is up to date.
Updating trueos-major repository catalogue...
trueos-major repository is up to date.
All repositories are up to date.
pkg-static: No packages available to install matching 'py36-iocage' have been found in the repositories
```

I see it here with a slightly different name:
https://github.com/trueos/freebsd-ports/tree/trueos-master/sysutils/py3-iocage

```
% sudo pkg install sysutils/py3-iocage
Updating trueos-base repository catalogue...
trueos-base repository is up to date.
Updating trueos-major repository catalogue...
trueos-major repository is up to date.
All repositories are up to date.
pkg-static: No packages available to install matching 'sysutils/py3-iocage' have been found in the repositories
```

**questions:**
where is iocage?
Why does my pkg say `pkg-static`?
Can YOU install iocage? If so, how?

**Comment by beanpole135** [comment]
Unfortunately, the iocage package (py3-iocage: sysutils/py3-iocage) is failing to build right now due to a `py3-libzfs` package build failure. We are looking into this and hope to get this resolved soon.

**Comment by beanpole135** [comment]
FYI: The build failure for py3-libzfs appears to be a port issue with a stale patch[1].

[1] https://builds.ixsystems.com/chimaera/data/unstable-trueosports/2017-08-05_12h33m09s/logs/errors/py27-libzfs-1.0.20170606.log

**Comment by asomers** [comment]
@beanpole135 iocage actually depends on py3-libzfs, not py-libzfs.  Though it seems that both ports are affected by the same patch problem.  It looks like TrueOS commit 804fc1221c31a6896f182adc796417d1ce2c388b by @kmoore134  is conflicting with the more recent FreeBSD ports commit r442781.
https://builds.ixsystems.com/chimaera/data/unstable-trueosports/2017-08-05_12h33m09s/logs/errors/py36-libzfs-1.0.20170606.log

**Comment by asomers** [comment]
Looks like those patches have been upstreamed, so you can just remove them.  I'll test and open a PR.

**Comment by asomers** [comment]
Fixed by https://github.com/trueos/freebsd-ports/commit/f4d793312046b69168d3af3cdc54d627e00268ca

**Comment by jungle-boogie** [comment]
Thank you! I updated the pkgs last night and I can now install iocage version 0.99.1

Many thanks to @asomers for fixing this!
