### ISSUE TITLE
5/6 August update fails

### ISSUE THREAD

**Issue by RodMyers** [trueos/trueos-core#1466]
Update runs fine, upon reboot, WiFi connects, vidalia/Tor sync with the net

Firefox/Thunderbird segfault, and never open, as does midori.

Qupzilla/opera never get online, hanging while trying

bad BE saved for reference

**Comment by q5sys** [comment]
Can you run whatever programs aren't running from the CLI and see if anything is spit out as an error?

**Comment by RodMyers** [comment]
segfault, and closes

**Comment by RodMyers** [comment]
grabbing the packages a 2nd time, and creating a 2nd account, to see if it's my ~/HOME directory

**Comment by RodMyers** [comment]
same issue for Firefox & thunderbird

firefox 
1502034802074   addons.webextension.jid1-s2tSKqH4h0BHUw@jetpack WARN    Please specify whether you want browser_style or not in your browser_action options.
Segmentation fault


[rodney@watton] ~% thunderbird
Segmentation fault

**Comment by RodMyers** [comment]
attempted upgrade again, download, etc

Still seg fault even with the "--safe-mode" entry

**Comment by darkfiberiru** [comment]
Is this the July-28th build if you look at the kernel?

**Comment by beanpole135** [comment]
There appears to have been a slight issue with the CDN over this last weekend which resulted in the wrong packages being seen/used during the upgrade routine. This has already been fixed.

Please revert to the previous/good boot environment and you should be able to do updates properly now.

**Comment by RodMyers** [comment]
just rebooted after 4th update this morning, update still fails same way firfox/thunderbird still seg faulting

**Comment by RodMyers** [comment]
just rebooted after 4th update this morning, update still fails same way firfox/thunderbird still seg faulting

**Comment by VulcanRidr** [comment]
My laptop (IBM T530) just upgraded last night, and I am having the same firefox failing to load issue as Rodney. I am not seeing a similar issue on my desktop machine. The error I am getting is

1502182112912   addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack WARN    Loading extension 'jid1-MnnxcxisBPnSXQ@jetpack': Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.
1502182112947   addons.webextension.jid1-MnnxcxisBPnSXQ@jetpack WARN    Please specify whether you want browser_style or not in your browser_action options.
Segmentation fault

Note that my desktop is not having the same issue. Both the desktop and the laptop have firefox-54.0.1_1,1 installed, both have kernel version:

FreeBSD yukon.sonsofthunder.nanobit.org 12.0-CURRENT FreeBSD 12.0-CURRENT #1 57b410cea(drm-next): Fri Jul 28 21:44:30 UTC 2017     root@chimera:/usr/obj/usr/src/sys/GENERIC  amd64

The main differences between them is the desktop is running on an AMD processor with an nVidia video card, while the laptop is Intel and Intel.

**Comment by RodMyers** [comment]
Mine is a Lenovo T520

**Comment by jungle-boogie** [comment]
Are the mozilla applications the only ones crashing? Does qupzilla crash?

**Comment by RodMyers** [comment]
for me, just thunderbird/firefox.

qupzilla opened and browsed just fine

**Comment by RodMyers** [comment]
after talking with @pkgdemon I tried to force firefox install after upgrade. no go.

I have 4 BE's. I attempted to force upgrade each one of them, same result "seg fault" for firefox/thunderbird

**Comment by VulcanRidr** [comment]
For me, I was able to open both qupzilla and chromium, but both crashed relatively quickly. Chrome with an abort trap, and qupzilla with a segmentation fault. I can produce a qupzilla crashlog, and maybe the chrome log...

**Comment by jungle-boogie** [comment]
I held my berth last night and updated. After the upgrade was completed, I was able to open qupzilla dn firefox without crashing. I didn't navigate too much in either browser. I did notice icons on qupzilla were extra large, which I definitely didn't have it set before.

I don't have thunderbird installed at this time.

**Comment by vestein463** [comment]
I have have problems with these update also, kernel 57b410cea(drm-next) from Jul 28 21:44.

sysadm-client crashes on signal 11
after that lumina-desktop signal 11
and PCDM-session signal 6
and sysadm-binary signal 11

I use VESA xorg-driver at the moment, but want to go to radeon.

Perhaps my issue is caused by dbus activity (I erroneously install xfce4 before the upgrade). I deinstalled xfce but don't know how to get rid of remain dbus-daemon and dbus-launch.

I don't even know whether this dbus is needed. The only application I am interested at the moment is GNU-octave. I had at some moment a swap space fillup, but not before the unstable upgrade.

Now to the actual state of drm-next in my case:  Changing to the radeon driver does not cause error messages any more, except that the EDID information is not readable on my system, so the resolution is only basic.
My system is AMD6350 KABINI integrated graphics.

**Comment by RodMyers** [comment]
okay, I'm closing this ticket, as my issue was fixed.

in last known working BE, type the following  --> sudo pkg delete gcc-ecj

upgrade as normal, and things should work
