### ISSUE TITLE
TrueOS kernel panic after latest unstable update

### ISSUE THREAD

**Issue by ryaeng** [trueos/trueos-core#1468]
I performed an update to the system. On reboot I was presented with a kernel panic just after initializing drm. I'm currently running TrueOS on an Acer Aspire One. Please advise.

**Comment by darkfiberiru** [comment]
I'm guessing that happens every time you boot?

If at anytime you have an update go bad you can change to the old Boot Enviroment in the loader by selecting 3 and then the last boot enviroment.

This will get you up and running in your pre-upgraded state. I'm not sure if the upgrade went bad or if the last build had some major hicups.

**Comment by ryaeng** [comment]
I was able to get the system back up on the old boot evrionment. Thank you. 


7. Aug 2017 00:24 by notifications@github.com:

**Comment by beanpole135** [comment]
There appears to have been a slight issue with the CDN over this last weekend which resulted in the wrong packages being seen/used during the upgrade routine. This has already been fixed.

Please revert to the previous/good boot environment and you should be able to do updates properly now.
