### ISSUE TITLE
 $powerdxx_enable is not set properly

### ISSUE THREAD

**Issue by Mystified1234** [trueos/trueos-core#147]
Hi,
This error shoes up on every boot.
/etc/rc: WARNING: $powerdxx_enable is not set properly - see rc.conf(5)
powerd_enable
(bool) If set to YES'', enable the system power control
facility with the powerd(8) daemon.
 powerd_flags
             (str) If powerd_enable is set to ``YES'', these are the flags
             to pass to the powerd(8) daemon.

This is my /etc/rc.d/powerd++, Before any changes that were made to rectify the issue.

cat /usr/local/etc/rc.d/powerd++
 #!/bin/sh

  -### # PROVIDE: powerdxx
  -# REQUIRE: DAEMON
  -# BEFORE: LOGIN
  -# KEYWORD: nojail shutdown

. /etc/rc.subr

name="powerdxx"
rcvar="powerdxx_enable"
command="/usr/local/sbin/powerd++"
pidfile="/var/run/powerd.pid"

load_rc_config $name
run_rc_command "$1"

The following was added 

 ${powerdxx_enable:="NO"}

immediately after the line: -
load_rc_config $name

I hope this issue may be rectified in the near future !

Thanks, for a Gr8 OS & even a better technical help team.

**Comment by pkgdemon** [comment]
We removed powerdxx from trueos-desktop which will resolve.  Initially we were testing it out but found that it reduced performance drastically to have it on.  So we disabled but left the package installed which triggered that warning message.
