### ISSUE TITLE
Cannot read files with UTF-8 symbols on automounted msdosfs USB sticks

### ISSUE THREAD

**Issue by q-pa** [trueos/trueos-core#1471]
I am on up-to-date TrueOS STABLE. Automounting USB sticks works great but when there are filenames with special characters (e.g. German Umlauts) I see � symbols and cannot open the file. 

I searched a bit around and found this on the FreeBSD forums (https://forums.freebsd.org/threads/61251/):

> But, with these settings, from handbook, you won't be able to read file names with UTF-8 symbols, like unicode, arabic letters, etc.
> (Even if your system locale is a *.UTF-8 locale.)
> Also, it won't be possible to edit files on mounted with autofs file systems as a regular user, as root only…
> 
> To fix these issues, you need to edit /etc/auto_master again:
> Code:
> /media          -media          -nosuid,-m=770,-L=en_US.UTF-8

But when I tried this in TrueOS' auto_master with the autofs line with L=de_DE.UTF-8 but it does not work.  When navigating to /autofs (or the desktop icon) I only see an empty directory. I attached an excerpt from a log where I first try the changed auto_master file and in the end I changed it back and mounting works again.
[log.txt](https://github.com/trueos/trueos-core/files/1220002/log.txt)

**Comment by pkgdemon** [comment]
I suspect the change needs to happen to line 46 in this file instead.

https://github.com/trueos/freebsd/blob/drm-next/etc/autofs/special_automount

**Comment by q-pa** [comment]
This got solved for me when I found out I could add the -L option in "special_automount":

"msdosfs")
		echo "-fstype=${_fstype},nosuid,async,-L=de_DE.UTF-8,-M=777,-o=longnames	:/dev/${_p}" 

Ken commented in https://github.com/trueos/trueos-core/issues/1478 it would be difficult to automatically implement localisation for mounting USB sticks so I leave it to you to close this issue.

**Comment by Mrt134** [comment]
Ok, thanks!
