### ISSUE TITLE
Cannot see directory contents on automounted msdosfs USB sticks

### ISSUE THREAD

**Issue by q-pa** [trueos/trueos-core#1478]
`about`

> boot environment now (N) … 12.0-CURRENT-up-20170828_214245 NR 2017-08-28
>        after restart (R) … 12.0-CURRENT-up-20170828_214245 NR 2017-08-28
> boot loader …………………………………… BSD
>             type ……………………… EFI
> CPU ………………………………………………………… Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
>     number of cores ……………… 8
> host ……………………………………………………… trueos-L
> memory ………………………………………………… 16384 MB available, 13452 MB free
> OS git branch ……………………………………………………………………………………… drm-next
> OS git revision ………………………………………………………………………………… 334f3850a
> OS kernel build time ………………………………………………………… Mon 2017 Aug 14 14:53:32 UTC
> OS kernel identity …………………………………………… (uname -i) GENERIC
> OS platform (architecture) ……………………… (uname -m) amd64
> OS release level ………………………………………………… (uname -r) 12.0-CURRENT
> OS version and patch level …… (freebsd-version) 12.0-CURRENT
> TrueOS package set ………………… UNSTABLE
> TrueOS version …………………………… TrueOS-Desktop-201707111911
> uptime ………………………………………………… 12 mins
> user  …………………………………………………… delipu
> 
> More (TrueOS Desktop):
> 
>     desktop environment …… Lumina
>     sound card driver ………… pcm0: <Conexant CX20590 (Analog 2.0+HP/2.0)> (play/rec) default
>     wireless driver ……………… iwn0
>     X11 drivers ………………………… intel_drv.so

After switching to UNSTABLE, I cannot see any directory contents on the same USB sticks that used worked with STABLE (apart from some UTF-8 problem with special characters).

`dmesg`

> ...
> ugen1.4: <General USB Flash Disk> at usbus1
> umass0 on uhub3
> umass0: <General USB Flash Disk, class 0/0, rev 2.00/1.00, addr 4> on usbus1
> umass0:  SCSI over Bulk-Only; quirks = 0xc101
> umass0:4:0: Attached to scbus4
> da0 at umass-sim0 bus 0 scbus4 target 0 lun 0
> da0: <General USB Flash Disk 1.00> Removable Direct Access SCSI-2 device
> da0: Serial Number 04161010000247E8
> da0: 40.000MB/s transfers
> da0: 15283MB (31299584 512 byte sectors)
> da0: quirks=0x2<NO_6_BYTE>
> WARNING: autofs_trigger_one: request for /autofs/da0s1/ completed with error 5
> WARNING: autofs_trigger_one: request for /autofs/da0s1/ completed with error 5
> WARNING: autofs_trigger_one: request for /autofs/da0s1/ completed with error 5
> WARNING: autofs_trigger_one: request for /autofs/da0s1/ completed with error 5
> WARNING: autofs_trigger_one: request for /autofs/da0s1/ completed with error 5
> WARNING: autofs_trigger_one: request for /autofs/da0s1/ completed with error 5
> WARNING: autofs_trigger_one: request for /autofs/da0s1/ completed with error 5
> WARNING: autofs_trigger_one: request for /autofs/da0s1/ completed with error 5
> WARNING: autofs_trigger_one: request for /autofs/da0s1/ completed with error 5
> ugen1.4: <General USB Flash Disk> at usbus1 (disconnected)
> umass0: at uhub3, port 1, addr 4 (disconnected)
> da0 at umass-sim0 bus 0 scbus4 target 0 lun 0
> da0: <General USB Flash Disk 1.00>  s/n 04161010000247E8 detached
> (da0:umass-sim0:0:0:0): Periph destroyed
> umass0: detached

Lumina-FM just shows an empty directory and says 

> (Limited Access) No Directory Contents

in the lower left corner. (When opening with root permissions it just says "No Directory Contents". There are files on the stick, I double-checked.

**Comment by Mrt134** [comment]
Thanks for reporting - we'll look into it.

**Comment by q-pa** [comment]
Please find attached the corresponding lines from /var/log/messages:

[messages_usb.txt](https://github.com/trueos/trueos-core/files/1268006/messages_usb.txt)

**Comment by danboid** [comment]
I have this prob under UNSTABLE too.

**Comment by SawFishDaemon** [comment]
I have this same problem on Stable.

**Comment by beanpole135** [comment]
Fixed in source - looks like the "large" flag in the msdosfs mounting routine got removed recently and that is causing the autofs mounting routine to fail.

If you want to fix it on your system right now, you can just remove that flag from "/etc/autofs/special_autmount" (you can copy the file from here[1] if you like - look at line 46).

[1] https://github.com/trueos/freebsd/blob/drm-next/etc/autofs/special_automount


One of the commits:
https://github.com/trueos/freebsd/commit/b350c7d7daa7428c505c40cf39de13f98bc4669a

**Comment by q-pa** [comment]
Many thanks Ken! I just fixed it on my system plus I added the locale option -L for my German locale setting:

```
"msdosfs")
		echo "-fstype=${_fstype},nosuid,async,**-L=de_DE.UTF-8**,-M=777,-o=longnames	:/dev/${_p}" 
```

**Feature suggestion:** 
Would it be possible to to automatically check for the system settings and add the corresponding locale option to "special_automount"?

**Comment by q-pa** [comment]
Explanation:  the -L option was supposed to be formatted bold. It should read -L=de_DE.UTF-8, of course.

**Comment by beanpole135** [comment]
@q-pa : The locale option only works on ~50% of the msdosfs devices in my experience, so I if we hardcode it into the mounting routine then we will probably start seeing these error reports about it really quickly.
In the old mounttray, we actually had a fallback mechanism where it would try to mount it with one command, then if it failed it would try a "no locale" mounting command after that. Since we moved to autofs for the actual mounting procedures, I do not know if it is possible to use something similar again or not.

**Comment by q-pa** [comment]
OK, I agree, more bug reports would not be helpful. Maybe a note could be added in the documentation, so a willing user knows which file to modify.

By the way, will the file special_automount be overwritten with each update?

**Comment by Mrt134** [comment]
I'll look into adding a note in the documentation, perhaps some kind of comment in **etc/autofs/special_automount** would be helpful too?

**Comment by q-pa** [comment]
Thanks, that would be very helpful!
