### ISSUE TITLE
Disk Manager defaulting to 'Align partitions to 1 MB boundary' may be problematic with some types of USB flash drive

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#148]
Screen shots from yesterday and today, with a 16 GB Duracell-branded device: 

![aiming to add fat32](https://cloud.githubusercontent.com/assets/192271/20097069/8ada656c-a5a4-11e6-922f-e53081431dc8.png)

![gpart](https://cloud.githubusercontent.com/assets/192271/20097074/90648a62-a5a4-11e6-8723-2771371d6acd.png)

> **Error report**
> 
> ! 
> An error was detected while executing 'gpart':
> 
> autofill: No space left on device
> 
> OK

I had the problem with both FAT32 and UFS. Worked around by disallowing the default alignment.

**Comment by grahamperrin** [comment]
I did not reproduce this problem with a device that's probably more recent: 

- Kingston DataTraveler G4.

_If_ the default is problematic with only some types of USB flash drive _then_ maybe: 

- a failure to align partitions to 1 MB boundary could be followed by a second attempt without that alignment.

**Comment by pkgdemon** [comment]
Disk Manager was written entirely by a contributor.  We planned to retire it but it was requested we bring it back.  It's not something we will be maintaining.  Instead when time allows it will be replaced by something in sysadm.
