### ISSUE TITLE
Unstable update 09192017 varnish most of packages.

### ISSUE THREAD

**Issue by araujobsd** [trueos/trueos-core#1481]
Here you can find the logs from new and old laptop.

New laptop:
- I did install i3wm before the update, after update all other WM were deleted and only i3wm stay.

Oldlaptop:
- I didn't install anything, after update everything weren't there anymore, pc-*tools*, Xorg basically all trueos-desktop was gone.

[logs.zip](https://github.com/trueos/trueos-core/files/1314346/logs.zip)

**Comment by kmoore134** [comment]
Thanks Marcelo! Those initial logs look fine, on the system after it failed to install, can you send me the contents of /usr/local/log/pc-updatemanager/* as well?

Looks like it failed in the 2nd stage after reboot somewhere.

**Comment by araujobsd** [comment]
Hi,

I gave you access in one of my machines (New laptop) :)

Best,

**Comment by kmoore134** [comment]
After some investigation, we found the upgrade was fine, was just Lumina bug which has been fixed in newer Unstable.
