### ISSUE TITLE
GUI improvements for sysadm

### ISSUE THREAD

**Issue by JoshDW19** [trueos/trueos-core#1487]
Can we have an icon for AppCafe on the right-click menu for sysadm? Adding applications should be one of the most used functions of a desktop. This will save the user from having to perform extra clicks any time they want a quick way to get into AppCafe and add applications.

Secondly, is there any workflow reason that the label to open sysadm client can't just say "Control Panel"? A control panel is what a user would expect. When you click on sysadm > local system it brings up the "sysadm: Control Panel".  I would suggest by making the "Local System" label "Control Panel" that it is more in line with what a user would expect.

Thank you!

**Comment by Mrt134** [comment]
This issue was moved to trueos/sysadm#28
