### ISSUE TITLE
Document or provide a migration for the need to update kldload_i915kms or kld_list for new drm-next-kmod package

### ISSUE THREAD

**Issue by NorwegianRockCat** [trueos/trueos-core#1489]
With the drm-next-kmod package/port, there are two i915kms kernel modules. One supplied by the base FreeBSD system (in /boot/kernel) and one by the package (in /boot/modules). If you are using an /etc/rc.conf from a previous system, the `kldload_i915kms="i915kms"` will load the base system's module, which won't work for newer Intel systems (e.g., Sky Lake, Kaby Lake) since they need the module in /boot/modules.

Changing these settings to a full path (i.e., `kldload_i915kms=/boot/modules/i915kms.ko` or `kld_list=/boot/modules/i915kms.ko`) then the correct modules are loaded for the new Intel systems.

This either needs to be documented somewhere, or needs a good migration or Stable users are going to be bitten by this.

**Comment by kmoore134** [comment]
I've started adding a migration for this :

https://github.com/trueos/trueos-desktop/commit/967f536f4fba2911d097b884502108509d3f28d5

**Comment by NorwegianRockCat** [comment]
Great! Looked at the patch. If possible, try to catch the kld_list case too. Somewhere along the line I merged all of the different things into a kld_list instead as the manpage for rc claims that it's much quicker to load everything in one go.

**Comment by kmoore134** [comment]
There you go, this should be covered now as well. If you find other ways in which it was loaded, we'll nuke those as well.
