### ISSUE TITLE
Disk Manager might report that a device is busy when truly, it is not busy

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#149]
1. Use Disk Manager to create a file system
2. use TrueOS Desktop mount tray to mount the file system
3. use Disk Manager to destroy the slice

## Expected

4. destruction of the slice that has the non-busy file system

## Actual result

4. Disk Manager reports that the device is busy 
5. repeat step (3)
6. again, Disk Manager reports that the device is busy
7. Refresh
8. Unmount the slice to be destroyed
9. umount succeeds i.e. the file system was not busy
10. repeat step (3)
11. success. 

That's probably an edge case, but the application might be improved by: 

- an automated refresh following initial false detection of a busy state; or 
- an automated (and maybe invisible) refresh immediately after the user clicks 'Destroy this slice'.

**Comment by pkgdemon** [comment]
Disk Manager was written entirely by a contributor.  We planned to retire it but it was requested we bring it back.  It's not something we will be maintaining.  Instead when time allows it will be replaced by something in sysadm.
