### ISSUE TITLE
UNSTABLE update: hp-systray fails to start

### ISSUE THREAD

**Issue by q-pa** [trueos/trueos-core#1490]
Since this week's updates hp-systray fails to start. Re-installing hplip did not solve this issue. These are the last few lines of /var/log/messages:
...
hp-systray: hp-systray(hpssd)[2852]: error: Unable to connect to dbus system bus. Exiting.
hp-upgrade: hp-upgrade[2856]: warning:  distro is not found in AUTH_TYPES
WARNING pid 2873 (python2.7): ioctl sign-extension ioctl ffffffff80087467

**Comment by q-pa** [comment]
Sorry, my fault. Somehow dbus was disabled.

**Comment by beanpole135** [comment]
Which port/package does that service belong to?

If it required that the system dbus service be active, then the "depends" section needs to have a "need dbus" listed and then it will automatically start dbus as a required dependency. That might be something that is easily fixable....

**Comment by q-pa** [comment]
The port/package is HPLIP (drivers and utilities for HP printers...). In SysAdm, I have to explicitly set dbus to start on boot.  Only then I see the HP Device Manager task bar icon.
