### ISSUE TITLE
Libreoffice broken on current unstable

### ISSUE THREAD

**Issue by ldemouy** [trueos/trueos-core#1492]
Libreoffice appears to get stuck in an infinite loop when starting with the current TrueOS unstable. One core ends up being run up to 100% and under Lumina the window for the splash disappears and there is no Libreoffice window, under GNOME shell it shows a black window after the splash disappears. There is no output in the terminal when used to launch Libreoffice.

**Comment by RodMyers** [comment]
okay, the required, it doesn't happen to me entry

Can you type --> about  <-- and post the results here?

**Comment by ldemouy** [comment]
===================
General information
===================

boot environment now (N) … 12.0-CURRENT-201710200548-post-install-3 NR 2017-10-20
       after restart (R) … 12.0-CURRENT-201710200548-post-install-3 NR 2017-10-20
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
    number of cores ……………… 4
host ……………………………………………………… 
memory ………………………………………………… 16384 MB available, 13591 MB free
OS git branch ……………………………………………………………………………………… trueos-master
OS git revision ………………………………………………………………………………… 88c007ae5
OS kernel build time ………………………………………………………… Sat 2017 Oct 14 20:33:43 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… UNSTABLE
TrueOS version …………………………… TrueOS-Desktop-201710161221
uptime ………………………………………………… 2:22
user  …………………………………………………… 

More (TrueOS Desktop):

    desktop environment …… Lumina
    sound card driver ………… pcm0: <Realtek ALC269 (Analog 2.0+HP/2.0)> (play/rec) default
    wireless driver ……………… iwn0
    X11 drivers ………………………… modesetting_drv.so

**Comment by ldemouy** [comment]
Also happens on a Ryzen 1700 with an R7 285 running amdgpu, same version of unstable

**Comment by RodMyers** [comment]
I just did a fresh install, and no loop.~/.libreoffice directory and try?

about

===================
General information
===================

boot environment now (N) … initial NR 2017-10-21
       after restart (R) … initial NR 2017-10-21
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
    number of cores ……………… 4
host ……………………………………………………… lenovo
memory ………………………………………………… 8192 MB available, 2966 MB free
OS git branch ……………………………………………………………………………………… trueos-master
OS git revision ………………………………………………………………………………… 88c007ae5
OS kernel build time ………………………………………………………… Sat 2017 Oct 14 20:33:43 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… UNSTABLE
TrueOS version …………………………… TrueOS-Desktop-201710161221
uptime ………………………………………………… 2 hrs
user  …………………………………………………… rodney

More (TrueOS Desktop):

    desktop environment …… Lumina
    sound card driver ………… pcm1: <Realtek ALC292 (Analog)> (play/rec) default
    wireless driver ……………… iwm0
    X11 drivers ………………………… modesetting_drv.so

**Comment by ldemouy** [comment]
So oddly enough deleting the ~/.config/libreoffice folder does restore libreoffice to full functionality on both machines, but my current assumption is that there's some incompatibility between libreoffice on Stable vs Unstable as both machines were upgraded from Stable to Unstable to take advantage of the new graphics support.

**Comment by RodMyers** [comment]
STABLE --     libreoffice-5.3.3
UNSTABLE - libreoffice-5.3.6_4

shouldn't make a difference.

What that tells me, something in the  ~/.libreoffice folders was corrupt, and nothing to do with STABLE or UNSTABLE :-(

**Comment by beanpole135** [comment]
I just tested this out on UNSTABLE and I could not reproduce the crash either.

This does indeed appear to be something in your particular LibreOffice settings which got corrupted rather than something systemic on TrueOS.
