### ISSUE TITLE
Please change the name of latest.iso

### ISSUE THREAD

**Issue by JoshDW19** [trueos/trueos-core#1495]
This is a reminder for Kris. We need to change the name of latest.iso to something a little more descriptive like latest-stable and latest-unstable. Please let me know when you have some free time to do this so I can switch the website over to the new path.

**Comment by yater** [comment]
This is a hint for Josh. :-p Please don't forget the _.img_. (This is a hint to improve the website. For the "real" TrueOS use case (installing directly to hardware) a lot of users are (downloading and) using the USB images. Or am I wrong?)

**Comment by Baemir** [comment]
@yater As a new user, I was wondering why I was given a .iso file that was incompatible with flash drives. The big download button should link to whatever works with USB drives; I doubt a lot of people are still using DVDs to install OSs.

**Comment by beanpole135** [comment]
This has been fixed on the website.
