### ISSUE TITLE
SetupInstall.sh copies /boot/pc-autoinstall.conf to /tmp; TrueOSStart.sh searches for it in /

### ISSUE THREAD

**Issue by rostwald** [trueos/trueos-core#1497]
There seems to be a discrepancy on where the pc-autoinstall.conf should be put:

/root/TrueOSStart.sh searches for the pc-autoinstall.conf file at the filesystem root, but if pc-autoinstall.conf has been placed in /boot, /etc/SetupInstall.sh copies it (+ pc-sysinstall.conf) to /tmp.

Either the code in SetupInstall.sh is obsolete (if we assume pc-autoinstall.conf is meant to be placed in /), or TrueOSStart.sh should look for it in /tmp.
Additionally, as per the comments in /usr/local/share/pc-sysinstall/examples/pc-autoinstall.conf the file should be placed in /boot.

Detailed description:
The TrueOSStart.sh script is contained in uzip/root-dist.txz on the install medium and is extracted to /root by /etc/trueos-rc.sh. The script is responsible for starting either pc-sysinstall for automated installation or the graphical installer.

At boot time, before trueos-rc.sh hands over to openrc, it runs /etc/SetupInstall.sh which checks for 
"pc-autoinstall.conf" and "pc-sysinstall.conf" in /boot/ and, if present, copies them to /tmp (because / is usually read-only for the install environment)
https://github.com/trueos/trueos-core/blob/12390b031008799fd7094cc382eda5b90146e36c/overlays/install-overlay/etc/SetupInstall.sh#L23-L24
https://github.com/trueos/trueos-core/blob/12390b031008799fd7094cc382eda5b90146e36c/overlays/install-overlay/etc/SetupInstall.sh#L27

However, TrueOSStart.sh tries to locate the "pc-autoinstall.conf" at the filesystem root:
https://github.com/trueos/trueos-core/blob/12390b031008799fd7094cc382eda5b90146e36c/overlays/install-overlay/root/TrueOSStart.sh#L90-L91

The path to pc-sysinstall.conf in pc-autoinstall.conf is not changed, therefore the copy in /tmp is never used and the original file may not be accessible later (?).

The "cleanest" solution (i.e. less code) would be to remove the whole copying routine from SetupInstall.sh:
https://github.com/trueos/trueos-core/blob/12390b031008799fd7094cc382eda5b90146e36c/overlays/install-overlay/etc/SetupInstall.sh#L23-L45
This would imply enforcing to put pc-autoinstall.conf in the filesystem root of the install media and rely on the user to ensure that pc-sysinstall.conf is placed somewhere it is accessible later when pc-sysinstall is run by TrueOSStart.sh
This would break any deployment where pc-autoinstall.conf is placed in /boot as the comments in /usr/local/share/pc-sysinstall/examples/pc-autoinstall.conf suggests.

The most permissive solution would be to extend the file-check and copying routine in SetupInstall.sh, so pc-autoinstall.conf can be fetched from both locations, and then change the path to pc-sysinstall.conf in it, so it is also fetched from /tmp.
This also ensures that pc-sysinstall.conf is still accessible when TrueOSStart.sh runs pc-sysinstall

I've created a pull request for the latter solution:
#1496

**Comment by beanpole135** [comment]
Fix merged!
Thanks for sending that in!
