### ISSUE TITLE
fastboot (android-tools-fastboot) reboots computer

### ISSUE THREAD

**Issue by RodMyers** [trueos/trueos-core#1499]
With the recent upgrade, was attempting to change/update custom recovery, so I attempted to make sure deice was found, using;

fastboot  devices

lenovo thinkpad t520 immediately started shutdown/reboot process. As soon as it rebooted, from the terminal, used the same command above. Immediate shutdown/reboot. So NOT a lumina problem

 about

===================
General information
===================

boot environment now (N) … 12.0-CURRENT-up-20171115_080031 NR 2017-11-15
       after restart (R) … 12.0-CURRENT-up-20171115_080031 NR 2017-11-15
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
    number of cores ……………… 4
host ……………………………………………………… laptop.hitwe-8.org
memory ………………………………………………… 12288 MB available, 9319 MB free
OS git branch ……………………………………………………………………………………… trueos-master
OS git revision ………………………………………………………………………………… 67a4643eb
OS kernel build time ………………………………………………………… Wed 2017 Nov 8 18:09:27 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… UNSTABLE
TrueOS version …………………………… TrueOS-Desktop-201710251909
uptime ………………………………………………… 2:47
user  …………………………………………………… rodney

More (TrueOS Desktop):

    desktop environment …… Lumina
    sound card driver ………… pcm0: <Conexant CX20590 (Analog 2.0+HP/2.0)> (play/rec) default
    wireless driver ……………… iwn0
    X11 drivers ………………………… modesetting_drv.so

**Comment by beanpole135** [comment]
Tracked this down.
Running "fastboot" runs "/sbin/fastboot" - a utility for dumping the system state into flash memory or some such thing.
To run the "fastboot" from the package (an android tool), you need to specify "/usr/local/bin/fastboot", or make some kind of symlink for that binary to give it a different name.
Example:
```
sudo ln -s /usr/local/bin/fastboot /usr/local/bin/fastboot-android
```
then running "fastboot-android" will run the utility from the package.
