### ISSUE TITLE
TrueOS mount tray: for a file system that is set to Auto-run, mount is not automated

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#150]
## Environment

- USB flash drive
- MBR
- a500 (FreeBSD disklabel). 

```
$ freebsd-version ; uname -a
12.0-CURRENT
FreeBSD momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #14 1717ae3(drm-next-4.7): Fri Oct 28 13:49:49 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
$ 
```

## Steps

1. In the mount tray dialogue
2. alongside what is to be automatically mounted, check [*] Auto-Run
3. Mount
4. Unmount
5. to escape, click away from the tray dialogue
6. disconnect the drive
7. reconnect the drive
8. after the drive appears to be ready (e.g. after its light ceases to flash), review the mount tray dialogue

## Expected

9. mount of the file system

## Actual result

9. no mount **and** [ ] Auto-Run is no longer checked.

**Comment by grahamperrin** [comment]
Reproduced with msdosfs; 

```
$ gpart show /dev/da1
=>      63  32358337  da1  MBR  (15G)
        63  32356352    1  fat32  (15G)
  32356415      1985       - free -  (993K)

$ 
```

– after steps (1)–(8) the end result (9) is the same; 

> no mount **and** [ ] Auto-Run is no longer checked.

**Comment by pkgdemon** [comment]
The autorun setting does not get saved.  The filesystem has to be remounted.

**Comment by pkgdemon** [comment]
Mounttray is being depreciated this week.  I have sent in the pull requests for the new devd based automounter to replace it.

**Comment by pkgdemon** [comment]
Mounttray is being depreciated this week.  I have sent in the pull requests for the new devd based automounter to replace it.
