### ISSUE TITLE
Problem with 'ping' command

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/trueos-core#1508]
Problem with 'ping' command.

[dmitry@trueos-2449] ~% ping trueos.org
Shared object "libcasper.so.0" not found, required by "ping"

[dmitry@trueos-2449] ~% about

General information

boot environment now (N) … 12.0-CURRENT-up-20171121_054630 NR 2017-11-21
       after restart (R) … 12.0-CURRENT-up-20171121_054630 NR 2017-11-21
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Pentium(R) CPU  N3700  @ 1.60GHz
    number of cores ……………… 4
host ……………………………………………………… trueos-2449.local
memory ………………………………………………… 4096 MB available, 2227 MB free
OS git branch ……………………………………………………………………………………… trueos-master
OS git revision ………………………………………………………………………………… 67a4643eb
OS kernel build time ………………………………………………………… Wed 2017 Nov 8 18:09:27 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… UNSTABLE
TrueOS version …………………………… TrueOS-Desktop-201711140940
uptime ………………………………………………… 4:45
user  …………………………………………………… dmitry
                                                                                                                                                                                              
More (TrueOS Desktop):
        
desktop environment …… Lumina                                                                                                                                                             
sound card driver ………… pcm1: <Realtek ALC283 (Front Analog Headphones)> (play) default                                                                                                    
wireless driver ……………… iwm0
X11 drivers ………………………… modesetting_drv.so

**Comment by RodMyers** [comment]
quickly looking at my UNSTABLE, if I type 

locate libcasper
/lib/libcasper.so.0
/usr/include/libcasper_service.h
/usr/include/libcasper.h
/usr/lib/debug/lib/libcasper.so.0.debug
/usr/lib/debug/usr/lib32/libcasper.so.0.debug
/usr/lib/debug/usr/tests/lib/libcasper
/usr/lib/debug/usr/tests/lib/libcasper/services
/usr/lib/debug/usr/tests/lib/libcasper/services/cap_dns
/usr/lib/debug/usr/tests/lib/libcasper/services/cap_dns/dns_test.debug
/usr/lib/debug/usr/tests/lib/libcasper/services/cap_grp
/usr/lib/debug/usr/tests/lib/libcasper/services/cap_grp/grp_test.debug
/usr/lib/debug/usr/tests/lib/libcasper/services/cap_pwd
/usr/lib/debug/usr/tests/lib/libcasper/services/cap_pwd/pwd_test.debug
/usr/lib/debug/usr/tests/lib/libcasper/services/cap_sysctl
/usr/lib/debug/usr/tests/lib/libcasper/services/cap_sysctl/sysctl_test.debug
/usr/lib/libcasper_p.a
/usr/lib/libcasper.a
/usr/lib/libcasper.so
/usr/lib32/libcasper_p.a
/usr/lib32/libcasper.a
/usr/lib32/libcasper.so
/usr/lib32/libcasper.so.0
/usr/local/lib/perl5/site_perl/mach/5.24/libcasper_service.ph
/usr/local/lib/perl5/site_perl/mach/5.24/libcasper.ph
/usr/local/pkg-cache/FreeBSD-libcasper-12.0.s20171019193822-6ae18711ba.txz
/usr/local/pkg-cache/FreeBSD-libcasper-12.0.s20171019193822.txz
/usr/local/pkg-cache/FreeBSD-libcasper-debug-12.0.s20171019193822-0e2bc78e93.txz
/usr/local/pkg-cache/FreeBSD-libcasper-debug-12.0.s20171019193822.txz
/usr/local/pkg-cache/FreeBSD-libcasper-development-12.0.s20171019193822-ba0b48a01f.txz
/usr/local/pkg-cache/FreeBSD-libcasper-development-12.0.s20171019193822.txz
/usr/local/pkg-cache/FreeBSD-libcasper-lib32-12.0.s20171019193822-f90e50705b.txz
/usr/local/pkg-cache/FreeBSD-libcasper-lib32-12.0.s20171019193822.txz
/usr/local/pkg-cache/FreeBSD-libcasper-lib32-debug-12.0.s20171019193822-fe6a281380.txz
/usr/local/pkg-cache/FreeBSD-libcasper-lib32-debug-12.0.s20171019193822.txz
/usr/local/pkg-cache/FreeBSD-libcasper-lib32-development-12.0.s20171019193822-0ff0b6f7c8.txz
/usr/local/pkg-cache/FreeBSD-libcasper-lib32-development-12.0.s20171019193822.txz
/usr/local/pkg-cache/FreeBSD-libcasper-lib32-profile-12.0.s20171019193822-f0eaf6cd74.txz
/usr/local/pkg-cache/FreeBSD-libcasper-lib32-profile-12.0.s20171019193822.txz                                                                                           
/usr/local/pkg-cache/FreeBSD-libcasper-profile-12.0.s20171019193822-ff4c8c1235.txz                                                                                      
/usr/local/pkg-cache/FreeBSD-libcasper-profile-12.0.s20171019193822.txz

It "appears" that you are missing a FreeBSD package or two

Can you go back one or two BE's (boot envireoments) and upgrade again. and watch to make sure you do not get the dreaded "mis-match error"

**Comment by DmitryPostolov** [comment]
Rod, I am re-download latest UNSTABLE TrueOS image, check MD5 (all OK) and reinstall UNSTABLE TrueOS from usb-stick with select Russian language and update TrueOS. The problem with 'ping' command and "Shared object "libcasper.so.0" not found, required by 'ping'" remain. Also I am try to delete latest BE and update again - no success, problem remain. Can you try clean install latest TrueOS UNSTABLE image from usb-stick and test 'ping' command?

**Comment by RodMyers** [comment]
just did a fresh  install on this Lenovo X1 Carbon. Lo and behold, you are correct.

Devs have been notified

**Comment by RodMyers** [comment]
Going to close this issue. A FreeBSD issue. Will attach when I get access to computer

**Comment by beanpole135** [comment]
This was already fixed upstream in FreeBSD[1], and we pulled this into the TrueOS tree in the latest sync. The new build with this fix is churning now - should be ready on Friday or early next week.

[1] https://github.com/freebsd/freebsd/commit/7a4fdbc7adff80fa1d097a2d686fecb8b644d0cd
