### ISSUE TITLE
Disk Manager: whenever a file system is mounted, automate a refresh to occur ASAP after the mount

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#151]
I see that a refresh of Disk Manager does not occur when a file system is mounted _manually_ with something other than Disk Manager. 

Also, I assume (#150 prevents me from knowing) that a refresh does not occur when a file system is mounted _automatically_. 

## Enhancement request

Automated refresh. And if Disk Manger is busy when something triggers a refresh, then queue the automation to occur ASAP after the busy period ends. 

Priority: maybe nice to have after more important things have been achieved with OpenRC :-)

**Comment by grahamperrin** [comment]
## Afterthought

Additional triggers for a refresh might include: 

- change of state of any device or slice
- addition, or removal, of any device …

**Comment by pkgdemon** [comment]
Disk Manager was written entirely by a contributor.  We planned to retire it but it was requested we bring it back.  It's not something we will be maintaining.  Instead when time allows it will be replaced by something in sysadm.
