### ISSUE TITLE
screen garbled after text bootloader

### ISSUE THREAD

**Issue by i3fe-at-work** [trueos/trueos-core#1516]
I have a problem with installing TrueOS. No matter what I try I cannot get the installer give good output on my display when I boot in UEFI mode. But it works if I do legacy mode. The trouble is that I need UEFI mode so that I can multi-boot with windows and ubuntu.

The graphics detected show up as Haswell ULT. 

The installer used was. 
TrueOS-Desktop-2017-12-12-UNSTABLE-x64-USB.img

**Comment by RodMyers** [comment]
why not close this and then ask a question over on https://discourse.trueos.org ?
