### ISSUE TITLE
pc-netmanager 'static ip' no gateway

### ISSUE THREAD

**Issue by hardcodes** [trueos/trueos-core#152]
If you configure a network card with pc-netmanager,
choose 'Configure' ,
check 'Assign static IP address',
there is no textbox the enter the address of a (standard-)IPv4-gateway for that connection.

After choosing 'Apply' there is some IPv6 entry in the 'Info' tab.

**Comment by patryk-s** [comment]
You can set the default gateway in the "Network Configuration (Advanced)" tab.

**Comment by hardcodes** [comment]
Didn't see that, thank you. Still a per-network-interface setting is not possible, is it?

**Comment by grahamperrin** [comment]
> a per-network-interface setting is not possible

As far as I know, that's true. A few weeks ago I had a brief chat (maybe in Gitter) about the wishes/requirements where e.g. the wired interface to a notebook must use DHCP in one environment (e.g. home), must use static addressing and a specified gateway in another environment (e.g. work).
