### ISSUE TITLE
hplip complian about missing QT4 support

### ISSUE THREAD

**Issue by RodMyers** [trueos/trueos-core#1521]
attempting to get the hp-systray started. was running in the background but no system tray icon. killed it

from the terminal I run;

 hp-systray 

HP Linux Imaging and Printing System (ver. 3.17.9)
System Tray Status Service ver. 2.0

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

error: Unable to lock /usr/home/rodney/.hplip/hp-systray.lock. Is hp-systray already running?
rodney@laptop:~ % ps aux | grep hp-systray
rodney  4782 100.0  0.5  140852  58748  -  Rs   Mon21   3905:33.66 /usr/local/bin/python2.7 /usr/local/bin/hp-systray -x
rodney 68199   0.0  0.0   11500   2476  1  S+   16:39      0:00.01 grep hp-systray
rodney@laptop:~ % kill -9 4782
rodney@laptop:~ % ps aux | grep hp-systray
rodney 68240   0.0  0.0   11500   2476  1  S+   16:39      0:00.01 grep hp-systray
rodney@laptop:~ % hp-systray

HP Linux Imaging and Printing System (ver. 3.17.9)
System Tray Status Service ver. 2.0

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

error: Unable to connect to dbus system bus. Exiting.
lthemeengine: using lthemeengine plugin

HP Linux Imaging and Printing System (ver. 3.17.9)
HPLIP upgrade latest version ver. 1.0

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

sh: lsb_release: not found
cat: /etc/issue: No such file or directory
warning:  distro is not found in AUTH_TYPES
error: Unable to load Qt4 support. Is it installed?

In AppCafe, I look at the build options, and QT5 is enabled, but QT4 is disabled

**Comment by beanpole135** [comment]
The real error is this:
```
error: Unable to connect to dbus system bus. Exiting.
```

Try starting up the "dbus" system service first and that will probably fix it.
