### ISSUE TITLE
autounmountd logs too verbosely

### ISSUE THREAD

**Issue by asomers** [trueos/trueos-core#1529]
Change https://github.com/trueos/freebsd/commit/447898430a8676aa5b2a577d7761213ae5993634 put autounmountd into debug mode, probably by accident.  Nothing rotates those log files, so on my system /var/log/autounmountd is now 17GB.  Please remove the "-d", and consider adding autounmountd to newsyslog.conf.

**Comment by beanpole135** [comment]
Unfortunately, the "-d" flag is also the flag to not daemonize the process (allowing supervise-daemon to manage/restart it as needed).
```
     -d     Debug mode: increase verbosity and do not daemonize.
```

I will look into this and see if there is some way we can rotate the log files and/or turn down the verbosity level. We might need to patch the tool to add a new flag for non-daemonizing **only**.

**Comment by beanpole135** [comment]
Fixed!
https://github.com/trueos/freebsd/commit/5be7ffec526a8b87f8ef0b01b819430daf37d80e
