### ISSUE TITLE
SysAdm: Boot-Up Configuration: preferred sort order is lost

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#153]
1. Sort the list by date (chronological order)
2. remove a boot environment

## Expected

3. chronological order

## Actual result

3. reverse

----

Disorienting, with the potential for a user to subsequently accidentally remove the wrong environment, if the user intended to remove two or more.

**Comment by pkgdemon** [comment]
This is not an issue when reversing the chronological order.  Only when using chronological order.
