### ISSUE TITLE
Qupzilla content is completely black on all pages

### ISSUE THREAD

**Issue by dufresnep** [trueos/trueos-core#1533]
Qupzilla content is completely black.
I can say it's somewhat responsive, because sometimes moving the cursor at some place
show the link's address at the bottom of the window.

About info:
Application version 2.1.2
QtWebEngine version 5.7.1
© 2010-2017 David Rosca
https://www.qupzilla.com
Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/537.36 (KHTML, like Gecko) QupZilla/2.1.2 Chrome/49.0.2623.111 Safari/537.36

[paul@trueos-6310] ~% uname -a
FreeBSD trueos-6310 12.0-CURRENT FreeBSD 12.0-CURRENT #10 d26791952(trueos-stable-17.12): Sat Dec  9 18:10:09 UTC 2017     root@chimera:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
[paul@trueos-6310] ~% 

I updated about an hour a go.
Was doing the same before, first installed stable this morning.

00:02.0 VGA compatible controller: Intel Corporation 82Q963/Q965 Integrated Graphics Controller (rev 02)

**Comment by dufresnep** [comment]
By content, I means the web page content is fully black.
Trying to select stuff does not help to see through the black.

The rest of the UI seems ok, tabs, address bar, menu, etc.
It's on Lumina.
The other desktop (FVWM?), I have tried, but about no program was launching... like if it was default
programs, and it was to me to edit the config files.

**Comment by digitalist** [comment]
I remember qupzilla didn't even launch on scfb without opengl... what's your xorg video driver?

**Comment by dufresnep** [comment]
The problem seems to exist on <all> platforms from v.2:
https://github.com/QupZilla/qupzilla/issues/1943

[paul@trueos-6310] ~% cat /var/log/Xorg.0.log|grep driver
[ 18074.596]    X.Org XInput driver : 22.1
[ 18074.623] (II) Loading /usr/local/lib/xorg/modules/drivers/vesa_drv.so
[ 18074.624] (II) VESA: driver for VESA chipsets: vesa
[ 18074.624] (--) Using syscons driver with X support (version 2.0)
[ 18075.309]    ABI class: X.Org XInput driver, version 22.1
[ 18075.309] (II) Using input driver 'kbd' for 'kbdmux'
[ 18075.503]    ABI class: X.Org XInput driver, version 22.1
[ 18075.503] (II) Using input driver 'mouse' for 'sysmouse'
[paul@trueos-6310] ~% 
[paul@trueos-6310] ~% cat /var/log/Xorg.0.log | grep glx
[ 18074.597] (II) "glx" will be loaded. This was enabled by default and also specified in the config file.
[ 18074.597] (II) LoadModule: "glx"
[ 18074.608] (II) Loading /usr/local/lib/xorg/modules/extensions/libglx.so
[ 18074.610] (II) Module glx: vendor="X.Org Foundation"
[paul@trueos-6310] ~% 

[paul@trueos-6310] ~% glxinfo | more
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_fbconfig_float, GLX_ARB_framebuffer_sRGB, GLX_ARB_multisample, 


So I guess the question is, does version 2+ works for someone?

**Comment by dufresnep** [comment]
I am writing this from Qupzilla.
I tried to go to unstable, and I was still having the same problem.
After broking too much my system trying to have intel driver to work,
I reinstalled the same old stable system (12.0), from the same media...
Maybe this time, on the screen that say that ask to choose a xorg driver (because intel
failed to load), I really chosed vesa, rather then skip (last installation).

**Comment by digitalist** [comment]
I'm on unstable, and qupzilla seems to display pages just fine.

intel driver should install ok now. you can build it from ports, iirc
there should be  NO any mention of it in rc.conf (
```
#kldload_i915=""
#kld_list="/boot/modules/i915kms.ko"
)
```

here's my xorg (without fonts section), as you can see it's almost default, apart from "intel" driver line

```
Section "ServerLayout"
        Identifier     "XFree86 Configured"
        Screen      0  "Screen0" 0 0
EndSection

Section "Files"
# XFree86 configuration file for RoFreeSBIE

Section "ServerLayout"
        Identifier     "XFree86 Configured"
        Screen      0  "Screen0" 0 0
EndSection

Section "Module"
        Load  "extmod"
        Load  "record"
        Load  "dbe"
        Load  "glx"
        Load  "dri"
        Load  "dri2"
EndSection

Section "Screen"
        Identifier "Screen0"
        Device     "Card0"
        Monitor    "Monitor0"
EndSection

Section "Device"
        Identifier      "Card0"
        Driver          "intel"
        BusID           "0:2:0"
EndSection

```

also you can run qupzilla from shell, it should log its errors to stdout
