### ISSUE TITLE
USB flash drive with MBR no longer mountable after using Disk Manager to remove then create a slice

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#154]
From https://github.com/trueos/trueos-core/issues/40#issuecomment-259526931

```
$ date ; freebsd-version ; uname -a
Wed  9 Nov 2016 21:12:13 GMT
12.0-CURRENT
FreeBSD momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #14 1717ae3(drm-next-4.7): Fri Oct 28 13:49:49 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
$ gpart show /dev/da1
=>      1  3915775  da1  MBR  (1.9G)
        1  3913728    1  fat32  (1.9G)
  3913729     2047       - free -  (1.0M)

$ 
```

> Is it working? It did work before I used Disk Manager (AFAIR I destroyed a single FAT16 slice to make way for the FAT32).
> 
> Is it working? It's no longer mountable at the 14 1717ae3(drm-next-4.7) system where Disk Manager was used; this should be reported as a separate issue (from what I recall of https://github.com/trueos/pc-mounttray/issues/1 this is quite different). 

----

_If_ this is a bug in Disk Manager, then should we immediately close this issue – as something to be addressed when features are added to SysAdm?

**Comment by pkgdemon** [comment]
Yeah.  I will talk talk to the others.  I think we should remove disk manager altogether as no one wants to work on it.  Closing for now.
