### ISSUE TITLE
databases/postgresql96-server openrc script has wrong home directory

### ISSUE THREAD

**Issue by hxw** [trueos/trueos-core#1542]
The UIDs file specifies the postgres user's home in /var/db, but the openrcscript has /usr/home; I suggest the following patch to: `databases/postgresql96/files/openrc-postgresql.in`

~~~
diff --git a/databases/postgresql96-server/files/openrc-postgresql.in b/databases/postgresql96-server/files/openrc-postgresql.in
index 09472ae95d86..2c1ed5b9efa2 100644
--- a/databases/postgresql96-server/files/openrc-postgresql.in
+++ b/databases/postgresql96-server/files/openrc-postgresql.in
@@ -20,7 +20,7 @@
 : ${postgresql_class:="default"}
 : ${postgresql_profiles:=""}
 : ${postgresql_user:="%%PG_USER%%"}
-: ${postgresql_data:="/usr/home/${postgresql_user}/data96"}
+eval : ${postgresql_data:="~${postgresql_user}/data96"}
 
 # If you have any profiles defined in /etc/conf.d/postgres, e.g.:
 #   postgresql_profiles="profile1"
~~~

**Comment by beanpole135** [comment]
I just opened a pull request with the necessary changes:
https://github.com/trueos/freebsd-ports/pull/104

Note that I did not use the "eval ~" expansion: that is generally not recommended in OpenRC services and instead it just points to /var/db directly (following the examples in the rc.d service).
