### ISSUE TITLE
OpenRC wpa_supplicant

### ISSUE THREAD

**Issue by jgroenveld** [trueos/trueos-core#1545]
I believe OpenRC /etc/init.d/wpa_supplicant requires /etc/rc.subr to obtain the ltr function.
Also, something in OpenRC is trying to exec "/etc/in". Not sure where that bug lies, but if I disable wpa_supplicant by removing it from /etc/init.d, booting completes without error.

# about|grep '^TrueOS'
TrueOS package set ………………… UNSTABLE
TrueOS version …………………………… TrueOS-Desktop-201803131015
# uname -srv
FreeBSD 12.0-CURRENT FreeBSD 12.0-CURRENT #25 fa797a5a3(trueos-master): Fri Mar 23 13:28:18 UTC 2018     root@chimera:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 

John
groenveld@acm.org

**Comment by bjar** [comment]
Hi!
I run the same TrueOS version and I can't find anything in /etc/init.d/wpa_supplicant that suggests it need /etc/rc.subr. Can't find anything about the ltr function either. What kind of error message are you getting and when?

I can't trigger the second issue either. Can you supply some logs where one can see the error message and also information about when it happens?

BR
/ Bjarne

**Comment by jgroenveld** [comment]
```
I see others have hit the missing ltr function in unstable:
<URL:https://discourse.trueos.org/t/solved-unstable-previous-be-is-not-full-working/2658/13>

The exec of /etc/in has been hellish for me to track down.
Is there a OpenRC debug guide?

John
groenveld@acm.org
```

**Comment by jgroenveld** [comment]
```
Unfortunately OpenRC removed the hardlink and re-created the symbolic link for /etc/init.d/wpa_supplicant.wlan0


However, "rc-update show" did not  show the wpa_supplicant service.
I added it to the boot runlevel and while OpenRC still tries to exec /etc/in, it does run wpa_supplicant and associate with the access point. 

Before I close this issue, I'd like to bounce back to a previous BE and repeat my steps, but I'm out of time.
Still I want this feedback here in case others stumble on wpa_supplicant going  tits up.

Also, this idiot needs to read your Idiots Guide to OpenRC to better understand how you debug and manage dependencies.
John
groenveld@acm.org
```

**Comment by jgroenveld** [comment]
```
Looks like this regression is also in the current stable:
https://discourse.trueos.org/t/wifi-not-working-properly-after-18-03-update/2741

The work-around:
# rc-update add wpa_supplicant boot

John
groenveld@acm.org
```

**Comment by jgroenveld** [comment]
```
Rod Myer's /etc/network.subr worked for me:
https://discourse.trueos.org/t/wifi-not-working-properly-after-18-03-update/2741/18?u=jgroenveld
John
groenveld@acm.org
```

**Comment by jgroenveld** [comment]
```
Trident beta3 does not have this bug.
John
groenveld@acm.org
```
