### ISSUE TITLE
Publish ISO hashes/checksums and torrent files (TrueOS 18.06)

### ISSUE THREAD

**Issue by allentiak** [trueos/trueos-core#1554]
Just to mention that:
- There are no links to any checksum file in https://www.trueos.org/downloads/
- There is no checksum file in http://pkg.trueos.org/iso/18.06/
- There are no 18.06 ISOs (nor checksum files) in https://download.trueos.org/master/amd64/ (nor in https://download.trueos.org/unstable/amd64)
- There are no torrent files for 18.06 in https://download.trueos.org/master/amd64 (nor in https://download.trueos.org/unstable/amd64)

**Comment by allentiak** [comment]
Blocks #1541

**Comment by pkgdemon** [comment]
@allentiak Noted.  I think this was just an oversight.  Others reported this issue internally as well.  I will bring this up when we have a meeting this next Friday and see what we are waiting on.

**Comment by ghost** [comment]
...  Any movement on this? I have TrueOS-Stable-x64-18.06.iso and no idea whether I can safely use it.

**Comment by kmoore134** [comment]
I've gone ahead and published the SHA256 and MD5 checksums on these images. 

https://pkg.trueos.org/iso/18.06/

I'm still working on a pubkey signature, should have something there in the upcoming week or so.

**Comment by elico** [comment]
@kmoore134 
- https://pkg.trueos.org/iso/18.06/TrueOS-Stable-x64-18.06.iso.sha256
```
404 Not Found
nginx/1.12.2
```

**Comment by allentiak** [comment]
It works now :-)
