### ISSUE TITLE
Packages in iocage repository needed for backuppc4

### ISSUE THREAD

**Issue by JoelLinn** [trueos/trueos-core#1559]
In the repository 
http://pkg.cdn.trueos.org/iocage/unstable
there seem to be packages missing that are available otherwise.
In my case I need

lang/perl5.26
textproc/p5-XML-RSS
net/rsync
net/rsync-bpc
www/mod_perl2
databases/rrdtool

for running backuppc4 as an iocage plugin
https://github.com/freenas/iocage-ix-plugins/pull/65

**Comment by MiwiDots** [comment]
Hi,
I have added those packages to the builder and will be available tonight german time :).

Thanks

**Comment by JoelLinn** [comment]
www/mod_perl2 does not seem to be added.
Not sure if this is because of the discussion about CGI in the linked pull request or because it was simlpy forgotten
> I have added _those packages_ to the builder
