### ISSUE TITLE
sysadm control panel should use a more standard way to navigate

### ISSUE THREAD

**Issue by jmdavis** [trueos/trueos-core#156]
I found it _very_ confusing to use the sysadm control panel. In particular, it presents

- Application Management
- SysAdm Server Settings
- System Management
- Utilities

and they appear to do nothing. Clicking on them does nothing except select them. Double-clicking on them does nothing except select them. Nothing is listed under them. It seems completely broken. It's only by accident that I stumbled on the fact that _right_-clicking causes them to expand to show items under them that actually do something when you click on them. Right-clicking is normally used for context menus, not for something like this, and I don't know how anyone is expected to know that right-clicking would cause the entries to expand.

I really think that it should be changed so that either single-clicking or double-clicking with the _left_ mouse button opens them up (probably single-clicking, since that's what's used to activate the entries under them once they're expanded, but either would be far less confusing than right-clicking).

**Comment by grahamperrin** [comment]
Please, which desktop environment? 

I used SysAdm a few minutes ago on KDE and found it responding, to simple clicks, in the way that you want.

**Comment by jmdavis** [comment]
Hmmm. Very weird. I am using KDE with the default mouse settings, and I confirm that if I have make that settings change, it fixes the problem in the sysadm control panel so that it's left-clicks that work rather than right-clicks, but I wouldn't have thought that the KDE settings would have any effect on the sysadm control panel, since it's clearly not a KDE app, since it doesn't depend on anything from KDE - though it is Qt5, I think. So, maybe something weird is going on because of that. And this raises the question of whether it's a sysadmin bug, a KDE bug, or a Qt bug. I had assumed that it was just a very weird design choice.

**Comment by pkgdemon** [comment]
Sorry we are only supporting Lumina going forward for TrueOS.  Glad there seems to be a workaround at least.  Closing.
