### ISSUE TITLE
Does pc-updatemanager pkgcheck still works on PC-BSD 10.3?

### ISSUE THREAD

**Issue by bsolano** [trueos/trueos-core#1560]
Greetings,

I am getting this when I try to run `pc-updatemanager pkgcheck`:

`Updating pcbsd repository catalogue...`
`Repository pcbsd has a wrong packagesite, need to re-create database`
`pkg: http://pkg.cdn.pcbsd.org/10.3-RELEASE/amd64/meta.txz: No address record`
`repository pcbsd has no meta file, using default settings`
`pkg: http://pkg.cdn.pcbsd.org/10.3-RELEASE/amd64/packagesite.txz: No address record`
`Unable to update repository pcbsd`
`ERROR: Error 70: /usr/sbin/pkg update`

Is it still possible to do that?

By the way, the site redirection on https://www.pcbsd.org/ has a an expired certificate.  It triggers an error.

Best regards.

**Comment by beanpole135** [comment]
PC-BSD was discontinued back in 2016 (the 10.3 release was the last version of PC-BSD).
[TrueOS](www.trueos.org) is the successor to the base-system pieces of PC-BSD (CLI OS similar to FreeBSD but with other improvements), and if you are looking for a graphical-system like PC-BSD then [Project Trident](www.project-trident.org) or [GhostBSD](www.ghostbsd.org) are both desktop distributions of TrueOS.

**Comment by bsolano** [comment]
For anyone having this issue just go and change /usr/local/etc/pkg.conf to this:

`PKG_CACHEDIR: /usr/local/tmp`
`repos_dir: [`
`                "/etc/pkg"`
`           ]`

FreeBSD still supports the 10 branch.  I am going to upgrade my server to pure FreeBSD in order to avoid this type of issues in the future.
