### ISSUE TITLE
Tor not working

### ISSUE THREAD

**Issue by Troub274** [trueos/trueos-core#157]
With the latest version of trueos with all the latest updates as of 11/14/2016 The "route through tor"
item on the network configuration tool bar item (lower right corner of screen) does not work.
I have looked through the script and I think it's the socat redirection.  it works if you route DNS through the unencrypted network but if you are trying to route your DNS queries through SOCAT to TOR it only works about 10% of the time.  I've disconnected the DNS portions and routed them through the normal network and then TOR works great but as soon as you route DNS through TOR everything hangs up. I think SOCAT is getting clogged up somewhere.

**Comment by Troub274** [comment]
I might add that most of the time it works for the first couple requests but subsequent request clog the pipe and don't get through so sometimes a simple site with only 1 page of html will work but a site with multiple request coming fast does not work. eventually everything clogs up and nothing will work. so it's not just getting the initial checking tor page. that usually works... it's what comes after

**Comment by pkgdemon** [comment]
I am seeing that this feature is broken altogether with the latest OpenRC enabled images.

**Comment by pkgdemon** [comment]
It looks like we need a tor service for OpenRC:

https://github.com/trueos/freebsd-ports/tree/xserver-next/security/tor

**Comment by Troub274** [comment]
Joe,

It's more than that.
Even when Tor is launching properly the DNS udp redirect is not working.
That's where things are getting clogged up.

Steve.

**Comment by pkgdemon** [comment]
Yeah there was an issue with the ipfw that went out to stable loading rulesets.  That was caught, and should be fixed in the next unstable push after packages build by tommorow hopefully.  Then I can start testing a new rc script.

**Comment by pkgdemon** [comment]
Sorry for the delay on this.  I have fixed part of the issue by adding a tor service.  

https://github.com/trueos/freebsd-ports/commit/fcd34944d314551407eb4ee5a226977547bce05f

**Comment by pkgdemon** [comment]
After adding the socat service as well, and fixing the reset-firewall-tor script it's working now in TrueOS-Desktop-201701261715.  I have enabled, and disabled tor more than 10 times.

**Comment by Troub274** [comment]
Working for me as well
