### ISSUE TITLE
TrueOS-Desktop-12.0-CURRENT-08-01-2016-x64-USB.img BTX Loader fails to boot to installer, reboot loop, without UEFI on HP EliteBook 8540p

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#16]
1. Insert the USB flash drive
2. switch on
3. at the HP dialogue, key F10 for BIOS setup
4. restore defaults (disables UEFI)
5. save changes and exit
6. observe the HP dialogue
7. observe a blinking white underscore cursor at top left with what may be a hyphen or dash' above that cursor
8. observe split-second appearance of a block of text that begins with _BTX Loader_

**Expected**

Progress beyond that loader. 

**Actual result**

After the split second, an automated reboot.

**Comment by pkgdemon** [comment]
Are you booting with any other USB devices connected such as a mouse, printer, etc?  Have you tried an ISO image to see if that has the same issue as well?

**Comment by grahamperrin** [comment]
> Are you booting with any other USB devices connected such as a mouse, printer, etc? 

No.

> Have you tried an ISO image burned to DVD to see if that has the same issue as well?

Yes; this _is_ the type of bug where I expect the DVD to succeed where the USB flash drive fails. 

I'm almost certain that in July, with a more modern HP EliteBook 8570p, the DVD approach was superior to the USB approach. 

Now with the 8540p, the DVD approach is superior.

**Comment by grahamperrin** [comment]
With a more recent installer (2016-08-19) on a USB flash drive, the symptom is different. 

No automated reboot loop. 

Instead, things appear to progress no further than BTX loader screen, with a blinking underscore cursor on the line below the _(root@devastator, …_ line. 

That happens only if I actively select the identifiable drive, e.g. (today) 

> USB Hard Drive 1 - Verbatim STORE N GO

If I allow the uppermost menu item –

> Notebook Upgrade Bay (UEFI) 

– then the EliteBook 8540p proceeds to present the TrueOS loader screen. 

I reckon that this issue is symptomatic of peculiarities with HP firmware. If you agree, please close this issue.

**Comment by grahamperrin** [comment]
https://gitter.im/trueos/Lobby/archives/2016/08/22

>  was the issue reproducible with freebsd? 

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211702 blocks comparison with FreeBSD – sorry.

**Comment by kmoore134** [comment]
Duplicate
