### ISSUE TITLE
pico-server rc problems

### ISSUE THREAD

**Issue by yaaarg32** [trueos/trueos-core#160]
/var/log/messages doesn't exist on this fresh, fully-updated install, so no logs...
I can provide SSH access to this internally.  Let me know if you need any more info, but here's all the useful info I can think of.

I used the pkg install route since appcafe doesn't want to start, neither does control panel (sysadm on 127.0.0.1 times out? not sure, but that's a different bug...)

[root@DECserver] ~# pkg info | grep pico
picoserver-0.3                 Server for hosting Pico clients

[root@DECserver] ~# uname -a
FreeBSD DECserver.ixsystems.com 12.0-CURRENT FreeBSD 12.0-CURRENT #34 56e6cbd(drm-next-4.7): Fri Nov 11 22:25:34 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64

[root@DECserver] ~# service picoserver start
 * service: service `picoserver' does not exist
[root@DECserver] ~# cat /etc/rc.conf | grep pico
picoserver_enable="yes"

[root@DECserver] ~# /usr/local/etc/rc.d/picoserver start
/usr/local/etc/rc.d/picoserver: source_rc_confs: not found
Cannot 'start' picoserver. Set picoserver_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'.
[root@DECserver] ~# /usr/local/etc/rc.d/picoserver onestart
/usr/local/etc/rc.d/picoserver: source_rc_confs: not found
Starting picoserver...

[root@DECserver] ~# ps aux | grep pico
root       1550   0.0  0.0    10460  1896  -  Is   10:30    0:00.00 daemon: /usr/local/bin/pico-server[1551] (daemon)
root       1551   0.0  0.0    30624  7068  -  I    10:30    0:00.05 /usr/local/bin/pico-server -daemon

[root@DECserver] ~# sockstat | grep pico
root     pico-serve 1551  4  udp4   *:5353                *:*
root     pico-serve 1551  6  udp6   *:5353                *:*
root     pico-serve 1551  7  tcp46  *:8400                *:*

So it looks like it's running, but the Pi never finds the pico server and sits waiting endlessly for it.

**Comment by kmoore134** [comment]
This was a problem with the ISO downloaded, it was an un-released WiP with OpenRC. Using the released ISO should fix the issues :)
