### ISSUE TITLE
SysAdm should not allow entry of a boot environment name that will be disallowed by beadm(1)

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#161]
## Background 

Whilst https://www.freebsd.org/cgi/man.cgi?query=beadm&sektion=1&manpath=FreeBSD+Ports does not specify which characters are allowed, through trial and error I found that (at least) spaces are disallowed. 

## Enhancement request

Please make SysAdm present an alert: 

- before _entry_ (of a string of characters)
- whenever a disallowed character is _typed_.

Red alert may be over-the-top. Yellow should suffice. 

## Reference

[FreeBSD and TrueOS manual pages for beadm(1) - Help and Support - TrueOS Community](https://discourse.trueos.org/t/freebsd-and-trueos-manual-pages-for-beadm-1/232?u=grahamperrin)

**Comment by pkgdemon** [comment]
Agreed.  We need some sanity checking here.  We had this before in our previous BE manager.

**Comment by grahamperrin** [comment]
Maybe also limit the number of characters. From https://discourse.trueos.org/t/-/248 in the lounge: 

> I experimented with relatively long names then realised that the names were misrepresented in the loader. …

**Comment by pkgdemon** [comment]
This seems to be fixed from what I can tell.  It will not allow me to save an invalid name.

**Comment by grahamperrin** [comment]
Thanks. Note to self: the 'blink and you'll miss it effect. A split-second of redness (redness that is normal when successfully renaming) without alerting the user to the failed rename.
