### ISSUE TITLE
SysAdm should allow renaming of the nickname, alone, of a boot environment

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#162]
## Observation

A rename performed by SysAdm affects the name but not the nickname. 

## Enhancement request

Allow SysAdm to rename the nickname only. 

## Reference

From [FreeBSD and TrueOS manual pages for beadm(1) - Help and Support - TrueOS Community](https://discourse.trueos.org/t/freebsd-and-trueos-manual-pages-for-beadm-1/232?u=grahamperrin): 

```
     rename  [-n] ⟨origBeName⟩ ⟨newBeName⟩

             Renames the given nonactive origBeName to the given newBeName If
             -n used, rename the nickname property only
```

– sic; there should be punctuation marks.

**Comment by kmoore134** [comment]
The nickname property was supposed to be a "freenas-only" feature. I didn't want to expose it to SysAdm, since I expect it may be removed from TrueOS down the road. (I did the implementation, but don't like it myself)

**Comment by grahamperrin** [comment]
>  I expect it may be removed from TrueOS down the road. (I did the implementation, but don't like it myself)

Thanks, noted: https://github.com/trueos/pc-updatemanager/commit/5691f8d0edc76a78ea9fe84df9d5016eda76a69d

>  Nuke the usage of "nicknames" for BE updates, not used anymore
