### ISSUE TITLE
SysAdm: with and without categories, allow the user to prefer an immediate overview

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#164]
## Enhancement request

Discussed a few months ago, and (if I recall correctly) coding should be not too difficult: 

- a preferred view of more than one category at a time :+1: 

Additionally, please: 

- allow the user to prefer a **non-categorised**, at-a-glance overview
- allow any such preference to persist.

### At-a-glance

A full overview should be possible _immediately_, without requiring keystrokes. (FAYT search results are a useful complement, resulting in partial overviews, but let's have a full overview without searching.)

### Apple Mac OS X

_System Preferences_ presents an overview by default. Some older versions of the OS allow the user to prefer a non-categorised view (the name and icon of each pane, sorted alphabetically); and that preference is persistent. 

### Microsoft Windows 7

The _Control Panel_ is categorised by default, the user can prefer a non-categorised view, and that preference is persistent. 

### Lumina desktop environment

`/usr/local/bin/lumina-config` (_Desktop Settings_) can present an overview after four clicks (one on each of the four categories), but that overview does not persist; if the window is closed, then all four clicks must be repeated.

**Comment by pkgdemon** [comment]
I second this request.  I find the default collapsed view difficult to operate.

**Comment by grahamperrin** [comment]
Also: if categories are to be forced, I prefer to work with one column (not two columns, fixed, beneath each category). 

Maybe a minority preference, but now's the time to mention it.
