### ISSUE TITLE
kernel panic during install wlan0

### ISSUE THREAD

**Issue by incin2b** [trueos/trueos-core#165]
![imag0203](https://cloud.githubusercontent.com/assets/23608286/20460125/79e1d980-ae9f-11e6-8f91-a415ee1051ba.jpg)

When trying to install TrueOS, before getting to the GUI install screen, the loading stops. I put the install in verbose mode to get this out put from the image attached.

I had to install TrueOS in safemode. After that my wlan0 interface worked.

I have a Intel Centrino N-135 wireless chip in my laptop.

Just wanted to let you guys know! Thanks!

**Comment by kmoore134** [comment]
Ok, thanks for the heads up! At the moment we don't have a particular way to reproduce this for testing, however I would check it periodically. If you still see it in the next few months, it might be worth getting a debug and submitting to upstream FreeBSD.
