### ISSUE TITLE
AppCafe expanding logo continually grows

### ISSUE THREAD

**Issue by hxw** [trueos/trueos-core#166]
On first opening AppCafe, it displays an animated logo that appears to grow larger both horizontally and vertically each time even if it is run with a maximised window.  After a few minutes running it is already 2 × screen height and 1.5 × screen width.

**Comment by pkgdemon** [comment]
I have been unable to reproduce this after attempting on multiple systems.  Please update to the latest release if you are not.  If it is still an issue please let us know so we can re-open.  It would be helpful to have a screenshot, and more detail about how to trigger the problem if it is still an issue.

**Comment by hxw** [comment]
I don't see this growing effect any more; though there is a slow shrinking effect if the window is resized smaller: which continues until the scroll bars disappear and the resize is complete which takes many minutes to complete.  In contrast resize larger is instant.
