### ISSUE TITLE
persistent reboots with wireshark /dev/bpf* issues

### ISSUE THREAD

**Issue by jungle-boogie** [trueos/trueos-core#170]
Hello,

I installed wireshark from pkg on my trueOS system and can't run it without root after I reboot my computer.

before reboot:

```
chgrp network /dev/bpf*
chmod g+r /dev/bpf*
chmod g+w /dev/bpf*
```
and it correctly reflects in `/dev/bpf*`
```
% ls -l /dev/bpf*
crw-rw----  1 root  network  0x23 Nov 25 17:02 /dev/bpf
lrwxr-xr-x  1 root  wheel       3 Nov 25 17:02 /dev/bpf0 -> bpf
```

But after the reboot, permissions reset to defaults.

```
% ls -l /dev/bpf*
crw-------  1 root  wheel  0x23 Nov 25 17:11 /dev/bpf
lrwxr-xr-x  1 root  wheel     3 Nov 25 17:11 /dev/bpf0 -> bpf
```

`FreeBSD 12.0-CURRENT #40 a8b0e29(drm-next-4.7): Tue Nov 22 16:43:26 UTC 2016`

```
% freebsd-version -ku
12.0-CURRENT
12.0-CURRENT
```

How do I run wireshark after rebooting my computer?

Thanks!

**Comment by itaylor57** [comment]
In order for this to persist across reboots, add the following to
/etc/devfs.conf:

own  bpf* root:network
perm bpf* 0660

**Comment by jungle-boogie** [comment]
> In order for this to persist across reboots, add the following to

ah! I knew I forgot something in my original post.
I already have that added. 

```
% tail /etc/devfs.conf
# Enable libgtop
perm    devstat 0444

# Link /dev/shm
link   /tmp   shm


own  bpf* root:network
perm bpf* 0660
```

**Comment by jungle-boogie** [comment]
Anyone have any ideas?

**Comment by jungle-boogie** [comment]
Okay, this _may_ be an issue with `FreeBSD 12.0-CURRENT #40 a8b0e29(drm-next-4.7): Tue Nov 22 16:43:26 UTC 2016`

I'm now back on 28 Oct and /dev/bpf shows this:

```
ls -l /dev/bp*
crw-rw----  1 root  network  0x21 Nov 30 10:06 /dev/bpf
lrwxr-xr-x  1 root  wheel       3 Nov 29 22:57 /dev/bpf0 -> bpf
crw-rw-rw-  1 root  wheel    0x2e Nov 29 22:57 /dev/bpsm0
```

**Comment by pkgdemon** [comment]
I suspect we are missing a boot service to correct this.  I have not had time to investigate which one yet.

**Comment by jungle-boogie** [comment]
@pkgdemon, let me know how I can help.

**Comment by pkgdemon** [comment]
Yeah we were missing devfs service.  Fixed in newest UNSTABLE packages.
