### ISSUE TITLE
USB ethernet: ue0 driven with with (2016-10-28) 14 1717ae3 but not with (2016-11-22 edge) 40 a8b0e29

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#172]
## Environment

MacBookPro11,2 with Apple adapter A1277. 

## After restarting to the initial boot environment

```
$ date ; uptime ; uname -a
Sat 26 Nov 2016 16:54:30 GMT
 4:54p.m.  up 8 mins, 0 users, load averages: 2.78, 1.77, 0.87
FreeBSD momh167-gjp4-macbookpro112-trueos.university.brighton.ac.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #14 1717ae3(drm-next-4.7): Fri Oct 28 13:49:49 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
$ beadm list
BE                              Active Mountpoint                                        Space Created           Nickname
initial                         NR     /                                                  3.6G 2016-11-26 15:15  initial
12.0-CURRENT-up-20161126_163130 -      /tmp/BE-12.0-CURRENT-up-20161126_163130.GY2O5zMK   2.6G 2016-11-26 16:26  12.0-CURRENT-up-20161126_163130
$ ifconfig -a
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128 
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
        inet 127.0.0.1 netmask 0xff000000 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo 
ue0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=80008<VLAN_MTU,LINKSTATE>
        ether ac:7f:3e:e6:09:96
        inet6 fe80::ae7f:3eff:fee6:996%ue0 prefixlen 64 scopeid 0x2 
        inet 192.168.2.59 netmask 0xffffff00 broadcast 255.255.255.255 
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
        media: Ethernet autoselect (100baseTX <full-duplex>)
        status: active
$ cat /tmp/BE-12.0-CURRENT-up-20161126_163130.GY2O5zMK/uname.txt 
FreeBSD 12.0-CURRENT #40 a8b0e29(drm-next-4.7): Tue Nov 22 16:43:26 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
$
```

**Comment by pkgdemon** [comment]
@grahamperrin As root can you try kldload uether to see if that loads the needed module?  if it does you can add uether to /etc/conf.d/modules, and we can add it globally so that is is loaded by default during upgrades.

**Comment by grahamperrin** [comment]
`kldload uether` runs without error but the `pc-netmanager` view of things remains empty; no network interfaces. 

(I normally see just one interface, the USB adapter. We don't expect the integral wireless interface to work.)

**Comment by pkgdemon** [comment]
It could also be attributed to the fact we were not starting devd.  If devd was responsible for loading the correct module, and bringing up ue0 when plugged in.  I know that this has effected some USB mice from not functioning post install.  

This was fixed in:

https://github.com/trueos/trueos-desktop/commit/a16a2c4f79ac2047f714035615195475e76fb8e4

It may be worth trying:

```rc-update add devd boot```

Then reboot the system with the usb ethernet device plugged in.  I happen to have a device which uses this exact driver I can test at the office tomorrow as well.

**Comment by pkgdemon** [comment]
@kmoore134, and I figured out this was in fact a devd issue loading a USB config file that loads the required module when a USB device is plugged in.

**Comment by pkgdemon** [comment]
Hope to have fixed by early next week.  In the meantime a workaround would be to...  cd /boot/kernel/ and run kldload if* to just load all the if modules.  I forget the particular module that devd discovers is the correct one.

**Comment by pkgdemon** [comment]
I can confirm this is working now.  This will make our next set of unstable packages.
