### ISSUE TITLE
HID: human input devices: the OS seems to respond properly for only a few moments to keyboard input

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#176]
When I tested the fix for #173 I realised an obscure symptom, which I recalled seeing just once _before_ that fix. HP EliteBook 850 G2 with an external keyboard and external trackball on USB. 

If the keyboard is used very soon after PCDM appears, e.g. the arrow keys to navigate the list of users, then the OS does respond but only momentarily. 

It may seem as if the OS stops responding to keyboard input but as shown in the movie at https://files.gitter.im/trueos/Lobby/bYqO/2016-11-30-20_39.mp4, shot after keying down more than once, it's as if the down key has been pressed and held. The downward movement became evident after I clicked the power menu.

**Comment by pkgdemon** [comment]
Pretty sure this is devd related.  I will ping back when we have the proper fixes in unstable.

**Comment by pkgdemon** [comment]
We have confirmed this was a devd loading issue.  Fixed, and will be in newer unstable packages.
