### ISSUE TITLE
disconnect/reconnect mouse results in non-functioning

### ISSUE THREAD

**Issue by jungle-boogie** [trueos/trueos-core#177]
Hi All,

Disconnecting and reconnecting my wired usb mouse results in the loss of functionality until I reboot my system.

I'm only guessing at what you might need to help track down and resolve the problem, so if more is needed, please let me know what you want.

dmesg:

post-disconnect:
```
ugen0.2: <vendor 0x0101> at usbus0 (disconnected)
ums0: at uhub0, port 3, addr 1 (disconnected)
ums0: detached
```

post-connect:
```
ugen0.2: <vendor 0x0101> at usbus0
ums0 on uhub0
ums0: <vendor 0x0101 USB OPTICAL MOUSE, class 0/0, rev 1.10/1.00, addr 4> on usbus0
ums0: 5 buttons and [XYZT] coordinates ID=0
```

```
% usbconfig
ugen0.1: <XHCI root HUB 0x8086> at usbus0, cfg=0 md=HOST spd=SUPER (5.0Gbps) pwr=SAVE (0mA)
ugen0.3: <USB Camera 04081-0005360015381025995> at usbus0, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (500mA)
ugen0.4: <USB2.0-CRW Generic> at usbus0, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (500mA)
ugen0.2: <USB OPTICAL MOUSE vendor 0x0101> at usbus0, cfg=0 md=HOST spd=LOW (1.5Mbps) pwr=ON (100mA)
```

**Comment by pkgdemon** [comment]
Sure enough I see the same thing.  Thanks for the heads up!

**Comment by kmoore134** [comment]
Have you tested with later packages that add devd?

**Comment by pkgdemon** [comment]
Not yet.  Will do.

**Comment by kmoore134** [comment]
We confirmed in house that the devd fixes correct this problem. Those packages just got pushed out to the UNSTABLE branch, you can update later today and get them :)
