### ISSUE TITLE
linux-defcon libGL error: failed to load driver: swrast

### ISSUE THREAD

**Issue by tiomadrid** [trueos/trueos-core#178]
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error:  BadValue
  Request Major code 153 (GLX)
  Request Minor code 3 ()
  Value 0x0
  Error Serial #30
  Current Serial #31

uname -a
FreeBSD trueos-513 12.0-CURRENT FreeBSD 12.0-CURRENT #14 1717ae3(drm-next-4.7): Fri Oct 28 13:49:49 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by pkgdemon** [comment]
Are you using NVIDIA by chance?

**Comment by tiomadrid** [comment]
No

ATI Radeon

**Comment by pkgdemon** [comment]
Strange.  If you run glxinfo | grep direct does it show direct rendering enabled?

**Comment by tiomadrid** [comment]
glxinfo | grep direct
direct rendering: Yes
    GL_ARB_depth_buffer_float, GL_ARB_depth_clamp, GL_ARB_direct_state_access, 
    GL_ARB_draw_elements_base_vertex, GL_ARB_draw_indirect, 
    GL_ARB_multi_draw_indirect, GL_ARB_occlusion_query2,

**Comment by tiomadrid** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=214989

**Comment by pkgdemon** [comment]
I tried what was suggested in the ticket, and I get nothing but a grey screen here unfortunately, and then it closes with an intel card.  I would pursue this further with the freebsd bug ticket.  You could try removing /compat/linux as they suggested, and reinstalling the linux-defcon package.  I would update the freebsd ticket if the results are different.

**Comment by tiomadrid** [comment]
The freebsd linux-defcon maintainer asked me to ask trueos why
their packages are outdated.

**Comment by kmoore134** [comment]
We will be pulling in the newer ports and packages later this week, give us a few more days to get the OpenRC changes wrapped up.
