### ISSUE TITLE
openntpd: enable contstraints?

### ISSUE THREAD

**Issue by jungle-boogie** [trueos/trueos-core#179]
Hi All,

Taking a look at `/usr/local/etc/ntp.conf` I see the constraints feature in openntpd is disabled:
```
# get the time constraint from a well-known HTTPS site
#constraints from "https://www.google.com/"
```

Is there a technical reason for this or is it because you're pulling from freebsd?

 ntpd(8) can be configured to query the ‘Date’ from trusted HTTPS servers via TLS. This time information is not used for precision but acts as an authenticated constraint, thereby reducing     the impact of unauthenticated NTP man-in-the-middle attacks. Received NTP packets with time     information falling outside of a range near the constraint will be discarded and such NTP servers will be marked as invalid.

http://man.openbsd.org/ntpd.conf

**Comment by kmoore134** [comment]
We don't customize that particular port. Just install the shipped conf / sample file from upstream. We could enable that feature, but I wonder why they ship it disabled in the first place.
