### ISSUE TITLE
TrueOS-Desktop-12.0-CURRENT-08-01-2016-x64-DVD.iso BTX loader halts without UEFI on HP EliteBook 8540p

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#18]
1. At the HP dialogue, key F10 for BIOS setup
2. restore defaults (disables UEFI)
3. place the DVD in the drive tray that's integral to the notebook
4. close the tray
5. save changes and exit
6. observe the HP dialogue
7. observe a loader screen that includes the following lines: 

> …
> CD Loader 1.2
…
> Starting the BTX loader
> 
> BTX loader 1.00  BTX version is 1.02
…

**Expected**

Progress beyond that loader.

**Actual result**

> …
> BTX halted

– and there's a flashing underscore cursor below 'Starting the BTX loader'.

![img_20160807_202937](https://cloud.githubusercontent.com/assets/192271/17464725/f3933634-5cdd-11e6-9e4a-93903c281d63.jpg)

**Comment by grahamperrin** [comment]
https://gitter.im/trueos/Lobby/archives/2016/08/22

> was this issue reproducible with freebsd? 

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211702 blocks comparison with FreeBSD – sorry. 

I have a mental note to review this issue some time after the next .iso appears at http://download.trueos.org/master/amd64/

**Comment by kmoore134** [comment]
This is most likely a FreeBSD issue, something that would need to be fixed on their end. No custom loader stuff here anymore.
