### ISSUE TITLE
Missing options from text installer

### ISSUE THREAD

**Issue by francisco1844** [trueos/trueos-core#184]
The CLI/text installer is missing 2 ZFS related options available from GUI
1- Name of pool
2- Force 4K block

**Comment by pkgdemon** [comment]
Good catch!

**Comment by pkgdemon** [comment]
Just an update I did take the time to confirm these options were missing.

**Comment by RodMyers** [comment]
still an issue with the TrueOS-Desktop-2017-02-22-x64-DVD.iso

**Comment by RodMyers** [comment]
Text Installer was removed.

Will close this ticket
