### ISSUE TITLE
nspluginwrapper: ELF binary type "0" not known for linux-c6-flashplugin 11.2r202.644 (Adobe Flash Player ESR)

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#187]
Following a change from STABLE to UNSTABLE: 

```
$ date ; uname -v
Fri  9 Dec 2016 00:40:10 GMT
FreeBSD 12.0-CURRENT #53 73f9e3e(drm-next-4.7): Thu Dec  8 18:50:25 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
$ pkg info trueos-desktop | grep -i version
Version        : 201612081442
$ pkg info linux-c6-flashplugin | grep -i version
Version        : 11.2r202.644
$ pkg info linux-c6-flashplugin | grep -i instal
Installed on   : Sun Dec  4 18:46:45 2016 GMT
$ sudo nspluginwrapper -v -a -i
Password:
Auto-install plugins from /usr/local/lib/browser_plugins
Looking for plugins in /usr/local/lib/browser_plugins
Auto-install plugins from /usr/local/lib/browser_plugins/linux-c6-flashplugin
Looking for plugins in /usr/local/lib/browser_plugins/linux-c6-flashplugin
ELF binary type "0" not known.
exec: /usr/local/lib/nspluginwrapper/i386/linux/npviewer.bin: Exec format error
ELF binary type "0" not known.
exec: /usr/local/lib/nspluginwrapper/i386/linux/npviewer.bin: Exec format error
Auto-install plugins from /usr/local/lib/browser_plugins/symlinks/linux-firefox
Looking for plugins in /usr/local/lib/browser_plugins/symlinks/linux-firefox
ELF binary type "0" not known.
exec: /usr/local/lib/nspluginwrapper/i386/linux/npviewer.bin: Exec format error
ELF binary type "0" not known.
exec: /usr/local/lib/nspluginwrapper/i386/linux/npviewer.bin: Exec format error
Auto-install plugins from /usr/home/bbsadmin-l/.mozilla/plugins
Looking for plugins in /usr/home/bbsadmin-l/.mozilla/plugins
$
```

**Comment by kmoore134** [comment]
I have a fix for this. You need to enable the abi service. Ill put it into the default runlevel tomorrow. ⁣

**Comment by pkgdemon** [comment]
Bigger issue...

[1/32] Installing linux_base-c7-7.2.1511_3...
[1/32] Extracting linux_base-c7-7.2.1511_3: ......... done
pkg-static: Fail to rename /compat/linux/.run.j88NAdlly399 -> /compat/linux/run: Is a directory

**Comment by pkgdemon** [comment]
I had to....

```umount /compat/linux/proc```
```cd /compat```
```rm -rf linux```

Then installing the linux-c7-flashplugin24: 24.0.0.154 package worked.  I know we create the /compat/linux/proc structure as we mount proc automatically with /etc/fstab.  Something we are doing in that routine or somewhere else however is causing problems with getting linux-base-c7 to install.  I am not sure this is directly related to the c6 issue but I want to keep this open until I verify we fix this.

**Comment by pkgdemon** [comment]
I was getting the same thing with c6.

[jmaloney@joe-desktop] ~% nspluginwrapper -v -a -i
Auto-install plugins from /usr/local/lib/browser_plugins
Looking for plugins in /usr/local/lib/browser_plugins
Auto-install plugins from /usr/local/lib/browser_plugins/symlinks/linux-firefox
Looking for plugins in /usr/local/lib/browser_plugins/symlinks/linux-firefox
ELF binary type "0" not known.
exec: /usr/local/lib/nspluginwrapper/i386/linux/npviewer.bin: Exec format error
ELF binary type "0" not known.
exec: /usr/local/lib/nspluginwrapper/i386/linux/npviewer.bin: Exec format error
Auto-install plugins from /usr/home/jmaloney/.mozilla/plugins
Looking for plugins in /usr/home/jmaloney/.mozilla/plugins

I have the new ABI service.  I had to actually load the linux kernel module.

```kldload linux```

Now it works.

**Comment by pkgdemon** [comment]
Ok ABI service in fact works.  If you set ```linux_enable="YES"``` in /etc/rc.conf.  I will work on adding that to trueos-desktop, and fix the issue with c7 getting installed before closing.

**Comment by pkgdemon** [comment]
Added to trueos-desktop.  Closing.  I am going to open another ticket for the c7 issue.
