### ISSUE TITLE
 GUI shrunken and partly off-screen with TrueOS-Desktop-12.0-CURRENT-08-01-2016-x64-USB.img on Intel GM45

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#19]
Ergo Vista 621. 

Comparable to #10 but initially to be treated as separate. 

![img_20160802_224623](https://cloud.githubusercontent.com/assets/192271/17464979/9409b76a-5ce2-11e6-8092-af8f36f38f57.jpg)

Agreed with Joe Maloney: 

>  worth a ticket until we fix it.  it seems related to the other issues.  but worth noting regardless.

**Comment by kmoore134** [comment]
Issue with DRM from upstream, should be reported here:

https://github.com/FreeBSDDesktop/freebsd-base-graphics
