### ISSUE TITLE
loss of preferred DNS servers after OpenRC restart of dhcpcd service

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#191]
## Environment

- MacBookPro11,2
- Apple USB Ethernet Adapter A1277
- Belkin [F5D5231-4](http://www.belkin.com/uk/support-product?pid=01t80000001qILuAAM) (F5D5231uk4) 4-Port Cable/DSL Gateway Router
- `FreeBSD 12.0-CURRENT #55 4fde044(drm-next-4.7): Fri Dec  9 20:03:40 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC`

## Steps

1. start the OS with an external Apple keyboard in the USB port on the left of the Mac 
2. after a respectable waiting period, connect the adapter to the USB port on the right
3. `drill`, observe DNS server 192.168.2.1 (the router)
4. `sudo pc-netmanager`
5. observe 192.168.2.1 as a custom preference, but the customisation was not mine
6. overwrite 192.168.2.1with 8.8.8.8
7. add a second DNS entry 8.8.4.4
8. Alt-A apply
9. OK
10. escape
11. `drill`
12. observe an error, 
> error sending query: Error creating socket
13. `sudo service dhcpcd restart`
14. observe the four lines, apparently without problem ('ok' at lines 1, 2 and 4)
15. `drill`

## Expected

- one of the two user-specified servers

## Actual result

- the server address that I had overwritten. 

----

The steps above touch upon multiple bugs but essentially: 

- a restart of a service should not lose a preference.

**Comment by pkgdemon** [comment]
If setting custom DNS we need to tell dhcpcd not to pull DNS in dhcpcd.conf.

**Comment by grahamperrin** [comment]
Thanks. For tracking I raised #213, which is probably a companion issue.

**Comment by pkgdemon** [comment]
Adding ```nohook resolv.conf``` to ```/usr/local/etc/dhcpcd.conf``` should be what is needed to configure globally to use custom dns.

**Comment by pkgdemon** [comment]
Some options found in the archwiki:

To be used in ```/usr/local/etc/dhcpcd.conf```

```
# define static profile
profile static_eth0
static ip_address=192.168.1.23/24
static routers=192.168.1.1
static domain_name_servers=192.168.1.1
# fallback to static profile on eth0
interface eth0
fallback static_eth0
```

**Comment by pkgdemon** [comment]
I think we just need to modify pc-netmanager to do the following when setting a custom gateway:

Add ```defaultrouter=``` to /etc/rc.conf as we are now but also make the ```static_routers=``` change in ```/usr/local/etc/dhcpcd.conf```

Add ```nameserver ``` as we are now in /etc/resolv.conf but also make the ```static domain_name_servers=``` change in ```/usr/local/etc/dhcpcd.conf``` 

We cannot strictly rely on setting with dhcpcd alone in cases where "DHCP" is not used on any interfaces at all.

**Comment by beanpole135** [comment]
Done!
This still needs to be checked/verified that it works though (so I am going to leave the ticket open for now)

https://github.com/trueos/pc-networkmanager/commit/53ae33919d2ccff0d5f6a4e91c432499d2e88144

**Comment by RodMyers** [comment]
still not working

http://pastebin.com/reDB2S25

**Comment by samob** [comment]
Hi, I'm new here. Saw a post on discourse that dual nic setups are testing, and here is my setup:

em0 connected to isp's first of 8 ports device on optical router. alc0 is connected to second port on same device. em0 is statically assigned, for alc0 i turned dhcp.

I get about 50 sec delay on boot, visible in log file:
http://pastebin.com/D566e441

Now, while this stuff is happening, I did followed tutorial on https://www.freebsd.org/doc/handbook/virtualization-host-bhyve.html and just enabled all those bridge and tap devices mentioned in the manual. My ifconfig looks like this:

em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=4209b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,VLAN_HWTSO>
        ether 74:d4:35:ec:ae:0c
        inet6 fe80::76d4:35ff:feec:ae0c%em0 prefixlen 64 scopeid 0x1 
        inet 93.103.220.xxx netmask 0xffff0000 broadcast 93.103.255.255 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect (100baseTX <full-duplex>)
        status: active
alc0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=c319a<TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,WOL_MCAST,WOL_MAGIC,VLAN_HWTSO,LINKSTATE>
        ether 74:d4:35:ec:ae:0e
        inet6 fe80::76d4:35ff:feec:ae0e%alc0 prefixlen 64 scopeid 0x2 
        inet 93.103.31.xxx netmask 0xffff0000 broadcast 93.103.255.255 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect (100baseTX <full-duplex>)
        status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet 127.0.0.1 netmask 0xff000000 
        inet6 ::1 prefixlen 128 
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo

**Comment by grahamperrin** [comment]
> … ifconfig looks like this after reboot:

The above, styled: 

```
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=4209b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,VLAN_HWTSO>
	ether 74:d4:35:ec:ae:0c
	inet6 fe80::76d4:35ff:feec:ae0c%em0 prefixlen 64 scopeid 0x1
	inet 93.103.220.xxx netmask 0xffff0000 broadcast 93.103.255.255
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (100baseTX )
	status: active
alc0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=c319a<TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,WOL_MCAST,WOL_MAGIC,VLAN_HWTSO,LINKSTATE>
	ether 74:d4:35:ec:ae:0e
	inet6 fe80::76d4:35ff:feec:ae0e%alc0 prefixlen 64 scopeid 0x2
	inet 93.103.31.xxx netmask 0xffff0000 broadcast 93.103.255.255
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (100baseTX )
	status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo
```

@samob thanks, and please share the content of `/etc/rc.conf`

----

Hint (link below): _styling with Markdown is supported_; you can view [a brief tutorial](https://gitter.im/gitterHQ/sandbox?at=585833f161e516c1578e34c7), and experiment, in the sandbox at Gitter.

**Comment by samob** [comment]
[samob@trueos] ~% more /etc/rc.conf
```
rc_parallel="YES"
rc_logger="YES"
rc_log_path="/var/log/rc.log"
linux_enable="YES"
kldload_nvidia="nvidia-modeset nvidia"
ifconfig_alc0="DHCP"
#ifconfig_alc0_ipv6="inet6 accept_rtadv"
powerdxx_enable="YES"
hostname="trueos.rula.org"
zfs_enable="YES"
sshd_enable="YES"
defaultrouter="93.103.0.1"
ifconfig_em0="93.103.220.190 netmask 255.255.0.0"
ifconfig_em0_ipv6="inet6 accept_rtadv"
tor_enable="YES"
socat_enable="YES"
socat_flags="UDP4-RECVFROM:53,fork UDP4-SENDTO:localhost:9530"
```

**Comment by grahamperrin** [comment]
Thanks @samob https://gitter.im/trueos/troubleshooting?at=58613e97db9cafe9183a8887 considers a possible workaround.

**Comment by pkgdemon** [comment]
Fixed here:
https://github.com/trueos/pc-networkmanager/commit/d8ac36048fe0e473e50e9cf93d9e85454d76b9e7
&
https://github.com/trueos/pc-networkmanager/commit/f6f390cdbe9787cb9cffb94fe5603c66a3b2f31a
