### ISSUE TITLE
No right click with a Synaptics touchpad in a Mac

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#192]
- `FreeBSD 12.0-CURRENT #55 4fde044(drm-next-4.7): Fri Dec  9 20:03:40 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC`
- MacBookPro11,2 and from https://wiki.archlinux.org/index.php/MacBookPro11,x#Touchpad I assume that the hardware is Synaptics. 

From https://wiki.freebsd.org/SynapticsTouchpad:

> … tap detection with one (left click), two (right click) or three (middle click) fingers. 

Present in `/boot/loader.conf.trueos` not in `/boot/loader.conf`: 

`hw.psm.synaptics_support="1"`

----

I tried tapping with two fingers, clicking with two fingers: nothing. 

I also tried the Mac tradition, Control-Click. 

----

Maybe related (although I took reasonable steps to avoid the peculiarities before reporting this issue): 

- [Peculiarities with Apple USB Ethernet Adapter A1172 - The Lounge - TrueOS Community](https://discourse.trueos.org/t/peculiarities-with-apple-usb-ethernet-adapter-a1172/350)

In Super User, with three answers (none accepted): 

- [How to Right Click Using the Keyboard from Ubuntu on a Mac](http://superuser.com/q/217615/84988) (2010-12-02)

**Comment by pkgdemon** [comment]
I have read that in some situations having moused enabled can mess with synaptics. However it's required in other cases for normal mice.  Could you try the following to see if it makes a difference?

```rc-update delete moused default```

Then just reboot.  If it breaks your mouse altogether to add it back...

```rc-update add moused default```

**Comment by grahamperrin** [comment]
(Please ignore the reference from `#76`, that was a typo (wrong number) in a comment.)

**Comment by grahamperrin** [comment]
> `rc-update delete moused default`

Done, as superuser, then disconnection of all USB devices and a restart of version `#55` of the OS. Result: 

- trackpad still not usable
- after I connect an Apple Pro Mouse (to the right-hand USB port), that mouse works. 

Again I disconnected the mouse then restarted the OS. Observed before appearance of the display manager: 

> … moused is already running

**Comment by pkgdemon** [comment]
You may also need to to try.

```rc-update delete devd boot``` 

To get rid of moused completely for testing.  It is currently setup to look for attached mice, and run moused when needed as well.

To add back in if needed....


```rc-update add devd boot```

**Comment by grahamperrin** [comment]
The two deletions had a positive effect for a different issue; discussed around https://gitter.im/trueos/troubleshooting?at=584d9d9903554185047b26cb

**Comment by grahamperrin** [comment]
Noted with thanks, in today's [Input Device Settings for Lumina Config are here! - TrueOS](https://www.trueos.org/blog/input-device-settings-lumina-config/): 

> … Future improvements include fixing a bug preventing detection of more than one USB mouse input (including laptop touchpads)…

**Comment by grahamperrin** [comment]
Also affected: an early 2009 17" **MacBookPro5,2**, which might become my preferred computer for production use of TrueOS Desktop.

**Comment by pkgdemon** [comment]
Ok thanks for your reworking of this ticket.  I was able to follow along with what you were saying this time that disabling the services impacted another problem but not this one.

Anyway I just discovered FreeBSD uses an Apple touchpad driver to produce right click.  Maybe try adding:

```atp_load="YES"``` to ```/boot/loader.conf```

Or you could just add ``atp``` to ```/etc/conf.d/modules``` as well to test.

You can do ```man atp``` to read about it as well.

**Comment by grahamperrin** [comment]
> … add atp to /etc/conf.d/modules …

Done, at the USB flash drive that I'm most recently using to test (an encrypted installation of) TrueOS Desktop. Success: 

- I now have contextual menus at a MacBookPro5,2 and a MacBookPro11,2 without requiring an external HID. 

I guess a manual page upstream in FreeBSD is outdated: 

- generally https://www.freebsd.org/cgi/man.cgi?query=atp&sektion=4&manpath=FreeBSD
- specifically https://www.freebsd.org/cgi/man.cgi?query=atp&sektion=4&manpath=FreeBSD+12-current

– both pages (or both representations of the single page) state: 

> … two-finger tap maps to the middle button; whereas a three-finger tap gets treated as a right button click. …

Here, neither FreeBSD-described treatment is true. Instead, at both Macs: 

- a contextual menu appears in response to a **two**-finger tap.

**Comment by pkgdemon** [comment]
Does it fix the right click issue?

**Comment by grahamperrin** [comment]
Yes and no. 

Off the top of my head, earlier, I couldn't think of anything other than the contextual menu. 

Now I remember: 

- **Alt + Two-finger-tap + Drag** inside a window, near its corner

– tested in Lumina, not fixed for that relatively obscure use case (if a two-finger-tap should be equivalent to a right click, then the combination/sequence of actions in that point should allow the window to be resized from any corner). I guess that for this to be fixed would require an enhancement upstream in FreeBSD.

**Comment by pkgdemon** [comment]
So it enables two finger tap to simulate right click?  Is it worth us including the module to close this issue?

**Comment by grahamperrin** [comment]
Yes and yes (thanks)

- provided inclusion does not adversely affect uses of combinations of HIDs in non-Mac environments

– would you like me to test any such environment? (I might test a Logitech USB mouse, Logitech USB trackball and Kensington USB keyboard with one of the following (take your pick): modern HP EliteBook 850 G2, mid-range HP EliteBook 8540p, old-ish Asus netbook, older Ergo Vista 621.)

**Comment by pkgdemon** [comment]
Sure.  I have tested loading atp so far on a few systems, and it has not broken anything.  We already load some other modules like this by default even when hardware is not present.  Let me know if you can confirm no breakage on your setups.

**Comment by grahamperrin** [comment]
Added to an HP EliteBook 850 G2: 

```
$ grep atp /etc/conf.d/modules
modules="atp libiconv libmchain msdosfs_iconv if_bwn if_bwi runfw if_iwm cuse sem geom_uzip fdescfs linsysfs iwn4965fw iwn1000fw iwn5000fw iwn5150fw iwn6000fw 
$ date ; uptime ; pkg info trueos-desktop | grep -i version ; uname -v ; uname -n
Thu  5 Jan 2017 15:32:53 GMT
 3:32p.m.  up  1:20, 5 users, load averages: 0.81, 0.82, 0.78
Version        : 201701042114
FreeBSD 12.0-CURRENT #12 5ef9376(drm-next-4.7): Thu Dec 29 16:26:36 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk
$ 
```

I'll restart the OS to tell the result.

**Comment by pkgdemon** [comment]
Just a thought.  We could also consider adding this to the Post Installation Tasks screen, and call that screen something else besides optional services.  Unless it may be more desirable to have right click all the way through the installation as well.

https://www.trueos.org/handbook/postinstall.html#config6

**Comment by grahamperrin** [comment]
> Added to an HP EliteBook 850 G2: 

… and overwritten, probably by an update to the OS, so I must retest. 

( :-) Elsewhere, I should create a user-friendly point of reference for areas that are, and are not, at risk of overwriting at such times. Which other files might I use to persistently define the load of the module?)

**Comment by pkgdemon** [comment]
Upon further investigation devd has this:

https://github.com/trueos/freebsd/blob/drm-next-4.7/etc/devd/usb.conf

Here is just an example from one of multiple instances:

```
nomatch 32 {
	match "bus" "uhub[0-9]+";
	match "mode" "host";
	match "vendor" "0x05ac";
	match "product" "(0x020d|0x020e|0x020f|0x0210|0x0214|0x0215|0x0216|0x0217|0x0218|0x0219|0x021a|0x021b|0x021c)";
	action "kldload -n atp";
};
```

Where it is doing match product it should be looking for something, and loading atp if that code is found.  I think if we could figure out what tool ```pciconf -lv``` or similar would present this information from your macbooks we could add those device codes for TrueOS, and event submit a patch upstream to fix in FreeBSD as well.  That may be the better fix.

**Comment by grahamperrin** [comment]
## MacBookPro11,2

```
Apple Internal Keyboard / Trackpad:

  Product ID:	0x0263
  Vendor ID:	0x05ac  (Apple Inc.)
  Version:	2.25
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Apple Inc.
  Location ID:	0x14400000 / 3
  Current Available (mA):	500
  Current Required (mA):	40
  Extra Operating Current (mA):	0
  Built-In:	Yes
```

This type of pad has a tangible click. Probably hinged at the top (where it's possible to tap but not click).

**Comment by pkgdemon** [comment]
Interestingly both the Vendor ID, and Product ID are present in ```/etc/devd/usb.conf``` but configured to load ```wsp``` "Wellspring touchpad driver" see ```man wsp```.  I would check ```kldstat | grep wsp``` to see if it is loaded, and maybe try ```kldload wsp``` if not.

Lines 1232-1238 https://github.com/trueos/freebsd/blob/drm-next-4.7/etc/devd/usb.conf

```
nomatch 32 {
	match "bus" "uhub[0-9]+";
	match "mode" "host";
	match "vendor" "0x05ac";
	match "product" "(0x0230|0x0231|0x0232|0x0236|0x0237|0x0238|0x023f|0x0240|0x0241|0x0242|0x0243|0x0244|0x0245|0x0246|0x0247|0x0249|0x024a|0x024b|0x024c|0x024d|0x024e|0x0252|0x0253|0x0254|0x0259|0x025a|0x025b|0x0262|0x0263|0x0264|0x0272|0x0273|0x0274|0x0290|0x0291|0x0292)";
	action "kldload -n wsp";
};
```

**Comment by grahamperrin** [comment]
wsp is loaded, when I unload atp I lose the ability to right-click (if there's an alternative to the two-finger tap, I can't guess what it is).

**Comment by pkgdemon** [comment]
Fixed will be in next unstable push after packages build.  https://github.com/trueos/trueos-core/commit/d0da1659cbaf9b940f77b3932ef299fb74189d23
