### ISSUE TITLE
Dead link in lpreserver's man page 

### ISSUE THREAD

**Issue by asomers** [trueos/trueos-core#193]
The SEE ALSO sectionof lpreserver(8) references http://wiki.pcbsd.org/index.php/Life_Preserver/, which no longer exists.  It should probably point to https://www.trueos.org/handbook/sysadmclient.html#life-preserver instead, or maybe to https://github.com/trueos/lpreserver .

**Comment by Mrt134** [comment]
Created pull request: https://github.com/trueos/lpreserver/pull/12

**Comment by beanpole135** [comment]
Pull request merged.
