### ISSUE TITLE
Losses of Internet connectivity with #59

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#201]
- `FreeBSD 12.0-CURRENT #59 deb4a9b(drm-next-4.7): Sun Dec 11 19:50:23 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC`
- HP EliteBook 850 G2
- docked
- wireless connection to eduroam, probably automated 
- wired (docked) connection to a network with a static IP address, with two DNS servers and a gateway specified, by me, after log in to KDE,

## Incident 01

Not long after I logged on, this incident occurred whilst Firefox was restoring windows from a previous session. 

In this case: after a few failed attempts to workaround, I successfully worked around the problem by using `pc-netmanager` to specify a search domain where previously, none was specified. (I understand that a search domain entry is not required, but I had a hunch that applying changes with that entry would do the trick.) A subsequent screenshot: 

![2016-12-12 09 17 24](https://cloud.githubusercontent.com/assets/192271/21097876/9b08bdb0-c05e-11e6-95b6-7d11cbe4c2a2.png)

## Incident 02

Shortly before 09:56, this incident occurred during normal use of Firefox, coincided with a load (or reload) of the https:// address of a ticket ('incident') within the LANDESK service at University of Brighton. 

In this case I requested a _re_start of the wpa_supplicant and (below) from the 'start-stop-daemon: no matching processes' response, I _assume_ that: 

- the WPA supplicant daemon had, previously, unexpectedly stopped; with 
- a consequent or coincidental undesirable effect on wired Internet connectivity. 

```
$ drill
Error: error sending query: Error creating socket
$ sudo service wpa_supplicant restart
Password:
wpa_supplicant| * Stopping WPA Supplicant Daemon ...
wpa_supplicant| * start-stop-daemon: no matching processes found                                                                                        [ ok ]
wpa_supplicant| * Starting WPA Supplicant Daemon ...
wpa_supplicant|Successfully initialized wpa_supplicant                                                                                                  [ ok ]
$ drill
Error: error sending query: Error creating socket
$ drill
Error: error sending query: Error creating socket
$ drill
Error: error sending query: Error creating socket
$ drill
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 61932
;; flags: qr rd ra ; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 12 
;; QUESTION SECTION:
;; .    IN      NS
```

[2016-12-12 09:16 terminal output.txt](https://github.com/trueos/trueos-core/files/645788/2016-12-12.09.16.terminal.output.txt)

[messages.txt](https://github.com/trueos/trueos-core/files/645789/messages.txt)

**Comment by pkgdemon** [comment]
Looking over your configuration this is bad, and invalid for dhcpcd:

```ifconfig_wlan0="WPA SYNCDHCP"```

It should be:

```ifconfig_wlan0="WPA DHCP"```

We had fixed pc-netmanager, trueosinit, and the firstboot wireless wizard to always SET DHCP.  Is that something that was just left over from an upgrade?  Or did you you set it up that way manually?

**Comment by pkgdemon** [comment]
The SYNCDHCP parameter was specifically for dhclient.  It would force dhclient not to background dhcp requests, and require everything to stop until an address was grabbed, or a timeout was reached.

**Comment by grahamperrin** [comment]
> … We had fixed pc-netmanager, trueosinit, and the firstboot wireless wizard to always SET DHCP. Is that something that was just left over from an upgrade? Or did you you set it up that way manually?

My first boot of `#59` was this morning at work. 

Now: 

```
$ date ; uptime ; uname -v
Mon 12 Dec 2016 14:10:46 GMT
 2:10p.m.  up  3:07, 3 users, load averages: 0.52, 0.71, 0.66
FreeBSD 12.0-CURRENT #59 deb4a9b(drm-next-4.7): Sun Dec 11 19:50:23 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
$ ifconfig 
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=4019b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,VLAN_HWTSO>
        ether 58:20:b1:d8:f9:66
        inet6 fe80::5a20:b1ff:fed8:f966%em0 prefixlen 64 scopeid 0x1 
        inet 193.62.168.100 netmask 0xffffff00 broadcast 193.62.168.255 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet 127.0.0.1 netmask 0xff000000 
        inet6 ::1 prefixlen 128 
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo 
wlan0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        ether 94:65:9c:0f:c3:9b
        inet6 fe80::9665:9cff:fe0f:c39b%wlan0 prefixlen 64 scopeid 0x3 
        inet 10.1.9.118 netmask 0xfffff800 broadcast 10.1.15.255 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: IEEE 802.11 Wireless Ethernet OFDM/36Mbps mode 11a
        status: associated
        ssid eduroam channel 40 (5200 MHz 11a) bssid a8:d0:e5:c2:72:c1
        regdomain FCC country US authmode WPA2/802.11i privacy ON
        deftxkey UNDEF AES-CCM 2:128-bit txpower 17 bmiss 10 mcastrate 6
        mgmtrate 6 scanvalid 60 wme roaming MANUAL
        groups: wlan 
$ cat /etc/rc.conf
# Auto-Enabled NICs from pc-sysinstall
ifconfig_em0="193.62.168.100 netmask 255.255.255.0"
# Auto-Enabled NICs from pc-sysinstall
hostname="momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk"
zfs_enable="YES"
wlans_iwm0="wlan0"
ifconfig_wlan0="WPA SYNCDHCP"
sshd_enable="YES"
ifconfig_em0_ipv6="inet6 accept_rtadv"
kldload_i915kms="i915kms"
kldload_vbox="vboxdrv"
vboxnet_enable="YES"
# dbus_enable="YES"
rc_parallel="YES"
rc_logger="YES"
rc_log_path="/var/log/rc.log"
# https://github.com/trueos/freebsd/commit/0af2dbd9b11c7ac54baef4b3bcd762f85bd3a658
linux_enable="YES"
defaultrouter="193.62.168.1"
$ 
```

If it helps: I guess that `ifconfig_wlan0="WPA SYNCDHCP"` is written to `rc.conf` in connection with eduroam.

**Comment by grahamperrin** [comment]
>> … guess that ifconfig_wlan0="WPA SYNCDHCP" is written to rc.conf in connection with eduroam.

Probably scrub that guess. From https://gitter.im/trueos/troubleshooting?at=5852f05e61e516c1578dc16a –

> I recall commenting out the ifconfig_wlan0="WPA SYNCDHCP" … 

– but there it is, the line, **not** commented out.

**Comment by grahamperrin** [comment]
Refocusing on this issue, as originally described **losses of Internet connectivity** whilst actively using the OS: 

- with superior versions of the OS, I can not recall an incident 

– so I guess that recent commits have fixed the issue. I'll close this, we can reopen if necessary. 

----

Someone might raise a separate issue for the _SYNCDHCP_ observations. From chat elsewhere I assume that the developers are suitably aware without the formality of an issue in GitHub.
