### ISSUE TITLE
PersonalCrypt - New user vs Excisting user

### ISSUE THREAD

**Issue by RodMyers** [trueos/trueos-core#202]
Attempted to setup and use PersonalCrypt (pc) on main computer (STABLE). Have a number of existing accounts, all lowercase names, except regular account, which had name in uppercase. Default sort order is Upper case names first, then lowercase. Accidentally selected working account and not a new account.

There was no progress bar indicating status of creating,copying,etc

Would be nice to had a popup asking if this is the correct user?

Would be nice to have some kind of "Progress Bar" indicating some kind of progress, especially if a large HOME directory is involved.

In a conversation with @kmoore134 , I was able to remove the "lock" file indicating that my account was a PC enabled. Allowing me to get my account back

**Comment by beanpole135** [comment]
Fixed!

We decided that within the GUI at least, the PersonaCrypt initialization option should only be available for *new* user accounts. Power users may still "convert" an existing user account to PC from the command line or via direct API call, but then they should be expecting long delays while that process runs.
