### ISSUE TITLE
Migrate to OpenRC leaves system with no cron running

### ISSUE THREAD

**Issue by mremski** [trueos/trueos-core#203]
Had a basic install running, around 12/4 pulled in updates from Edge.  Didn't realize it at the time, but cron was not reenabled after the reboot.  Noticed it today after pulling in updates that my periodic scripts had not run.
The /etc/rc.conf.trueos had anacron_enable=YES, anacron was available in /usr/local/etc/init.d, but the rc-update add anacron default was not run.  
The migrate_rc_openrc should probably look at both /etc/rc.conf and /etc/rc.conf.trueos for what's enabled/disabled (similar to the way current rc files are processed).
I'm assuming the basic install of openrc has the correct symlinks for most of the needed items.

**Comment by kmoore134** [comment]
We just fixed this a few hours ago, didn't realize cron was missing. Thanks for the heads up though!
