### ISSUE TITLE
Intel Centrino Advanced-N 6200 wireless Internet service not gained until after starts and/or restarts of services

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#205]
There's a history of commands but unfortunately a problem with terminal scrollback caused loss of output from all commands. Sorry. As far as I recall: 

- after I started the OS and then logged in to Lumina, the tray icon did not indicate a connection to the required network (it was 'fuller' than is normally seen with the required network … maybe the OS had initially automated a connection to an unwanted unsecured network)
- some time after log to lumina, `ifconfig` showed that there was a connection to the required network 'piano' 
- `drill` could not open a socket, words to that effect
- according to `service`, neither dhcpcd nor wpa_supplicant was started but those status reports were inconsistent with what I saw in output from `ifconfig` (a leased IP address)
- when I started the supposedly stopped wpa_supplicant, the response was that it was already started
- and so on (sigh, I wish that terminal output had not been lost)
- Internet service was not gained until the 19:36 restart of dhcpcd

```
$ uname -v
FreeBSD 12.0-CURRENT #2 f71568c(drm-next-4.7): Tue Dec 13 21:04:35 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
$ cat /etc/rc.conf
kldload_nvidia="nvidia-modeset nvidia"
# Auto-Enabled NICs from pc-sysinstall
ifconfig_em0="DHCP"
wlans_iwn0="wlan0"
ifconfig_wlan0="WPA DHCP"
# Auto-Enabled NICs from pc-sysinstall
ifconfig_em0_ipv6="inet6 accept_rtadv"
hostname="momh167-gjp4-hpelitebook8540p-trueos.university.brighton.ac.uk"
zfs_enable="YES"
if_rtwn_load="YES"
sshd_enable="YES"
rc_parallel="YES"
rc_logger="YES"
rc_log_path="/var/log/rc.log"
linux_enable="YES"
$ 
```

[2016-12-13 19:11 messages.txt](https://github.com/trueos/trueos-core/files/652735/2016-12-13.19.11.messages.txt)
[rc.log.txt](https://github.com/trueos/trueos-core/files/652739/rc.log.txt)
[history.txt](https://github.com/trueos/trueos-core/files/652740/history.txt)
[pciconf -lv.txt](https://github.com/trueos/trueos-core/files/652744/pciconf.-lv.txt)

----

```
$ date ; uptime ; rc-status
Wed 14 Dec 2016 20:08:40 GMT
 8:08p.m.  up 58 mins, 1 users, load averages: 1.12, 1.04, 1.04
Runlevel: default
 zfs                                                   [  started  ]
 rpcbind                                               [  started  ]
 automount                                             [  started  ]
 statd                                                 [  started  ]
 lockd                                                 [  started  ]
 moused                                                [  started  ]
 netmount                                              [  started  ]
 sshd                                                  [  started  ]
 local                                                 [  started  ]
 dbus                                                  [  started  ]
 cupsd                                                 [  started  ]
 openntpd                                              [  started  ]
 sysadm                                                [  started  ]
 cups_browsed                                          [  started  ]
Dynamic Runlevel: hotplugged
Dynamic Runlevel: needed/wanted
 automountd                                            [  started  ]
 nfsclient                                             [  started  ]
 modules-load                                          [  started  ]
 avahi-daemon                                          [  started  ]
Dynamic Runlevel: manual
 network.lo0                                           [  started  ]
 moused.psm0                                           [  started  ]
 network.wlan0                                         [  started  ]
 network.em0                                           [  started  ]
 wpa_supplicant                                        [  started  ]
 wpa_supplicant.wlan0                                  [  started  ]
 dhcpcd                                                [  started  ]
 dhcpcd.wlan0                                          [  started  ]
$ 
```

I'll restart the OS then repeat the `rc-status` command before attempting to work around the problem.

**Comment by q5sys** [comment]
assuming you have your wireless config already saved, after you boot and fail to connect run `sudo service wpa_supplicant restart` then run `ifconfig` after a few seconds and see if you get associated.  If that doesnt work, run `sudo service network restart` wait a few seconds and check `ifconfig` again and then try `sudo service wpa_supplicant restart` again if you still havent connected.  its a known issue right now.  The network manager utility needs to be tweaked due to a few changed on the back end.

**Comment by grahamperrin** [comment]
As far as I recall, the association was good – and was with the proper network (no longer wrongly associated with the unsecured network (probably 'BTWi-fi')) – long before the starts/restarts of `wpa_supplicant`. 

For convenience, from the history.txt file: 

```
   100  8:29    sudo shutdown -h now
   101  19:15   drill
   102  19:15   date ; uptime ; uname -v
   103  19:15   ifconfig
   104  19:15   service wpa_supplicant status
   105  19:16   cat /etc/rc.conf
   106  19:16   date ; time drill
   107  19:16   date ; ifconfig
   108  19:17   date ; time drill
   109  19:19   pciconf -lv
   110  19:21   date ; time drill
   111  19:22   ifconfig
   112  19:22   service wpa_supplicant status
   113  19:22   service dhcpcd status
   114  19:23   date ; service wpa_supplicant status ; ifconfig ; time sudo service wpa_supplicant start
   115  19:23   service wpa_supplicant status
   116  19:23   date ; time drill
   117  19:23   ifconfig
   118  19:24   date ; time drill
   119  19:29   date ; time drill
   120  19:29   service wpa_supplicant status
   121  19:29   service wpa_supplicant.wlan0 status
   122  19:30   service dhcpcd status
   123  19:30   date ; time sudo service dhcpcd start
   124  19:30   service dhcpcd status
   125  19:30   ifconfig
   126  19:30   date ; time drill
   127  19:35   date ; time drill
   128  19:36   date ; time sudo service wpa_supplicant.wlan0 restart
   129  19:36   date ; time drill
   130  19:36   date ; time sudo service dhcpcd restart
```

----

Two subsequent starts/restarts of the OS were not bugged. 

A third is more revealing. At the manual runlevel: 

> dhcpcd.wlan0    [  **crashed**  ]

– I guess, that's consistent with one of my points above, 

> Internet service was not gained until the 19:36 restart of dhcpcd

**Comment by q5sys** [comment]
you also didnt run 'sudo service wpa_supplicant restart' until 19:36.   I've run that within a minute of booting and it's worked for both Ken and I.  If I waited ~20 minutes before running that it'd probably have taken me ~20 minutes to get my network working as well.  

Try a complete restart and instead of trying everything you tried before, follow what I wrote and see if it still takes you ~20 minutes to connect.  If it does... then we need to figure out what's going on.

**Comment by grahamperrin** [comment]
OK, thanks. 

Two subsequent restart of the OS were not bugged. 

If/when I next reproduce the bug I'll attempt a restart of wpa_supplicant in good time.

**Comment by q5sys** [comment]
Cool, look forward to hearing back from you on it...  or perhaps I should say I hope I don't hear back from you about it being a continued issue. lol.

**Comment by grahamperrin** [comment]
For the record: discussed at length, https://gitter.im/trueos/troubleshooting?at=5851b40296a565f844056096 and very recent https://github.com/trueos/freebsd/commit/cc46c554cc8eabd4cdeeb129f21f8a47a9b2a2bf should make things easier to troubleshoot if symptoms recur at the HP EliteBook 8540p (with Intel Centrino Advanced-N 6200) with `cc46c55(drm-next-4.7)` or greater.

**Comment by grahamperrin** [comment]
```

$ uname -v
FreeBSD 12.0-CURRENT #9 0d57090(drm-next-4.7): Thu Dec 22 01:53:46 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
$ uname -n
momh167-gjp4-hpelitebook8540p-trueos.university.brighton.ac.uk
$ 
```

https://gitter.im/trueos/Lobby?at=585c212161e516c1578ebf83

> … first and second impressions … more prone to crashes of dhcpcd.

[2016-12-22 18:21 terminal output.txt](https://github.com/trueos/trueos-core/files/670046/2016-12-22.18.21.terminal.output.txt)

**Comment by grahamperrin** [comment]
```
$ uname -v
FreeBSD 12.0-CURRENT #12 5ef9376(drm-next-4.7): Thu Dec 29 16:26:36 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
$ 
```

Following the update, whilst editing 
`/etc/rc.conf` (and `/boot/loader.conf.trueos`, to restore my preferences, which had been overwritten) I observed the absence of: 

`wlans_iwn0="wlan0"`

It's _possible_ that I accidentally cut the line (Control-K in `nano`) but in this case, I doubt it. 

With the missing line rewritten, and with some extraordinary preferences (below), early indications are that **wireless Internet access has become reliable**; no need for manual or custom scripted intervention after each start of the OS. 

```
rc_verbose="YES"
rc_interactive="YES"
rc_depend_strict="YES"
rc_parallel="YES"
rc_crashed_start="NO"
```

```
# Speed up boot time
autoboot_delay="01"
```

```
# Enable the TrueOS splash-screen
# boot_mute="YES"
```

Whilst we are reliably advised that `rc_parallel="YES"` will cause problems, for now that _is_ my preference for this hardware. Maximising the likelihood of reliable Internet access, I can probably treat parallel-related problems as of secondary importance with this hardware (it's a test bed, not a production environment).

**Comment by jungle-boogie** [comment]
Note: I haven't read this entire issue yet.

I'm running `8b9df91(drm-next-4.7): Sat Dec 24 15:17:28 UTC 2016` and upon reboots, my wireless network is not associated with any connection. If I restart the network manager within GUI, it will associate and I'll stay connected.

**Comment by grahamperrin** [comment]
Thanks; @jungle-boogie please, was all of that with _Intel Centrino Advanced-N 6200_ and if so, with what make and model of computer? 

Here: 

- `hostname="momh167-gjp4-hpelitebook8540p-trueos.university.brighton.ac.uk"`

– that's [an HP EliteBook 8540p notebook](https://discourse.trueos.org/t/hp-elitebook-8540p-notebook/305?u=grahamperrin). 

## Network error reported by [drill](https://www.freebsd.org/cgi/man.cgi?query=drill&sektion=1&manpath=FreeBSD)(1)

> My network connection died for about 30-60 seconds as I was using my laptop:
> 
> `% drill`
> `Error: error sending query: Could not send or receive, because of network error`
> 
> running `netstat -r` took about 30-60 seconds until it returned the results.
> 
> I had to restart the network manager for it to establish a connection again.

I recall just one comparable situation, but I can not recall whether it was with the EliteBook 8540p. In my case IIRC truly there **was** a network error, beyond the control of the computer. I _might_ have run e.g. the script at https://gist.github.com/grahamperrin/121bc018a1675e7532e0cf88de0c22f9 and subsequently realised that the run was unnecessary given the true nature of the error. 

Incidentally I am prepared to eventually retire that script; see below.

## With, without, with `netif`

2016-11-15: [Joe wrote](https://discourse.trueos.org/t/-/210/6?u=grahamperrin) under _OpenRC is coming to TrueOS - Announcements_: 

> … replaces the netif / wpa supplicant / network.subr routines for network mangement. …

2016-12-28: https://gitter.im/trueos/Lobby?at=5863b9b361e516c1578f2f0d quoted the intention (2016-12-27) of Kris to port `netif`directly from FreeBSD. 

@kmoore134 @pkgdemon I was ready to ask, _whether_ any part of my recent successful (or at least partial) experiments with OpenRC might dangle the prospect of continuing **without** the port of `netif`. 

Then I read, https://github.com/trueos/trueos-changelog/commit/a4ee07fd4b818ae40233b52235259329c9dc86b2 (2016-12-28 15:37:48 PST): 

> Large update to network startup code. Import from FreeBSD's /etc/rc.d/netif only slightly updated for some OpenRC functionality. This should allow alias to work again, as well as fix a variety of regressions.

## `FreeBSD 12.0-CURRENT #12 5ef9376(drm-next-4.7): …`

I get confused with time zones but I guess that this does (or will) include the logged import from FreeBSD's `netif`. Please correct me if I'm wrong.

**Comment by jungle-boogie** [comment]
Hi @grahamperrin, 

It's this laptop: https://www.asus.com/us/Notebooks/X555LA/specifications/

I don't see why TZ matters because the time is listed as UTC.

**Comment by pkgdemon** [comment]
As far az I know the netif port was successful, and should be in next unstable packages.  It will still use dhcpcd.

**Comment by grahamperrin** [comment]
Thanks @jungle-boogie 

> … TZ … UTC.

My confusions with time zones e.g. when UTC is not explicit are probably the dyslexic side of me, https://gitter.im/trueos/Random?at=586230a996a565f84406df34 if you'd like to follow up. 

## Hardware and drivers

###  HP EliteBook 8540p

Intel Centrino Advanced-N 6200 driven by [iwn](https://www.freebsd.org/cgi/man.cgi?query=iwm&sektion=4&manpath=FreeBSD )(4). 

### Asus X555LA

> https://www.asus.com/us/Notebooks/X555LA/specifications/

>> Intel® Core™ i7 4510U 2 GHz ~ 3.1 GHz Processor
>> Intel® Core™ i5 4210U 1.7 GHz ~ 2.7 GHz Processor

>> Integrated 802.11 b/g/n

Intel ARK finds: 

- http://ark.intel.com/products/81016/Intel-Core-i5-4210U-Processor-3M-Cache-up-to-2_70-GHz?q=%204210U for 4210U
- http://ark.intel.com/products/81015/Intel-Core-i7-4510U-Processor-4M-Cache-up-to-3_10-GHz?q=%204510U for 4510U

I can't tell whether `iwn`(4) drives either of those.

**Comment by jungle-boogie** [comment]
dmesg shows:
re0: <RealTek 8168/8111 B/C/CP/D/DP/E/F/G PCIe Gigabit Ethernet> port 0x3000-0x30ff mem 0xb2104000-0xb2104fff,0xb2100000-0xb2103fff irq 18 at device 0.0 on pci2

**Comment by grahamperrin** [comment]
Thanks, that's probably wired (not wireless).

**Comment by pkgdemon** [comment]
This should be fixed in latest UNSTABLE.  Let me know if it is not, and I will reopen.
