### ISSUE TITLE
trueos/trueos-utils: /usr/local/share/trueos/version contains nothing

### ISSUE THREAD

**Issue by baitisj** [trueos/trueos-core#206]
According to `about`, this should contain the version of TrueOS that the user has installed

**Comment by pkgdemon** [comment]
I would propose this contain the output of pkg info trueos-desktop:

```Name           : trueos-desktop
Version        : 201612132146```

**Comment by pkgdemon** [comment]
Fixed in https://github.com/trueos/trueos-utils/commit/4db68fd7fcbef9aac8b14858405692c4504f88e5
