### ISSUE TITLE
openrc: some scripts need to move from `/usr/local/etc/rc.d` to `/usr/local/etc/init.d`

### ISSUE THREAD

**Issue by baitisj** [trueos/trueos-core#207]
Currently, it appears that some services are NOT installed into the locations where openrc is expecting them.

Some packages (such as `pcdm`) are installed into both `rc.d/` and `init.d/`

```
(ins)baitisj@raid: ~/ $ service samba_server start
 * service: service `samba_server' does not exist
```

```
ls /usr/local/etc/rc.d/
avahi-daemon   git_daemon     miniupnpc      pcdm           socat          sysadm-bridge  tor            uuidd          vboxwebsrv
avahi-dnsconfd gpsd           mysql-server   samba_server   svnserve       sysadm-rest    tpmd           vboxheadless   wacom
ffserver       kpropd         openntpd       slpd           sysadm         tcsd           trueosinit     vboxwatchdog
```

**Comment by baitisj** [comment]
```
(ins)baitisj@raid: /usr/local/etc/init.d/ $ ls /usr/local/etc/init.d/ > /tmp/inits
(ins)baitisj@raid: /usr/local/etc/init.d/ $ ls /usr/local/etc/rc.d/ > /tmp/rcs
(ins)baitisj@raid: /usr/local/etc/init.d/ $ diff -u /tmp/inits /tmp/rcs 
--- /tmp/inits	2016-12-14 18:48:14.284558000 -0800
+++ /tmp/rcs	2016-12-14 18:48:23.492429000 -0800
@@ -1,17 +1,26 @@
-anacron
 avahi-daemon
 avahi-dnsconfd
-cups_browsed
-cupsd
-dbus
-dhcpcd
-dhcpcd.em0
-hald
+ffserver
+git_daemon
+gpsd
+kpropd
+miniupnpc
+mysql-server
 openntpd
 pcdm
+samba_server
+slpd
+socat
+svnserve
 sysadm
 sysadm-bridge
 sysadm-rest
-vboxnet
-webcamd
-wpa_supplicant
+tcsd
+tor
+tpmd
+trueosinit
+uuidd
+vboxheadless
+vboxwatchdog
+vboxwebsrv
+wacom
```

**Comment by pkgdemon** [comment]
@baitisj It most likely means we have not added them yet.  if the ports are still using ```USE_RC_SUBR``` instead of ```USE_OPENRC_SUBR``` then they may not have the updated openrc compatible scripts yet.

**Comment by pkgdemon** [comment]
@baitisj I do see what you mean now about duplicates!  Not sure what is causing that I will have to dig further.

**Comment by rebost** [comment]
a few more not working:
vm-bhyve
rsyncd
postgresql96-server

$ /usr/local/etc/rc.d/postgresql start
/usr/local/etc/rc.d/postgresql: source_rc_confs: Permission denied

$ sudo service postgresql start
 * service: service `postgresql' does not exist

**Comment by rebost** [comment]
$ vm list
/usr/local/sbin/vm: source_rc_confs: not found
/usr/local/sbin/vm: WARNING: $vm_enable is not set properly - see rc.conf(5).
/usr/local/sbin/vm: ERROR: $vm_enable is not enabled in /etc/rc.conf!


Needless to say, $vm_enable is correctly set up in rc.conf

```
$ cat /etc/rc.conf | grep vm
# vm-bhyve
vm_enable="YES"
vm_dir="zfs:tank/BHYVE"
vm_list="centos01 extractor"
vm_delay="5"
```

**Comment by asomers** [comment]
Add sysutils/iocage to the list

**Comment by c0psrul3** [comment]
+ nginx

**Comment by kmoore134** [comment]
its more than just moving, they have to be updated with openrc specific bits. Could you open tickets for specific ones, so its easier to track? Already done iocage / nginx / vm-bhyve

**Comment by baitisj** [comment]
Rsync and samba4 have been done. Expect others forthcoming
