### ISSUE TITLE
rc-service(8) (service) cosmetics

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#208]
Compare: 

- actual outputs http://pastebin.com/raw/1QSsmCVU (taken from https://gist.github.com/grahamperrin/fa83b973a150eed0aaea60f9455e8973)
- mocked-up https://gist.githubusercontent.com/grahamperrin/83051b982c66fbec618847c3358066fc/raw/4e28c36be4c16c3f23fe02d923fb6195792afbd6/2016-12-15%2520trueos%2520rc-service%2520cosmetics.txt (the raw view of https://gist.github.com/grahamperrin/83051b982c66fbec618847c3358066fc)

**Comment by pkgdemon** [comment]
Has this been resolved for you?  I am no longer seeing anything like this.

**Comment by grahamperrin** [comment]
Output from e.g. `rc-service network restart` is very different now. I imagine some minor cosmetic improvements, but not enough to keep this issue open at this time. 

Thanks
