### ISSUE TITLE
Not able to select boot loader

### ISSUE THREAD

**Issue by jmdavis** [trueos/trueos-core#21]
I have PC-BSD 10.3 installed and am using grub, but when I tried to upgrade with TrueOS-Desktop-12.0-CURRENT-08-02-2016-x64-DVD.iso, the drop down for the boot loader selection said BSD, and I wasn't able to change it. The control for selecting it didn't respond at all (I'm pretty sure that the customize button had the same problem too, but I'd have to redo it to be sure).

**Comment by grahamperrin** [comment]
Using a trackpad? Or a mouse?

**Comment by jmdavis** [comment]
Mouse. This is a desktop.

**Comment by kmoore134** [comment]
This issue was moved to trueos/trueos-utils-qt5#3
