### ISSUE TITLE
`beadm` doesn't understand what to do when it's launched from a rescue environment

### ISSUE THREAD

**Issue by baitisj** [trueos/trueos-core#210]
Real user scenario:

Suppose you royally screw up your current boot environment, and can no longer boot.

The natural solution is to boot the install media, slip into the rescue environment, and have the rescue `chroot` into the working boot environment.

When you do this, `beadm` doesn't think that you are booting from ZFS (because you didn't! you booted from installation media), and refuses to be helpful.

I foresee two options, with my preferred solution listed first:

1. Add a 'Manage boot environments' to the TrueOS Utility Menu;
2. Make `beadm` smart enough to figure out it's fixing stuff from a rescue shell.

**Comment by baitisj** [comment]
Additionally: it might be nice to either initiate or stop a `zfs scrub` on a pool from this menu. So maybe break this into a sub-menu of ZFS rescue options. Maybe not.

**Comment by RodMyers** [comment]
@baitisj have you attempted this with the new install media?

Is this still valid?

**Comment by beanpole135** [comment]
This is an issue with beadm functionality - that dev team will have to add functionality.
