### ISSUE TITLE
Undefined symbol "basename"

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#211]
Observed during the first stage of, and after, an update. 

[pc-updatemanager.log.txt](https://github.com/trueos/trueos-core/files/656107/pc-updatemanager.log.txt)

In the .log file –

> /usr/bin/touch: Undefined symbol "basename"

– and seventy-nine other matches. 

The resulting boot environment can not mount ZFS file systems; can not use beadm; and so on. 

> /lib/libzfs.so.2: Undefined symbol "basename"

**Comment by baitisj** [comment]
Do you have a test case that can replicate this condition (e.g. something I can run in VirtualBox to reproduce?)

**Comment by grahamperrin** [comment]
I reproduced the symptom at a third machine. Greying out of login options when attempting to log in (login fails because the file system for the user's home is not mounted). At this machine (HP EliteBook 8540p) a console without X (e.g. Control-Alt-F2) is illegible so with a simple press on the power button I shut down the OS, then booted an earlier environment and mounted the bugged environment to identify its version level: 

- `FreeBSD 12.0-CURRENT #5 2a77bff(drm-next-4.7): Thu Dec 15 16:30:10 UTC 2016`

The AppCafe view of installed software is not huge but it's too large for a screenshot, and (driving to work in a few minutes) right now I don't have time to find the command line method of gaining an equivalent list of what's installed. For now, I see, at a glance: 

- Adobe Flash Player (linux-c6 not linux-c7, ESR not beta)
- Chromium
- dtrace-toolkit
- fish
- HexChat
- htop
- nano
- nspluginwrapper
- lines relating to desktop environments GNOME, KDE and MATE
- Web (epiphany)

**Comment by grahamperrin** [comment]
Testing at a MacBookPro11,2 with very little software installed: 

<img width="431" alt="2016-12-16 13 11 05" src="https://cloud.githubusercontent.com/assets/192271/21264078/2a4c63a6-c392-11e6-8b90-484fe75f791f.png">

**Comment by grahamperrin** [comment]
```
$ uname -v
FreeBSD 12.0-CURRENT #6 3a85611(drm-next-4.7): Fri Dec 16 19:46:18 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
$ 
```

At two previously affected machines, the bug is no longer reproducible.
