### ISSUE TITLE
Dual boot support for MBR disks

### ISSUE THREAD

**Issue by NaomasaMaruyama** [trueos/trueos-core#212]
Although the world is quickly shifting to GPT+UEFI era, I still want to request you to properly support "legacy boot MBR disks", that is, pre-Windows7 machines.  Please apply the attached patch to /root/pc-sysinstall/backend/functions-bsdlabel.sh(of PCBSD11.0-CURRENTJUNE2016-06-10-2016-x64-USB installer):

[bsdlabel-patch.txt](https://github.com/trueos/trueos-core/files/656167/bsdlabel-patch.txt)

Here I explain some background and history for this patch.  If you use the current functions-bsdlabel.sh for MBR disks, you will typically get the following slice layout, but this causes serious confllict between traditional bsdlabel scheme and zfs functionalities:

=>        0  449054720  ada0s4  BSD  (214G)
          0  440635392       1  freebsd-zfs  (210G)
  440635392    8388608       2  freebsd-swap  (4.0G)
  449024000      30720          - free -  (15M)

In the traditional BSD label scheme, the beginning 16 sectors of each slice are reserved, one for bsdlabel itself and the others for stage 1 boot code.  In case a UFS FS is located at the beginning of a slice, there will be no such conflict, because UFS does not use first 16 sectors of each partition.  It seems that zfs does not have such special treatment for beginning sectors so that it will easily destroy the bsdlabel.  The correct layout should be like the followings, and in order to achieve this, you need the patch attached:

=>        0  449054720  ada0s4  BSD  (214G)
          0         16          - free -  (8.0K)
         16  440635392       1  freebsd-zfs  (210G)
  440635408    8388608       2  freebsd-swap  (4.0G)
  449024016      30704          - free -  (15M)

Note that geom data is cached in kernel memory so that the destruction of bsdlabel is less visible by "gpart show" command until a reboot.  Also note that it seems that the zfs uses some kind of random algorithm for allocating sectors inside the pool.  So the results are not uniform, but so far as I experienced,  partition information of the slice is lost after reboot in very high percentage and get the following, or in some case I could not even reboot:

# zpool status
  pool: tank
 state: ONLINE
  scan: none requested
config:

        NAME        STATE     READ WRITE CKSUM
        tank        ONLINE       0     0     0
          ada0s4    ONLINE       0     0     0 

You can see in the above "ada0s4", which should be "ada0s4a".  Also, in very high percentage, ada0s4b is lost so that one can not use a swap area.

I raised this issue as a bug report to the previous bug tracking system around July of 2015,
and Kris Moore took care of the ticket.  The attached patch is due to Kris, and after some correspondence between him, I felt this issue was solved.  So I was very disappointed to see
the patch is perfectly forgotten in 11.0.  I hope this point will again be included in 11.0.

**Comment by pkgdemon** [comment]
This was confirmed to be a bug in FreeBSD which we cannot fix.  GPT is the recommended scheme for dual booting at this time.
