### ISSUE TITLE
The user-preferred gateway is not used by the OS when, for example, Network Manager (pc-netmanager) is used to apply the preference

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#213]
From https://gitter.im/trueos/troubleshooting?at=5852b055589f411830ea5fdb (Thursday 2016-12-15, with correction to what I guess was a minor typo (dhcpd in lieu of dhcpcd)): 

> … turn off dhcp for all interfaces. dhcpcd will override … a critical bug for sure that takes priority … before next week…

The effects of this bug became clearer to me after I encountered the effects of the unwanted override in a campus network environment where, for access to some resources, it is essential (not merely desirable) to use a given gateway.

**Comment by pkgdemon** [comment]
Added notes in related ticket.

**Comment by pkgdemon** [comment]
Fixed in https://github.com/trueos/pc-networkmanager/commit/9dac7b128c4ada2869a7dee781478430e5a4ac6c
