### ISSUE TITLE
microSD card wit SD adapter not recognized

### ISSUE THREAD

**Issue by SoloBSD** [trueos/trueos-core#217]
When inserting SD card adapter with microSD card inside, TrueOS does not send anything thru dmesg, is like the card has never been inserted.
No mmX or daX device is created, nor exists in the system.
Maybe is a hardware issue.
Acer Aspire E 15 ES1-511-C4TC
8 Gb RAM
Intel Celeron N2830

**Comment by pkgdemon** [comment]
Is this hardware recognized by stock FreeBSD?  Maybe a required module in ```/boot/kernel/``` is not getting loaded?

**Comment by SoloBSD** [comment]
Good question, I've never got stock FreeBSD installed on that laptop, only HardenedBSD but never tried to mount the SD card :(

**Comment by pkgdemon** [comment]
I have a built in SD card reader which works on my desktop, a different reader on laptop, a usb adapter for setting up a raspberry pi at work, and a raspberry pi which all work.  I suspect in general we should have what is needed enabled.  If you find we don't, and it works elsewhere please let me know so I can reopen.
