### ISSUE TITLE
Strange behavior of X during installation and the first boot 

### ISSUE THREAD

**Issue by NaomasaMaruyama** [trueos/trueos-core#218]
Sorry, I tested on JULY2016 version of TrueOS-Desktop USB, little bit old.

I am using lenovo X230 for this test.  Selected "xorg" on TrueOS Installation Menu, creating QTerminal windows and double-click the status bar of them several times, I got the screens below:

![screen1](https://cloud.githubusercontent.com/assets/24597157/21283856/d9530064-c44e-11e6-9ced-66e3b6f4b642.jpg)
![screen2](https://cloud.githubusercontent.com/assets/24597157/21283858/df408f5a-c44e-11e6-984e-d590d87b9013.jpg)

It seems that backing store is not working correctly.  And when I once switch to VTY screen  by Ctrl+Alt+F2 and came back to X by Alt+F9, I got more nasty screen!

![screen3](https://cloud.githubusercontent.com/assets/24597157/21283879/60d4e35e-c44f-11e6-955f-b86b2c2dfb48.jpg)
  
Nevertheless, I could finish the installation patiently ignoring this strange phenomenon.
But at the first boot, I encountered more serious problem: after the boot messages,
a screen saying
# Preparing to start the desktop...
and blank screen alternatively appears in short time interval, and repeats infinitely.
I see this with both boot mode: Lagecy and UEFI.

Terrible.  Is this problem solved by the latest version 2016-12-15-x64-USB.img  ? 
 I guess the team hasn't tested the installer on intel graphics machines before this July. 
But intel graphics machines are major share of the PC market, so I strongly recommend, and request you to test EVERY version first with intel graphic machines. 

Perhaps you can buy a second hand x230 on Yahoo auction at less than 300$.  I got one on Yahoo Japan auction and I guess similar things are taking place on Yahoo.com.

**Comment by NaomasaMaruyama** [comment]
I tested TrueOS-Desktop-2016-12-15-x64-USB on my Lenovo ThinkPad X230.  Thanks.  It seems this issue is already solved for at least lenovo x230.  In both legacy and UEFI boot mode, I got fine results.   Please close this issue.

**Comment by q5sys** [comment]
People always recommend we buy 2nd hand units for testing when it's their 
unit that doesn't work.  But what about everyone else?  There are at least 
9 x200 series think pads: x200, x201, x201t, x220, x220t, x230, x230t, 
x240, x250, x250. (Some of the t units have different spec hardware.). You 
have the x100 series units, which I don't know anything about. There's the 
T series line which, there are probably a dozen versions of, then you have 
the W series, the X1 series, etc... and that's just Thinkpads and not the 
rest of the lenovo line let alone other manufactures (Dell, HP, Acer, Asus, 
need I go on?)

If I win the lottery, I'll happily buy the project test units, but until 
then its not practical for us to purchase units to test.  That's what we 
rely on the community for.  I'd love to be able to test every release on 
every laptop out there, but not only do we not have the hardware to do 
that... we don't have an entire paid QA team to actually do the testing.  
The QA depts at Lenovo and Dell have tons of people paid to do just that.  
Unfortunately, that's not something we are able to do.

But hey... here's to hoping I win the lottery. ;)

**Comment by NaomasaMaruyama** [comment]
Thanks for commenting on already closed issue.  My point is not "second hand", but "market share".  I hope the team properly prioritize their job taking market share into account.  In addition, I think you have to check the new release on at least one real machine even if you are doing developing work on virtual machines.  The above symptom is relating to X11 intel driver, so I guess all intel graphic machines reproduced that.  It is almost a mystery that the team missed such a big point.
  But its already gone.  I will help you as a tester for X230 as a community member.
BTW, X230 is a very good machine.  It has both legacy and UEFI boot modes, main internal disk is plugable, and it is NOT an evil machine subject to "lenovofix" mentioned in "man gpart" (typical such evil machine is X220).  If you can not win a lottery and can afford only one machine, the best choice is X230, I assure you.

**Comment by q5sys** [comment]
I saw that you had closed the issue, but I wanted to reply anyway because
it's something that does come up all the time. Now I have a place to point
to when it comes up again. :P  I used to have a X230T, and I did really
like that unit, the only downside for me was the screen resolution
(1366x768).   As for Intel X11 driver, that's what we all use.  Everyone on
the team has an X1 carbon that uses the Intel GPU, so we do significant
testing on Intel units (I also test on an X250).  That's why it was
somewhat confusing that suddenly there was a problem with the Intel
Graphics chipset since we hadn't seen that issue yet.  Of course with Intel
there's the chance that they changed something wonky in the newer versions
which cause a regression with the newer driver.  But typically, Intel would
catch something like that in their own internal pipeline.  Sometimes
though, things slip through the cracks.

**Comment by NaomasaMaruyama** [comment]
OK.  I reopen this issue for future reference.
And, I still keep TrueOS-Desktop-11.0-CURRENTJULY2016-07-26-2016-x64-USB.img in my disk, so if you need further detail information  about the above symptom, I am very happy to provide that.
Thanks for all your efforts.

**Comment by q5sys** [comment]
nah, we can keep it closed.  it wont disappear off the site... anyone can leave further information if its relevant.  If it becomes an issue in the future, we can reopen it then.

**Comment by NaomasaMaruyama** [comment]
Sorry for misunderstanding.
