### ISSUE TITLE
ipfw state tracking doesn't work with UDP

### ISSUE THREAD

**Issue by asomers** [trueos/trueos-core#219]
I had an NFSv3 UDP mount before I upgraded TrueOS to OpenRC.  After, I couldn't boot.  The problem turned out to be that IPFW's state tracking wasn't working with UDP, so I couldn't reach the remote lockd.  Switching the mount to either NFSv3 with TCP or NFSv4 worked.  But it would be better if the default IPFW configuration supported UDP state tracking.

**Comment by kmoore134** [comment]
This should be fixed here:

https://github.com/trueos/freebsd/commit/49fc7cccbe8390f3cf872e705b120dce2eb43834

We were using some broken ipfw script from elsewhere, corrected it with one that correctly runs "/etc/ipfw.rules" that does indeed enable keep-state.
