### ISSUE TITLE
%s for pool name

### ISSUE THREAD

**Issue by jmdavis** [trueos/trueos-core#22]
I'm running PC-BSD 10.3, and I tried to upgrade to TrueOS-Desktop-12.0-CURRENT-08-02-2016-x64-DVD.iso. I have three zpools currently hooked up to my machine - zroot, zdata, and zbackup. zroot has my root file system, and that's what I selected to upgrade. However, on the disk selection screen, for the summary, it said `Installing to new dataset in existing zpool: %s`. I don't know if that's indicative of a larger problem or not (I didn't try to actually go beyond this screen, because I couldn't select the bootloader I wanted - which I reported separately), but it looks like at minimum, your format string didn't get filled in properly.

**Comment by kmoore134** [comment]
That was a cosmetic issue, which I've corrected in trueos/trueos-utils-qt5 about a week ago.

Thanks!
