### ISSUE TITLE
/etc/init.d/localmount tries to mount remote file systems

### ISSUE THREAD

**Issue by asomers** [trueos/trueos-core#220]
The /etc/init.d/localmount script has a syntax error that causes it to attempt to mount remote filesystems, causing the boot to fail.  The script appends a "no" to each remote filesystem type, but it should only be append the "no" to the beginning of the list.  I think that this is true for both FreeBSD and Linux.  The patch is below.

```
--- /tmp/localmount     2016-12-16 22:31:04.722398000 -0700
+++ /etc/init.d/localmount      2016-12-16 22:31:25.123275000 -0700
@@ -24,7 +24,7 @@
        # Mount local filesystems in /etc/fstab.
        local critical= types="noproc" x= no_netdev= rc=
        for x in $net_fs_list $extra_net_fs_list; do
-               types="${types},no${x}"
+               types="${types},${x}"
        done
 
        if [ "$RC_UNAME" = Linux ]; then
```

**Comment by kmoore134** [comment]
Very good eye! Yea, I don't know what that did on Linux, but it was broken on FreeBSD for sure. Thanks for the heads up!
