### ISSUE TITLE
IP aliases don't work with with OpenRC

### ISSUE THREAD

**Issue by asomers** [trueos/trueos-core#222]
Before OpenRC, I had three static IP addresses specified in /etc/rc.conf as follows.  After OpenRC, the first address gets configured correctly but the two aliases do not.  If this syntax is no longer supported, `rc.conf(5)` should be updated with its replacement.

```
ifconfig_re0="inet 192.168.0.16/24"
ifconfig_re0_alias0="inet 192.168.0.18/32"
ifconfig_re0_alias1="inet 192.168.0.20/32"
```

**Comment by pkgdemon** [comment]
It looks like this was done with network.subr, and we need to replace this functionality in order for it to work again.

https://github.com/freebsd/freebsd/blob/master/etc/network.subr
