### ISSUE TITLE
sanity of dhcpcd.wlan0 persisting in a crashed state after an explicit stop of wpa_supplicant.wlan0

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#223]
## Environment

- HP EliteBook 8540p with an OS-independent switch to enable or disable wireless
- Intel Centrino Advanced-N 6200
- with `dhcpcd.wlan0` occasionally found in a crashed state soon after login to Lumina.

## Background

Experimenting with (amongst other things): 

1. stop of crashed `dhcpcd.wlan0`
2. stop of `wpa_supplicant.wlan0`
3. stop of `network.wlan0`
4. start of `network.wlan0`
5. await gracefully-timed automated starts of `wpa_supplicant.wlan0` and then `dhcpcd.wlan0`

– that sequence of events, not too rushed, in lieu of any restart. 

## Observation/issue

In a parellel experiment I see that if 
` dhcpcd.wlan0` is crashed before an explicit 
stop of `wpa_supplicant.wlan0`, then 
` dhcpcd.wlan0` persists in that state long after the stop of the supplicant. 

Is there logic to that persistence? 

Would it be saner, at least _tidier_, for an explicit stop of `wpa_supplicant.wlan0` to trigger an automated stop of ` dhcpcd.wlan0`?

----

From results of the background experiments, I have a sense that recovery in crash situations will be more consistently achievable if a more managed approach is taken to _stops_.

**Comment by kmoore134** [comment]
This is fixed now, wpa stop will also stop dhcpcd.wlan0
