### ISSUE TITLE
When the OS is without Internet connectivity, a check for updates must not result in a false positive that the system is up-to-date

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#229]
Falseness may explain observations such as those around https://discourse.trueos.org/t/-/403/4, in particular: 

> it reported it was up to date. …

Here: 

![screenshot-2016-12-18-08-39-26](https://cloud.githubusercontent.com/assets/192271/21292887/6cd65068-c50b-11e6-8449-2dda34f5cfb0.png)

![screenshot-2016-12-18-08-42-30](https://cloud.githubusercontent.com/assets/192271/21292888/774fc7d6-c50b-11e6-86e3-6a13f9e9d3f7.png)

[terminal output.txt](https://github.com/trueos/trueos-core/files/659349/terminal.output.txt)

**Comment by q5sys** [comment]
This is actually a `sysadm` issue not a trueos-core issue.  The Back end needs to be able to verify internet connectivity to the repo first and then be able to pass that along to the `sysadm-qt-ui` to notify the user that the repo connectivity is needed before checking for updates.

Do not go and make duplicate threads in those repos... I'll assign this to Ken.

**Comment by grahamperrin** [comment]
> Do not go and make duplicate threads in those repos..

Where did that assumption come from?
