### ISSUE TITLE
Sleep (suspend) supported but not offered by the operating system

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#23]
Ergo Vista 621 notebook, circa 2007. 

There's a hot key combination (Function+F1) that's effective for sleep, and the notebook does wake without difficulty, but TrueOS Desktop does not offer the option to sleep.

**Comment by kmoore134** [comment]
You mean a GUI option? Moving this over to lumina

**Comment by kmoore134** [comment]
This issue was moved to trueos/lumina#246
