### ISSUE TITLE
pkg(8): OS no longer bootable, OpenRC commands no longer usable, following removals with e.g. AppCafe

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#230]
## Symptom 

> Shared object "libeinfo.so.1" not found, …

## tl;dr 

From @kmoore134 at https://gitter.im/trueos/troubleshooting?at=5856ec4e058ca967376218e5: 

> Need to find some pkg work around to prevent removal of base system packages. 

At an HP EliteBook 8540p I can create, activate and then boot from an environment where I certainly can reproduce this issue. If I then **identify a removal that will trigger this issue**, will that help?

**Comment by baitisj** [comment]
AppCafe should probably save the user from blowing their system up by determining if certain actions will make their system unstable. The solution in the backend is probably to:

```
pkg -f $PACKAGE_NAME
```

This will remove *individual* packages, leaving dependencies dangling.

The next step done by the back-end should be to resolve the dangling dependencies.
