### ISSUE TITLE
pc-netmanager superfluous modal dialogue about restarting the OS when a restart is not required

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#231]
Wherever it's _extremely rare_ to change the host name or domain, it's annoying to have _every_ GUI-applied restart of the network interrupted by a modal dialogue that is superfluous, irrelevant, misleading:  

![you must restart](https://cloud.githubusercontent.com/assets/192271/21296338/787551f2-c561-11e6-9f04-6efc5f1116ae.png)

**Comment by pkgdemon** [comment]
It was actually required to apply the hostname when it was added.  I do recall.  It's no longer required so the dialog could be removed.

**Comment by pkgdemon** [comment]
Fixed in https://github.com/trueos/pc-networkmanager/commit/f6f390cdbe9787cb9cffb94fe5603c66a3b2f31a
