### ISSUE TITLE
Wrong keyboard layout after first run of the TrueOS Desktop with a UK preference

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#24]
Ergo Vista 621 notebook with a UK layout for its keyboard. 

Prefer English (UK) when installing the OS, and on first run of the OS. 

**Expected**

A UK keyboard layout. 

**Actual result**

I can't tell the layout (what's required is probably missing from SysAdm) but keying Shift-2 produces @

**Comment by pkgdemon** [comment]
Ken,
can you please look into a fix for this since you claimed this functionality should work without ibus?

**Comment by grahamperrin** [comment]
I might have omitted a key point: there's a less prominent button (not as prominent as the menu) for setting something UK related, but I would expect the change to be made automatically when I make a selection in the menu.

**Comment by grahamperrin** [comment]
**Additional details**

In the 'TrueOS' dialogue I select what's required, then click Apply, then click 'Close'. 

Without proceeding further, if I again click the key/flag icon then the TrueOS dialogue shows –

> English 'US' - (us)

– that's not what I selected. 

----

More broadly

It may be **essential** to have no mistakes or misunderstandings around this stage of (first run) setup. 

If the end user is not aware that something other than their preferred layout is in use, then there's a risk of their preferred pass phrase, presented on screen as bullets, being misinterpreted by the setup routine. If that happens then eventually (when the preferred layout is _truly_ in use by the OS) the user might find the OS rejecting the entered phrase.
