### ISSUE TITLE
Display manager GUI invisible

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#246]
### HP EliteBook 850 G2

Tuesday 2016-12-20 around 09:25. After allowing **Display Settings** (if I recall correctly, pc-xgui launched automatically following updates to the OS) to apply an apparently good configuration (IIRC one of the Intel options at 1,920 x 1,080): 

- PCDM presented only the desktop background, no GUI. 

The OS responded properly to Escape, both external displays (DisplayPort, HP dock) presented the shut down confirmation dialogue: 

![img_20161220_092828](https://cloud.githubusercontent.com/assets/192271/21441131/73478486-c88e-11e6-9286-4d839ff51c5a.jpg)

Side note: **blackness**, not greyness, at the integral display. 

I keyed Control-Alt-F2, logged in as root, set aside the most recent offending file and automated backup: 

[xorg.conf.txt](https://github.com/trueos/trueos-core/files/669917/xorg.conf.txt)
[xorg.conf.bak.txt](https://github.com/trueos/trueos-core/files/669918/xorg.conf.bak.txt)

### Prepared workaround

At `/etc/X11/xorg.conf-2016-12-09` I keep a copy of a superior .conf file – 

```
# XFree86 configuration file for RoFreeSBIE

Section "ServerLayout"
	Identifier     "XFree86 Configured"
	Screen      0  "Screen0" 0 0
EndSection

Section "Files"
	ModulePath   "/usr/local/lib/modules"
	ModulePath   "/usr/local/lib/xorg/modules"
	FontPath     "/usr/local/share/fonts/cyrillic/"
	FontPath     "/usr/local/share/fonts/TrueType/"
	FontPath     "/usr/local/share/fonts/illinoy/"
	FontPath     "/usr/local/share/fonts/webfonts/"
	FontPath     "/usr/local/share/fonts/misc/"
	FontPath     "/usr/local/share/fonts/TTF/"
	FontPath     "/usr/local/share/fonts/Speedo/"
	FontPath     "/usr/local/share/fonts/Type1/"
	FontPath     "/usr/local/share/fonts/CID/"
	FontPath     "/usr/local/share/fonts/75dpi/"
        FontPath     "/usr/local/share/fonts/100dpi/"
	FontPath     "/usr/local/share/fonts/dejavu/"
	FontPath     "/usr/local/share/fonts/cyrillic/"
	FontPath     "/usr/local/share/fonts/hebrew/"
	FontPath     "/usr/local/share/fonts/vietnamese/"
	FontPath     "/usr/local/share/fonts/indic/"
	FontPath     "/usr/local/share/fonts/ae_fonts1/AAHS"
	FontPath     "/usr/local/share/fonts/ae_fonts1/AGA"
	FontPath     "/usr/local/share/fonts/ae_fonts1/FS"
	FontPath     "/usr/local/share/fonts/ae_fonts1/Kasr"
	FontPath     "/usr/local/share/fonts/ae_fonts1/MCS"
	FontPath     "/usr/local/share/fonts/ae_fonts1/Shmookh"
	FontPath     "/usr/local/share/fonts/local/"
EndSection

Section "Module"
        Load  "extmod"
        Load  "record"
        Load  "dbe"
        Load  "glx"
        Load  "dri"
        Load  "dri2"
EndSection

Section "Screen"
	Identifier "Screen0"
	Device     "Card0"
	Monitor    "Monitor0"
EndSection

Section "Device"
        Identifier  "Card0"
        Driver      "modesetting"
        Option      "AccelMethod"               "none"
        Option      "SWcursor"                  "true"
EndSection
```

– that probably originated in August 2016 –

```
$ uname -a
FreeBSD momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #9 0d57090(drm-next-4.7): Thu Dec 22 01:53:46 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
$ beadm list | grep initial
initial                         -      -            9.1G 2016-08-22 11:24        initial
$ 
```

– and with the name given by me (`xorg.conf-2016-12-09`, not a `.bak`) I know that the kernel mode-setting goodness will not be overwritten by the OS. 

With #189 I can not use Display Settings to recreate the KMS goodness, so I copied `xorg.conf-2016-12-09` to xorg.conf` and then restarted the OS. Result: 

![img_20161220_093806](https://cloud.githubusercontent.com/assets/192271/21441722/7d69c8f4-c891-11e6-9e12-05dc3a86404e.jpg)

– both external displays driven
– greyness at the integral display (a separate issue, presumably upstream in Linux). 

### Lenovo x121e, Sandy Bridge Core i3

From [Some problems/bugs after upgrade from pcbsd to / using TrueOS-Desktop-2016-12-15-x64-USB.img](https://discourse.trueos.org/t/some-problems-bugs-after-upgrade-from-pcbsd-to-using-trueos-desktop-2016-12-15-x64-usb-img/429?u=grahamperrin): 

> … PCDM: With external display there is no login GUI - neither on the main display (laptop/netbook) nor on the external one. 

– that's consistent with **Display manager GUI invisible** (the subject of this issue), and –

> Login GUI only displayed if external display is disconnected and pcdm is reloaded. – 

– I _assume_ that in the absence of the login GUI, the reload was performed from a root console e.g. Control-Alt-F2. (Or in this Lenovo x121e case, was the power menu visible? I'll seek clarification.)

**Comment by grahamperrin** [comment]
I can't provide `Xorg.0.log` for the incident above (sorry; the need to use the machine for work overtook the wish to gather information for troubleshooting). Maybe when I'm next at work, in January.

**Comment by pkgdemon** [comment]
This has been a longstanding issue with ```pc-xgui```.  We should adjust it to do no more than swap conf files present in ```/usr/local/share/trueos/cardDetect/```.
