### ISSUE TITLE
upgrade fails (attempted twice, same result)

### ISSUE THREAD

**Issue by RodMyers** [trueos/trueos-core#248]
lenovo X1carbon, 2nd GEN

attempted to do an upgrade UNSTABLE, all files download fine.

When issuing the "shutdown -r now" command, goes through the motions.

I get the Ctrl-Alt-F2 message, quickly followed by

init:  /etc/rc.shutdown returned status 1

at this point no updates installed, no new BE, but an immediate reboot

**Comment by RodMyers** [comment]
ran a 3rd time 3.5 hours later. same result

ran "sudo pc-updatemanager pkgupdate -f" fixed problem

**Comment by kmoore134** [comment]
That was something I had to fix upstream with pc-updatemanager, should be good to go now.
