### ISSUE TITLE
Diversity: presence of pc-sysinstall at  /usr/sbin/ and at /usr/local/sbin/

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#249]
```
$ date ; uname -v
Sun 25 Dec 2016 07:27:59 GMT
FreeBSD 12.0-CURRENT #11 8b9df91(drm-next-4.7): Sat Dec 24 15:17:28 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
$ which pc-sysinstall
/usr/sbin/pc-sysinstall
$ wc /usr/sbin/pc-sysinstall
     240     871    6760 /usr/sbin/pc-sysinstall
$ wc /usr/local/sbin/pc-sysinstall
     229     838    6559 /usr/local/sbin/pc-sysinstall
$ 
```

Is one of the two redundant? 

Credit: Francisco Reyes at https://discourse.trueos.org/t/the-two-pc-sysinstalls/422

**Comment by francisco1844** [comment]
@grahamperrin I was more concerned on why they were producing different output. If it was the same program.. easy.. one is redudant, but the fact they are either different programs, or different versions of a program, is a little more troublesome.

**Comment by pkgdemon** [comment]
FreeBSD includes pc-sysinstall by default.  We do not use the version shipped in base.   We use our version in the /usr/local prefix for our installer backend.
