### ISSUE TITLE
sudo pc-wificonfig: use of the OS prevented by arrays of 'Wireless Configuration' and 'WPA Personal Config' dialogues after using the contextual menu of the system tray icon for wlan0 to select a network

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#253]
High priority, please. 

## Forewarning

Be prepared, as root, in a separate console (e.g. `ttyv1`) to work around this issue with 
`killall -m sudo`
– if not worked around quickly, the desktop environment may become unusable with an unexpected log out and/or need to restart the OS. 

Be prepared for the possibility of a consequent separate issue, without workaround but hopefully transient, that may prevent subsequent log out from the desktop environment (e.g. KDE). 

## Steps

1. point at the system tray icon

2. present the contextual menu (e.g. right-click)

3. click the name of any network

4. observe the authentication dialogue

## Expected

5. an opportunity to enter credentials

## Actual result

5. rapidly appearing arrays of dialogues with no obvious way to cease additions to the arrays.

From a screen recording that began before reproducing the bug: 

![2016-12-27 13-49-48](https://cloud.githubusercontent.com/assets/192271/21513264/5a276952-ccae-11e6-84c4-37389e0d2860.png)

## Background

https://gitter.im/trueos/Lobby?at=585da2da058ca9673785429c from @scobiehague:

> … wifi tool, …  attempting to double click the AP spawns what seems like infinite loop of password prompts, which I have to pkill. Anyone experienced similar problems? …

https://gitter.im/trueos/Lobby?at=585dd03e96a565f84406a64c from me and @scobiehague: 

> yes, but I can't recall whether the array of password dialogues was in response to the same actions, and I did not find it necessary to kill anything. 

> the loop does not seem to happen all the time. I'm not exactly sure what triggers it

https://gitter.im/trueos/Lobby?at=586247150730ce6937144976 from @ldemouy: 

> I just triggered the network manager infinite dialog spawn bug by opening the context menu of the networkmanager tray icon and clicking on a network
> 
> and it's reproducible for me

**Comment by ldemouy** [comment]
I was asked to confirm that I was using Lumina, which I was.

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/pc-networkmanager/commit/45e9af8f14a741a15520cb925b83d083da8cdfb1
