### ISSUE TITLE
SysAdm must not encourage a reboot for system update purposes

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#255]
![2016-12-24 21-23-27 sysadm-client use of cpu whilst prompting the user to reboot](https://cloud.githubusercontent.com/assets/192271/21547246/b8cdabea-cddc-11e6-81ab-da5a744ca1dd.png)

> Reboot required to finish updates

No; [reboot](https://www.freebsd.org/cgi/man.cgi?query=reboot&sektion=8&manpath=FreeBSD)(8) will certainly **prevent** progression to stage two of the upate routine.

**Comment by kmoore134** [comment]
I'm not sure we need to change this. Its not instructing you to run the command "reboot", rather just to "reboot" in the generic sense. Any normal re-boot call from the GUI will do the right thing.
