### ISSUE TITLE
Not all files are installed on text install

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/trueos-core#26]
Not all files are installed on text install. With Graphic installer all OK, but with text installer not all files are installed and after reboot -> problem with Graphic mode after text install. TrueOS Image from 2016-08-08. NUC DN2820FYKH. CPU Intel N2830.

**Comment by DmitryPostolov** [comment]
I am try again with TrueOS Image from 2016-08-14 and this problem with text installer is not solved. After text installation some applications are absent, for example: qterminal and browser. And problem with Graphic mode after text install not solved. There no problems with absent applicatinos and Graphic mode after Graphic Installation. Intel NUC DN2820FYKH. CPU N2820 HD Graphics.
![aftertextinstall](https://cloud.githubusercontent.com/assets/20837310/17702881/8aeaf610-63f1-11e6-8c35-14d15d9cdc3f.jpg)

**Comment by kmoore134** [comment]
This issue was moved to trueos/trueos-utils#1
