### ISSUE TITLE
PCDM-session does not need either to loop or to fork, those being already done for it

### ISSUE THREAD

**Issue by jdebp** [trueos/trueos-core#261]
Consider `/usr/local/sbin/PCDMd`:
```/bin/sh
while [ ! -e /var/run/nologin -a ! -e ${STOPFILE} ]; do
  ...
  xinit /usr/local/bin/PCDM-session -once -- :0 -auth ${PCDMAUTHFILE} $XOPTS vt9
  ...
done
```

It already has a loop, and it invokes `PCDM-session` with the `-once` flag.  Run `xinit` with `PCDM-session` under a proper service manager &mdash; such as daemontools, runit, s6, and so forth &mdash; and one even gets the auto-restart loop as part of the service management.  But even with `PCDMd` run from an old `rc` system, a loop is in the invoking script.  It is completely unnecessary inside `PCDM-session` itself, whichever way one approaches it.

Indeed, `PCDM-session` actually acts as if the `-once` flag is always set _anyway_.  The whole forking mechanism is entirely superfluous, and `main()` can thus be greatly simplified:
```c++
int main(int argc, char *argv[])
{
  setenv("MM_CHARSET", "UTF-8", 1); //ensure UTF-8 text formatting
  
  qDebug() << " -- PCDM Session Starting...";
  int sid = setsid(); //become a session leader
  qDebug() << "-- Session ID:" << sid;
  int retCode = runSingleSession(argc,argv);
  qDebug() << "-- PCDM Session Ended --";
  return retCode;
}
```

**Comment by pkgdemon** [comment]
Some of these hacks were necessary to background properly with OpenRC.  Issues were getty would steal vt2 breaking keyboard input, and if pcdmd did not backgrounded properly other services could not start, or it might not start up at all.  If you have tested this change, and can confirm it doesn't break anything please submit a PR for this change to be reviewed.

https://github.com/trueos/pcdm/tree/master/src-qt5

**Comment by jdebp** [comment]
This word for word identical comment is just as wrong here as it was with with #260, and again you are referencing things done to a completely different program.  You are talking about things that happened to `PCDMd`.  This issue is about what `PCDM-session` does, which isn't anything to do with virtual terminals or OpenRC at all.  Please look at the right program.

**Comment by pkgdemon** [comment]
Updated the message to simply request a PR.
