### ISSUE TITLE
The boot_mute boolean is not entirely effective

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#262]
## 1: confusing wording

`# Enable the TrueOS splash-screen`

For that, I would expect a YES in the following line to enable the splash screen. If I understand correctly, the opposite is true – or _might_ be true, if the boolean was effective (see the second part of this report). In context: 

```
$ tail /boot/loader.conf.trueos
hw.psm.synaptics_support="1"

# Enable Elantech touchpad support
hw.psm.elantech_support="1"

# Speed up boot time
autoboot_delay="01"

# Enable the TrueOS splash-screen
boot_mute="NO"
$ 
```

## 2: improper muting of verbosity when `boot_mute="NO"`

I read, more than once, that this was fixed. However there are multiple, more recent reports of boot verbosity remaining muted when `boot_mute="NO"`. 

For example: [HOWTO deactivate boot splash logo](https://discourse.trueos.org/t/howto-deactivate-boot-splash-logo/506?u=grahamperrin) where what Rick reports is consistent with what I found: 

- it is necessary to `# ` comment out the offending line.

**Comment by pkgdemon** [comment]
This also means that when ```boot_mute`` is set in general ``boot_verbose="YES"``` does not work either to override the splash.  Only when it is selected in the menu which is a problem.

**Comment by grahamperrin** [comment]
Above all, still, in my mind, there's the confusing wording. 

What precisely _is_ `boot_mute`? What is it muting? 

A few weeks before use of OpenRC became visible, there was (if I understand correctly): 

- normal boot
- verbose boot (option 2 in the FreeBSD boot loader)

– one type more verbose than the other, and the greater level of verbosity was visible in an increased number of messages (lines) on screen before the display manager appeared. 

## Now

`# Enable the TrueOS splash-screen` implies that **if** `YES` **then**: 

- **neither a normal boot level of messaging, nor a verbose boot level of messaging will be visible**
- _whatever_ the level, those messages are **muted by the enabled splash screen**.

**Comment by pkgdemon** [comment]
It mutes kernel boot even if vervose is set.  It also is the only way to enable the splash screen.  Verbose displays more kernel messages.

**Comment by grahamperrin** [comment]
Maybe the dyslexic side of me, I'm confused:

> … After kernel boot it contiues to show more kernel messages …

Why does muting – for _less_ of something – cause _more_?

**Comment by pkgdemon** [comment]
It doesnt.  Muting hides the kernel boot, and displays the splash screen instead.

**Comment by grahamperrin** [comment]
I've been thinking about this for a few days: 

- instead of `boot_mute` (a negative, which can be confusing when used with a `NO`)
- `show_splash` or `trueos_splash` or something like that.

**Comment by grahamperrin** [comment]
## Wording

> - instead of `boot_mute`
> - `show_splash` or `trueos_splash` or something like that.

– that might be the last suggestion that folks want to be bumped at this time, but here it is: **bump** :-) 

One way, one way alone, to describe the splash screen should suffice. Attempting to simultaneously describe it as a (negative) muter of something other than a splash, something vague, still is, and probably will continue to be, confusing. 

> `# Enable the TrueOS splash-screen`

– that's fine although (personal preference) I would not hyphenate the two words.

## trueos-desktop-201701042114 and trueos-desktop-201701060022

### Bug

`boot_mute="NO"` in 
`/boot/loader.conf` causes appearance of the splash screen. 

#### Workaround 

Comment out the line.

**Comment by pkgdemon** [comment]
Changed here
https://github.com/trueos/freebsd/commit/f97b51ab43d3b46330effd5450b33983432207e8

Boot_mute is no longer hardcoded in normal startup.

**Comment by grahamperrin** [comment]
Thanks, and apologies, I lost sight of a key point above: 

> … `boot_mute` parameter wording to enable the splash screen. That was a FreeBSD specific choice …

**Comment by pkgdemon** [comment]
See this for boot_mute parameter wording:

https://reviews.freebsd.org/rS257722

It shows todo tunable for splash screen.

**Comment by grahamperrin** [comment]
A love heart for that comment because I had lazily bookmarked https://reviews.freebsd.org/ in 2015 without realising the value of FreeBSD's Phabricator. 

https://reviews.freebsd.org/rS150469 shows `boot_mute` added in 2005. No amount of confusion on my part is likely to convince upstream that a better phrase might be used after more than a decade of use :-)
