### ISSUE TITLE
Installing or updating the OS should not overwrite the user-preferred boolean for boot_mute

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#263]
Around https://gitter.im/trueos/Lobby?at=58658f0edb9cafe9183ad5f6: 

>> … started in single user mode and :thumbsdown: there again is the bloody logo. Maybe not intentional but (sorry, iXsystems folks) it is a barrier that we could do without whilst there's so much activity around OpenRC. Yeah the cosmetics are nice if a technology has settled but where we're paying attention to startup and shutdown stuff, it's counterintuitive to block our visions of that stuff. 

>> – for me that's especially true for the first boot after any update.

> overwrote my boot_mute="NO" with boot_mute="YES" thus re-enabling the splash screen (logo) on boot. :worried:

**Comment by pkgdemon** [comment]
Only ```loader.conf.trueos``` is overwritten.  However setting ```boot_mute``` to yes or no has no effect.  I will remote that flag entirely from our default file now as it doesn't do anything.  It's hardcoded into normal startup, and can only be turned off by verbose booting.

**Comment by cryptorick** [comment]
I should add that, if user-level overrides should instead be going into `/boot/loader.conf`, I can report that **any** setting of `boot_mute` in `/boot/loader.conf` has **no** effect on removing the logo on boot.

More specifically: while the default `boot_mute="YES"` was still set in `/boot/loader.conf.trueos`, I tried the following in `/boot/loader.conf` to no avail.

- `boot_mute="NO"`
- `boot_mute=""`

It appears that if `boot_mute` is set to **any** value (even the empty string `""`), it is equivalent to `YES`.

**Comment by pkgdemon** [comment]
Due to ```boot -m -q``` being hardcoded it's impossible to change it via ```boot_mute``` at all.

**Comment by cryptorick** [comment]
@pkgdemon at the risk of incurring an "RTFM" response, what do the `-m` and `-q` flags do? thanks,

**Comment by grahamperrin** [comment]
> can only be turned off by verbose booting.

Please: how recently was/is that true? 

I ask because of the positive (verbose) effect of commenting out the `boot_mute` line. Subsequent boots are verbose, splash-free **without** me pausing at the FreeBSD loader to request verbosity. 

(If I'm still confused: sorry!)

**Comment by pkgdemon** [comment]
The -m is the mute flag.  Which oddly enough is what FreeBSD chose to enable the splash screen.  Confusing I know which is why we were not aware of it for 3 years.  The -q flag is to suppress additional messages on console during next stages after kernel boot.  I removed boot_mute for now since it has no effect.  I added a warning not to use this file, and to use ```/boot/loader.conf``` as well.

https://github.com/trueos/trueos-core/commit/5d1c10293315dab2d5770f6337d5f13f391d5943

**Comment by cryptorick** [comment]
> However setting boot_mute to yes or no has no effect. I will remote that flag entirely from our default file now as it doesn't do anything.

Wha?  Right now, we can comment out the `boot_mute` setting in `/boot/loader.conf.trueos` and we can see the console messages.  Are you saying that that will not be the case anymore?  I hope not.

**Comment by grahamperrin** [comment]
If it helps, Joe, from an edition of https://discourse.trueos.org/t/howto-deactivate-boot-splash-logo/506/2?u=grahamperrin: 

> ## Where TrueOS GRUB is used
> 
> … With this one installation, I **never** see a TrueOS splash screen after the TrueOS boot loader. I guess that it's simply not implemented, yet.

**Comment by pkgdemon** [comment]
Well I removed boot_mute entirely from /etc/loader.conf.trueos.  Indeed that does fix the problem.  Since I have removed it from loader.conf.trueos, and that file will be overwritten it will no longer be on by default.

**Comment by cryptorick** [comment]
@pkgdemon does this mean that "no logo" is now the default and if user wants logo, he has to set `boot_mute="YES"` in `/boot/loader.conf`?  That what it sounds like to me.

**Comment by grahamperrin** [comment]
To clarify (summarise?): a suitable user-specificied system preference  
at `/boot/loader.conf` 
not at `/boot/loader.conf.trueos`  
will allow boot to be verbose without pausing at the FreeBSD loader

– true?

**Comment by pkgdemon** [comment]
To enable verbose by default ```boot_verbose="YES"``` in ```/boot/loader.conf````.
To summarize only ```/boot/loader.conf``` should be used for customization.
When my changes make the next package build that will be shown in ```/boot/loader.conf.trueos```.
Splash screen is off entirely now until we fix it right allowing the user to disable with ```boot_mute="NO"```.

**Comment by grahamperrin** [comment]
> Splash screen is off entirely now 

Thanks, and will that equate to verbose mode? As verbose as is optional in the FreeBSD loader?

**Comment by pkgdemon** [comment]
I forgot @grahamperrin you had already created a ticket which kind of describes the other problem already.  

https://github.com/trueos/trueos-core/issues/262

I will add my findings to that.

**Comment by grahamperrin** [comment]
A recent update removed my preferences from `/boot/loader.conf`.
