### ISSUE TITLE
 Installing or updating the OS should not overwrite the user-preferred integer for autoboot_delay

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#264]
Around https://gitter.im/trueos/Lobby?at=58658f0edb9cafe9183ad5f6: 

>> …  if I'm not mistaken the update has overwritten the user-preferred `autoboot_delay` integer at `/boot/loader.conf.trueos`

> I believe you are not mistaken.

**Comment by pkgdemon** [comment]
You can add ```autoboot_delay="08"``` to ```/boot/loader.conf``` to override TrueOS defaults.  That would be the preferred file to make user customizations.  It is expected for /boot/loader.conf.trueos to get overwritten by upgrades, and it is currently necessary.  Not having that would not give the user a way to override our customizations that we set by default.

**Comment by grahamperrin** [comment]
Ah OK, thanks, some of that vaguely rings a bell. Rung from Gitter, maybe. 

I'll take a look at forthcoming guidance on OpenRC in TrueOS, but probably not until after it has been published.

**Comment by RodMyers** [comment]
@pkgdemon was wondering this myself
