### ISSUE TITLE
pc-sysconfig(8) obscurity of help

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#267]
I sought help after reading about `pc-sysconfig` exiting _on signal 11_ at [Pcdm auto login and pc-mounttray](https://discourse.trueos.org/t/pcdm-auto-login-and-pc-mounttray/420?u=grahamperrin).

From https://github.com/trueos/pc-mounttray/commit/72e0c06d0c5511db5081a5129d675086e6c7d388 and other commits I assume that `pc-sysconfig` will be integral to TrueOS Desktop for the foreseeable future; and from https://github.com/trueos/pc-mounttray/blob/master/src-qt5/pc-sysconfig/pc-sysconfig.8 I assume that there should be on-screen help with usage, but I can't guess how to present that help: 

```
$ man pc-sysconfig
No manual entry for pc-sysconfig
$ pc-sysconfig
No manual entry for pc-sysconfig
$ which pc-sysconfig
/usr/local/bin/pc-sysconfig
$ /usr/local/bin/pc-sysconfig
No manual entry for pc-sysconfig
$ /usr/local/bin/pc-sysconfig list-remdev
cdrom
$ /usr/local/bin/pc-sysconfig supportedfilesystems
FAT, NTFS, EXT, CD9660, UFS, REISERFS, XFS, UDF, ZFS, MTPFS
$ pkg info | grep hfs
hfsutils-3.2.6_3               Utilities for accessing Apple's HFS volumes
$ /usr/local/bin/pc-sysconfig --help
No manual entry for pc-sysconfig
$ /usr/local/bin/pc-sysconfig -h
No manual entry for pc-sysconfig
$ date ; uname -v ; uname -n
Mon  2 Jan 2017 15:48:25 GMT
FreeBSD 12.0-CURRENT #12 5ef9376(drm-next-4.7): Thu Dec 29 16:26:36 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk
$ 
```

**Comment by pkgdemon** [comment]
Not seeing the value in this one.  It is meant as a backend for mounttray.  I also do not see us keeping it around forever.
