### ISSUE TITLE
Request port inclusion - gpodder

### ISSUE THREAD

**Issue by VulcanRidr** [trueos/trueos-core#273]
I noticed that gPodder failed to load due to a new python module, python-podcastparser. 

What I get in TrueOS is

  Error: Module "podcastparser" (python-podcastparser) not found.
         The podcastparser module can be downloaded from
         http://gpodder.org/podcastparser/

  From a source checkout, you can download local copies of all
  CLI dependencies for debugging (will be placed into "src/"):

      python tools/localdepends.py

I emailed the FreeBSD port maintainer, Ruslan Makhmatkhanov, and he updated it to version 3.9.3. I was wondering if it would be possible to pull that in and upgrade our 3.9.2 and include the podcastparser module?

Thanks,
--b

**Comment by pkgdemon** [comment]
I just checked, and gpodder 3.9.3 is building now.
