### ISSUE TITLE
devfs isn't enabled in default runlevels

### ISSUE THREAD

**Issue by asomers** [trueos/trueos-core#275]
Since upgrading to the OpenRC-enabled TrueOS, devfs rulesets are no longer getting loaded at boot.  On vanilla FreeBSD, the devfs service is enabled by default.  TrueOS should enable it by default, too.  This is especially important for desktop users, who have lots of USB devices.

**Comment by pkgdemon** [comment]
Thanks.  We fixed this earlier this week in unstable push which just went out tonight.  It should get promoted to stable with a few days.

**Comment by asomers** [comment]
Thanks Joe.  BTW, which git repo is this stuff in?  I didn't see anything that looked related in the history of trueos-core.

**Comment by pkgdemon** [comment]
I made the change in trueos-desktop pkg-install file.
