### ISSUE TITLE
openntpd rc script is passing /etc/ntp.conf to ntpd

### ISSUE THREAD

**Issue by mremski** [trueos/trueos-core#277]
After the latest stable update, openntpd will not start.  It "crashes" according to rc-status.
I tweaked the script to dump out $args when started,  here's what I get:
Starting Network Time Protocol Daemon args  -f /etc/ntp.conf -p /var/run/ntpd.pid -d -S 

everything is good except for -f, it should be looking at /usr/local/etc/ntpd.conf.  /etc/ntp.conf is base FreeBSD NTP config and is not compatible with openntpd.  The only spot ntpd_config is set to /etc/ntp.conf is in /etc/defaults/rc.conf.

Creating /usr/local/etc/conf.d/openntpd with the contents of:
ntpd_config=/usr/local/etc/ntpd.conf

makes it work

**Comment by kmoore134** [comment]
Fixed here:
https://github.com/trueos/freebsd-ports/commit/99efc7f92b894c3d6c8f30b85e45bf331d19aefb
