### ISSUE TITLE
Unexpected changes of names of media

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#279]
Spun off from [Unexpected changes of names of media – at least, ZFS pools and ext2](https://discourse.trueos.org/t/unexpected-changes-of-names-of-media-at-least-zfs-pools-and-ext2/551?u=grahamperrin) in particular, from [post 3](https://discourse.trueos.org/t/unexpected-changes-of-names-of-media-at-least-zfs-pools-and-ext2/551/3?u=grahamperrin):

>> …  the "folder" that is created in /media/ isn't deleted after unmounting via mount tray. …

Thinking aloud (without testing) … I wonder whether the debris occurs only if an unmount is forced in a busy (open file(s)) situation.

https://gitter.im/trueos/Lobby?at=5872d29061fac5a03db1fee8 from Joe: 

> The new way I have been testing will fix those tickets, and do proper cleanup.

**Comment by grahamperrin** [comment]
For subscribers to this issue, a hint (from the linked topic): 

`sudo zpool import -R /media ZEVO-2 ZEVO`

Re: https://gitter.im/trueos/troubleshooting?at=5873464cdec171b811c48913 I don't know how to deal with ext2 cases.

**Comment by pkgdemon** [comment]
Mounttray is being depreciated this week.  I have sent in the pull requests for the new devd based automounter to replace it.
