### ISSUE TITLE
safe mode results in an unresponsive OS

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#28]
There's the torn GUI, which I know is work in progress, but there's also no response to keyboard input and no response to the power button. 

**Environment** 

HP EliteBook 8540p

**Workaround**

Force; press and hold the power button.

**Comment by pkgdemon** [comment]
This explains a little of what safe mode is. Its just a way for FreeBSD to boot with acpi off.  Some systems do not support this.  https://www.freebsd.org/doc/handbook/bsdinstall-start.html
