### ISSUE TITLE
vlc: add ncurses support request

### ISSUE THREAD

**Issue by jungle-boogie** [trueos/trueos-core#280]
Hi All,

This is regarding the port multimedia/vlc, but I didn't see an option to open an issue up on that project page.

I was wondering if ncurses support could be added to vlc for a console mode.
https://wiki.videolan.org/Console

I don't know how well (or not so well) ncurses works under freebsd, so maybe there's a legitimate reason it's not enabled in the port.

There is a way to audio play streams through the cli without opening vlc, but the ncurses mode is a slightly cleaner way.

Thanks for the consideration!

**Comment by pkgdemon** [comment]
@jungle-boogie If you want you can just add any port options here, and send a PR.  We can give it a try with the build system after we merge your PR.  If it doesn't break anything no reason not to have it on.

**Comment by pkgdemon** [comment]
@jungle-boogie Here is the file to add, or update port options.  I forgot to link it the first time.

https://github.com/trueos/trueos-core/blob/master/build-files/conf/desktop/port-make.conf

**Comment by jungle-boogie** [comment]
Hi @pkgdemon,

Thanks! I didn't know it would be that easy. ;) Let's see if this breaks anything. 

https://github.com/trueos/trueos-core/pull/281

**Comment by pkgdemon** [comment]
@jungle-boogie We try to make it easy.  Feel free to send PR anytime you need a change there.
