### ISSUE TITLE
Post-installation, first run (setup) offers to 'Change the installation language'

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#29]
Post-installation, after the installer medium is ejected, the first GUI offers a menu of languages. 

Without clicking, point at the menu. In the status bar, there's a hint: 

> Change the installation language

I would expect that form of wording before or _during_ installation, not afterwards. 

This issue is probably a companion to https://github.com/trueos/trueos-core/issues/24 and a better wording for a hint about the menu (as it currently appears) might be: 

> Change the setup language

**Comment by pkgdemon** [comment]
Fixed in https://github.com/trueos/trueos-utils-qt5/blob/master/src-qt5/pc-installgui/installer.ui
