### ISSUE TITLE
Updates to TrueOS every day for four days (apparently repeated, looping, since Wednesday 2017-01-11 or earlier)

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#291]
Reported at https://discourse.trueos.org/t/update-behavior-question/600?u=grahamperrin and we have probably the same problem observed by @johalun at https://gitter.im/trueos/troubleshooting?at=58797d91873d96e16d66b9c9

From posts [5](https://discourse.trueos.org/t/updates-to-trueos-every-day-for-four-days-apparently-repeated-looping-since-wednesday-2017-01-11-or-earlier/600/5?u=grahamperrin) and 6 in the linked topic: 

```
beadm list
BE Active Mountpoint Space Created
initial - - 19.8G 2016-12-30 22:31
12.0-CURRENT-201701072218 - - 3.1G 2017-01-07 16:18
12.0-CURRENT-up-20170111_032532 - - 8.5G 2017-01-11 03:19
12.0-CURRENT-up-20170112_023906 - - 8.4G 2017-01-12 02:32
12.0-CURRENT-up-20170112_224547 - - 8.4G 2017-01-12 22:39
12.0-CURRENT-up-20170112_225809 - - 8.4G 2017-01-12 22:51
12.0-CURRENT-up-20170113_003835 NR / 58.2G 2017-01-13 00:32
```

## beadm(1)

@kmoore134 

> … **beadm-1.2.6_1** 2017-01-06 in STABLE.
> 
> Sources: the closest I can find is older https://github.com/trueos/trueos-core/blob/master/overlays/install-overlay/root/beadm.install, is the code for last week's change not at https://github.com/trueos ?

**Comment by sergwish** [comment]
Examples package conflicts with runtime package:
`FreeBSD-examples-12.0.s20170106195032 [trueos-base] conflicts with FreeBSD-runtime-12.0.s20170106195032 [installed] on /usr/share/examples/etc/make.conf`

This leads to repeated re-install of FreeBSD-runtime package.
Previous version of FreeBSD-examples (12.0.s20161224153902) did not have make.conf in it.
Please, rebuild FreeBSD-examples.

**Comment by pkgdemon** [comment]
I was seeing this as well.  I was only seeing it upgrading from unstable to unstable, and I have not been able to reproduce it elsewhere.   Reverting back to initial, and perforning the upgrade fixed my issue.

**Comment by wost0k** [comment]
thx - this work for me.

**Comment by grahamperrin** [comment]
Today in PC-BSD forums: [SYSADM CLIENT WANTS TO UPDATE THE SAME THING OVER AND OVER](https://forums.pcbsd.org/thread-21135.html) … plus last week I might have seen another new topic in TrueOS Community.

**Comment by pkgdemon** [comment]
Is the looping still occurring for anyone now that the CDN has had time to settle?

**Comment by pkgdemon** [comment]
Found the workaround today over here:

#303 (comment)

The short answer is ```pkg remove freebsd-examples``` & ```pkg-static install -f freebsd-runtime.```

**Comment by jungle-boogie** [comment]
As mentioned in #308, I recommend rebooting via terminal, `sudo reboot`. I don't know if this is actually needed or hearsay at this point, but worked for me.

**Comment by pkgdemon** [comment]
@jungle-boogie Thanks for mentioning the ```reboot``` command.  I updated my response to reflect that as well.  Good idea!

**Comment by grahamperrin** [comment]
Thanks folks. There's now [a wiki post](https://discourse.trueos.org/t/having-trouble-updating/687/2?u=grahamperrin) in an announcement, **Having Trouble Updating?**
