### ISSUE TITLE
/var/log/dmesg.yesterday does not contain stuff from yesterday

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#293]
Output from `sudo less /var/log/dmesg.yesterday` appears to be much older than yesterday. Also: 

```
$ date ; ls -hl /var/log/dmesg.yesterday 
Sat 14 Jan 2017 07:03:53 GMT
-rw-------  1 root  wheel    92K  9 Jan 01:10 /var/log/dmesg.yesterday
$ 
```

If there's rotation and if it's not daily, then a better name for the file might be `dmesg.previous` (not `dmesg.last`; the word _last_ is ambiguous).

**Comment by jungle-boogie** [comment]
12th was the yesterday for me:
`-rw-------  1 root  wheel      82816 Jan 12 00:08 dmesg.yesterday`

**Comment by grahamperrin** [comment]
… better, name the file with the date of its content. So for the example above, a better name will be: 

`dmesg.2017-01-09`

(Best from my point of view would be names that begin with explicit dates so, for example, `2017-01-09-dmesg`. But I don't expect others to share that preference.)

**Comment by jungle-boogie** [comment]
Just curious, what's the uptime of your machine?

**Comment by grahamperrin** [comment]
` 9:46a.m.  up 11:39, 6 users, load averages: 0.75, 0.79, 0.70`

**Comment by grahamperrin** [comment]
Sorry. Whilst I had no installation FreeBSD-CURRENT, I compared with FreeBSD-based GhostBSD but failed to seek information in FreeBSD domains. https://lists.freebsd.org/pipermail/freebsd-questions/2003-November/026680.html and other finds suggest that: 

- this is not an issue with TrueOS.
