### ISSUE TITLE
Client shouldn't be able to power off host server

### ISSUE THREAD

**Issue by Passaita** [trueos/trueos-core#295]
Connected clients should be limited in terms of powering off hosting server.
At the moment by powering off on the client side entire server goes down.

**Comment by grahamperrin** [comment]
Can you describe the environment? Thanks.

**Comment by Passaita** [comment]
Server part: TrueOS-Desktop-2016-12-27-x64-DVD.iso
Running on ESXi 6.0 (probably a separate 2 bugs but out from the box evethough ssh is enabled it is not starting and when started manually is blocked by firewall, second problem was that picoserver_enable="yes" was "ignored" by the system too, so when attempted to start manually discovered service picoserver doesn't exist so used pico-server -daemon command to start the server)
Client part: TrueOS-pico-rpi2-2016-11-07.img
Maybe because I had to go thrue so many workarounds I didn have pleasant experience but this is how it was in my case.

**Comment by RodMyers** [comment]
@Passaita   Is this still an issue?

**Comment by Passaita** [comment]
I am unable to reproduce this issue with an updated OS version. Can't, actually log in at all but this is separate bug.
