### ISSUE TITLE
trueos stable

### ISSUE THREAD

**Issue by mayerrs** [trueos/trueos-core#296]
not issue but.. i would like to ask if somebody know when the next stable trueos is comming out?

thank you

**Comment by jungle-boogie** [comment]
The latest I have is from 6th of January, but they didn't generate ISO/IMGs for it:
http://download.trueos.org/master/amd64/

**Comment by RodMyers** [comment]
the devs were waiting on DRM-49(?) to land in CURRENT, and working on the rc chanegover, plus other bug fixes

**Comment by mayerrs** [comment]
yes, i was wondering about new iso. i have had problem with nvidia in DEC27 and 6th of january makes me trouble. so i am looking for new iso.

**Comment by kmoore134** [comment]
Next week sometime is the plan. ⁣
