### ISSUE TITLE
OpenRC support for musicpd

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#297]
From https://discourse.trueos.org/t/building-a-port-throws-clang-errors/625?u=grahamperrin: 

> … service 'musicpd' does not exist …

**Comment by pkgdemon** [comment]
Looks like the port is failing to build due to some linker error:

https://builds.ixsystems.com/guantlet/data/master-trueosports/2017-01-16_21h03m25s/logs/errors/musicpd-0.19.15_8.log

**Comment by pkgdemon** [comment]
Fixed here https://github.com/trueos/freebsd-ports/commit/bacfe18425c215ac853377a6793f79d2b0c1a520
