### ISSUE TITLE
idle machine suddenly unresponsive?

### ISSUE THREAD

**Issue by jungle-boogie** [trueos/trueos-core#299]
Hi All,

I don't have a lot to go by at the moment, but I wanted to get this reported to see how I can track down the issue.

Running 6 January, 2017 image of trueOS stable, and after some period of inactivity on the machine (6-8 hours), the machine will become unresponsive and I cannot ssh into it, but the connection doesn't timeout--just won't prompt for user/pass. I can still ping the machine so I know it's responding in some way.
The machine also goes unresponsive to mouse movement and key presses on the laptop, so my only option is to reboot the machine and log back in.

The only application I leave open is Tilda, I close firefox and any other application that may have been running. I don't think Tilda is causing this unresponsiveness, though.

My machine is something like this, except from 2015: https://www.asus.com/us/Notebooks/F555LA/
i3 process with only 4GB of RAM, but I haven't had a problem with it in the past. I haven't seen any zfs warnings about the disk, so I don't think it's a hardware issue as this point.

So should I revert to a previous BE, wait for the next trueOS stable release, provide some kind of diagnostics, etc?

Thanks!

**Comment by pkgdemon** [comment]
We were seeing this on a machine at the office as well.  I believe it has been fixed.  It was sysadm, or some other process using up memory.  Maybe pasting the output after 5 hours of ```top```?

**Comment by jungle-boogie** [comment]
Yeah, five hours does seem to be the issue. At this point I have it shut off because it was crashing quite a bit yesterday when I was using it. I'll apply the next stable build to it when it's ready and see if it's better.

Good to know I'm not the only affected user.

**Comment by pkgdemon** [comment]
This fix should be in the latest UNSTABLE packages.  We have a newer set pushing now.  We plan to promote later this week I believe if all goes well.

**Comment by grahamperrin** [comment]
I, too, found exhaustion of swap space but [not enough information](https://gist.github.com/grahamperrin/66b84c903333ca28ee9c38a23979c753) for analysis. 

For future possible incidents (different issues) it should be good to have the option of something run periodically to measure uses of memory. I'll seek a script, maybe something that can be run safely with `cron`(8).

**Comment by jungle-boogie** [comment]
I have about a day and a half of uptime without the crashing I experienced above. This is from a new install to release on the 18th of January. Tonight to tomorrow, I'll leave the laptop lid open to have screensaver active to see if anything changes.

**Comment by pkgdemon** [comment]
Sounds like this is fixed?  If not let me know, and I will re-open.  I am no longer seeing the issues here.
