### ISSUE TITLE
boot environment doesn't apply Lumina completely

### ISSUE THREAD

**Issue by jungle-boogie** [trueos/trueos-core#301]
Hello,

I noticed when attempting to test various boot environments for issue https://github.com/trueos/trueos-core/issues/299, I was able to login, but the whole lumina DE didn't load. Specially, I didn't have the bottom toolbar nor the icons on the 'desktop'. I was able to right-click the desktop and navigate to applications that way, though. 
I had about 4 or 5 BE and they all acted the say way. 

Is this expected, already reported, feature, known issue, etc?

Thanks!

**Comment by pkgdemon** [comment]
I have enountered this as well after changing display drivers, or reverting back to an old BE.  The fix seems to be blowing away something in ```.config/lumina-desktop```.  I have been blowing away the entire directory to get around it.

**Comment by jungle-boogie** [comment]
hi @pkgdemon,

Good trick! Thanks for the quick follow up and keep up the great job!

Best,
j.b.

**Comment by grahamperrin** [comment]
> … after changing display drivers …

Keyword **blind**; for example [post 8](https://discourse.trueos.org/t/drm-display-rendering-graphics-with-and-without-vendor-specific-drivers/230/8?u=grahamperrin) and others (to follow) under _DRM: display rendering (graphics) with and without vendor-specific drivers_ and in that **Lumina** case I worked around https://github.com/trueos/trueos-core/issues/189 to regain use of KMS, which almost certainly allowed reappearance of panels. 

Lumina was, maybe still is, bugged by a more troublesome blindness issue; see today's **Lumina** postscript at https://discourse.trueos.org/t/hp-elitebook-850-g2/343/5?u=grahamperrin
