### ISSUE TITLE
Boot may stall (pause, hang) at WLAN time (wireless, Wi-Fi) without a wired network connection

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#304]
[2017-01-11](https://gitter.im/trueos/troubleshooting?at=587592da300f220a66d181b7) from @Mystified1234: 

> … If I reboot with out the lan connected, the boot process hangs … 
> 
> I'm now convinced this must be a bug in the update. I am using an old usb wifi dongle. …

[Later](https://gitter.im/trueos/troubleshooting?at=5875ae54dec171b811d2a00b): 

> Again boot stopped when looking for wireless lan, after I reinserted the land cable boot continued. I immediately removed the lan cable. Boot process completed & wireless was working without requiring any configuration. 

[2017-01-13](https://gitter.im/trueos/troubleshooting?at=587961f76c1635643c2750ba): 

> … Still, without lan cable connected, boot hangs.

[2017-01-14](https://gitter.im/trueos/troubleshooting?at=5879b1016c1635643c2890cd): 

> Still issues with reboot. Freezes without lan connection. Below is the text , immediately prior to the boot hanging. At the end of the text If I "Insert the lan cable". The boot process completes as per normal. So in a nutshell, if there is no active lan, the computer will not boot. 

> ```
> ipfw2 (+ipv6)initialized,divert loadble,notladable,default to accept,logging disabled. 
> *Staring ipfw 
> *Firewiwall rules loaded 
> *Executing /libexec/rc/sh/openrc-run.sh /libexec/rc/sh/openrc-run.sh
> /etc/init.d/ipfw start /etc/rc.subr:Source_rc_confs #:not found
> Wlan0:Etherenet address: …
> Created wlan(4) Interfaces : Wlan0. 
> /etc/rc.subr:Source_rc_confs# Not found 
> Starting wpa. Supplicant.
> ```

Mystified1234, please share your 
`/etc/rc.conf` 
and information about the network hardware, this might be enough to cover it: 
`pciconf -lv | grep -B 3 -A 2 -i network`

----

[Regressions and problems in/with TrueOS-Desktop-2017-01-17-x64-USB.img]()

to-user wrote: 

> … installation stick wouldn't boot through unless I disabled wlan in BIOS. …

From the photographs I can tell that there's use of [alc](https://www.freebsd.org/cgi/man.cgi?query=alc&sektion=4&manpath=FreeBSD)(4) (Atheros AR813x/AR815x/AR816x/AR817x	Gigabit/Fast Ethernet driver) but I can not tell the wireless hardware or driver.

**Comment by grahamperrin** [comment]
https://discourse.trueos.org/t/regressions-and-problems-in-with-trueos-desktop-2017-01-17-x64-usb-img/651/8?u=grahamperrin: 

> LAN: Atheros AR8151 PCI-E Gigabit Ethernet Controller
> WLAN: Intel(R) Centrino(R) Wireless-N 1000

**Comment by Mystified1234** [comment]
FreeBSD x58-Tos 12.0-CURRENT FreeBSD 12.0-CURRENT #14 f92c24b(drm-next-4.7): Fri Jan  6 19:28:21 UTC 2017     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
FreeBSD 12.0-CURRENT #14 f92c24b(drm-next-4.7): Fri Jan  6 19:28:21 UTC 2017     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 

cat /etc/rc.conf
rc_verbose="YES"
rc_interactive="YES"
rc_depend_strict="NO"
rc_crashed_start="YES"
#kldload_nvidia="nvidia-modeset nvidia"
kldload_nvidia="nvidia-modeset nvidia"
# Auto-Enabled NICs from pc-sysinstall
wlans_urtw0="wlan0"
# Auto-Enabled NICs from pc-sysinstall
hostname="x58-Tos"
zfs_enable="YES"
if_rtwn_load="YES"
sshd_enable="YES"
kldload_vbox="vboxdrv"
vboxnet_enable="YES"
smartd_enable="YES"
rc_parallel="NO"
rc_logger="YES"
rc_log_path="/var/log/rc.log"
linux_enable="YES"
hald_enable="YES"
ifconfig_wlan0="WPA DHCP country au"
ifconfig_re0="WPA DHCP"
ifconfig_re0_ipv6="inet6 accept_rtadv"
ntpdate_enable="YES"

pciconf -lv | grep -B 3 -A 2 -i network

re0@pci0:1:0:0: class=0x020000 card=0x81681849 chip=0x816810ec rev=0x03 hdr=0x00
    vendor     = 'Realtek Semiconductor Co., Ltd.'
    device     = 'RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller'
    class      = network
    subclass   = ethernet
hostb1@pci0:255:0:0:    class=0x060000 card=0x2c411849 chip=0x2c418086 rev=0x05 hdr=0x00

drill
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 50660
;; flags: qr rd ra ; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 15 
;; QUESTION SECTION:
;; .    IN      NS

;; ANSWER SECTION:
.       38011   IN      NS      a.root-servers.net.
.       38011   IN      NS      b.root-servers.net.
.       38011   IN      NS      c.root-servers.net.
.       38011   IN      NS      d.root-servers.net.
.       38011   IN      NS      e.root-servers.net.
.       38011   IN      NS      f.root-servers.net.
.       38011   IN      NS      g.root-servers.net.
.       38011   IN      NS      h.root-servers.net.
.       38011   IN      NS      i.root-servers.net.
.       38011   IN      NS      j.root-servers.net.
.       38011   IN      NS      k.root-servers.net.
.       38011   IN      NS      l.root-servers.net.
.       38011   IN      NS      m.root-servers.net.

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:
a.root-servers.net.     3479615 IN      A       198.41.0.4
b.root-servers.net.     3453546 IN      A       192.228.79.201
c.root-servers.net.     3463937 IN      A       192.33.4.12
d.root-servers.net.     3522171 IN      A       199.7.91.13
e.root-servers.net.     3452236 IN      A       192.203.230.10
f.root-servers.net.     3597552 IN      A       192.5.5.241
g.root-servers.net.     3450736 IN      A       192.112.36.4
h.root-servers.net.     3446945 IN      A       198.97.190.53
i.root-servers.net.     3599655 IN      A       192.36.148.17
j.root-servers.net.     3451101 IN      A       192.58.128.30
k.root-servers.net.     3597779 IN      A       193.0.14.129
l.root-servers.net.     3597779 IN      A       199.7.83.42
m.root-servers.net.     3586219 IN      A       202.12.27.33
a.root-servers.net.     3586170 IN      AAAA    2001:503:ba3e::2:30
b.root-servers.net.     3453784 IN      AAAA    2001:500:84::b

;; Query time: 19 msec
;; SERVER: 192.168.0.1
;; WHEN: Fri Jan 20 17:34:09 2017
;; MSG SIZE  rcvd: 492

**Comment by Mystified1234** [comment]
Thanks Graham for looking at this, If you like I can go back to an earlier BE and provide other aspects that me different in Tueos.
Mystified.

**Comment by pkgdemon** [comment]
@Mystified1234 Do you have any network mounts being listed in /etc/fstab?

**Comment by pkgdemon** [comment]
@Mystified1234 Also you are missing something important for wireless to work.

```ifconfig_rtwn0="wlan0"```

**Comment by pkgdemon** [comment]
@Mystified1234 I would change this:

```ifconfig_wlan0="WPA DHCP country au"```

To this as well:

ifconfig_wlan0="WPA DHCP"

To make sure it is not the special options throwing something off.

**Comment by pkgdemon** [comment]
I am adding ```if_rtwn``` to our default modules list so this won't be needed in ```rc.conf``` for a future release.

**Comment by pkgdemon** [comment]
https://github.com/trueos/trueos-core/commit/491b7e6879af15a26e8eff659595e0915af2d70c

**Comment by Mystified1234** [comment]
x58-Tos % cat /etc/fstab
# Device                Mountpoint              FStype          Options Dump Pass
/dev/label/swap0.eli    none            swap    sw      0       0
procfs                  /proc                   procfs          rw              0       0
linprocfs               /compat/linux/proc      linprocfs       rw              0       0

**Comment by Mystified1234** [comment]
Thx @pkgdemon 
Your input is really appreciated !
The changes you have suggested, have been added to  /etc/rc.conf

I'll keep you in the loop , as to how the changes  affect the OS.

**Comment by grahamperrin** [comment]
Another topic: 

- [TrueOS-Desktop-2017-01-27-x64-USB.img (again) not booting properly on Sandy Bridge machine](https://discourse.trueos.org/t/trueos-desktop-2017-01-27-x64-usb-img-again-not-booting-properly-on-sandy-bridge-machine/736?u=grahamperrin)

**Comment by pkgdemon** [comment]
I think I recall we resolved this.  Perhaps removing network from the boot runlevel, or something else that was tried.  If not let me know, and we can troubleshoot further.
