### ISSUE TITLE
OpenRC script for VMware `open-vm-tools`

### ISSUE THREAD

**Issue by clauseggers** [trueos/trueos-core#305]
Currently the VMware `open-vm-tools` are not loading. The usual `rc.conf` config options for `open-vm-tools` are not functional, so an OpenRC init-script for `open-vm-tools` is needed.

**Comment by pkgdemon** [comment]
Added
https://github.com/trueos/freebsd-ports/commit/e5888086ae5659d98f4f114a90b6a0fbc335869e
