### ISSUE TITLE
Thinkpad T430 Graphics(Intel HD Graphics 4000) not detected properly after GUI install

### ISSUE THREAD

**Issue by rosedovell** [trueos/trueos-core#306]
This issue is relevant for the USB installation media found here, I haven't tested any other install methods: http://download.trueos.org/master/amd64/TrueOS-Server-2017-01-17-x64-USB.img

When installing via the text install, I get a window before the first time configuration after rebooting that detects the intel GPU and asks if I would like to use the intel driver and it sets it properly in /etc/X11/xorg.conf.  

However, after installing via the GUI install, that window does not appear and I get some default 'modesetting' driver(I don't know anything about it, I just know it's nowhere near as nice as the intel driver for my card) in my /etc/X11/xorg.conf.

**Comment by pkgdemon** [comment]
So you are manually selecting the intel driver for install, and that brings up the graphical installer?  Are you saying that just post install its using the wrong xorg?

Post install other xorg templates can be copied from /usr/local/share/trueos/CardDetect/.  If that is the case I believe copying over the file that ends in .intel may workaround until we can resolve.

**Comment by rosedovell** [comment]
Thanks for the fast response, I meant that post install it doesn't appear to autodetect any graphics settings.

When I use the text install this window pops up after rebooting that says something to the effect of "We detected your resolution is 1366x768 and your graphics driver is Intel, are those settings OK?" and that doesn't happen after the GUI install.  

Whenever I'm choosing the GUI install, I just pick that top default auto graphics settings, I know there was also a 'legacy Intel' mode i could have picked but I wasn't sure if that applied to my card.

I'll use your workaround for now, thanks!

**Comment by pkgdemon** [comment]
Hmm.  If you are doing autodetect that should be using modesetting for the install, and post install as well.  I would check ```/etc/rc.conf``` to make sure ```kldload_i915kms="i915kms"``` is present as well.

**Comment by pkgdemon** [comment]
Intel graphics should be fully fixed in the latest builds with acceleration as well.  Let us know if not, and we can re-open.
