### ISSUE TITLE
clicks on 'Mixer' are not reliable

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#307]
The sixteen-second screen recording at https://files.gitter.im/trueos/Lobby/IRQD/loudspeaker-menu-problem-with-clicks.ogv shows the audio menu in a panel at the top of a screen of Lumina. 

Three of three clicks on _Mixer_ do nothing more than cause the menu to disappear. 

>  [because the word _Mixer_ never responded to clicks, I used PC-BSD – then TrueOS Desktop – for more than a year with an assumption that _Mixer_ was simply a name for the menu.](https://gitter.im/trueos/Lobby?at=5883a4a461e516c15791c23d) …

**Comment by grahamperrin** [comment]
## Reproducibility

:-) I half-expected the behaviour to be not immediately reproducible by someone but truly, it bugged me for more than a year (probably **more than two years**; I began using using PC-BSD around July 2014) – consistently – so that I simply never discovered the separate Mixer application. 

Maybe the bug bites only if the sub-menu has both:

1. appeared **and** 
2. been passed over

– as shown in the screen recording. 

### Side note

It should help to have a recorder that captures clicks. Maybe OBS, although there's trouble at [post 13](https://discourse.trueos.org/t/trueos-as-viable-video-editing-platform/79/13?u=grahamperrin) under _TrueOS as viable video-editing platform_

**Comment by pkgdemon** [comment]
It's quite possible there is a problem that can't be conveyed in the video as described.  I'm hesitant to keep it open knowing it's something we cannot do anything about it until have sufficient information required to reproduce.
