### ISSUE TITLE
Constant nagging updates

### ISSUE THREAD

**Issue by jungle-boogie** [trueos/trueos-core#308]
Hi All,

So I was on 6 January stable release and sysadm wasn't telling me I had any available updates, even though a new stable release was pushed. I wiped the install and downloaded the IMG and put it on my machine.
Now sysadm thinks I have updates every time I turn the computer on and re-applying the updates over and over does not fix anything. I switched to unstable in hopes something was fixed, but I have the same issues with constant nagging from sysadm stating there's new updates.

Are there any known issues with constant updates? Which logs would help determine a problem? I'm all for the latest packages, but I can't imagine that many new apps/changes are being pushed that quickly.

**Comment by jungle-boogie** [comment]
I've seen this update a few times.
```
Boot-strapping updater...OK
Updating trueos-base repository catalogue...
trueos-base repository is up-to-date.
Updating trueos-major repository catalogue...
trueos-major repository is up-to-date.
All repositories are up-to-date.
Updating trueos-base repository catalogue...
trueos-base repository is up-to-date.
Updating trueos-major repository catalogue...
trueos-major repository is up-to-date.
All repositories are up-to-date.
Updating database digests format: .......... done
Checking for upgrades (423 candidates): .......... done
Processing candidates (423 candidates): . done
The following 1 package(s) will be affected (of 0 checked):

Installed packages to be UPGRADED:
        FreeBSD-examples: 12.0.s20170117032329 -> 12.0.s20170118145349 [trueos-base]

Number of packages to be upgraded: 1

179 KiB to be downloaded.
The following updates are available:
------------------------------------
NAME: System package updates
TYPE: PKGUPDATE

To install: "pc-updatemanager pkgupdate"
```

**Comment by jungle-boogie** [comment]
This log shows 17 checks without any updates needed:
https://www.pastiebin.com/58845d1f78974

**Comment by jungle-boogie** [comment]
When restarting the system, as requested by sysadm, I see this:

```
graphics/phototonic phototonic-1.7.20_1.txz
mail/thunderbird thunderbird-45.6.0_1.txz
misc/trueos-meta-hunspell trueos-meta-hunspell-20160701,1.txz
multimedia/openh264 openh264-1.5.0,2.txz
multimedia/vlc vlc-2.2.4_6,4.txz
print/cups-pdf cups-pdf-2.6.1_4.txz
print/gutenprint-cups gutenprint-cups-5.2.10_3.txz
sysutils/fusefs-ntfs fusefs-ntfs-2016.2.22_1.txz
www/firefox firefox-50.1.0_5,1.txz
x11-fonts/droid-fonts-ttf droid-fonts-ttf-20131024_3.txz
x11-fonts/noto-lite noto-lite-1.0.4.txz
x11-themes/cursor-jimmac-theme cursor-jimmac-theme-0.1_2.txz
x11/qterminal qterminal-0.7.0.txz
x11/xterm xterm-327.txz
```

**Comment by pkgdemon** [comment]
Found the workaround today over here:

https://github.com/trueos/trueos-core/issues/303#issuecomment-274285138

The short answer is ```pkg remove freebsd-examples``` & ```pkg-static install -f freebsd-runtime```.

**Comment by grahamperrin** [comment]
! that may be a workaround for a _different_ issue; please see https://github.com/trueos/trueos-core/issues/303#issuecomment-274359574

@pkgdemon maybe (sorry) move some stuff from 303 to https://github.com/trueos/trueos-core/issues/291

**Comment by jungle-boogie** [comment]
I'll do what @pkgdemon recommended and see what happens upon a reboot. I don't really have anything to lose at this point.

**Comment by pkgdemon** [comment]
Whatever you do, do not install freebsd-examples.  Bad, bad idea.

**Comment by jungle-boogie** [comment]
heh. I have not gone out of my way to install it. Is it installed by default with trueOS?

**Comment by RodMyers** [comment]
does not appear to be, no

**Comment by jungle-boogie** [comment]
How's it installed? I can't find a port/package with that name:
https://www.freshports.org/search.php?stype=name&method=match&query=examples&num=10&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head

**Comment by RodMyers** [comment]
it's in the base-system

**Comment by pkgdemon** [comment]
It was part of base but was depreciated.  Reinstalling it will remove all FreeBSD packages, and leave you with an empty system.

**Comment by jungle-boogie** [comment]
Okay, I think @pkgdemon's trick fixed it. Initially I ran those commands and rebooted the machine via start menu. Upon shutdown, I was prompted to update. I said yes and things were 'updated'. Once I logged back in, I was advised about pending updates.

Running the commands in the terminal followed by `reboot` seemed to have cleared sysadm's head and isn't prompting for updates ATM.

**Comment by jungle-boogie** [comment]
Closing now. I didn't see any more update requests from yesterday. Assuming any updates from this point forward are legitimate.
