### ISSUE TITLE
GRUB: inital boot @ Desktop 20170117 install: `error 2: unknown filesystem`

### ISSUE THREAD

**Issue by baitisj** [trueos/trueos-core#309]
Selecting the `GRUB` bootloader results in a system that does not boot.

The scrollback buffer shows that there are dependencies missing when loading the `zfs.ko` kernel module:

![zfs ko](https://cloud.githubusercontent.com/assets/12502877/22188669/4ea56638-e0cc-11e6-9af2-b4f40210cad0.png)

The last screen of logs shows:

![grub](https://cloud.githubusercontent.com/assets/12502877/22188461/34c7a8b8-e0ca-11e6-8384-3b08bf55d054.png)

Work-around: Use BSD bootloader
Problem with work-around: GELI full-disk encryption is only supported by `grub`

**Comment by backerman** [comment]
Still present in 20170209.

**Comment by pkgdemon** [comment]
Working with BIOS/EFI + GELI + Grub with 02-22-17 ISO pushing now.

**Comment by pkgdemon** [comment]
Actually I was mistaken.  It's failing in the same place.  Re-opening.

**Comment by ahtotaat** [comment]
Confirming the issue still stands. Bare metal, GRUB, GPT/MBR (failed to boot using either). Installation image from Feb22.

**Comment by pkgdemon** [comment]
Grub removed from upcoming stable, and replaced with refind.
