### ISSUE TITLE
pc-updatemanager check ERROR: Update file failed verification

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#310]
```
$ sudo pc-updatemanager check
Boot-strapping updater...OK
Update file failed verification...
ERROR: Update file failed verification...
$ 
```

Errors of that type have been observed by a number of users over a period of months. Later I might find some points of reference in chat (keywords might include _signature_).  

If I understand correctly, there's no urgency to fix this – the error may be negligible – but we should have somewhere to track the issue.

**Comment by pkgdemon** [comment]
I see this as well when local_unbound is enabled.

**Comment by jungle-boogie** [comment]
So it's disappointing to see this closed without any action taken. On a NEW install of trueOS, I can't check for updates:

```
% sudo pc-updatemanager check
Boot-strapping updater...OK
Update file failed verification...
ERROR: Update file failed verification...
```

```
% about

===================
General information
===================

boot environment now (N) … initial NR 2017-04-11
       after restart (R) … initial NR 2017-04-11
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i3-5020U CPU @ 2.20GHz
    number of cores ……………… 4
host ……………………………………………………… fixme
memory ………………………………………………… 4096 MB available, 2280 MB free
OS git branch ……………………………………………………………………………………… drm-next
OS git revision ………………………………………………………………………………… d44fdf245
OS kernel build time ………………………………………………………… Thu 2017 Mar 30 18:18:02 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… UNSTABLE
TrueOS version …………………………… TrueOS-Desktop-201703311459
uptime ………………………………………………… 8:51
user  …………………………………………………… sean

More (TrueOS Desktop):

    desktop environment …… Lumina
    sound card driver ………… pcm1: <Realtek ALC233 (Internal Analog)> (play/rec) default
    wireless driver ……………… ath0
    X11 drivers ………………………… modesetting_drv.so
```

**Comment by RodMyers** [comment]
Why disappointing? And why can't you check for updates?

the bootstrap message is transitory, and not how TrueOS checks for updates?

**Comment by jungle-boogie** [comment]
> Why disappointing? And why can't you check for updates?

sudo pc-updatemanager check

Is this the tool used to check for updates?

**Comment by RodMyers** [comment]
sudo pc-updatemanager pkgcheck

and it still has the "bootstrap check". mine fails 2 or 3 times a week, but does nothing to stop checking for updates

**Comment by jungle-boogie** [comment]
hi @RodMyers,

So pkgcheck should be used in place of check? pkgcheck will check for system updates and installed package updates, since they're basically one in the same now?

**Comment by RodMyers** [comment]
it's the TrueOS way, so I guess they merged/modified it into the current way

**Comment by jungle-boogie** [comment]
Hi @RodMyers,

Okay, got it. Hopefully one will be removed/deprecated one day to prevent confusion.

Thanks for the replies!
