### ISSUE TITLE
Bootloader media install hang

### ISSUE THREAD

**Issue by croquagei** [trueos/trueos-core#311]
Hi

Both TrueOS and FreeBSD installers fail to boot on my latop (Asus ux21e) in UEFI mode.  They both succeed in booting in BIOS mode.

Here's an image of where the BSD loader gets to before locking up.
http://imgur.com/a/a5zlz

Any thoughts?

**Comment by pkgdemon** [comment]
It would be best to also attempt booting stock FreeBSD media with UEFI, and report the bug upstream if the problem persists.
