### ISSUE TITLE
reproducible panic on heavy network load

### ISSUE THREAD

**Issue by gallatin** [trueos/trueos-core#313]
To reproduce:  run netperf -H linuxhost, while running "netserver" on the linuxhost.

(I'm not certain that it is important if the other host is linux; if it matters, it is running Ubuntu 16.04 4.4.0-57-generic )

Below is a brief exploration of the core with kgdb.  The TL;DR is that sbcut_internal was called with length 2560 on an mbuf chain with 1536 bytes in it, and panic'ed on line 1053 when it ran out of non-null mbufs with data:

 1041  static struct mbuf *
  1042  sbcut_internal(struct sockbuf *sb, int len)
  1043  {
  1044          struct mbuf *m, *next, *mfree;
  1045  
  1046          next = (m = sb->sb_mb) ? m->m_nextpkt : 0;
  1047          mfree = NULL;
  1048  
  1049          while (len > 0) {
  1050                  if (m == NULL) {
  1051                          KASSERT(next, ("%s: no next, len %d", __func__, len));
  1052                          m = next;
  1053                          next = m->m_nextpkt;
  1054                  }

It was called from here:

  2880                  } else {
  2881                          mfree = sbcut_locked(&so->so_snd, acked);
  2882                          if (tp->snd_wnd >= (uint32_t) acked)
  2883                                  tp->snd_wnd -= acked;
  2884                          else
  2885                                  tp->snd_wnd = 0;
  2886                          ourfinisacked = 0;
  2887                  }

Fatal trap 12: page fault while in kernel mode
cpuid = 2; apic id = 02
fault virtual address   = 0x8
fault code              = supervisor read data, page not present
instruction pointer     = 0x20:0xffffffff80b87240
stack pointer           = 0x28:0xfffffe08576dc430
frame pointer           = 0x28:0xfffffe08576dc460
code segment            = base 0x0, limit 0xfffff, type 0x1b
                        = DPL 0, pres 1, long 1, def32 0, gran 1
processor eflags        = interrupt enabled, resume, IOPL = 0
current process         = 12 (irq271: igb0:que 2)
trap number             = 12
panic: page fault
cpuid = 2
KDB: stack backtrace:
db_trace_self_wrapper() at db_trace_self_wrapper+0x2b/frame 0xfffffe08576dc010
vpanic() at vpanic+0x186/frame 0xfffffe08576dc090
panic() at panic+0x43/frame 0xfffffe08576dc0f0
trap_fatal() at trap_fatal+0x322/frame 0xfffffe08576dc140
trap_pfault() at trap_pfault+0x1bc/frame 0xfffffe08576dc1a0
trap() at trap+0x280/frame 0xfffffe08576dc360
calltrap() at calltrap+0x8/frame 0xfffffe08576dc360
--- trap 0xc, rip = 0xffffffff80b87240, rsp = 0xfffffe08576dc430, rbp = 0xfffffe08576dc460 ---
sbcut_internal() at sbcut_internal+0x70/frame 0xfffffe08576dc460
tcp_do_segment() at tcp_do_segment+0x125a/frame 0xfffffe08576dc570
tcp_input() at tcp_input+0xf9a/frame 0xfffffe08576dc6e0
ip_input() at ip_input+0x192/frame 0xfffffe08576dc740
netisr_dispatch_src() at netisr_dispatch_src+0xff/frame 0xfffffe08576dc7a0
ether_demux() at ether_demux+0x149/frame 0xfffffe08576dc7d0
ether_nh_input() at ether_nh_input+0x330/frame 0xfffffe08576dc840
netisr_dispatch_src() at netisr_dispatch_src+0xff/frame 0xfffffe08576dc8a0
ether_input() at ether_input+0x54/frame 0xfffffe08576dc8d0
igb_rxeof() at igb_rxeof+0x7a1/frame 0xfffffe08576dc980
igb_msix_que() at igb_msix_que+0x173/frame 0xfffffe08576dc9e0
intr_event_execute_handlers() at intr_event_execute_handlers+0x20f/frame 0xfffffe08576dca20
ithread_loop() at ithread_loop+0xc6/frame 0xfffffe08576dca70
fork_exit() at fork_exit+0x85/frame 0xfffffe08576dcab0
fork_trampoline() at fork_trampoline+0xe/frame 0xfffffe08576dcab0
<....>
(kgdb) info reg
rax            0x0      0
rbx            0x700    1792
rcx            0x700    1792
rdx            0x0      0
rsi            0xfffff8027246fd00       -8785585832704
rdi            0xfffff8001f983518       -8795562953448
rbp            0xfffffe08576dc460       0xfffffe08576dc460
rsp            0xfffffe08576dc430       0xfffffe08576dc430
r8             0xffffffff80d37210       -2133626352
r9             0x140000 1310720
r10            0x0      0
r11            0x4      4
r12            0xfffff8027246fd00       -8785585832704
r13            0x0      0
r14            0x0      0
r15            0xfffff8027246fd00       -8785585832704
rip            0xffffffff80b87240       0xffffffff80b87240 <sbcut_internal+112>
eflags         0x10246  [ PF ZF IF RF ]
cs             0x20     32
ss             0x28     40
ds             <unavailable>
es             <unavailable>
fs             <unavailable>
gs             <unavailable>
(kgdb) info locals
m = 0x0
mfree = <optimized out>
next = <optimized out>

(kgdb) up
#10 0xffffffff80d250ca in tcp_do_segment (m=<optimized out>, 
    th=<optimized out>, so=0xfffff8001f983360, tp=0xfffff8023a3243f8, 
    drop_hdrlen=80, tlen=<optimized out>, iptos=<optimized out>, 
    ti_locked=<error reading variable: Cannot access memory at address 0x1>)
    at /usr/src/sys/netinet/tcp_input.c:2881
2881    /usr/src/sys/netinet/tcp_input.c: No such file or directory.
(kgdb) info locals
needoutput = <error reading variable needoutput (Cannot access memory at address 0x1)>
thflags = <optimized out>
inc = 0xfffff80200000000
sack_changed = <error reading variable sack_changed (Cannot access memory at address 0x0)>
nsegs = 1
tiwin = <optimized out>
to = <optimized out>
s = <optimized out>
win = <optimized out>
todrop = <optimized out>
acked = 2560
ourfinisacked = <error reading variable ourfinisacked (Cannot access memory at address 0x1)>
mfree = <optimized out>
(kgdb) info reg
rax            0x0      0
rbx            0xfffff8001f983360       -8795562953888
rcx            0x700    1792
rdx            0x0      0
rsi            0xfffff8027246fd00       -8785585832704
rdi            0xfffff8001f983518       -8795562953448
rbp            0xfffffe08576dc570       0xfffffe08576dc570
rsp            0xfffffe08576dc470       0xfffffe08576dc470
r8             0xffffffff80d37210       -2133626352
r9             0x140000 1310720
r10            0x0      0
r11            0x4      4
r12            0xfffff8001f983518       -8795562953448
r13            0xfffff8023a3243f8       -8786526714888
r14            0xa00    2560
r15            0x0      0
rip            0xffffffff80d250ca       0xffffffff80d250ca <tcp_do_segment+4698>
eflags         0x10246  [ PF ZF IF RF ]
cs             0x20     32
ss             0x28     40
ds             <unavailable>
es             <unavailable>
fs             <unavailable>
gs             <unavailable>

**Comment by pkgdemon** [comment]
Are you by chance using igb?  I saw this as well with a couple of supermicro servers until I enabled a tunable in /boot/loader.conf posted here:

**https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210417**

**Comment by gallatin** [comment]
Yes, with MSI-X and 4 queues on a Supermicro X10SRA.   I think I'll leave MSI-X enabled & wait for the iflib integration to hit the TrueOS tree.  That will hopefully fix it.   Thanks for the pointer to the bug.

**Comment by pkgdemon** [comment]
Thanks.  Let us know if we need to do something else to get this resolved.
