### ISSUE TITLE
tree(1) in TrueOS base, please

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#315]
https://www.freebsd.org/cgi/man.cgi?query=tree&sektion=1&manpath=ports

Inclusion of `tree` will allow (for example) neat, partly educational representation of information about OpenRC. Consider: 

- https://discourse.trueos.org/t/-/368/11?u=grahamperrin
- https://discourse.trueos.org/t/-/411/35?u=grahamperrin

**Comment by pkgdemon** [comment]
We could just make tree a requirement for the about utility?

**Comment by pkgdemon** [comment]
RUN_DEPENDS in this Makefile might be the place to add tree:

https://github.com/trueos/trueos-utils/blob/master/port-files/Makefile

**Comment by grahamperrin** [comment]
Wherever you think will be best, thanks.

If it helps to decide: might `tree` (with or without a subset of future `about` features) ever be useful in an installation troubleshooting situation? 

Limited to mobile phone here so I can't read up as easily as usual.

**Comment by pkgdemon** [comment]
I think having ```tree``` in the ```about``` tool would be helpful for sure.

**Comment by pkgdemon** [comment]
I do think having the ```about``` tool would be useful to have on the installation media as well if it is not already part of it.  I need to look.

**Comment by pkgdemon** [comment]
Added tree to run depend here https://github.com/trueos/trueos-utils/commit/7c42c19c0515ab551abd0a7fc34388bf800585e7
