### ISSUE TITLE
After SCFB is chosen, 'about' does not show use of SCFB

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#316]
![2017-02-02 07-59-12 scfb](https://cloud.githubusercontent.com/assets/192271/22542994/639b94a6-e926-11e6-8bad-fe26ad7d292d.png)

Note the terminal output. 

From the combination of those two drivers – `intel_drv.so` with `vesa_drv.so` – can we reliably infer SCFB? 

## Context

Work in progress on https://github.com/grahamperrin/trueos-utils/blob/master/src-sh/trueos-utils/about/about

**Comment by pkgdemon** [comment]
This is valid.  SCFB is not actually a video driver.  It just uses a framebuffer.  Strange that intel, and vesa both show.  But that is more than likely valid.
