### ISSUE TITLE
OpenRC script for plexmediaserver

### ISSUE THREAD

**Issue by samob** [trueos/trueos-core#317]
I have followed instructions on install page, but looks like openrc script is not yet available:

```
# service plexmediaserver start
 * service: service `plexmediaserver' does not exist

```
Thanks in advance

**Comment by grahamperrin** [comment]
If it helps developers, **three plex-related lines** below:

```
$ grep -r USE_RC_SUBR /usr/ports/multimedia
/usr/ports/multimedia/freevo/Makefile:USE_RC_SUBR=      ${PORTNAME}
/usr/ports/multimedia/vdr/Makefile:USE_RC_SUBR= vdr
/usr/ports/multimedia/ffmpeg0/Makefile:USE_RC_SUBR=     ffserver${FFMPEG_SUFFIX}
/usr/ports/multimedia/mythtv/Makefile:USE_RC_SUBR=      mythbackend
/usr/ports/multimedia/mjpg-streamer/Makefile:USE_RC_SUBR=       mjpg_streamer
/usr/ports/multimedia/ptx-kmod/Makefile:USE_RC_SUBR=    ptx
/usr/ports/multimedia/plexmediaserver/Makefile:USE_RC_SUBR?=    ${PORTNAME}
/usr/ports/multimedia/ffmpeg/Makefile:FFSERVER_VARS=            USE_RC_SUBR+=ffserver
/usr/ports/multimedia/emby-server/Makefile:USE_RC_SUBR= ${PORTNAME}
/usr/ports/multimedia/cx88/Makefile:USE_RC_SUBR=                cx88d
/usr/ports/multimedia/plexpy/Makefile:USE_RC_SUBR=      ${PORTNAME}
/usr/ports/multimedia/kissdx/Makefile:USE_RC_SUBR=      kissdx
/usr/ports/multimedia/motion/Makefile:USE_RC_SUBR=      ${PORTNAME}
/usr/ports/multimedia/zoneminder-h264/Makefile:USE_RC_SUBR=     zoneminder
/usr/ports/multimedia/oscam/Makefile:USE_RC_SUBR=       oscam
/usr/ports/multimedia/zoneminder/Makefile:USE_RC_SUBR=  zoneminder
/usr/ports/multimedia/tvheadend/Makefile:USE_RC_SUBR=   ${PORTNAME}
/usr/ports/multimedia/plexmediaserver-plexpass/Makefile:USE_RC_SUBR=    ${PORTNAME}_plexpass
$ 
```

Notes: 

1. I don't know whether all three matches require attention for OpenRC purposes
2. I didn't `grep` beyond the _multimedia_ part of the tree
3. I don't know [whether my copy of the ports tree is properly updated](https://discourse.trueos.org/t/managing-ports-with-git/629/4?u=grahamperrin).

**Comment by pkgdemon** [comment]
Added script here:

https://github.com/trueos/freebsd-ports/commit/499ba9aa7b18d5527bc119486b8ccc104a0f64d8

**Comment by ahilananantha** [comment]
Your openrc script isn't working. The LD_LIBRARY_PATH environment variables set in the plex_precmd() doesn't get exported to plex. I even tried changing out the command from /usr/sbin/daemon to /usr/local/share/plexmediaserver/Plex_Media_Server but it didn't help. For now I worked around it using a wrapper script.

**Comment by samob** [comment]
Can't make it work either. Running 12.0-CURRENT #48 d44fdf245(drm-next): Thu Mar 30 18:18:02 UTC 2017

Followed instructions upon installing port, it said to add those lines to /etc/rc.conf:
`plexmediaserver_enable="YES"
plexmediaserver_support_path="/usr/local/plexdata"
plexmediaserver_tmp="/var/tmp/plex"
plexmediaserver_maxplugins="6"
`
Running from command line # service plexmediaserver start                                                                                                         
 service `plexmediaserver' does not exist

**Comment by pkgdemon** [comment]
This may have gotten lost in the ports tree reorg.  I will take a look.

**Comment by ZackaryWelch** [comment]
The OpenRC service file has been made and a typo fixed so the file should be installed by default. When the port tree is built next the OpenRC script should run by default.
