### ISSUE TITLE
Can no longer mount network volumes from Thunar or PCmanFM

### ISSUE THREAD

**Issue by clauseggers** [trueos/trueos-core#320]
I can no longer mount network volumes from Thunar or PCmanFM. When I click on the Browse Network item in the sidebar of Thunar I am presented with all the servers (due to Avahi being installed), but today I am no longer presented with a login window if I double-click on one of these servers. Only after some 10 mins. or so I get a window reporting that my request timed out. I can mount from CLI as usual. I used to be able to mount from the GUI, so I don’t know if this is a regression or if I have changed some configuration. Disabling the firewall does not fix it, and in any event the relevant ports were open.

**Comment by grahamperrin** [comment]
Cross reference: [I can no longer mount network volumes from Thunar or PCmanFM](https://discourse.trueos.org/t/i-can-no-longer-mount-network-volumes-from-thunar-or-pcmanfm/763?u=grahamperrin)

I suspect a regression. 

I found two file managers – in my case: Dolphin and Files – no longer working with file servers … maybe two or three weeks ago. I did mentioned the problem, maybe in a chat room, but (sorry) the test environment was not suitable for reporting. 

If I can find a record of the chat, I'll add it here.

**Comment by pkgdemon** [comment]
We can only officially support Lumina, and Lumina-fm.  Please reach on discourse for community help for other desktops, amd file managers.

**Comment by grahamperrin** [comment]
Thanks. Second cross reference: [How do I downgrade a package to a previous version?](https://discourse.trueos.org/t/how-do-i-downgrade-a-package-to-a-previous-version/766?u=grahamperrin) in particular: 

> … `tevent-0.9.31` … blocks mounting network shares in GUI-file managers …

– and: 

```text
[3/4] Installing openldap-sasl-client-2.4.44...
pkg-static: openldap-sasl-client-2.4.44 conflicts with openldap-client-2.4.44 (installs files into the same place).  Problematic file: /usr/local/bin/ldapadd
$
```

In the community topic, I'll advise caution.

**Comment by grahamperrin** [comment]
> reach out on discourse 

The topic was closed. I have flagged it for moderation, to be reopened.

**Comment by pkgdemon** [comment]
Oh thanks.  Sorry I was not aware of that.  I have asked the moderator to reopen.
