### ISSUE TITLE
Lenovo X230 - Can't boot from USB after updating BIOS to 2.67

### ISSUE THREAD

**Issue by roomi19** [trueos/trueos-core#321]
I have updated my x230 bios to latest 2.67 version but now i am not able to boot from usb. i want to clean install windows 10. the boot order displays usb at startup but does not boot. while i have tried the same use on my other x230 notebook whose bios is 2.62.

please help

**Comment by pkgdemon** [comment]
What does this have anything to do with TrueOS?
