### ISSUE TITLE
user-friendly access to SMB/CIFS and other types of file server

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#322]
From https://discourse.trueos.org/t/-/249/11 (2016-11-22): 

> … accessing SMB shares in insight … assuming no credentials are required. We have more work to do to improve that experience …

## Enhancement request 

TrueOS Desktop should offer a GUI for authenticated access to file servers. Related: 

- the FreeBSD manual page for [autofs](https://www.freebsd.org/cgi/man.cgi?query=autofs&sektion=5&manpath=FreeBSD)(5)

## Visions

I imagine this GUI being usable with, but not limited to, Insight. From [post 19](https://discourse.trueos.org/t/pc-sysconfig-et-al/515/19?u=grahamperrin) (2017-01-07) under _Pc-sysconfig et al_, with added emphasis: 

> … Allow a handful of things, including The File Manager **and SysAdm**, to reign supreme! Make 'em great. … 

Plenty of kicking the ball around in that topic, but not yet enough for me to have a coherent vision of how this issue 322 might be addressed. I'll continue to kick the ball around in the community. Maybe some time next week.

**Comment by slughorn0850** [comment]
Could it be, if this issue is solved, one can share folders between TrueOS as virtualbox guest and the host system? Because the features "shared folder", drag-drop and USB doesn't work, although guest addition is installed within TrueOS..

**Comment by grahamperrin** [comment]
@slughorn0850 that's probably a separate issue.
