### ISSUE TITLE
sysadm rc-service sysadm stop does not work

### ISSUE THREAD

**Issue by mremski** [trueos/trueos-core#325]
Trying to stop the sysadm service, I get the following error:
[root@trueos-8226] ~# rc-service sysadm stop
 * Executing: /libexec/rc/sh/openrc-run.sh /libexec/rc/sh/openrc-run.sh /usr/local/etc/init.d/sysadm stop
 * Stopping SysAdm Server (WebSocket) ...
 * Failed to stop SysAdm Server (WebSocket)                                                                                 [ !! ]
 * ERROR: sysadm failed to stop
ps aux | grep -i sysadm
root       1320   0.0  0.3   157856 52664  -  Ss   10:16    0:09.33 /usr/local/bin/sysadm-binary

cat /var/run/sysadm.pid
1319

If I manually edit the /var/run/sysadm.pid file, the stop works correctly, starting back up works, I notice this:
 * Detaching to start `/usr/local/bin/sysadm-binary'                                                                        [ ok ]

Is OpenRC using the wrong PID?

**Comment by pkgdemon** [comment]
Thanks for letting us know.

I fixed here:

https://github.com/trueos/freebsd/commit/73a6ea939734c00f56e39da611b1cfb9b383f941
https://github.com/trueos/sysadm/commit/8080a83e1bbe8d9cbb36953222c5d3a58593141e
