### ISSUE TITLE
Provide TrueOS Live ISO

### ISSUE THREAD

**Issue by probonopd** [trueos/trueos-core#326]
Please provide a TrueOS Live ISO that lets one use the system without installing it to hard disk, the same way Ubuntu Live ISOs can be used. Ideally, it could be booted using the [GRUB2 loopback mechanism](https://help.ubuntu.com/community/Grub2/ISOBoot/Examples), which would allow it to be integrated into tools like [SystemImageKit](https://github.com/probonopd/SystemImageKit), and provide a [Loopback.cfg](http://www.supergrubdisk.org/wiki/Loopback.cfg) file.

I am 100% sure that this would tremendously help TrueOS adoption, by significantly lowering the barrier to entry.

**Comment by q5sys** [comment]
Most Linux distribution have Live CD functionality through the use of AUFS 
or Overlay FS. Since neither of those work with the BSD kernel, I doubt 
this will happen anytime soon.  While there is a FreeBSD livecd, it's CLI 
only and the file system is read only.  I don't believe r/w userspace 
persistence is possible with it.

Hopefully Joe or Kris will chime in with their thoughts.

**Comment by probonopd** [comment]
https://en.wikipedia.org/wiki/UnionFS seems to be available for *BSD.

Is FUSE available? Then https://github.com/trapexit/mergerfs or https://github.com/rpodgorny/unionfs-fuse might be additional options.

**Comment by q5sys** [comment]
Yes, unions is available, but it operates differently than AUFS and 
OverlayFS.  Those layered files stems were designed to address limitations 
in the older UnionFS which BSD still has.  I have extensive layeredFS 
experience when I used to be a Linux Distro Developer. I wish BSD had AUFS. 
 AUFS and OverlayFS are the main reasons Linux can do fancier things with 
live systems eaiser. I'm not stating that a TrueOS live cd would be 
impossible to accomplish in some way... but it would be much harder and I'm 
pretty sure that no one in the project has the time to work on it.  But, 
again, I'd wait for Joe or Kris to weigh.

**Comment by pkgdemon** [comment]
I have proposed this before.   The current situation is that unionfs is not reliable on CURRENT, and we don't have the caching options for good performance.

**Comment by probonopd** [comment]
Too bad! Can you pitch the idea to ixSystems so that a good one gets written? ;-)

**Comment by pkgdemon** [comment]
I did.  Not an option at the moment.  If someone in the community is willing to work on it we will take patches.  :)

**Comment by probonopd** [comment]
Did you also consider https://github.com/rpodgorny/unionfs-fuse ("You get caching which speeds things up a lot for free")?

**Comment by pkgdemon** [comment]
Yes.  It is not something the team wants to work on.  Better for the community to take it on.

**Comment by joancatala** [comment]
A live CD/DVD would be great., but a live USB-pendrive installation would be fucking awesome.

**Comment by glixx** [comment]
Please provide a TrueOS Live ISO

**Comment by probonopd** [comment]
Is this something that might be more feasible today compared to three years ago? Every time I hear about TrueOS I'd like to try it out but I for that a Live ISO would be so much more convenient.

**Comment by probonopd** [comment]
Just discovered this:

> Hey TrueOS Community! I just wanted to take a few minutes to address what some of you may have already guessed. With a heavy heart, the TrueOS Project’s core team has decided to discontinue the development of TrueOS for the foreseeable future. We’ll still be heavily involved in other Open Source projects like FreeNAS & TrueNAS CORE. We’re incredibly proud of the work we put into TrueOS and its predecessor, PC-BSD.
>
> TrueOS source code will remain available on GitHub for others that may want to continue the work that we started so many years ago. I can’t explain just how much we appreciate you all being loyal fans of TrueOS and PC-BSD in the past. We’re confident that even though this is a hard decision, it’s also the correct decision because of the exciting new projects that we’re all becoming more involved in like TrueNAS CORE. If you have any questions don’t hesitate to ask.
>
> Many thanks and best wishes,
>
> Joshua & Kris

Very sorry to hear. Thanks for the great amout of work you have to put into this so far.

Hopefully the community will be able to pick it up and continue it.

**Comment by probonopd** [comment]
Just in case someone reads this searching for a FreeBSD desktop-oriented Live ISO:
There is now https://www.furybsd.org/ and it is exactly what I was looking for, including an overlay filesystem.
