### ISSUE TITLE
GRUB boot fail: Update from FreeBSD 12.0-CURRENT #18 4f888bf(drm-next) to 27d3221(drm-next)

### ISSUE THREAD

**Issue by baitisj** [trueos/trueos-core#328]
Updating the system (currently using the GRUB boot method) resulted in an "un-bootable" system with
```text
grub rescue >
```
prompt.

## Workaround & Repair

Point the grub-rescue environment to a working GRUB installation on a previous BE; e.g. using `ls` command to find the boot-device, and

```text
grub rescue > set p=(hd0,msdos3)/ROOT/12.0-current-up-20170124_010934/@
grub rescue > set path=$p/boot/grub
grub rescue > insmod normal
grub rescue > normal
```

This brought up a functioning GRUB menu, wherein I selected an old BE, booted, and repaired GRUB through:

```text
$ beadm activate 12.0-CURRENT-up-20170106_212203
$ beadm activate 12.0-CURRENT-up-20170212_105141
```

**Comment by pkgdemon** [comment]
Restamping grub from the installation media should also fix the CURRENT broken BE.  Known problem that this can happen with grub from time to time, and that is why the restamp option was added years ago for PC-BSD.  If it still does not work as expected let me know, and I will reopen.
