### ISSUE TITLE
no web browser after text-based installation

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#331]
- `TrueOS-Desktop-2017-02-09-x64-USB.img` 
- text installation

## Expected

- a web browser

## Actual result

- no browser

– and in the 'open access' network environment where I tried, today, to use the OS: a browser is **required**. Without it, no Internet access; and without Internet access, I can't install a browser …

**Comment by pkgdemon** [comment]
Yeah.  I've said it before, and I'll continue to say it.  We should do few things, and do them well.  I understand that people want a text installer but maintaining 2 different installers is not something I have time for.  I would prefer to see this alternate installer removed, and will continue to stress that to the team.

**Comment by grahamperrin** [comment]
Thanks. (Is the absence of a web browser peculiar to the text installer? I tried only one other option, auto-detect video, which failed in this case.)

**Comment by pkgdemon** [comment]
The text installer does not use the same code path as the GUI installer.  So any changes we make in the GUI installer do not show up in the text installer.  The lack of firefox is a prime example that no one has been maintaining the text installer code.

**Comment by jungle-boogie** [comment]
So firefox is no longer being 'shipped' with trueOS?

**Comment by pkgdemon** [comment]
My problem is not the text installer feature itself.  It is the lack of maintainership.  If it is not going to be maintained, or share a code path which is maintained I say drop the feature.  Otherwise it is just another support nightmare when it comes to troubleshooting other users installation issues.  Who knows what other quirks it may have which no one knows about.

**Comment by pkgdemon** [comment]
I already know about the lack of 4k alignment options, pool naming, problems with user account display names.

**Comment by pkgdemon** [comment]
Firefox is included with the GUI installer code path.  There is currently not an option for the text installer code path.  No one ever added it, or thought to add it.  Which would not be a problem if it used the same code path for all functions.

**Comment by jungle-boogie** [comment]
@pkgdemon, ah, gotcha. no web browser when installing trueOS desktop via text installation.
