### ISSUE TITLE
service pcdm after update has to be started by hand

### ISSUE THREAD

**Issue by slughorn0850** [trueos/trueos-core#332]
After update TrueOS stable service pcdm has to be started by hand.
My last working BE is from 28.10.2016 and starts pcdm by default.
This is annoying because I have to login 
first as user and password with en keyboard layout
second as root with en keyboard layout
third on pcdm as user with de keyboard layout.
 

about -v

General info:
       Host:...............trueos-874.TrueOS
       User:...............slughorn
       Uptime:.............36 mins
       FreeBSD kernel ver:.12.0-CURRENT
       FreeBSD world ver:..12.0-CURRENT
       FreeBSD git branch:.drm-next
       FreeBSD git rev:....27d3221
       TrueOS ver:.........TrueOS-Desktop-201702011813
       Arch:...............amd64
       Kernel ident:.......GENERIC
       Bootloader:.........BSD
       Bootloader type:....BIOS
       CPU:................AMD Athlon(tm) 64 X2 Dual Core Processor 6000+
       CPU cores:..........1
       Memory (free/avail):773 / 1707 Mb
       Package set:........EDGE
       Desktop environment:Lumina
       X11 Driver:.........vboxvideo_drv.so 
       OSS Driver:.........pcm0: <Intel ICH (82801AA)> (play/rec) default
       WIFI Driver:........

Network IPV4 address: 
       169.254.132.129
       127.0.0.1

Network IPv6 address: 
       fe80::a00:27ff:fef4:d5b4%em0
       ::1
       fe80::1%lo0

Do you need more information?

**Comment by pkgdemon** [comment]
Can you post the output of ```rc-update```?

**Comment by slughorn0850** [comment]
rc-update
                  abi | boot                                   
            adjkerntz | boot                                   
             bootmisc | boot                                   
                 cron | boot                                   
                 devd | boot                                   
               dumpon | boot                                   
                 fsck | boot                                   
               hostid | boot                                   
             hostname | boot                                   
                local |      default nonetwork                 
           localmount | boot                                   
             loopback | boot                                   
              modules | boot                                   
                 motd | boot                                   
             netmount |      default                           
              network | boot                                   
            newsyslog | boot                                   
            nisdomain | boot                                   
                 root | boot                                   
              routing | boot                                   
            savecache |                        shutdown        
             savecore | boot                                   
          staticroute | boot                                   
                 swap | boot                                   
              syscons | boot                                   
               sysctl | boot                                   
              syslogd | boot                                   
              urandom | boot                                   
                  zfs | boot default                           
                 zvol | boot

**Comment by pkgdemon** [comment]
Thanks @kmoore134 said this fix should resolve after we release our next STABLE in a few weeks.  

https://github.com/trueos/trueos-desktop/commit/929983003ef787fca97eb7c42296521878678cd1

For now if you wanted to fix you could run the following commands:

```
  /sbin/rc-update add ipfw boot
  /sbin/rc-update add devd boot
  /sbin/rc-update add devfs boot
  /sbin/rc-update add routing boot
  /sbin/rc-update add automount default
  /sbin/rc-update add statd default
  /sbin/rc-update add lockd default
  /sbin/rc-update add rpcbind default
  /sbin/rc-update add cupsd default
  /sbin/rc-update add cups_browsed default
  /sbin/rc-update delete dhcpcd default
  /sbin/rc-update delete wpa_supplicant default
  /sbin/rc-update add openntpd default
  /sbin/rc-update add pcdm default
  /sbin/rc-update add sysadm default
  /sbin/rc-update add dbus default
  /sbin/rc-update add hald default
  /sbin/rc-update add trueosinit default
  /sbin/rc-update add moused default
  /sbin/rc-update add bsdstats default
  /sbin/rc-update add automountd default
  /sbin/rc-update add autounmountd default
```

**Comment by slughorn0850** [comment]
I made this commands and got 4 answers:
* rc-update: service `dhcpcd' is not in the runlevel `default'
* rc-update: service `wpa_supplicant' is not in the runlevel `default'
* rc-update: service `trueosinit' does not exist
 * rc-update: service `bsdstats' does not exist
This issue seems to be fixed.
Thanks
