### ISSUE TITLE
No connection to the Internet with stable update

### ISSUE THREAD

**Issue by slughorn0850** [trueos/trueos-core#334]
After update TrueOS stable there is no connection to the internet.
BE from 28.10.2016 works fine on virtualbox.

about -v

General info:
       Host:...............trueos-874.TrueOS
       User:...............slughorn
       Uptime:.............36 mins
       FreeBSD kernel ver:.12.0-CURRENT
       FreeBSD world ver:..12.0-CURRENT
       FreeBSD git branch:.drm-next
       FreeBSD git rev:....27d3221
       TrueOS ver:.........TrueOS-Desktop-201702011813
       Arch:...............amd64
       Kernel ident:.......GENERIC
       Bootloader:.........BSD
       Bootloader type:....BIOS
       CPU:................AMD Athlon(tm) 64 X2 Dual Core Processor 6000+
       CPU cores:..........1
       Memory (free/avail):773 / 1707 Mb
       Package set:........EDGE
       Desktop environment:Lumina
       X11 Driver:.........vboxvideo_drv.so 
       OSS Driver:.........pcm0: <Intel ICH (82801AA)> (play/rec) default
       WIFI Driver:........

Network IPV4 address: 
       169.254.132.129
       127.0.0.1

Network IPv6 address: 
       fe80::a00:27ff:fef4:d5b4%em0
       ::1
       fe80::1%lo0
-----------------------------------------

dmesg
Copyright (c) 1992-2017 The FreeBSD Project.
Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
        The Regents of the University of California. All rights reserved.
FreeBSD is a registered trademark of The FreeBSD Foundation.
FreeBSD 12.0-CURRENT #23 27d3221(drm-next): Sun Feb  5 13:22:47 UTC 2017
    root@gauntlet:/usr/obj/usr/src/sys/GENERIC amd64
clang version 3.9.0 (tags/RELEASE_390/final)
VT(vga): text 80x25
CPU: AMD Athlon(tm) 64 X2 Dual Core Processor 6000+ (2807.67-MHz K8-class CPU)
  Origin="AuthenticAMD"  Id=0x60fb2  Family=0xf  Model=0x6b  Stepping=2
  Features=0x783fbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,MMX,FXSR,SSE,SSE2>
  Features2=0x1<SSE3>
  AMD Features=0xea100800<SYSCALL,NX,FFXSR,RDTSCP,LM,3DNow!+,3DNow!>
  AMD Features2=0x11<LAHF,CR8>
real memory  = 1790902272 (1707 MB)
avail memory = 1688862720 (1610 MB)
Event timer "LAPIC" quality 100
ACPI APIC Table: <VBOX   VBOXAPIC>
random: unblocking device.
WARNING: VIMAGE (virtualized network stack) is a highly experimental feature.
ioapic0 <Version 1.1> irqs 0-23 on motherboard
Timecounter "TSC-low" frequency 1403833027 Hz quality 800
random: entropy device external interface
netmap: loaded module
module_register_init: MOD_LOAD (vesa, 0xffffffff80feca90, 0) error 19
kbd1 at kbdmux0
nexus0
vtvga0: <VT VGA driver> on motherboard
cryptosoft0: <software crypto> on motherboard
aesni0: No AESNI support.
acpi0: <VBOX VBOXXSDT> on motherboard
acpi0: Power Button (fixed)
acpi0: Sleep Button (fixed)
cpu0: <ACPI CPU> on acpi0
attimer0: <AT timer> port 0x40-0x43,0x50-0x53 on acpi0
Timecounter "i8254" frequency 1193182 Hz quality 0
Event timer "i8254" frequency 1193182 Hz quality 100
Timecounter "ACPI-fast" frequency 3579545 Hz quality 900
acpi_timer0: <32-bit timer at 3.579545MHz> port 0x4008-0x400b on acpi0
pcib0: <ACPI Host-PCI bridge> port 0xcf8-0xcff on acpi0
pci0: <ACPI PCI bus> on pcib0
isab0: <PCI-ISA bridge> at device 1.0 on pci0
isa0: <ISA bus> on isab0
atapci0: <Intel PIIX4 UDMA33 controller> port 0x1f0-0x1f7,0x3f6,0x170-0x177,0x376,0xd000-0xd00f at device 1.1 on pci0
ata0: <ATA channel> at channel 0 on atapci0
ata1: <ATA channel> at channel 1 on atapci0
vgapci0: <VGA-compatible display> mem 0xe0000000-0xe0ffffff irq 18 at device 2.0 on pci0
vgapci0: Boot video device
em0: <Intel(R) PRO/1000 Network Connection> port 0xd010-0xd017 mem 0xf0000000-0xf001ffff irq 19 at device 3.0 on pci0
em0: attach_pre capping queues at 1
em0: using 1024 tx descriptors and 1024 rx descriptors
em0: allocated for 1 tx_queues
em0: allocated for 1 rx_queues
em0: Ethernet address: 08:00:27:f4:d5:b4
Link state changed to up
em0: netmap queues/slots: TX 1/1024, RX 1/1024
pcm0: <Intel ICH (82801AA)> port 0xd100-0xd1ff,0xd200-0xd23f irq 21 at device 5.0 on pci0
pcm0: <SigmaTel STAC9700/83/84 AC97 Codec>
ohci0: <Apple KeyLargo/Intrepid USB controller> mem 0xf0804000-0xf0804fff irq 22 at device 6.0 on pci0
usbus0 on ohci0
pci0: <bridge> at device 7.0 (no driver attached)
acpi_acad0: <AC Adapter> on acpi0
atkbdc0: <Keyboard controller (i8042)> port 0x60,0x64 irq 1 on acpi0
atkbd0: <AT Keyboard> irq 1 on atkbdc0
kbd0 at atkbd0
atkbd0: [GIANT-LOCKED]
psm0: <PS/2 Mouse> irq 12 on atkbdc0
psm0: [GIANT-LOCKED]
psm0: model IntelliMouse Explorer, device ID 4
orm0: <ISA Option ROM> at iomem 0xc0000-0xc7fff on isa0
vga0: <Generic ISA VGA> at port 0x3c0-0x3df iomem 0xa0000-0xbffff on isa0
atrtc0: <AT realtime clock> at port 0x70 irq 8 on isa0
Event timer "RTC" frequency 32768 Hz quality 0
ppc0: cannot reserve I/O port range
ZFS NOTICE: Prefetch is disabled by default if less than 4GB of RAM is present;
            to enable, add "vfs.zfs.prefetch_disable=0" to /boot/loader.conf.
ZFS filesystem version: 5
ZFS storage pool version: features support (5000)
Timecounters tick every 1.000 msec
pcm0: measured ac97 link rate at 32186 Hz
em0: link state changed to UP
usbus0: 12Mbps Full Speed USB v1.0
ugen0.1: <Apple OHCI root HUB> at usbus0
uhub0: <Apple OHCI root HUB, class 9/0, rev 1.00/1.00, addr 1> on usbus0
ada0 at ata0 bus 0 scbus0 target 0 lun 0
cd0 at ata1 bus 0 scbus1 target 0 lun 0
cd0: <VBOX CD-ROM 1.0> Removable CD-ROM SCSI device
cd0: Serial Number VB2-01700376
cd0: 33.300MB/s transfers (UDMA2, ATAPI 12bytes, PIO 65534bytes)
cd0: Attempt to query device size failed: NOT READY, Medium not present
ada0: <VBOX HARDDISK 1.0> ATA-6 device
ada0: Serial Number VB87ba7cc3-1a6c2046
ada0: 33.300MB/s transfers (UDMA2, PIO 65536bytes)
ada0: 51492MB (105456768 512 byte sectors)
Trying to mount root from zfs:tank/ROOT/12.0-CURRENT-up-20170216_192756 []...
Root mount waiting for: usbus0
uhub0: 8 ports with 8 removable, self powered
interface iwn.1 already present in the KLD 'kernel'!
linker_load_file: Unsupported file type
Cuse v0.1.34 @ /dev/cuse
acpi_video0: <ACPI video extension> on vgapci0
fuse-freebsd: version 0.4.4, FUSE ABI 7.8
vboxguest0 port 0xd020-0xd03f mem 0xf0400000-0xf07fffff,0xf0800000-0xf0803fff irq 20 at device 4.0 on pci0
vboxguest: loaded successfully
GEOM_ELI: Device label/swap0.eli created.
GEOM_ELI: Encryption: AES-XTS 128
GEOM_ELI:     Crypto: software

-----------------------------------------------------

lspci -v
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
        Flags: fast devsel, IRQ 255

00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
        Flags: bus master, medium devsel, latency 0, IRQ 255

00:01.1 IDE interface: Intel Corporation 82371AB/EB/MB PIIX4 IDE (rev 01) (prog-if 8a [Master SecP PriP])
        Flags: bus master, fast devsel, latency 0, IRQ 255
        I/O ports at d000

00:02.0 VGA compatible controller: InnoTek Systemberatung GmbH VirtualBox Graphics Adapter (prog-if 00 [VGA controller])
        Flags: bus master, fast devsel, latency 0, IRQ 18
        Memory at e0000000 (32-bit, prefetchable)

00:03.0 Ethernet controller: Intel Corporation 82540EM Gigabit Ethernet Controller (rev 02)
        Subsystem: Intel Corporation PRO/1000 MT Desktop Adapter
        Flags: bus master, 66MHz, medium devsel, latency 0, IRQ 19
        Memory at f0000000 (32-bit, non-prefetchable)
        I/O ports at d010
        Capabilities: [dc] Power Management version 2
        Capabilities: [e4] PCI-X non-bridge device

00:04.0 System peripheral: InnoTek Systemberatung GmbH VirtualBox Guest Service
        Flags: bus master, fast devsel, latency 0, IRQ 20
        I/O ports at d020
        Memory at f0400000 (32-bit, non-prefetchable)
        Memory at f0800000 (32-bit, prefetchable)

00:05.0 Multimedia audio controller: Intel Corporation 82801AA AC'97 Audio Controller (rev 01)
        Subsystem: Intel Corporation Device 0000
        Flags: bus master, medium devsel, latency 0, IRQ 21
        I/O ports at d100
        I/O ports at d200

00:06.0 USB controller: Apple Inc. KeyLargo/Intrepid USB (prog-if 10 [OHCI])
        Flags: bus master, fast devsel, latency 0, IRQ 22
        Memory at f0804000 (32-bit, non-prefetchable)

00:07.0 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 08)
        Flags: bus master, medium devsel, latency 0, IRQ 9

**Comment by pkgdemon** [comment]
Thanks for the heads up.  Sounds like something in the migration is not working.  We will take a look.

**Comment by pkgdemon** [comment]
Thanks @kmoore134 said this fix should resolve after we release our next STABLE in a few weeks.  

https://github.com/trueos/trueos-desktop/commit/929983003ef787fca97eb7c42296521878678cd1

For now if you wanted to fix you could run the following commands:

```
  /sbin/rc-update add ipfw boot
  /sbin/rc-update add devd boot
  /sbin/rc-update add devfs boot
  /sbin/rc-update add routing boot
  /sbin/rc-update add automount default
  /sbin/rc-update add statd default
  /sbin/rc-update add lockd default
  /sbin/rc-update add rpcbind default
  /sbin/rc-update add cupsd default
  /sbin/rc-update add cups_browsed default
  /sbin/rc-update delete dhcpcd default
  /sbin/rc-update delete wpa_supplicant default
  /sbin/rc-update add openntpd default
  /sbin/rc-update add pcdm default
  /sbin/rc-update add sysadm default
  /sbin/rc-update add dbus default
  /sbin/rc-update add hald default
  /sbin/rc-update add trueosinit default
  /sbin/rc-update add moused default
  /sbin/rc-update add bsdstats default
  /sbin/rc-update add automountd default
  /sbin/rc-update add autounmountd default
```

**Comment by slughorn0850** [comment]
I made this commands and got 4 anwers:
* rc-update: service `dhcpcd' is not in the runlevel `default'
* rc-update: service `wpa_supplicant' is not in the runlevel `default'
* rc-update: service `trueosinit' does not exist
 * rc-update: service `bsdstats' does not exist 

This issue is not fixed yet.

**Comment by pkgdemon** [comment]
The first two answers were just from attempts to remove services that may have xisted previously.  Ignore those.  The fact that trueosinit service does not exist seems a problem.  If you do ```pkg info trueos-desktop``` does anything show?  Does the ```about``` command output anything?  We did just promote a new stable branch a few hours ago.  It might be worth rolling back to your previous boot environment, and trying the upgrade again with the additional commands.  Otherwise it should be fully fixed with the next stable push.

**Comment by slughorn0850** [comment]
pkg info trueos-desktop
trueos-desktop-201702011813
Name           : trueos-desktop
Version        : 201702011813
Installed on   : Thu Feb 16 19:27:46 2017 CET
Origin         : misc/trueos-desktop
Architecture   : freebsd:12:x86:64
Prefix         : /usr/local
Categories     : misc
Licenses       : BSD2CLAUSE
Maintainer     : jmaloney@ixsystems.com
WWW            : UNKNOWN
Comment        : TrueOS Desktop
Annotations    :
Flat size      : 51.3MiB
Description    :
TrueOS Desktop

https://www.github.com/trueos/trueos-desktop


about
[: =: unexpected operator
  ______                   ____  _____
 /_  __/______  _____     / __ \/ ___/ 
  / / / ___/ / / / _ \   / / / /\__ \ 
 / / / /  / /_/ /  __/  / /_/ /___/ / 
/_/ /_/   \__,_/\___/   \____//____/  

General info:
       Host:...............trueos-874.TrueOS
       User:...............slughorn
       Uptime:.............9 mins
       FreeBSD kernel ver:.12.0-CURRENT
       FreeBSD world ver:..12.0-CURRENT
       FreeBSD git branch:.drm-next
       FreeBSD git rev:....27d3221
       TrueOS ver:.........TrueOS-Desktop-201702011813
       Arch:...............amd64
       Kernel ident:.......GENERIC
       Bootloader:.........BSD
       Bootloader type:....BIOS
       CPU:................AMD Athlon(tm) 64 X2 Dual Core Processor 6000+
       CPU cores:..........2
       Memory (free/avail):779 / 1773 Mb
       Package set:........EDGE
       Desktop environment:Lumina
       X11 Driver:.........vboxvideo_drv.so 
       OSS Driver:.........pcm0: <Intel ICH (82801AA)> (play/rec) default
       WIFI Driver:........

**Comment by slughorn0850** [comment]
Now I have only tryed a new update with my last working BE..
1. I started Appcafe-> update manager. But I got the information: Checking for updates. I waited for half an hour. Nothing happens. 
2. I tryed as su pc-updatemanager pkgcheck. I got the answer: permission denied
Because my last update process on the command line worked. I think it has something to do with the server on your side.

**Comment by grahamperrin** [comment]
> `su pc-updatemanager pkgcheck`

Instead: 

`sudo pc-updatemanager pkgupdate`

That's `sudo` (not `su`). 

Also, in your present situation it should be acceptable to proceed with the `pkgupdate` command (without `pkgcheck`).

**Comment by slughorn0850** [comment]
Last time I used su and pkgcheck and it worked with the stable version from 28.10.2016.
And with sudo pc-updatemanager pkgupdate I get the answer: "Befehl nicht gefunden" = command not found. I think this is vary odd.

**Comment by grahamperrin** [comment]
> … `sudo pc-updatemanager pkgupdate` I get the answer: "Befehl nicht gefunden" = command not found. … 

I see that as point 2 in #338
