### ISSUE TITLE
Update from 10/28/16 and eariler pre OpenRC no longer working

### ISSUE THREAD

**Issue by slughorn0850** [trueos/trueos-core#338]
Now I have  tryed a new update with my last working BE..
1. I started **Appcafe**-> update manager. But I got the information: Checking for updates. I waited for half an hour. Nothing happens. 
2. I tryed as su **pc-updatemanager pkgcheck**. I got the answer: permission denied
Because my last update process on the command line worked. I think it has something to do with the server on your side.
3. With command sudo pc-updatemanager pkgupdate - I get the answer: "Befehl nicht gefunden"
= Command not found.
4. With su and PW than pc-updatemanager pkgupdate: I get the answer: /usr/local/bin/pc-updatemanager permission denied.
Vary odd
Last time it worked.

My last working BE:

pkg info trueos-desktop
trueos-desktop-201610141335
Name           : trueos-desktop
Version        : 201610141335
Installed on   : Fri Oct 28 14:35:37 2016 CEST
Origin         : misc/trueos-desktop
Architecture   : freebsd:12:x86:64
Prefix         : /usr/local
Categories     : misc
Licenses       : BSD2CLAUSE
Maintainer     : jmaloney@ixsystems.com
WWW            : UNKNOWN
Comment        : TrueOS Desktop
Annotations    :
        repo_type      : binary
        repository     : trueos-major
Flat size      : 51.4MiB
Description    :
TrueOS Desktop

https://www.github.com/trueos/trueos-desktop

    ____  _____
 /_  __/______  _____     / __ \/ ___/ 
  / / / ___/ / / / _ \   / / / /\__ \ 
 / / / /  / /_/ /  __/  / /_/ /___/ / 
/_/ /_/   \__,_/\___/   \____//____/  

General info:
       Host:...............trueos-874.TrueOS
       User:...............slughorn
       Uptime:.............12 mins
       FreeBSD kernel ver:.12.0-CURRENT
       FreeBSD world ver:..12.0-CURRENT
       TrueOS ver:.........
       Arch:...............amd64
       Kernel ident:.......GENERIC
       CPU:................AMD Athlon(tm) 64 X2 Dual Core Processor 6000+
       CPU cores:..........2
       Memory (free/avail):239 / 1773 Mb
       Package set:........EDGE
/usr/local/bin/about: de-info: not found
       Desktop environment:
       X11 Driver:.........vboxvideo_drv.so

Network IPV4 address: 
       192.168.178.24
       127.0.0.1

Installed desktop environments:
       Lumina:.......201610141335,2

System components:
       PC-BSD CLI:...r201610141335
  PC-BSD UI:....r201610141335

With this BE I got the update the last time:
trueos-desktop-201702011813
Name           : trueos-desktop
Version        : 201702011813
Installed on   : Thu Feb 16 19:27:46 2017 CET
Origin         : misc/trueos-desktop

This time nothing happens.

**Comment by pkgdemon** [comment]
Renaming this issue to reflect the problem.  I was able to confirm it as well, and it cannot be fully resolved until we push the next stable.

**Comment by pkgdemon** [comment]
This fix is supposed to be in this commit https://github.com/trueos/trueos-desktop/commit/929983003ef787fca97eb7c42296521878678cd1 but I cannot verify it works until the next set of packages are built.

**Comment by slughorn0850** [comment]
Thanks to all of you. In the meantime I have downloaded the latest iso and installed in a new VM.
It works.
