### ISSUE TITLE
Hard drive mounts to .snap

### ISSUE THREAD

**Issue by way2OLDman** [trueos/trueos-core#343]
After the 2-25-2017 TrueOS 1.2.0 major update, my hard drive's contents started mounting to the /mnt/.snap hidden directory.  The .snap folder is read/write accessible with Insight. Will mirroring backup software write to a hidden directory?

Computer: Asus Z-97 MB, 8GB ram, Haswell CoreI5 CPU, Corsair Caviar Black 1TB hard drive.

**Comment by Mrt134** [comment]
Many apologies for the inactivity! Is this still an issue with the latest STABLE/UNSTABLE builds?

**Comment by Mrt134** [comment]
Closed for inactivity. Please comment or reopen if this is still an issue. Thanks!
