### ISSUE TITLE
skylake/modesetting drm crashes with warnings in drm_atomic.c

### ISSUE THREAD

**Issue by rostwald** [trueos/trueos-core#348]
After updating TrueOS from oct 28 STABLE build to feb 21 STABLE build on a skylake i7 machine, X crashes and throws me to the debugger prompt with the following output:

![img_20170303_103828](https://cloud.githubusercontent.com/assets/18121333/23546372/90864a98-ffff-11e6-8c71-52ca009c4c7e.jpg)

I can reproduce this error by trying to download a file with firefox by right click -> 'save as'. After clicking 'save file' X crashes after a short (<1sec) delay.

I'm using the modesetting driver, acceleration = none

December and January builds caused random kernel panics /w complete lockups, hence this machine (my daily workhorse) is still running the october build...

**Comment by barulheira** [comment]
I have similar settings (Intel GPU and modesetting driver, acceleration = none), and cannot reproduce this crash. Downloading with Firefox works just fine.
Using Intel video driver, such kernel panics remain happening (they haven't been fixed yet), but they are different than this one.

**Comment by rostwald** [comment]
I can't reproduce it on another skylake system either. The firefox 'download as' is just the first thing I was able to safely reproduce the issues with. The crashes also occur relatively random during other workloads.

I'll try installing the current image into a new BE as soon as I can free some time for this. The system was set up with one of the first TrueOS images just after the rebranding and I had to revert back to previous BEs several times in the beginning (mostly due to graphics-related issues...), so i'll try to get a clean, fresh install and check if the problem still persists...

**Comment by Troub274** [comment]
I am also having a similar problem I have a dell optiplex 755 stock with intel card.  the previous releases worked but 2/22 hangs hard just before x starts with a black screen. Typically the resolution changes from 80x20 in the terminal when rc scripts are running.  the last line of rc I see is if-iwn  then the screen goes to flash/change resolution  and hangs normally I see about 50 more lines of RC scripts loading till x starts but this time in never get's that far.

**Comment by rostwald** [comment]
Installing in new BE doesn't help - still getting the same crashes within a few minutes after booting.

dmesg output at drm initialisation:

> [drm] Initialized
> drmn0: <drmn> on vgapci0
> vgapci0: child drmn0 requested pci_enable_io
> vgapci0: child drmn0 requested pci_enable_io
> [drm] Memory usable by graphics device = 4096M
> Failed to add WC MTRR for [0xc0000000-0xcfffffff]: -22; performance may suffer
> [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
> [drm] Driver supports precise vblank timestamp query.
> [drm] Connector eDP-1: get mode from tunables:
> [drm]   - kern.vt.fb.modes.eDP-1
> [drm]   - kern.vt.fb.default_mode
> [drm] failed to retrieve link info, disabling eDP
> [drm] Memory usable by graphics device = 4096M
> Failed to add WC MTRR for [0xc0000000-0xcfffffff]: -22; performance may suffer
> [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
> [drm] Driver supports precise vblank timestamp query.
> [drm] Connector eDP-1: get mode from tunables:
> [drm]   - kern.vt.fb.modes.eDP-1
> [drm]   - kern.vt.fb.default_mode
> [drm] failed to retrieve link info, disabling eDP
> drmn0: failed to load firmware image i915_skl_dmc_ver1_26_bin
> drmn0: Failed to load DMC firmware [https://01.org/linuxgraphics/intel-linux-graphics-firmwares], disabling runtime power management.
> [drm] Connector HDMI-A-1: get mode from tunables:
> [drm]   - kern.vt.fb.modes.HDMI-A-1
> [drm]   - kern.vt.fb.default_mode
> [drm] Connector HDMI-A-2: get mode from tunables:
> [drm]   - kern.vt.fb.modes.HDMI-A-2
> [drm]   - kern.vt.fb.default_mode
> [drm] Connector DP-1: get mode from tunables:
> [drm]   - kern.vt.fb.modes.DP-1
> [drm]   - kern.vt.fb.default_mode
> [drm] GuC firmware load skipped
> [drm:i915_setup_sysfs] RC6 residency sysfs setup failed
> [drm] Initialized i915 1.6.0 20160919 for drmn on minor 0
> VT: Replacing driver "efifb" with new "fb".
> start FB_INFO:
> type=11 height=1080 width=1920 depth=32
> cmsize=16 size=8294400
> pbase=0xc0000000 vbase=0xffffffff82610000
> name=drmn0 flags=0x0 stride=7680 bpp=32
> cmap[0]=0 cmap[1]=7f0000 cmap[2]=7f00 cmap[3]=c4a000
> end FB_INFO
> drmn0: fb0: inteldrmfb frame buffer device
> [drm] RC6 on

I'm using 2 displays on this machine - maybe this causes drm to keel over? All other skylake systems I'm running TrueOS on are only using one display...

**Comment by rostwald** [comment]
Update:
The problem seems to be solved with the latest updates. Yesterday I finally found the time to try and update the system from the 'old-but-functional' oct. 28 build and so far no more crashes or hiccups:

```text

===================
General information
===================

boot environment now (N) … 12.0-CURRENT-up-20170406_111737 NR 2017-04-06
       after restart (R) … 12.0-CURRENT-up-20170406_111737 NR 2017-04-06
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    number of cores ……………… 8
host ……………………………………………………… h-itbuero.gassner.lan
memory ………………………………………………… 16384 MB available, 7023 MB free
OS git branch ……………………………………………………………………………………… drm-next
OS git revision ………………………………………………………………………………… d44fdf245
OS kernel build time ………………………………………………………… Thu 2017 Mar 30 18:18:02 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… STABLE
TrueOS version …………………………… TrueOS-Desktop-201703311459
uptime ………………………………………………… 23:02
user  …………………………………………………… sko

More (TrueOS Desktop):

    desktop environment …… Lumina
    sound card driver ………… pcm0: <Realtek ALC892 (Rear Analog)> (play/rec) default
    wireless driver ……………… 
    X11 drivers ………………………… modesetting_drv.so 

```

The uptime of 23h includes ~10h of working actively with the system with various workloads. As the described problem was triggered within ~30min max time, I consider it as solved and close the issue for now.

**Comment by Troub274** [comment]
Yes Mine is working again as well. Just installed the new version.

S.
