### ISSUE TITLE
TrueOS MixerTray no sound

### ISSUE THREAD

**Issue by slughorn0850** [trueos/trueos-core#349]
I play music with VLC player.  VLC shows that the music is on. pavucontrol shows output is on. The bar chart works.
If I open the Mixer Icon in the quicklaunch and press the Test button only a short test sound comes out. No Music.
After I switched the output of the Mixer from VIA VT1708B_1 from Analog to digital and back the bar charts of of pavucontrol are gone.
But no sound.
This happened as well in my virtualbox machine as in a new installation on a spare machine.

about

===================
General information
===================

boot environment now (N) … initial NR 2009-07-07
       after restart (R) … initial NR 2009-07-07
boot loader …………………………………… BSD
            type ……………………… BIOS
CPU ………………………………………………………… AMD Athlon(tm) II X2 240 Processor
    number of cores ……………… 2
host ……………………………………………………… trueos-8815.Slughorn
memory ………………………………………………… 2048 MB available, 356 MB free
OS git branch ……………………………………………………………………………………… drm-next
OS git revision ………………………………………………………………………………… a7f7424
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… STABLE
TrueOS version …………………………… TrueOS-Desktop-201702212122
uptime ………………………………………………… 40 mins
user  …………………………………………………… slughorn

More (TrueOS Desktop):

    desktop environment …… Lumina
    sound card driver ………… pcm0: <VIA VT1708B_1 (Analog 2.0+HP/2.0)> (play/rec) default
    wireless driver ……………… 
    X11 drivers ………………………… nvidia_drv.so nv_drv.so modesetting_drv.so scfb_drv.so vesa_drv.so

**Comment by slughorn0850** [comment]
Today I got the message: GStreamer-Backend_ -Error Could not initialise Xv output.
Does this help?

**Comment by Mrt134** [comment]
Could not reproduce, looks to be working alright now.
