### ISSUE TITLE
Two AppCafe programs partially or totally removed Lumina on current and other BEs during installation requiring TrueOS reinstallation.

### ISSUE THREAD

**Issue by way2OLDman** [trueos/trueos-core#350]
Two AppCafe programs partially or totally removed Lumina from current and other BEs during installation.  TrueOS re-installation was required.

AppCafe programs Jags and Xpostit during installation reported that they had "removed" the "TrueOS desktop."  The programs were installed using two different boot environments. Neither of the Lumina desktops could be restored. In both cases AppCafe's "Installed" tab was left with a column of black flags. If memory serves: (1) Jags, on closing AppCafe, left a black desktop with no functioning symlinks or visible directories where there had been a total of 36  on the desktop. The black screen was not an X Window. (2) Xpostit left a black background with only three or four "iffy" surviving symlinks of the original 36 symlinks and directories. Those vanished when I logged out and then logged in. 

There was a temporary work-around.  Most, and perhaps all of the BE desktops were damaged, but a less severely damaged BE allowed transfer of the directories to USB flash drives before re-installation of TrueOS. Both Jags and Xposit currently remain available on AppCafe.

This problem occurred a few weeks ago, before I joined GitHub. The OS version may have been TrueOS 1.1.0, but I'm not certain.

**Comment by Mrt134** [comment]
Not fully tested, but Jags and Xpostit are still available in Appcafe.

**Comment by Mrt134** [comment]
Finally had some testing time - jags and xpostit appear to install and function properly now - no crashing or destroying BEs, as far as I can tell. Thanks for reporting this!
