### ISSUE TITLE
floppy drive fails after latest update

### ISSUE THREAD

**Issue by Troub274** [trueos/trueos-core#353]
Hi, I just updated today 3/5/1017.  The PC hadn't been hooked to the net for an update for about a month.  The machine I am using has a floppy drive installed and I do need it.  Today it will no longer boot.  I get the TRUSOS white logo then it starts booting but at a certain point it queries the floppy drive.  At that point it hangs.  Whether a floppy is in it or not it will just hang with the green light on the floppy forever.  I suspect it's the new auto mount code that went in a few days ago.

**Comment by Troub274** [comment]
Let me do more investigating first

**Comment by q5sys** [comment]
I have a USB floppy drive, and I could test this as well, but I'm on the road for a week and won't be able to test till then.  Please report back if you are able to learn anymore about this.

**Comment by Troub274** [comment]
JT,

I'm not sure it's the floppy drive.  It seems to happen even when I
disconnect it. that is why I closed the issue and started another one.
The floppy I have is an old onboard one not a usb one so I'm not sure
that would test correctly, still I don't think it's the floppy now.
However, I've been a developer since 1978 so if you need something
specific tested I can do it.

However what is happening is that it hangs with a black screen and the
power light of the floppy on with the following error in the messages log:

Console-Kit-daemon (2162) WARNING: Error waiting for native console 9
activation Inappropriate ioctl for device

After that is a hard hang requiring power off. nothing further in the logs.
This is before x starts or perhaps just as it starts.

In the previous version at this point the console changes resolution
from 80x20 to a higher res.

So I get a few lines of low res text after the trueos logo. the last
line of that is a kernel load failure for if-ifw.  then it goes black.

I don't have wifi on this machine. it's too old.

Steve

**Comment by q5sys** [comment]
Steve, is this an old PATA drive?  I do have an internal Sata floppy drive somewhere I can dig out, but Im not sure if I have any Pata lying around. I have plenty of old systems with Pata, but none that are 64 bit, so trueos won't run on them.

**Comment by Troub274** [comment]
It's an old internal dell floppy from an optiplex 755. It was working
till this last update.
However like I said I don't think it's the floppy I think it's something
to do with the video.
Steve

**Comment by Troub274** [comment]
That was why I closed this issue I realized it wasn't the floppy.
The machine hangs hard even with the floppy removed.

Steve

**Comment by q5sys** [comment]
I understood why you closed the ticket, but if there are people out there with machines with floppy drives, it's a good idea for us to know what type of hardware is being used so we can try to test accordingly in the future.
