### ISSUE TITLE
SSHD not enabling correctly during install

### ISSUE THREAD

**Issue by chief1983** [trueos/trueos-core#361]
During the Desktop install process I was offered the choice of enabling the `sshd` service.  I checked it, but instead of it enabling the new OpenRC script, it added `sshd_enable="YES"` to `/etc/rc.conf`.  I believe the correct thing here would have been to run `rc-update add sshd default`, or some equivalent change to whatever that actually does.  Running that myself and the associated service start command has the daemon running as I would have expected it to be.

**Comment by beanpole135** [comment]
Fixed!

Thanks for reporting that!
https://github.com/trueos/trueos-utils-qt5/commit/bc07d7454ce58a540db02c88feb11e02fda27902
