### ISSUE TITLE
Web stack packages needing OpenRC conversion

### ISSUE THREAD

**Issue by chief1983** [trueos/trueos-core#362]
Notice:  This info is from current STABLE, if anything here has been updated in UNSTABLE since 22 Feb 2017 release, please disregard.

While trying to set up a web stack on the latest STABLE, I ran across numerous packages that are in need of OpenRC support.  I was trying to make a TrueOS/Web Server/Database/PHP stack.  Originally I planned for TrueOS/Apache 2.4/MariaDB 10.0/PHP 7.1, but here's what I ended up discovering.

Apache 2.4 and Apache 2.2 are both still using rc.conf style scripts.  So that rules out Apache.  Now I need to be concerned that both an nginx and php-fpm version have OpenRC scripts.  Would be good to at least get Apache 2.4, as 2.2 is nearing EOL and probably not worth converting at this point if it's much more work.

Luckily, nginx has OpenRC, so no issues there.  PHP 7.1 and 7.0 both use rc.conf for their php-fpm install though, so I had to go back to PHP 5.6 before I found a version that had been converted to OpenRC.  5.6 is nearing EOL so it would be nice to get 7.1 and/or 7.0 updated to OpenRC.

That leaves me with databases.  I found that no version available for MySQL (5.5, 5.6, 5.7) or MariaDB (5.5, 10.0) has OpenRC support yet.

PostgreSQL does seem to support it but I can't get it to start, which I will seek help for in a discourse thread or file a separate issue.

lighttpd also seems to need a conversion to OpenRC.

I think that basically leaves the only web stack option of TrueOS/nginx/PostgreSQL/PHP5.6.  Not too much choice here.  I haven't looked into the ruby or python side of things yet.  I am not even familiar enough to know what actual daemons would be running in order to test if those packages are correct or not.  Ok I lied, I installed uwsgi, a common python proxy and noticed that it is using rc.conf style as well.  So, packages needing attention:

apache22
apache24
php70
php71
mysql55
mysql56
mysql57
mariadb55
mariadb100
firebird
uwsgi
lighttpd

I think that's all I saw so far.

**Comment by chief1983** [comment]
@pkgdemon They suggested I make sure to loop you in on this, if this is in the wrong place let me know.  Also if there's anything I can do to help with these, such as testing, I'd be happy to.  I'm not too familiar with actually writing OpenRC scripts but I don't mind testing any of these as they are addressed.

**Comment by ZackaryWelch** [comment]
As far as I know, all packages in the port tree which have rc.d scripts now have corresponding OpenRC scripts. All of the ones you listed should have been completed.

**Comment by chief1983** [comment]
You can close now then, or I will confirm when this work has made it into STABLE, and I run an update on my machine and check these out.
