### ISSUE TITLE
Service 'picoserver' does not exist

### ISSUE THREAD

**Issue by Passaita** [trueos/trueos-core#368]
Fresh installation of TrueOS-Desktop-2016-12-27-x64-DVD.iso on VM ESXi host then:
sudo pc-updatemanager pkgupdate
power off and update installation

And then followed Pico Server installation instruction:
sudo pkg install picoserver
sudo service picoserver start

System is returning an error:
service 'picoserver' does not exist

Reboot didn't fix a problem. This prevents me from further testing.

**Comment by ZackaryWelch** [comment]
I installed picoserver via pkg and it started for me. Perhaps it was looking for an OpenRC script, which has been created. Try reinstalling it. Picoserver should exist in /usr/local/etc/init.d.
