### ISSUE TITLE
Unable to build sysadm on freebsd 10.3 or 11

### ISSUE THREAD

**Issue by Mrt134** [trueos/trueos-core#371]
Duplicated from https://github.com/trueos/sysadm-docs/issues/1

telefax

I tried to find a way to contact you for issues, but cannot find any, so I'll try here since I tried to follow the installation guide on https://sysadm.us/handbook/server/basics.html#building-sysadm
on Freebsd 10.3 release as well on Freebsd 11 Release.

Both bails out on qmake, this is from freebsd 10.3:

    /usr/local/lib/qt5/bin/qmake -recursive
    /usr/local/lib/qt5/bin/qmake: Command not found.

Is this supposed to run on FreeBSD?
on www.sysadm.us you can read

    SysAdm™ is a FreeBSD-based service which provides a stable API for administrating FreeBSD and TrueOS systems.

I'm a little bit confused, so much basic information is missing on the web page and in the documentation, also there is no issue tracker except for the documentation here?

Thanks
----------------------------------------------------------------------------------------------------------------------------------
I'm also keeping the ticket in the docs repo until I've addressed the docs concerns.

**Comment by beanpole135** [comment]
Re-assigning this back to Tim: The issue was resolved on the ticket this is a copy of (needed to install the Qt5 build tools).

**Comment by Mrt134** [comment]
Both issues resolved, closing now.
