### ISSUE TITLE
rc_logger and rc_log_path appear to have no effect

### ISSUE THREAD

**Issue by clinta** [trueos/trueos-core#377]
I have the following options in `/etc/rc.conf` but nothing is written to `/var/log/rc.log` after a reboot.

```
rc_logger="YES"
rc_log_path=”/var/log/rc.log”
```

**Comment by Mrt134** [comment]
Apologies for the inactivity - there have been a number of bugfixes to openrc, and testing my system shows this issue is now resolved. Thanks for reporting it!
