### ISSUE TITLE
Issues Related to usbus??

### ISSUE THREAD

**Issue by eyoung100** [trueos/trueos-core#379]
Please consider this a tracker type bug, open for discussion, with proof.  I reported my original issue on the Discourse Board:  [New Kernel lost track of my SATA HDD’s](https://discourse.trueos.org/t/new-kernel-lost-track-of-my-sata-hdds/1135)

I then read issue #376  and issue #378 and realized my issue might be related to these other 2.  In an older system, I have 3 HDD's all connected via SATA, to keep my system as current as I can without building a new system.  I only installed the TrueOS system day before yesterday, using the 02-27 DVD ISO.  My BIOS is too old to use the Hybrid USB GPT/MBR.  After installing a fresh system, I was informed of updates, installed them, rebooted, and had the failure below.  As I said in my post, the failure also occurs on the new ISO uploaded yesterday, but not on the 2-27 disk I used for my initial install, much like the picture below, which came from trying to boot the new Boot Environment after installing the updates.

Being disabled I couldn't catch all the pictures I wanted: 
![img_0049](https://cloud.githubusercontent.com/assets/5230163/24592991/1e353164-17e4-11e7-8287-529f33b63829.JPG)

But please know that the failure starts at usbus trying to probe my Photosmart D5069 USB Printer and times out after no wait at all.  Since all my HDD's are SATA, the kernel then cascades failure trying to attach/probe my SATA HDD's, which contain my root tank, and the above picture repeats infinitely, allowing no keyboard input etc. I believe this is a kernel issue because the BE created after my initial install and the one I created before attempting to apply the update a 3rd time also boots.  

I cannot install any software until this is fixed or at least investigated then pushed with a tree update because AppCafe complains that my local repository is out of sync with the remote.  Let me know if you need any other information, and I'll happily attach it as we go.  I already mounted the bad BE using `beadm mount` but /var/log was empty as the system never successfully boots

**Comment by eyoung100** [comment]
Adding SMART Control Test:
```
ecyoung@bedroom-ubuntu:~$ sudo smartctl -t long /dev/sdc
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.8.0-45-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF OFFLINE IMMEDIATE AND SELF-TEST SECTION ===
Sending command: "Execute SMART Extended self-test routine immediately in off-line mode".
Drive command "Execute SMART Extended self-test routine immediately in off-line mode" successful.
Testing has begun.
Please wait 81 minutes for test to complete.
Test will complete after Mon Apr  3 00:16:33 2017

Use smartctl -X to abort test.
ecyoung@bedroom-ubuntu:~$ sudo smartctl -l selftest /dev/sdc
[sudo] password for ecyoung: 
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.8.0-45-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Extended offline    Completed without error       00%      1942         -
```

Will try Disabling MSI, as documented here:  [SATA controller going bad?](https://forums.freebsd.org/threads/49420/) and [the manpage](https://www.freebsd.org/cgi/man.cgi?ahci(4)).

**Comment by eyoung100** [comment]
Adding #380.  Another USB type issue

**Comment by eyoung100** [comment]
Tried todays tree pull.  Still experiencing error.  I'll update this comment with the dates I  pull the tree

April 3rd - Still Broken

**Comment by eyoung100** [comment]
I've compiled this list of possible offenders, in regards to the kernel failure:

```
FreeBSD-libcam: 12.0.s20170222000447 -> 12.0.s20170330184551 [trueos-base]
FreeBSD-libusbhid-profile: 12.0.s20170222000447 -> 12.0.s20170330184551 [trueos-base]
FreeBSD-libusbhid-lib32-profile: 12.0.s20170222000447 -> 12.0.s20170330184551 [trueos-base]
FreeBSD-libusbhid-lib32-development: 12.0.s20170222000447 -> 12.0.s20170330184551 [trueos-base]
FreeBSD-libusbhid-lib32: 12.0.s20170222000447 -> 12.0.s20170330184551 [trueos-base]
FreeBSD-libusbhid-development: 12.0.s20170222000447 -> 12.0.s20170330184551 [trueos-base]
FreeBSD-libusbhid: 12.0.s20170222000447 -> 12.0.s20170330184551 [trueos-base]
FreeBSD-libusb-profile: 12.0.s20170222000447 -> 12.0.s20170330184551 [trueos-base]
FreeBSD-libusb-lib32-profile: 12.0.s20170222000447 -> 12.0.s20170330184551 [trueos-base]
FreeBSD-libusb-lib32-development: 12.0.s20170222000447 -> 12.0.s20170330184551 [trueos-base]
FreeBSD-libusb-lib32: 12.0.s20170222000447 -> 12.0.s20170330184551 [trueos-base]
FreeBSD-libusb-development: 12.0.s20170222000447 -> 12.0.s20170330184551 [trueos-base]
FreeBSD-libusb: 12.0.s20170222000447 -> 12.0.s20170330184551 [trueos-base]
FreeBSD-kernel-generic: 12.0.s20170222000447 -> 12.0.s20170330184551 [trueos-base]
```

See also: 
[USB_ERR_TIMEOUT, then stuck @ mountroot ](http://freebsd.1045724.x6.nabble.com/USB-ERR-TIMEOUT-then-stuck-mountroot-td5446367.html).  This is the exact behaviour I am experiencing, before the drives fail to mount, and what I couldn't catch a picture of.

I'll try adding the usb_quirk and the timeout options one after the other and report back.

**Comment by eyoung100** [comment]
Waiting for the next release DVD to come out.  My 12/27 disk is no longer readable...

**Comment by Mrt134** [comment]
Investigating this appears that these issues were/are related to FreeBSD. As we've updated/resynced with FreeBSD many times and adjusted STABLE to be on a 6 month update scheme, this issue appears to be resolved.

If it pops up again, please add a comment or reopen this issue. Thanks!
