### ISSUE TITLE
Unable to install packages

### ISSUE THREAD

**Issue by ctuffli** [trueos/trueos-core#38]
Installed the 12.0 alpha on a Lenovo laptop without issue. The available applications seem to work fine, but installing any application fails with a libssl error. Tried via both AppCafe and command line with the same result.
```
# uname -mrsv
FreeBSD 12.0-CURRENT FreeBSD 12.0-CURRENT #12 2281f25(drm-next-4.7): Thu Jul 28 19:41:42 UTC 2016     root@devastator:/usr/obj/usr/src/sys/GENERIC  amd64
# pkg install firefox
Shared object "libssl.so.39" not found, required by "pkg"
# pkg update -f
Shared object "libssl.so.39" not found, required by "pkg"
#
```

**Comment by ctuffli** [comment]
A little hackery
```
# ln -s /usr/local/lib/libssl.so.3{9,8}
# ln -s /usr/local/lib/libcrypto.so.3{7,8}
```
allows
```
# pkg update -f
# pkg upgrade -f
```
to run. On a different system with the same problem,
```
# pkg-static update -f
# pkg-static upgrade -f
```
seems to accomplish the same result as the above (very sketchy) .so shenanigans.

In both cases, pkg runs normally after the update without any modifications.

**Comment by pkgdemon** [comment]
We were seeing this as well after the libressl import.  All issues have been resolved in the current ISO/img media.
