### ISSUE TITLE
Automounter issue with internal drive

### ISSUE THREAD

**Issue by TerryTate-TrueOS-Linebacker** [trueos/trueos-core#380]
During a timeout I needed to make some notes about some new smackdown moves I learned, but the automounter doesnt mount my laptops 2nd internal drive which is NTFS.  I took a few minutes to see what's going on, but Terry ain't got time to be futzing around on these keys to figure out what the problem is.  I've gotta spend my time doing what God put me on this earth to do -- Taking names and sackin fools.  There's so many fools that need sacked... and only so much time in a day.  Spending time doing fiddle-diddle with these keys and not being able to sack fools that need sackin make Terry a sad man, believe that.  

from dmesg:
```
ada0 at ahcich0 bus 0 scbus0 target 0 lun 0
ada0: <KINGSTON SHFS37A120G 580ABBF0> ATA8-ACS SATA 3.x device
ada0: Serial Number 50026B724707FFB0
ada0: 600.000MB/s transfers (SATA 3.x, UDMA6, PIO 512bytes)
ada0: Command Queueing enabled
ada0: 114473MB (234441648 512 byte sectors)
```

```
[terry@thepaintrain] ~/Desktop% ls /dev/ada*
/dev/ada0   /dev/ada0s1 /dev/ada0s2 /dev/ada0s3 /dev/ada1   /dev/ada1p1 /dev/ada1p2 /dev/ada1p3
```

```
[terry@thepaintrain] ~/Desktop% camcontrol devlist
<KINGSTON SHFS37A120G 580ABBF0>    at scbus0 target 0 lun 0 (pass0,ada0)
<TS128GMTS400 O0918B>              at scbus1 target 0 lun 0 (pass1,ada1)
```

```
[terry@thepaintrain] ~/Desktop% gpart show
=>       63  234441585  ada0  MBR  (112G)
         63       1985        - free -  (993K)
       2048     204800     1  ntfs  [active]  (100M)
     206848  233308160     2  ntfs  (111G)
  233515008     921600     3  !39  (450M)
  234436608       5040        - free -  (2.5M)

=>       40  250069600  ada1  GPT  (119G)
         40        512     1  freebsd-boot  (256K)
        552  241649664     2  freebsd-zfs  (115G)
  241650216    8388608     3  freebsd-swap  (4.0G)
  250038824      30816        - free -  (15M)
```

Double clicking on the Icon on the desktop gives me the following error:
`Application entry is invalid: /media/da0p2.desktop
`
```
[terry@thepaintrain] /media% more da0p2.desktop
[Desktop Entry]                                                                   
Version=1.1                                                                       
Type=Dir                                                                          
Name=NO_NAME                                                                      
GenericName=da0p2 - msdosfs                                                       
Comment=da0p2 - msdosfs                                                           
Icon=drive-removable-media-usb-pendrive                                           
Path=/autofs/da0p2
```
I thought automounter would ignore internal drives, but it appears to be trying to do something.  I do not have any 'da' devices on my laptop, there is no 'da0' device.  I only have ada0 and ada1.  I have no external drives plugged in.

**Comment by grahamperrin** [comment]
> … no 'da0' … no external …

From https://github.com/trueos/trueos-core/issues/357#issue-212179484 (2017-03-06): 

>> … be prepared to remove the debris in `/media/` and/or the mount point debris. …

– AFAIR (I did not report all cases) the debris occurred in a variety of situations.
