### ISSUE TITLE
Install fails as a VM

### ISSUE THREAD

**Issue by brunoomartin** [trueos/trueos-core#381]
Hello,

I wanted to test TrueOS first as a VM. Downloaded TrueOS-Desktop-2017-03-31-x64-DVD.iso.
Tried to install on a Mac running 10.12.4 with VMware Fusion 8.5.6 (see screen).
Installer is never launched. Boot stops after bringing up the network.
Also tried with VirtualBox with the instructions from TrueOS webpage. Boot also stops (a bit further).
Thanks,

![trueos](https://cloud.githubusercontent.com/assets/21077839/24794437/f468e9d4-1b85-11e7-806b-ceee5d8b3610.png)

**Comment by iSiek** [comment]
I had exactly the same issue. I could resolve it by myself.
In network card specification, expand advance node and from dropdown list select virtio-net network card type.
Save changes and restart installation, now you should be good but...
... I have then another issue. Cannot start graphical installation, VBox gets panic and stops working all the time.

When I chose text installation it is installing but then after reboot the same issue. Looks like VBox or TrueOS cannot handle graphic card at all :|

Regards,
Krzysztof

**Comment by Mrt134** [comment]
This appears resolved in the last STABLE release.
