### ISSUE TITLE
Nvidia binary driver no longer works after update

### ISSUE THREAD

**Issue by gallatin** [trueos/trueos-core#382]
After the latest update, the nvidia driver (nvidia-driver-375.26_1) no longer autoconfigures.  To get X to work, I was forced to 

a) move aside a bad  /etc/X11/xorg.conf that some package had created
b) create a  /usr/local/etc/X11/xorg.conf.d/driver-nvidia.conf with the contents
Section "Device"
	Identifier "Card0"
	Driver     "nvidia"
	# BusID    "PCI:1:0:0"
EndSection

Without step (b), the nv driver tries to control the Nvidia card, but fails, as it does not support the Nvidia card that I have.

**Comment by Mrt134** [comment]
We've made a number of fixes to video drivers since this issue was opened, which appears to have resolved this issue. Please reopen or make a new issue if this is still a problem. Thanks!
