### ISSUE TITLE
WLAN-manager does not work correctly

### ISSUE THREAD

**Issue by nielsk** [trueos/trueos-core#384]
When I started to use TrueOS a couple of days ago I tried to use the wlan-manager.
It didn't see any WLANs. Then I created my own wpa_supplicant.conf and I got connected. I looked into the wlan-manager and suddenly it saw networks but when I tried to start using it, wlan stopped working again. 
When I removed the following line:
`ctrl_interface=/var/run/wpa_supplicant`
from the wpa_supplicant.conf and restarted the network-service wlan worked again.

**Comment by Mrt134** [comment]
I believe this and https://github.com/trueos/trueos-core/issues/398 are related - has this been fixed in recent patches, or is this still an issue?

**Comment by nielsk** [comment]
This works now for me

**Comment by Mrt134** [comment]
Great, thanks for the update!
