### ISSUE TITLE
"ƔETRƆ ga" unknown text displayed next to taskbar clock.

### ISSUE THREAD

**Issue by ahtotaat** [trueos/trueos-core#388]
Got "ƔETRƆ ga 11:30" displayed on the taskbar clock (Lumina). I used the google extensively and finally found out it does mean "afternoon" in some Nigeri-Congo dialect (Ewe).

Also, clicking on the clock, would open up calendar with incomprehensible abbreviations designating days of week.

Lumina's "Preferences" is showing "Afrikaans (af)" for some reason.

I tried to change Lumina's localization settings under "Desktop settings" to "eesti" but it did not solve the issue (I restarted the system). Language/Messages/Time settings were properly saved as "eesti" (but had no visible effect as "ƔETRƆ ga" did not disappear) on the but rest of the settings (Numeric/Monetary/Collate/Ctype) reverted back to "System defaults" after restart.

I initially selected "Eesti keel" in the TrueOS installer (Estonian language).

EDIT: dug around some more, noticed PCDM showing "ee_GH" keyboard layout as selected in the botton left corner. After I changed it for "et_EE" and tried logging into Lumina, I noticed problem gone and also proper abbreviations being displayed in the calendar.

**Comment by Mrt134** [comment]
It appears this issue is resolved, so I'm going to close. Thanks for the report!

**Comment by ahtotaat** [comment]
It is 'resolved' only when user consciously notices wrong locale in PCDM and elects to change it manually. If he/she doesn't, it would still be there, confusing the fu** out of him/her -> because by default, PCDM still  is offering completely wrong locale after installation (checked it with last TrueOS UNSTABLE)
