### ISSUE TITLE
Bridges with vlan members don't pass traffic

### ISSUE THREAD

**Issue by clinta** [trueos/trueos-core#389]
This is an open bug in FreeBSD: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=208910

It was patched for a time in FreeNAS with this [commit](https://github.com/freenas/os/commit/ec62a3c76f3dbec0f9911738d103d3a744ed71e4), but that commit never made it into FreeBSD and discussion on the issue has been stalled for about a year.

I'm opening this issue to request that this commit be merged into TrueOS so that vnet jails and bhyve vm's can be isolated into separate vlans.

**Comment by q5sys** [comment]
Since we primarily pull from FreeBSD and want to stay in line with them as much as possible, please try to follow up with upstream on this issue.  I'll let Kris or Joe decide if we want to go ahead and pull this change in ahead of FreeBSD doing so... so I wont close this ticket.

**Comment by Mrt134** [comment]
I believe the preference (at this time) is to stay in closer sync with FreeBSD.
