### ISSUE TITLE
TrueOS Disk Wizard: N underlined on the 'Next' button but Alt-N does not take the user to the next screen

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#39]
1. [*] check the box for ZFS pool name 
2. type a name and observe the underlined N of Next
3. Alt-N

**Expected**

The next screen.

**Actual result**

n is appended to the name

**Comment by kmoore134** [comment]
That's kinda a Qt thing. Since your pool box has focus, it gets the key event by default. If you hit "tab" first and get out of a text-input box, it should re-enable alt-N
