### ISSUE TITLE
fresh install with nvidia hardware hangs at pcdm launch

### ISSUE THREAD

**Issue by tkoham** [trueos/trueos-core#392]
Working with a gtx 1070, most recent .img. Verified md5, installer detects and installs nvidia correctly, but the first boot fails and hangs after openrc checklist

**Comment by Mrt134** [comment]
Many apologies for the late response - could we get an update if this is still an issue with the latest version?

**Comment by Mrt134** [comment]
Closed for inactivity. Please comment or reopen if this is still an issue. Thanks!
