### ISSUE TITLE
Old logo PC-BSD in installed system after reboot

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/trueos-core#394]
Old logo "PC-BSD" in installed system after reboot. May be at modern systems this is invisible, but on Intel Atom N2830 (slow CPU) I see old logo PC-BSD after install TrueOS and reboot before configured OS for a few seconds.

**Comment by q5sys** [comment]
We had a report of something similar a while back regarding PCBSD graphics, but I thought we resolved it. What's the date on the install image you used?

**Comment by DmitryPostolov** [comment]
Latest at this time 2017-03-31.

**Comment by DmitryPostolov** [comment]
3 problems with my Intel NUC 2820 and TrueOS on this video. Its recommended to download video and watch it in video-player, but dont watch online.

https://yadi.sk/i/s_gKTkA63H6NkB

1. PC-BSD old logo after first reboot after installation OS and before configured OS (before English setting of language).
2. rEFInd shows screen as "zebra". Only one or two times rEFInd shows correct screen with Beastie Logo.
3. 15-Seconds PAUSE on EFI booting process.

**Comment by RodMyers** [comment]
i think Ken fixed the PC-BSD logo flashing on first reboot last week. installed on his older Asus laptop, and we saw it flash by really quick

**Comment by DmitryPostolov** [comment]
Yes, it was fixed.
