### ISSUE TITLE
error in installation time (Ошибка во время установки)

### ISSUE THREAD

**Issue by ZloyHohol** [trueos/trueos-core#395]
Hello, I am owner of notebook HP 255 g4 (l8b85es). I cannot install OS from image: TrueOS-Desktop-2017-03-31-x64-USB.img. In installation time i had troubles... pre-installation process had crashed... I was trying install with EFI mode and without efi mode. installation flash drive I made with: dd method, and GUI program of writting instalation image ROSA image writer.

Original text: "Я владелец ноутбука HP 255 g4 (l8b85es). Я не могу установить ОС с образа: TrueOS-Desktop-2017-03-31-x64-USB.img. Во время установки у меня были проблемы ... был прерван процесс установки ... Я пытался установить с режимом EFI и без режима efi. Установочный флеш-диск, сделанный с помощью: dd-метода, и графической программы для создания образа установки ROSA-image-writer"

please look on these photos and video: https://yadi.sk/d/x8B27CyS3H4rCe

P.S.
previous version OS was installed successfully, however from PC-BSD 9 to trueos 11 i was cannot use some devices: wifi and BT on Broadcom (Bcm43142) and WiFi on tp-link tl-wn721n (atheros chip ath9k)... I hope that current or newer releases of OS can be really user-friendly and work with bigger list of user`s devices.
sorry for my english ...

**Comment by DmitryPostolov** [comment]
Are you try change between AHCI and legacy HDD mode in Bios?

Пробовали ли вы переключаться между режимом AHCI и legagy для накопителя в Bios?

**Comment by ZloyHohol** [comment]
"Пробовали ли вы переключаться между режимом AHCI и legacy для накопителя в Bios?"

- в uefi ноутбука hp 255 g4 (l8b85es) нет выбора работы диска ahci/ide, есть только возможность включения bios legacy support(для загрузки систем без поддержки efi) - trueos не устанавливается в режиме uefi и bios legacy(смотрим видео по ссылке)
