### ISSUE TITLE
GPU HANG error during boot on Intel Braswell / Airmont GPU

### ISSUE THREAD

**Issue by danboid** [trueos/trueos-core#396]
I have installed TrueOS-2017-04-21-x64-USB.img on my Gigabyte N3150N-d3v w/ 8GB RAM. I installed into a boot env in my FreeBSD 11 zroot pool. I thought it was very cool that that part of the installation went without a hitch but then when I try to boot TrueOS it hangs with the error in shown in the attached screenshot, which is clearly a GPU/xorg/DRM related error, well above my paygrade.

https://en.wikichip.org/wiki/intel/microarchitectures/airmont

https://en.wikichip.org/wiki/intel/celeron/n3150

Here is the pciconf output from FreeBSD 11 running on the same box:

hostb0@pci0:0:0:0:	class=0x060000 card=0xd0001458 chip=0x22808086 rev=0x21 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Braswell SoC Transaction Router'
    class      = bridge
    subclass   = HOST-PCI
vgapci0@pci0:0:2:0:	class=0x030000 card=0xd0001458 chip=0x22b18086 rev=0x21 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Braswell Integrated Graphics Controller'
    class      = display
    subclass   = VGA
    bar   [10] = type Memory, range 64, base 0x80000000, size 16777216, enabled
    bar   [18] = type Prefetchable Memory, range 64, base 0x90000000, size 268435456, enabled
    bar   [20] = type I/O Port, range 32, base 0xf000, size 64, enabled
ahci0@pci0:0:19:0:	class=0x010601 card=0xb0021458 chip=0x22a38086 rev=0x21 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Braswell SATA Controller'
    class      = mass storage
    subclass   = SATA
    bar   [20] = type I/O Port, range 32, base 0xf060, size 32, enabled
    bar   [24] = type Memory, range 32, base 0x81515000, size 2048, enabled
xhci0@pci0:0:20:0:	class=0x0c0330 card=0x50071458 chip=0x22b58086 rev=0x21 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Braswell USB xHCI Host Controller'
    class      = serial bus
    subclass   = USB
    bar   [10] = type Memory, range 64, base 0x81500000, size 65536, enabled
none0@pci0:0:26:0:	class=0x108000 card=0x1c3a1458 chip=0x22988086 rev=0x21 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Braswell Trusted Execution Engine Interface'
    class      = encrypt/decrypt
    bar   [10] = type Memory, range 32, base 0x81100000, size 1048576, enabled
    bar   [14] = type Memory, range 32, base 0x81000000, size 1048576, enabled
hdac0@pci0:0:27:0:	class=0x040300 card=0xa1821458 chip=0x22848086 rev=0x21 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Braswell HD Audio Controller'
    class      = multimedia
    subclass   = HDA
    bar   [10] = type Memory, range 64, base 0x81510000, size 16384, enabled
pcib1@pci0:0:28:0:	class=0x060400 card=0x50011458 chip=0x22c88086 rev=0x21 hdr=0x01
    vendor     = 'Intel Corporation'
    device     = 'Braswell PCIe Port 1'
    class      = bridge
    subclass   = PCI-PCI
pcib2@pci0:0:28:1:	class=0x060400 card=0x50011458 chip=0x22ca8086 rev=0x21 hdr=0x01
    vendor     = 'Intel Corporation'
    device     = 'Braswell PCIe Port 2'
    class      = bridge
    subclass   = PCI-PCI
pcib3@pci0:0:28:2:	class=0x060400 card=0x50011458 chip=0x22cc8086 rev=0x21 hdr=0x01
    vendor     = 'Intel Corporation'
    device     = 'Braswell PCIe Port 3'
    class      = bridge
    subclass   = PCI-PCI
pcib5@pci0:0:28:3:	class=0x060400 card=0x50011458 chip=0x22ce8086 rev=0x21 hdr=0x01
    vendor     = 'Intel Corporation'
    device     = 'Braswell PCIe Port 4'
    class      = bridge
    subclass   = PCI-PCI
isab0@pci0:0:31:0:	class=0x060100 card=0x50011458 chip=0x229c8086 rev=0x21 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Braswell Platform Controller Unit LPC'
    class      = bridge
    subclass   = PCI-ISA
none1@pci0:0:31:3:	class=0x0c0500 card=0x50011458 chip=0x22928086 rev=0x21 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = 'Braswell Platform Controller Unit SMBus'
    class      = serial bus
    subclass   = SMBus
    bar   [10] = type Memory, range 32, base 0x81514000, size 32, enabled
    bar   [20] = type I/O Port, range 32, base 0xf040, size 32, enabled
re0@pci0:1:0:0:	class=0x020000 card=0xe0001458 chip=0x816810ec rev=0x0c hdr=0x00
    vendor     = 'Realtek Semiconductor Co., Ltd.'
    device     = 'RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller'
    class      = network
    subclass   = ethernet
    bar   [10] = type I/O Port, range 32, base 0xe000, size 256, enabled
    bar   [18] = type Memory, range 64, base 0x81400000, size 4096, enabled
    bar   [20] = type Prefetchable Memory, range 64, base 0xa0100000, size 16384, enabled
re1@pci0:2:0:0:	class=0x020000 card=0xe0001458 chip=0x816810ec rev=0x0c hdr=0x00
    vendor     = 'Realtek Semiconductor Co., Ltd.'
    device     = 'RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller'
    class      = network
    subclass   = ethernet
    bar   [10] = type I/O Port, range 32, base 0xd000, size 256, enabled
    bar   [18] = type Memory, range 64, base 0x81300000, size 4096, enabled
    bar   [20] = type Prefetchable Memory, range 64, base 0xa0000000, size 16384, enabled
pcib4@pci0:3:0:0:	class=0x060400 card=0x118f1b21 chip=0x11821b21 rev=0x00 hdr=0x01
    vendor     = 'ASMedia Technology Inc.'
    class      = bridge
    subclass   = PCI-PCI
ahci1@pci0:5:0:0:	class=0x010601 card=0x10601b21 chip=0x06121b21 rev=0x02 hdr=0x00
    vendor     = 'ASMedia Technology Inc.'
    device     = 'ASM1062 Serial ATA Controller'
    class      = mass storage
    subclass   = SATA
    bar   [10] = type I/O Port, range 32, base 0xc050, size 8, enabled
    bar   [14] = type I/O Port, range 32, base 0xc040, size 4, enabled
    bar   [18] = type I/O Port, range 32, base 0xc030, size 8, enabled
    bar   [1c] = type I/O Port, range 32, base 0xc020, size 4, enabled
    bar   [20] = type I/O Port, range 32, base 0xc000, size 32, enabled
    bar   [24] = type Memory, range 32, base 0x81200000, size 512, enabled
![20170426_230955](https://cloud.githubusercontent.com/assets/1429783/25461429/dfb8fd7a-2ae0-11e7-9874-4f6b9808da3d.jpg)

**Comment by danboid** [comment]
BTW I've tried scfb under FreeBSD but its useless for anyting other than running an xterm or a text editor. I cannot play a video at any resolution with vlc or mpv when using scfb.

**Comment by DmitryPostolov** [comment]
I owner of Intel NUC5PPYH with CPU Intel Braswell N3700. My nettop now in reservation, but when I used it there is also STOP working situation with going to debugger in last releases of TrueOS. Not 2017-04-21 (not tested), but some previous. The error code is unknown, I dont write it. Sorry for my bad English.

**Comment by Mrt134** [comment]
Sorry about the inactivity on this issue! Is this still a problem with the current STABLE and UNSTABLE builds?

**Comment by DmitryPostolov** [comment]
Mrt134, in my case on NUC5PPYH all OK with Intel video driver and scfb video driver on TrueOS current STABLE and UNSTABLE.

**Comment by danboid** [comment]
I currently don't have broadband access but as soon as I have access I shall download the latest ISO and try again on my machine.

**Comment by danboid** [comment]
This issue can be closed as I don't get a crash on boot anymore after installing the latest dev image but there are still a couple of issues with my gpu. The intel, scfb and mode setting drivers all mostly work but vesa doesn't however I'm not really concerned about that as I'll prob only use modesetting.

The issues now are that that the lumina display config tool shows my monitor as HDMI when my mobo only has DVI and it is connected via a DVI cable to a DVI port but the main prob now is that with all the working drivers I cannot choose a res greater than 1920x1080 when connected to my 4k display. Under an older version of trueos I was able to output 4k on this box.

**Comment by Mrt134** [comment]
Ken has been working on the Lumina display config - I don't know if any of that work is available yet, but there should be some improvements on that front soon.

**Comment by beanpole135** [comment]
Yes, the lumina-xconfig utility has had a nearly complete overhaul and functions much better now. If you rebuild Lumina from source you can get it now, otherwise it will be getting pushed out with the next round of updates.

By the same token, don't worry about "vesa" not working. "vesa" is the fallback driver for non-UEFI booted systems, while "scfb" is the fallback driver for UEFI-booted systems. Only one of them is supposed to work for the way the system is setup, not both.
