### ISSUE TITLE
legacy NVidia drivers not included

### ISSUE THREAD

**Issue by clobkowicz** [trueos/trueos-core#397]
On legacy Macbook 5,1 hardware, with NVIDIA GeForce 9400M 256 MB.
Using usb img file, Trueos boots with normal kernel messages (FreeBSD bootsplash, boot menu, kernel messages).
Following error occurs at kernel level before installer launches, and installer launches to a black screen. 
NVRM: "The GeForce 9400M GPU installed is supported by the 340.xx Legacy drivers. Please see ...."
NVRM: "The 379.39 driver will ignore this GPU."
nvidia-modeset : Loading Nevidia Kernel Mode Setting Driver for Unix platforms 375.39"

Similar behaiviour was exhibited on older installers, and the system could only be installed using the text installer or the framebuffer. System would be successfully installed, but no legacy NVidia drivers would be utilized by X, even with digging thru TrueOS handbook, or FreeBSD handbook.

NVidia's website (https://www.nvidia.com/Download/driverResults.aspx/113002/en-us) and it appears NVidia doesn't support FreeBSD-CURRENT with that driverset.

**Comment by beanpole135** [comment]
The 304.x, 340.x, and latest (currently 379.x) NVIDIA drivers are currently included on the TrueOS install media and can be selected as optional install componenets.
