### ISSUE TITLE
Wireless information is wrong and wireless icon is inaccurate

### ISSUE THREAD

**Issue by JoshDW19** [trueos/trueos-core#398]
I'll attach a couple of images here.  The gist of this ticket is that the wireless information on my Lenovo Thinkpad T61 does not show up.  You can see in the image there is no information on wireless strength even though when you are initially selecting a wireless network, that information is available.  Also, the icon is completely misleading.  Notice that when the wireless is not connected, the wireless icon appears to be demonstrating that it has a full and strong connection shown through the multiple waves on the outside of the wireless router icon.  When you connect to a wireless network you can have a very strong connection, but the wireless icon appears to have no signals emitting from it and the top of the antenna appears red.  

Expected Behavior:

Wireless icon changes dynamically based on signal strength and accurately demonstrates when a signal is low or high.
Make sure the information displayed when you hover over the wireless icon is available and accurate.

![wireless2](https://cloud.githubusercontent.com/assets/6586006/25495739/55b2effc-2b4c-11e7-9d23-4ad89ac12d65.jpg)
![wireless](https://cloud.githubusercontent.com/assets/6586006/25495738/55b30cd0-2b4c-11e7-9ccb-2035cf8e68c9.jpg)

**Comment by Mrt134** [comment]
I know there have been some changes on this since the issue was opened, but is the issue fully solved?

**Comment by Mrt134** [comment]
Confirmed fix from related issue.
