### ISSUE TITLE
Distorted Video (Unusable) After Installer Boots on Linux KVM Host

### ISSUE THREAD

**Issue by bsdbox** [trueos/trueos-core#399]
Attempting to install the latest TrueOS release image as of this posting fails due to distorted/unusable graphics after the installer boots.

Host system is Fedora 25 running kernel version 4.10.11-200.fc25.x86_64.

Result is the same using virt-manager or Boxes GUI.

![screenshot_trueos-testing_2017-04-29_19 56 52](https://cloud.githubusercontent.com/assets/8220076/25560187/cc18c836-2d1a-11e7-9d93-45120b91f8ee.png)

**Comment by pkgdemon** [comment]
Known issue unfortunatley.  We recommend virtualbox for TrueOS.
