### ISSUE TITLE
Failed saving config to USB media.

### ISSUE THREAD

**Issue by kmoore134** [trueos/trueos-core#40]
_From @grahamperrin on August 25, 2016 5:48_

> Is the device working and formatted MSDOSFS/FAT32?

Yes. 

Confirmed (at a different computer): 

```
$ gpart show /dev/da1
=>     63  7821249  da1  MBR  (3.7G)
       63  7821198    1  fat32  (3.7G)
  7821261       51       - free -  (26K)

$ sudo mount -t msdosfs /dev/da1s1 /mnt
$ ls -l /mnt
total 8
-rwxr-xr-x  1 root  wheel  1588 24 Aug 09:21 gpart-show-MacBookPro11,2-trueos-2016-08-23.txt
$ sudo umount /dev/da1s1
$ 
```

_Copied from original issue: trueos/pc-sysinstall#13_

**Comment by kmoore134** [comment]
So this doesn't really help me. I need the output / error messages from the script when it runs on install GUI. It should be doing it in an xterm / qterminal now. Does it not pop-up? Does it show an error when it tries mounting /dev/da0s1?

**Comment by grahamperrin** [comment]
I see: 

> Your system is now installed! 
> Click Finish to reboot. After rebooting you may eject the install media. 

(There's no 'Finish' button, but that's a separate issue.)

I click _Save Config to USB_.

A modal dialogue appears, 

> TrueOS Installer
> ? 
> This will save your installation configuration to a MSDOSFS/FAT32 formatted USB stick. Continue? 
> [Yes] [No]

Click _Yes_

Another modal dialogue, 

> TrueOS Installer
> i 
> Please insert a USB stick now, and click OK to continue. 
> [OK]

I insert the drive, then click _OK_

Another modal dialogue, 

> TrueOS Installer
> Please enter the nickname you want to save this configuration as.
> [default]
> [OK] [Cancel]

I click _OK_

Another modal dialogue, 

> TrueOS Installer
> X
> Failed saving config to USB media. Is the device working and formatted MSDOSFS/FAT32?

Yes :-) it is, and no terminal window appears, and sorry for the initially terse report …

**Comment by kmoore134** [comment]
Ok, I've fixed the issue with missing Qterminal window showing output from the script. We'll need to re-test in the next ISO to determine if some other error shows up now.

**Comment by pkgdemon** [comment]
@grahamperrin Can you re-test this with the 08-31-2016 image?

**Comment by grahamperrin** [comment]
Tested 2016-09-09-x64 with two USB flash drives. 

From what I recall of the output (visible in QTerminal), in each case: 

1. mount failed …`da0`
2. the script proceeded to attempt a save to partition 1 of `da0` as if mount had succeeded.

Hmm … da**0** smells not right. I'll watch more closely when I next perform an installation. 

At a different machine running TrueOS Desktop, here's output from `gpart show` for the two devices: 

```
=>     63  7821249  da1  MBR  (3.7G)
       63  7821198    1  fat32  (3.7G)
  7821261       51       - free -  (26K)

=>      1  7814303  da2  MBR  (3.7G)
        1        1       - free -  (512B)
        2  7814302    1  fat32  (3.7G)
```

**Comment by pkgdemon** [comment]
Does gpart show not report anything for /dev/da0?  If you run `ls -la /dev/da*` does that list a /dev/da0 device?  If you run `more /var/log/messages | grep /dev/da0` does that show anything?  I have seen some systems with sd card readers show up as /dev/da0.  I suspect this may be the issue you are seeing as the installer expects /dev/da0.

**Comment by grahamperrin** [comment]
> … At a different machine running TrueOS Desktop … 

I normally use PersonaCrypt with /dev/da0 the first connected USB flash drive, the provider. 

In the opening of this issue I see that mount was performed manually. Re: https://discourse.trueos.org/t/issues-in-github/115/6 I suspect that we'll not resolve this issue (40) until after https://github.com/trueos/pc-mounttray/issues/1 is found/copied/reviewed.

**Comment by pkgdemon** [comment]
I defintley would not install with a personacrypt device also connected.  However this is totally a valid problem in the case an sdcard is picked up as da0 which the user can do nothing easily to disconnect it while installing.  I dont think the mount tray issue is related.  But we could perhaps fixup mounttray, and include it in the installer for mounting the USB to replace the exitsting option which may hardcode /dev/da0.

**Comment by grahamperrin** [comment]
> I defintley would not install with a personacrypt device also connected. 

Sorry, I should have been clearer. The PersonaCrypt device was not connected before, during or after the installation. 

The PersonaCrypt device (_not_ affected by this bug) was simply present when later, after booting a working installation of TrueOS, I used gpart and mount commands to gather information about the _affected_ device(s)

**Comment by grahamperrin** [comment]
TrueOS-Desktop-2016-11-08-x64-USB.img 

Observed in the QTerminal window: 

> mount_msdosfs: /dev/da0: Invalid argument
> Saved config to USB: /dev/da0p1
> Press ENTER to continue

– that is, with a Lexar USB flash drive in the left-hand port of a MacBook Pro, after using a Kingston USB flash drive in the right-hand port to install the OS to the Mac.
