### ISSUE TITLE
Installer TrueOS-Desktop-2016-08-24-x64-USB.img fails to start on Intel Graphics

### ISSUE THREAD

**Issue by d3xter** [trueos/trueos-core#41]
Just tried to run the current Installer-USB-Image on my Samsung Series 9 Ultrabook with an onboard 3rd Gen Intel Graphics card.

It stops at the following error messages:

![img_20160826_000003](https://cloud.githubusercontent.com/assets/159784/17988022/be14b8ee-6b23-11e6-93e3-dbc3ce865030.jpg)

**Comment by pkgdemon** [comment]
We have received confirmation that older chipsets pre SB are known not to be supported by drm-next-4.7. The reason given is "the AGP bits need to be updated to sync up with DRM changes". For an ETA "it's just not that big a priority compared to making SB+ work reasonably well".

**Comment by d3xter** [comment]
3rd Gen Hardware is Ivy Bridge, so its SB+ :D

**Comment by pkgdemon** [comment]
Ah.  Good point.  I had just closed a bulk of G41 tickets with the same canned answer, and accidently took this as pre SB as well.  Please make sure you file something over here about it if you have not.  https://github.com/FreeBSDDesktop/freebsd-base-graphics/issues

**Comment by grahamperrin** [comment]
+1 and FWIW I'd be inclined to make two bug reports (a separate one for the EFI case).
