### ISSUE TITLE
Installation GUI: more clarity around nondestructive installation (reuse of an existing pool); 'Cancel' is not the best word, and so on

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#42]
The routine for this recently added feature includes the following modal dialogue: 

> **Install to existing zpool?**
> The following existing zpool(s) have been found. 
> Do you wish to install fresh into a new BootEnvironment? (This will preserve your $HOME data and other datasets)
> [menu of pools]
> [[OK]] [Cancel]

**Consistency**

Re https://github.com/trueos/sysadm-ui-qt/issues/15 and https://www.illumos.org/issues/5659#note-4 it's proper to use the word _pool_ (not zpool) to describe a pool. And/but see below …

**Plain English/language**

Designed from the ground up for [**ease of use**](https://web.archive.org/web/20160827064235/https://www.trueos.org/downloads/) so let's consider use cases such as –

- a newcomer to PC-BSD making first use of an installer for TrueOS Desktop
- a newcomer to TrueOS Desktop reinstalling the OS, or using a more recent installer

– in such cases, phrases such as _pool_, _tank_, _tank1_, _BootEnvironment_ (one word), _$HOME_ and _datasets_ may be quite alien to the user. 

Generally, the dialogue may be confusing. 

A question in the title bar (to which a Yes/No answer will be appropriate), then a mention of something that follows, then what follows (a different question requiring a Yes/No answer) is not what was mentioned, then an explanation in parentheses, then something in a non-labelled menu, then instead of Yes/No there's OK/Cancel and the untrained user might reasonably expect Cancel to cancel the installation – or cancel the proceedings – but Cancel causes installation to proceed to a different screen. 

The modal dialogue approach is OK for early alpha/beta testing the new nondestructive approach to installation :+1: but I reckon that in addition to improved wording, it will be more user-friendly to **integrate _the question_ and _the menu of pools_ into the underlying interface** (with Back, Next and so on). 

I'll sit on this for a while, maybe play ball with some wording ideas in IRC and https://gitter.im/trueos/Lobby before adding something more constructive to this issue :)

**Comment by kmoore134** [comment]
This issue was moved to trueos/trueos-utils-qt5#7

**Comment by grahamperrin** [comment]
Without reopening this: https://gitter.im/trueos/Lobby?at=5801ee6e457ae29b71dfbd40 recalls that https://github.com/trueos/trueos-utils-qt5/issues/7 included some post-closure comments.
