### ISSUE TITLE
2016-08-31 lumina/fluxbox fails to start because wrong /tmp permissions

### ISSUE THREAD

**Issue by emestee** [trueos/trueos-core#45]
Straight after installing the 31st August release, I couldn't log in because the dbus client wasn't able to open a socket and thus the DE couldn't be launched; as it turned out, +t flag was missing on /tmp.

The sympthom of this issue is the PCDM failing to start a session and returning to login screen immediately.

**Comment by pkgdemon** [comment]
Is this after a fresh install, or an upgrade?

**Comment by emestee** [comment]
A fresh virtualbox install

**Comment by pkgdemon** [comment]
This seems to be working with the TrueOS-Desktop-2016-09-09-x64-DVD.iso.  We don't yet have virtualbox-ose-additions working therefore VESA, and SCFB (efi only) are the only options.  Please let us know if it still persists with the new image, and we can reopen.
