### ISSUE TITLE
Very strange issue with Intel NUC5PPYH & TrueOS/FreeBSD

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/trueos-core#46]
Intel NUC5PPYH. Latest Bios. (and problem with observed with all prev.)

Time to start Bios from Logo to F2.. message is very big, up to minute after to install TrueOS/FreeBSD and reboot. May be this problem in MBR and GPT mode and cooperating NUC & TrueOS/FreeBSD, because on original FreeBSD workaround: MBR HDD mode to fix this problem. Afrer shutdown and poweroff APC filter, and power on APC again all OK until next reboot.

Video: https://yadi.sk/i/VdjH9Uc4unULn

On Linux and DragonFlyBSD problem is not observed.

**Comment by DmitryPostolov** [comment]
I need more testing with installing TrueOS/FreeBSD on combination of MBR/GPT and 512B/4K HDD sector size.

**Comment by grahamperrin** [comment]
>> Video: https://yadi.sk/i/VdjH9Uc4unULn

> The owner may have deleted the file or restricted access to it.
> Or you might have received a link with a typo.

**Comment by DmitryPostolov** [comment]
https://yadi.sk/i/09PbmhWAwtzFU

**Comment by kmoore134** [comment]
Can you re-test this with later ISOs? We've disabled the "lenovofix" option by default that seemed to cause a few systems difficulty.

**Comment by DmitryPostolov** [comment]
I am test now with TrueOS IMG from 2016-10-28 with UEFI boot setting in Bios and by default settings in TrueOS Installer. The problem is NOT solved. :-( But on OpenBSD in UEFI and GPT mode this problem is not observed after reboot/shutdown on NUC5PPYH.

Video for TrueOS and OpenBSD cases. Its recommended to download video file and watch it in Video player, but not watch online.

Video for OpenBSD: https://yadi.sk/i/2m7W9CaRz75mn

Video for TrueOS: https://yadi.sk/i/_xGoMemRz75nT

My (Antarex nickname) message on FreeBSD forums:  https://forums.freebsd.org/threads/49058/ and in this Forum another user (digital_turtle) has reported about NUC5CPYH (analog of 2-Cores of my NUC5PPYH) issue: "I noticed that the Intel NUC POST boot up runs slower after installing FreeBSD (about 1:15 min only to wait until Intel NUC display disappeared [...] but no problem for me since I only used it as headless machine.."

---

Intel TechSupport:

In regard to your inquiry, as you mentioned before, Intel does not test and validate Intel® NUC on FreeBSD OS or TrueOS, as you can confirm on the following link:
 
http://www.intel.com/content/www/us/en/support/boards-and-kits/intel-nuc-boards/000005628.html
 
What we recommend is basically what you did, which is the BIOS update to the latest version.
 
So, in this case, in order to get further assistance to try to fix this issue, the best thing to do will be to access the forums or support department for that __specific__ operating system:
 
https://www.freebsd.org/support.html
 
For testing purposes, if you have the option to use Windows, that will be really helpful, because if the NUC does the same, then it could be related to a hardware problem.
 
Regards, Alberto

---

There no answers at  FreeBSD bugtracker for this ticket at this time. I have not Windows, so I am try OpenBSD (no problem with slow Bios Start on my NUC) and Xubuntu (also no problem with NUC Bios slow starts).

**Comment by grahamperrin** [comment]
@DmitryPostolov re: the 2016-10-28 build at http://download.trueos.org/master/amd64/ it's known that the change of defaults, mentioned by Kris, was not in that build. 

Re: https://builds.ixsystems.com/jenkins/view/Push/ the next 'TrueOS - Push ISO' should be good for testing.

**Comment by DmitryPostolov** [comment]
kmoore134> Can you re-test this with later ISOs? We've disabled the "lenovofix" option by default that seemed to cause a few systems difficulty.

Thanks! This problem is [SOLVED] in TrueOS 2016-12-15.USB Image Do you need video for TrueOS case?
