### ISSUE TITLE
TrueOS boot under kvm hangs 

### ISSUE THREAD

**Issue by berlineddy** [trueos/trueos-core#50]
trying to boot the TrueOS-Desktop-2016-08-31-x64-DVD.iso with qemu-kvm and then select the option **xorg** results in **Xorg Fatal server error**.

![screenshot_trueos_2016-09-05_08 27 19](https://cloud.githubusercontent.com/assets/896504/18271513/c5057734-7432-11e6-928c-2f32d43374a0.png)

The Xorg Server tries to restart several times and after 20-40 seconds this succeeds. During this time it is not possible to interact with the machine and it looks like it hanged.

**Comment by pkgdemon** [comment]
This likely just means we don't have a xf86-video driver that kvm typically looks for.  Have you tried VESA, or SCFB?

**Comment by berlineddy** [comment]
VESA works
SCFB does not work.

Oddly when booting under kvm and tianocore-uefi  VESA does not work but SCFB does. 

So the solution for this issue would be to update the auto-detect :

1. to use the VESA driver (and #54) if it finds the QXL graphics card. 
2. but to use SCFB if QXL and UEFI boot is active.

**Comment by pkgdemon** [comment]
This is fixed as of 09-20-16 with Fedora 24 + KVM.  Redhat video adapter is detected, and either VESA, or SCFB are used.  QXL is not yet supported by FreeBSD.
