### ISSUE TITLE
TrueOS-Desktop-2016-08-31-x64-USB UEFI install on ZFS with GELI encryption unable to boot

### ISSUE THREAD

**Issue by rostwald** [trueos/trueos-core#53]
Trying to install TrueOS Desktop from TrueOS-Desktop-2016-08-31-x64-USB.img with UEFI, ZFS and GELI encryption fails to boot.

Installation was performed using the graphical installer; changing the given preset from ada0 to ada1, enforcing 4k blocks and activating GELI full disk encryption.

After the Reboot the UEFI boot block fires, but only probes for ZFS and UFS:

---

\>> FreeBSD EFI boot block
  Loader path: /boot/loader.efi

  Initializing modules: ZFS UFS
  Probing 9 block devices............ done
    ZFS found no pools
    UFS found no partitions
Failed to load '/boot/loader.efi'
panic: No bootable partitions found!
_

---

Installation without GELI disk encryption "just works".

I'm off during the weekend from tomorrow on, but I can perform some more tests next week if helpful.

**Comment by kmoore134** [comment]
EFI + GELI full-disk isn't supported with BSD loader right now. (Should be in near future). You'll have to use GRUB or not use full-disk encryption.

**Comment by rostwald** [comment]
Maybe a hint on that or even completely preventing to choose this combination would be helpful until it is supported.

**Comment by grahamperrin** [comment]
Side note: upstream, a different bug (different symptom) that, I guess, affects all installations of TrueOS where encryption is chosen at the time of installation: 

- [213491 – gpt{,zfs}boot after r305353 crash in GELIBoot](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213491)
