### ISSUE TITLE
Fresh install (Thinkpad x201) Crash - Sep 11, 2016

### ISSUE THREAD

**Issue by sreiger** [trueos/trueos-core#56]
Completed a fresh install of as of Sep 11, 2016 and after singing into my wifi the setup screen bounced over to this:

![img_3085](https://cloud.githubusercontent.com/assets/10444339/18423120/4bcf13d0-785f-11e6-99ad-a9fb5ff99c98.JPG)

Did a hard shutdown and got the same error again during boot.

System is an Thinkpad x201 running an i5, intel video, and intel network card.

**Comment by pkgdemon** [comment]
Please try our 09-20-16 ISO here.  

http://download.trueos.org/master/amd64/

There may also be a newer ISO posted depending on when you review this.  Let us know if it is still an issue, and I will re-open.
