### ISSUE TITLE
2016-08-31 DVD ISO X11 Installer crashes in VMware Fusion 7.1.3

### ISSUE THREAD

**Issue by pyfbbs** [trueos/trueos-core#58]
I tried to install using the 2016-08-31 DVD ISO but the X11 installer simply rebooted my virtual machine (VMWare Fusion v7.1.3 in FreeBSD 64-bit mode), however the VESA installer worked.

This of course led to me having to manually edit the xorg conf files to use the vmware drivers.

**Comment by pkgdemon** [comment]
I have been testing with vSphere, and the vmware drivers seem to load but the mouse does not work.  After editing xorg.conf are you able to use the vmware drivers?  If so would you mind posting a copy of your config?

**Comment by pyfbbs** [comment]
Here are the changes I made to the Monitor, Screen and Device sections to get it to use VMware DISPLAY drivers. I don't think i'm using the VMware mouse driver, the mouse does work but is strangely "slippery."

http://pastebin.com/UWv6KZSV

![screenshot_3172](https://cloud.githubusercontent.com/assets/4235384/18839411/95e568c4-8413-11e6-86ad-2c8651c6313a.png)

**Comment by pyfbbs** [comment]
FYI,

I added the following section /etc/X11/xorg.conf and the mouse is working far better:

Section "InputDevice"
	Identifier  "Mouse0"
	Driver      "vmmouse"
	Option	    "Protocol" "auto"
	Option	    "Device" "/dev/sysmouse"
	Option	    "ZAxisMapping" "4 5 6 7"
EndSection

I used this as the reference:

http://www.unibia.com/unibianet/freebsd/freebsd-10-vmware-and-xorg

I also set the mouse speed to minimum and everything is working quite well including the mouse integration with the host system.

![screenshot_3189](https://cloud.githubusercontent.com/assets/4235384/18866925/a871db02-84aa-11e6-8ce2-4c137c78c285.png)

**Comment by pkgdemon** [comment]
Nice!  If you could edit this https://github.com/trueos/trueos-core/blob/master/xtrafiles/local/share/trueos/cardDetect/XF86Config.vmware with all of your fixes, and submit a pull request when done I can merge the fixes in to our ISO / packages.

**Comment by pkgdemon** [comment]
@pyfbbs If you can post your full working configuration let me know, and I will commit the needed changes.
