### ISSUE TITLE
CA cert problems with default browser

### ISSUE THREAD

**Issue by pyfbbs** [trueos/trueos-core#59]
There seems to be some problem with the certificate chain shipped with the default web browser (see screenshot, pkgupdate run on 14-SEP-2016).

![screenshot_3084](https://cloud.githubusercontent.com/assets/4235384/18510678/0ab65680-7a88-11e6-9a6e-2e4b46700ca3.png)

**Comment by pkgdemon** [comment]
Unfortunately we need a new version of qupzilla to fix this, and this depends on qtwebengine which cannot be ported at this time.  After numerous discussions we will be shipping Firefox again as our default browser in the upcoming image.

**Comment by pyfbbs** [comment]
Sounds like the right move, I'm using Firefox now that the version in the repos doesn't have the security issue from #60
