### ISSUE TITLE
Problem with mouse in Installer and TrueOS Desktop

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/trueos-core#6]
Hi to all! Sorry for my bad English...
TrueOS Desktop: uname -a: FreeBSD 12.0-CURRENT FreeBSD-12.0-CURRENT #12 2281f25 (drm-next-4.7): Thu Jul 28 19:41:42 UTC 2016 root@devastator: /usr/obj/usr/src/sys/Generic amd64

md5 sum of USB.img is OK. When system is booted then mouse cursor works fine in console, but no mouse cursor in Graphic Installer and Graphic mode after TrueOS is installed and booted. If go to the physical console from Lumina-DE then mouse cursor works fine, but if to return to Graphical mode of Lumina-DE then no mouse cursor again. There is no this problem on TrueOS Desktop USB-Image from 19 Jul 2016.

**Comment by kmoore134** [comment]
Ok, I've done some further digging, and managed to replicate this issue here. This fixed it on my skylake box:

https://github.com/trueos/trueos-core/commit/f5832c3633f03c42b55bb52e5a071e21b234ffe4
