### ISSUE TITLE
pkg audit -F turns up problems with gnutls and Firefox as of 13-SEP-2016

### ISSUE THREAD

**Issue by pyfbbs** [trueos/trueos-core#60]
Please see screenshot for vulnerabilities remaining unpatched as of 13-SEP-2016 despite running full pkgupdate.

![screenshot_3083](https://cloud.githubusercontent.com/assets/4235384/18510737/53020a4c-7a88-11e6-9403-9ae732c7ecba.png)

**Comment by pkgdemon** [comment]
Firefox has been upgraded to 49.  I am no longer seeing CVE's myself.  Please let us know if you see this again.  Thanks.

**Comment by pyfbbs** [comment]
OK, Firefox and gnutls are fine now however curl is listed against a CVE, please see screenshot.

Should I open a new ticket for this?

![screenshot_3171](https://cloud.githubusercontent.com/assets/4235384/18838748/35966790-8411-11e6-8c29-2afefdf62937.png)

**Comment by pkgdemon** [comment]
I have verified the curl CVE will be fixed in this weeks package push.  Most likely it will land tomorrow at the latest.

**Comment by pyfbbs** [comment]
Cool, just thought I'd let you know.
