### ISSUE TITLE
Libreoffice will not start after update

### ISSUE THREAD

**Issue by RodMyers** [trueos/trueos-core#62]
from the shell, I get

/usr/local/lib/libreoffice/program/soffice
/usr/local/lib/libreoffice/program/oosplash: Undefined symbol "dirname"

**Comment by pkgdemon** [comment]
Is this with a personacrypt device attached?  I have noticed this as well, and I had to use openoffice.  I've been able to use libreoffice for other setups without the personacrypt device attached.

**Comment by RodMyers** [comment]
negative. it's on a grey box downstairs that is having trouble updating. I removed libreoffice and upgraded it. I did the same nano. it has the same issue as well

**Comment by pkgdemon** [comment]
When you updated did you use ```pkg upgrade```?  Or ```pc-updatemanager pkgupdate```?

**Comment by RodMyers** [comment]
always do a "pc-updatemanager pkguodate"

though in the upgrade(s) of the past week or so, and a lumina upgrade, it works on the laptop and gray box now

**Comment by pkgdemon** [comment]
Nice.  We did have some GTK breakage we fixed something on the build server which in turn fixed many ports building as well.  I will close for now.  Let us know if it breaks again.
