### ISSUE TITLE
building wireshark fails

### ISSUE THREAD

**Issue by zhunsaker** [trueos/trueos-core#63]
When I attempt to build a port using make (trying wireshark and wireshark-qt5) I get the following error

You are using openssl from ports and have selected GSSAPI from base please select another GSSAPI value

***Error code 1

Any reason we can't have wireshark available in app cafe? is there a setting I can change that will let this build properly? As far as I know I haven't changed anything, this is a fresh install as of today.  Sep 18 2016. I don't know much, but i'd be willing to help in any way that I can.

**Comment by kmoore134** [comment]
This is fixed now:

https://builds.ixsystems.com/guantlet/build.html?mastername=master-trueosports&build=2016-09-19_16h18m15s

We should have it in the next set of packages in 24-48 hours or so.
