### ISSUE TITLE
TrueOS Desktop first boot onwards - blank display on X launch Ctrl Alt F1/2 doesn't recover.

### ISSUE THREAD

**Issue by TrueBSD** [trueos/trueos-core#67]
This is a laptop with no LVDS (LCD) panel but PC-BSD 10.3 & 11.0-CURRENT install & X11 works on the VGA port set in the BIOS as default. 

Current ISO: TrueOS-Desktop-2016-09-20-x64-DVD.iso
FreeBSD 12.0-CURRENT #8 a212210(drm-next-4.7): Tue Sep  6 12:20:35 UTC 2016

The VT driver successfully transitions from VGA to FB the console text is redrawn in the native display resolution with the mouse pointer. X attempts to start & the display blanks & the monitor transitions to power save

I have retrieved the logs by booting to singleuser & then carried out the necessary ZFS/network steps to access the logs & scp them off. I second the request for the return of the boot to console - or some scripts to take the user from single user to multi-user without X. Anyhow hopefully relevant log sections follow:
[logs.zip](https://github.com/trueos/trueos-core/files/496051/logs.zip)

Sep 27 14:58:03 trueos-1952 kernel: [drm] Initialized drm 1.1.0 20060810
Sep 27 14:58:03 trueos-1952 kernel: drmn0: <drmn> on vgapci0
Sep 27 14:58:03 trueos-1952 kernel: vgapci0: child drmn0 requested pci_enable_io
Sep 27 14:58:03 trueos-1952 kernel: vgapci0: child drmn0 requested pci_enable_io
Sep 27 14:58:03 trueos-1952 kernel: [drm] Memory usable by graphics device = 2048M
Sep 27 14:58:03 trueos-1952 kernel: [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
Sep 27 14:58:03 trueos-1952 kernel: [drm] Driver supports precise vblank timestamp query.
Sep 27 14:58:03 trueos-1952 kernel: [drm] Connector LVDS-1: get mode from tunables:
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.modes.LVDS-1
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.default_mode
Sep 27 14:58:03 trueos-1952 kernel: [drm] Connector VGA-1: get mode from tunables:
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.modes.VGA-1
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.default_mode
Sep 27 14:58:03 trueos-1952 kernel: [drm] Connector HDMI-A-1: get mode from tunables:
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.modes.HDMI-A-1
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.default_mode
Sep 27 14:58:03 trueos-1952 kernel: [drm] Connector DP-1: get mode from tunables:
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.modes.DP-1
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.default_mode
Sep 27 14:58:03 trueos-1952 kernel: [drm] Connector HDMI-A-2: get mode from tunables:
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.modes.HDMI-A-2
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.default_mode
Sep 27 14:58:03 trueos-1952 kernel: [drm] Connector HDMI-A-3: get mode from tunables:
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.modes.HDMI-A-3
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.default_mode
Sep 27 14:58:03 trueos-1952 kernel: [drm] Connector DP-2: get mode from tunables:
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.modes.DP-2
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.default_mode
Sep 27 14:58:03 trueos-1952 kernel: [drm] Connector DP-3: get mode from tunables:
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.modes.DP-3
Sep 27 14:58:03 trueos-1952 kernel: [drm]   - kern.vt.fb.default_mode
Sep 27 14:58:03 trueos-1952 kernel: [drm:0xffffffff828c1c40s] *ERROR* RC6 residency sysfs setup failed
Sep 27 14:58:03 trueos-1952 kernel: [drm:0xffffffff828c1c7ds] *ERROR* RC6p residency sysfs setup failed
Sep 27 14:58:03 trueos-1952 kernel: [drm] Initialized i915 1.6.0 20160425 for drmn on minor 0
Sep 27 14:58:03 trueos-1952 kernel: VT: Replacing driver "vga" with new "fb".
Sep 27 14:58:03 trueos-1952 kernel: start FB_INFO:
Sep 27 14:58:03 trueos-1952 kernel: type=11 height=768 width=1024 depth=32
Sep 27 14:58:03 trueos-1952 kernel: cmsize=16 size=7680000
Sep 27 14:58:03 trueos-1952 kernel: pbase=0xe0065000 vbase=0xfffff800e0065000
Sep 27 14:58:03 trueos-1952 kernel: name=drmn0 flags=0x0 stride=6400 bpp=32
Sep 27 14:58:03 trueos-1952 kernel: cmap[0]=0 cmap[1]=7f0000 cmap[2]=7f00 cmap[3]=c4a000
Sep 27 14:58:03 trueos-1952 kernel: end FB_INFO
Sep 27 14:58:03 trueos-1952 kernel: drmn0: fb0: inteldrmfb frame buffer device
Sep 27 14:58:25 trueos-1952 kernel: [drm:0xffffffff8290f80as] *ERROR* uncleared pch fifo underrun on pch transcoder B
Sep 27 14:58:25 trueos-1952 kernel: [drm:0xffffffff828c0cdas] *ERROR* PCH transcoder B FIFO underrun
Sep 27 14:58:44 trueos-1952 kernel: [drm:0xffffffff8290f555s] *ERROR* uncleared fifo underrun on pipe A
Sep 27 14:58:44 trueos-1952 kernel: [drm:0xffffffff828bca45s] *ERROR* CPU pipe A FIFO underrun
Sep 27 15:00:05 trueos-1952 kernel: , 1097.
Sep 27 15:00:05 trueos-1952 kernel: .
Sep 27 15:00:05 trueos-1952 root: /etc/rc.shutdown: WARNING: $powerdxx_enable is not set properly - see rc.conf(5).

Ctrl Alt Del from Ctrl Alt F1 enables a graceful shutdown,

Xorg.0.log:
[    53.028] Current Operating System: FreeBSD trueos-1952 12.0-CURRENT FreeBSD 12.0-CURRENT #8 a212210(drm-next-4.7): Tue Sep  6 12:20:35 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC amd64
[    53.070] (II) VESA(0): initializing int10
[    53.071] (II) VESA(0): Bad V_BIOS checksum
[    53.072] (II) VESA(0): Primary V_BIOS segment is: 0xc000
[    53.073] (II) VESA(0): VESA BIOS detected
[    53.073] (II) VESA(0): VESA VBE Version 3.0
[    53.073] (II) VESA(0): VESA VBE Total Mem: 65472 kB
[    53.073] (II) VESA(0): VESA VBE OEM: Intel(R) Sandybridge/Ivybridge Graphics Chipset Accelerated VGA BIOS
[    53.073] (II) VESA(0): VESA VBE OEM Software Rev: 1.0
[    53.073] (II) VESA(0): VESA VBE OEM Vendor: Intel Corporation
[    53.073] (II) VESA(0): VESA VBE OEM Product: Intel(R) Sandybridge/Ivybridge Graphics Controller
[    53.089] (II) LoadModule: "ddc"
[    53.089] (II) Module "ddc" already built-in
[    53.205] (II) VESA(0): VESA VBE DDC supported
[    53.205] (II) VESA(0): VESA VBE DDC Level 2
[    53.205] (II) VESA(0): VESA VBE DDC transfer in appr. 1 sec.
[    53.218] (II) VESA(0): VESA VBE DDC read successfully
[    53.219] (II) VESA(0): Manufacturer: SAM  Model: 1ad  Serial#: 1112683056
[    53.219] (II) VESA(0): Year: 2006  Week: 33
[    53.219] (II) VESA(0): EDID Version: 1.3
[    53.219] (II) VESA(0): Analog Display Input,  Input Voltage Level: 0.700/0.300 V
[    53.219] (II) VESA(0): Sync:  Separate  Composite  SyncOnGreen
[    53.219] (II) VESA(0): Max Image Size [cm]: horiz.: 41  vert.: 31
[    53.219] (II) VESA(0): Gamma: 2.20
[    53.219] (II) VESA(0): DPMS capabilities: Off; RGB/Color Display
[    53.219] (II) VESA(0): First detailed timing is preferred mode
[    53.219] (II) VESA(0): redX: 0.640 redY: 0.330   greenX: 0.300 greenY: 0.600
[    53.219] (II) VESA(0): blueX: 0.150 blueY: 0.060   whiteX: 0.313 whiteY: 0.329
[    53.219] (II) VESA(0): Supported established timings:
[    53.219] (II) VESA(0): 720x400@70Hz
[    53.219] (II) VESA(0): 640x480@60Hz
[    53.219] (II) VESA(0): 640x480@67Hz
[    53.219] (II) VESA(0): 640x480@72Hz
[    53.220] (II) VESA(0): 640x480@75Hz
[    53.220] (II) VESA(0): 800x600@56Hz
[    53.220] (II) VESA(0): 800x600@60Hz
[    53.220] (II) VESA(0): 800x600@72Hz
[    53.220] (II) VESA(0): 800x600@75Hz
[    53.220] (II) VESA(0): 832x624@75Hz
[    53.220] (II) VESA(0): 1024x768@60Hz
[    53.220] (II) VESA(0): 1024x768@70Hz
[    53.220] (II) VESA(0): 1024x768@75Hz
[    53.220] (II) VESA(0): 1280x1024@75Hz
[    53.220] (II) VESA(0): 1152x864@75Hz
[    53.220] (II) VESA(0): Manufacturer's mask: 0
[    53.220] (II) VESA(0): Supported standard timings:
[    53.220] (II) VESA(0): #0: hsize: 1600  vsize 1200  refresh: 60  vid: 16553
[    53.220] (II) VESA(0): #1: hsize: 1280  vsize 1024  refresh: 60  vid: 32897
[    53.220] (II) VESA(0): #2: hsize: 1280  vsize 960  refresh: 60  vid: 16513
[    53.220] (II) VESA(0): #3: hsize: 1152  vsize 864  refresh: 75  vid: 20337
[    53.220] (II) VESA(0): Supported detailed timing:
[    53.220] (II) VESA(0): clock: 162.0 MHz   Image Size:  408 x 306 mm
[    53.220] (II) VESA(0): h_active: 1600  h_sync: 1664  h_sync_end 1856 h_blank_end 2160 h_border: 0
[    53.220] (II) VESA(0): v_active: 1200  v_sync: 1201  v_sync_end 1204 v_blanking: 1250 v_border: 0
[    53.220] (II) VESA(0): Ranges: V min: 56 V max: 75 Hz, H min: 30 H max: 81 kHz, PixClock max 175 MHz
[    53.220] (II) VESA(0): Monitor name: SyncMaster
[    53.220] (II) VESA(0): Serial No: HSHL805896
[    53.220] (II) VESA(0): EDID (in hex):
[    53.220] (II) VESA(0): 	00ffffffffffff004c2dad0130325242
[    53.221] (II) VESA(0): 	211001030e291f782aee95a3544c9926
[    53.221] (II) VESA(0): 	0f5054bfef80a94081808140714f0101
[    53.221] (II) VESA(0): 	010101010101483f403062b0324040c0
[    53.221] (II) VESA(0): 	130098321100001e000000fd00384b1e
[    53.221] (II) VESA(0): 	5111000a202020202020000000fc0053
[    53.221] (II) VESA(0): 	796e634d61737465720a2020000000ff
[    53.221] (II) VESA(0): 	004853484c3830353839360a20200087
[    53.221] (II) VESA(0): EDID vendor "SAM", prod id 429
[    53.221] (II) VESA(0): Using hsync ranges from config file
[    53.221] (II) VESA(0): Using vrefresh ranges from config file
[    53.221] (II) VESA(0): Printing DDC gathered Modelines:
[    53.221] (II) VESA(0): Modeline "1600x1200"x0.0  162.00  1600 1664 1856 2160  1200 1201 1204 1250 +hsync +vsync (75.0 kHz eP)
[    53.221] (II) VESA(0): Modeline "800x600"x0.0   40.00  800 840 968 1056  600 601 605 628 +hsync +vsync (37.9 kHz e)
[    53.221] (II) VESA(0): Modeline "800x600"x0.0   36.00  800 824 896 1024  600 601 603 625 +hsync +vsync (35.2 kHz e)
[    53.221] (II) VESA(0): Modeline "640x480"x0.0   31.50  640 656 720 840  480 481 484 500 -hsync -vsync (37.5 kHz e)
[    53.221] (II) VESA(0): Modeline "640x480"x0.0   31.50  640 664 704 832  480 489 492 520 -hsync -vsync (37.9 kHz e)
[    53.221] (II) VESA(0): Modeline "640x480"x0.0   30.24  640 704 768 864  480 483 486 525 -hsync -vsync (35.0 kHz e)
[    53.221] (II) VESA(0): Modeline "640x480"x0.0   25.18  640 656 752 800  480 490 492 525 -hsync -vsync (31.5 kHz e)
[    53.221] (II) VESA(0): Modeline "720x400"x0.0   28.32  720 738 846 900  400 412 414 449 -hsync +vsync (31.5 kHz e)
[    53.222] (II) VESA(0): Modeline "1280x1024"x0.0  135.00  1280 1296 1440 1688  1024 1025 1028 1066 +hsync +vsync (80.0 kHz e)
[    53.222] (II) VESA(0): Modeline "1024x768"x0.0   78.75  1024 1040 1136 1312  768 769 772 800 +hsync +vsync (60.0 kHz e)
[    53.222] (II) VESA(0): Modeline "1024x768"x0.0   75.00  1024 1048 1184 1328  768 771 777 806 -hsync -vsync (56.5 kHz e)
[    53.222] (II) VESA(0): Modeline "1024x768"x0.0   65.00  1024 1048 1184 1344  768 771 777 806 -hsync -vsync (48.4 kHz e)
[    53.222] (II) VESA(0): Modeline "832x624"x0.0   57.28  832 864 928 1152  624 625 628 667 -hsync -vsync (49.7 kHz e)
[    53.222] (II) VESA(0): Modeline "800x600"x0.0   49.50  800 816 896 1056  600 601 604 625 +hsync +vsync (46.9 kHz e)
[    53.222] (II) VESA(0): Modeline "800x600"x0.0   50.00  800 856 976 1040  600 637 643 666 +hsync +vsync (48.1 kHz e)
[    53.222] (II) VESA(0): Modeline "1152x864"x0.0  108.00  1152 1216 1344 1600  864 865 868 900 +hsync +vsync (67.5 kHz e)
[    53.222] (II) VESA(0): Modeline "1280x1024"x0.0  108.00  1280 1328 1440 1688  1024 1025 1028 1066 +hsync +vsync (64.0 kHz e)
[    53.222] (II) VESA(0): Modeline "1280x960"x0.0  108.00  1280 1376 1488 1800  960 961 964 1000 +hsync +vsync (60.0 kHz e)
[    53.222] (II) VESA(0): Searching for matching VESA mode(s):
[    53.291] (II) VESA(0): Total Memory: 1023 64KB banks (65472kB)
[    53.291] (II) VESA(0): Monitor0: Using hsync range of 28.00-78.00 kHz
[    53.291] (II) VESA(0): Monitor0: Using vrefresh range of 50.00-76.00 Hz
[    53.291] (II) VESA(0): Monitor0: Using maximum pixel clock of 175.00 MHz
[    53.291] (II) VESA(0): Not using built-in mode "1600x1200" (width too large for virtual size)
[    53.292] (II) VESA(0): Not using built-in mode "1280x1024" (width too large for virtual size)
[    53.293] (--) VESA(0): Virtual size is 1024x768 (pitch 1024)
[    53.293] (**) VESA(0): *Built-in mode "1024x768"
[    53.293] (**) VESA(0):  Built-in mode "1024x768"
[    53.294] (**) VESA(0):  Built-in mode "800x600"
[    53.294] (**) VESA(0):  Built-in mode "640x480"
[    53.294] (**) VESA(0): Display dimensions: (410, 310) mm
[    53.294] (**) VESA(0): DPI set to (63, 62)
[    53.294] (**) VESA(0): Using "Shadow Framebuffer"
[    53.294] (II) Loading sub module "shadow"
[    53.294] (II) LoadModule: "shadow"
[    53.294] (II) Loading /usr/local/lib/xorg/modules/libshadow.so

[    53.299] (II) VESA(0): initializing int10
[    53.300] (II) VESA(0): Bad V_BIOS checksum
[    53.300] (II) VESA(0): Primary V_BIOS segment is: 0xc000
[    53.301] (II) VESA(0): VESA BIOS detected
[    53.301] (II) VESA(0): VESA VBE Version 3.0
[    53.301] (II) VESA(0): VESA VBE Total Mem: 65472 kB
[    53.301] (II) VESA(0): VESA VBE OEM: Intel(R) Sandybridge/Ivybridge Graphics Chipset Accelerated VGA BIOS
[    53.301] (II) VESA(0): VESA VBE OEM Software Rev: 1.0
[    53.301] (II) VESA(0): VESA VBE OEM Vendor: Intel Corporation
[    53.301] (II) VESA(0): VESA VBE OEM Product: Intel(R) Sandybridge/Ivybridge Graphics Controller
[    53.301] (II) VESA(0): VESA VBE OEM Product Rev: Hardware Version 0.0
[    53.301] (II) VESA(0): virtual address = 0x807e00000,
	physical address = 0xe0000000, size = 67043328
[    53.311] (II) VESA(0): Setting up VESA Mode 0x117 (1024x768)
[    53.412] (==) VESA(0): Default visual is TrueColor
[    53.414] (==) VESA(0): Backing store enabled
[    53.415] (==) VESA(0): DPMS enabled
[    53.415] (==) RandR enabled
[    53.417] (II) AIGLX: Screen 0 is not DRI2 capable
[    53.417] (EE) AIGLX: reverting to software rendering
[    54.074] (II) AIGLX: enabled GLX_MESA_copy_sub_buffer
[    54.075] (II) AIGLX: Loaded and initialized swrast
[    54.075] (II) GLX: Initialized DRISWRAST GL provider for screen 0

[    54.208] (II) config/devd: device /dev/psm0 already opened
[   155.135] (WW) config/devd: devd socket is lost
[   155.136] (EE) config/devd: fail to connect to devd
[   155.200] (II) config/devd: terminating backend...
[   155.202] (II) UnloadModule: "mouse"
[   155.202] (II) UnloadModule: "kbd"
[   155.225] (II) Server terminated successfully (0). Closing log file.

**Comment by TrueBSD** [comment]
I've done some debugging & worked a few things out. The Xorg log is obviously showing that the vesa driver is active for X. Which is odd. Since the log shows the DDE identification of the monitor, I wondered what would happen if I unplugged the VGA for the boot & then re-attached it once X would have launched? Result a weirdly partially off-screen 1024x768 PCDM, with the lower part of the screen showing a static random screen corruption. But I can login & then have a similar experience in Lumina.

**Comment by TrueBSD** [comment]
I noticed the backup xorg.conf in /etc/X11/ that the installer switched from after the first-run failed to be able to complete the configuration. So I reverted to that & rebooted.
Result fullscreen 1600x1200 X with a distorted TrueOS logo & no visible PCDM.
I guessed that the PCDM was running but off-screen for some reason so tried typing the password blind & Lumina initialised but scaled incorrectly, using only part of the screen. I can now switch to ttyv0 but only 48 lines are displayed - the same area that the attached images would indicate.
I have found a way to make a somewhat usable Lumina desktop by adding VGA1 & removing the ghostly LVDS1:
![1](https://cloud.githubusercontent.com/assets/22476758/18931488/58fa3220-85c4-11e6-8ef9-dac3ad18b8d3.png)
![2](https://cloud.githubusercontent.com/assets/22476758/18931511/74ae7fbc-85c4-11e6-9e5d-446682845370.png)
![3](https://cloud.githubusercontent.com/assets/22476758/18931515/7704f732-85c4-11e6-984c-4b12ed6d4fcd.png)
![4](https://cloud.githubusercontent.com/assets/22476758/18931520/7bca332c-85c4-11e6-9d63-7cdaa4b829b2.png)
![5](https://cloud.githubusercontent.com/assets/22476758/18931525/7e945204-85c4-11e6-8f5a-443a881d0c51.png)

**Comment by pkgdemon** [comment]
Which driver option did you choose?  Autodetect?  Or legacy intel?  It looks like you might be using intel due to the black QT apps.  You might try copying over this file https://github.com/trueos/trueos-core/blob/master/xtrafiles/local/share/trueos/cardDetect/XF86Config.modesetting to ```/etc/X11/xorg.conf```, and restart.  It should be present on your system under ```/usr/local/share/trueos/cardDetect``` after install.

**Comment by TrueBSD** [comment]
Thanks Joe, to be honest I think I had a tussle to get enough of the installer ISO functional.
I started with setting the BIOS to EFI first, which just hung - not booting anything & an unmemorable error.
I switched back to Legacy BIOS first & had fragments of screens with a nasty Floyd-Steinberg like dither pattern & no dialogues, nor means to move elements that I suspected were there but rendered off-screen.
I definitely tried different Intels & VESA.
Is it possible to change the default TrueOS backdrops to ones that are flat - low in memory & easy to screenshot/png compress using your screenshot app? Might make the debug images more portable. As you can see I swapped them out for a less extensive jpeg.

I'll try the file you have linked & am happy to rebuild since the BE install is non-destructive :)
I enabled the loginmanager VNC & could send you a screenshot of the PCDM screen - but it's just your default backdrop image & a mouse pointer... I login by typing blind :(

Switching ttyvs eventually caused a total hang too, but post power removal there was no capture of the screen text that occurred when it happened in messages. :( I'll use a physical camera to capture that if it recurs..

**Comment by TrueBSD** [comment]
Thanks again Joe, that's sorted the black - the issue appears to be that TrueOS & the kernel/driver framework believes that the Intel LVDS-1 is enabled. Since the panel doesn't exist, I can't confirm what the hardware is doing for sure. I'll reboot to 10.3 & see what Xorg thinks is there. ;)

![1](https://cloud.githubusercontent.com/assets/22476758/18954206/ca4da38c-8649-11e6-9687-f03d17380383.png)
[Xorg.0.log.txt](https://github.com/trueos/trueos-core/files/500633/Xorg.0.log.txt)
[Xorg.1.log.txt](https://github.com/trueos/trueos-core/files/500634/Xorg.1.log.txt)

**Comment by TrueBSD** [comment]
Verified in 10.3 - we don't see this issue, nor in 11 afair. KDE is confused for the preload anim but recovers, Lumina has the similar issues to 12 - confusion as to resolution Lumina thinks there are 2 Screens & maintains separate settings for them. They are however displayed on-top of one-another :(
![screenshot 10 3 pcdm](https://cloud.githubusercontent.com/assets/22476758/18955846/f92e89ee-8650-11e6-8558-3d7285ab3862.png)
![screenshot 10 3 lumina1](https://cloud.githubusercontent.com/assets/22476758/18956091/0f8c3bcc-8652-11e6-85f7-f0958e8b25dc.png)
![screenshot 10 3 lumina2](https://cloud.githubusercontent.com/assets/22476758/18956092/117e50dc-8652-11e6-83ff-a41f97df760e.png)

But there is only one display - a ghost of one... This part is a Lumina behaviour which my odd hardware case reveals. :(
![screenshot 10 3 display](https://cloud.githubusercontent.com/assets/22476758/18956191/695e9da2-8652-11e6-9aa4-31b71d8e7c3e.png)

**Comment by TrueBSD** [comment]
Thanks again Joe, that's sorted the black - the issue appears to be that TrueOS & the kernel/driver framework believes that the Intel LVDS-1 is enabled. Since the panel doesn't exist, I can't confirm what the hardware is doing for sure. I'll reboot to 10.3 & see what Xorg thinks is there. ;)

![1](https://cloud.githubusercontent.com/assets/22476758/18954206/ca4da38c-8649-11e6-9687-f03d17380383.png)
[Xorg.0.log.txt](https://github.com/trueos/trueos-core/files/500633/Xorg.0.log.txt)
[Xorg.1.log.txt](https://github.com/trueos/trueos-core/files/500634/Xorg.1.log.txt)

**Comment by TrueBSD** [comment]
[Xorg.0.log.txt](https://github.com/trueos/trueos-core/files/500789/Xorg.0.log.txt)
[Xorg.1.log.txt](https://github.com/trueos/trueos-core/files/500791/Xorg.1.log.txt)

Aside from some verification of some Lumina edge cases, I guess the question is, can we in OSland disable LVDS1 as a configurable sysctrls or config entries/overrides?

Thanks again.

**Comment by TrueBSD** [comment]
xrandr --output LVDS1 --off

Gives all sorts of errors amongst which is:
Sep 29 15:59:34 pcbsd-2279 kernel: error: [drm:pid0:intel_lvds_enable] *ERROR* timed out waiting for panel to power off
Sep 29 15:59:35 pcbsd-2279 kernel: error: [drm:pid0:intel_lvds_enable] *ERROR* timed out waiting for panel to power off

I guess there may not be a way, but it's not just me:
https://forums.freebsd.org/threads/54061/

**Comment by TrueBSD** [comment]
https://forums.pcbsd.org/thread-20994.html looks related too.

**Comment by TrueBSD** [comment]
Now I have more insight into the layers & technology here, I downloaded the 09-29 ISO & re-ran:
1.) Chose the default 1st option: xorg autodetect.
2.) Nasty badly displaying screen texture appears, no branding. Can tell there is a screen to the left but not right by walking the pointer out of sight & back, can't find the window to try to move it, can't find an active fluxbox key binding to do so either. 3-button scroll mouse: left nothing, middle Workspaces menu - nothing here is useful, right Fluxbox default menu - Xterm - console says xterm: command not found Restart - nothing, Exit - fluxbox quits, but X stays,
3.) Ctrl-Alt-2 ttyv1 login root:trueos, kill pc-sysinstall - hmmm X dies & respawns. No Xrandr - can't offline LVDS-1 :(. pc-sysinstall -display :0.0 -geometry +1024+0 & - we have a visible installer on X.
4.) Install works & completes, no error, But no reboot afair - so reboot from ttyv1
5.) First reboot - Grub2 screen background rendered in wrong aspect ratio TrueOS logo is a flaming egg!
6.) No PCDM & it's off to the left of the only screen I have :(.
7.) ttyv1 after some investigating I think xrandr --output LVDS-1 --off & killing PCDM worked, but I couldn't find where to put xrandr to be spawned when X started but before PCDM.
8.) Tried changing the xorg.conf in /etc/X11, but it was ignored & edits removed. Created /usr/local/etc/X11/xorg.conf.d/monitors.conf, used Left-of & Right-of, but that just moved where the headless screen was... :( but this worked:
Section "Monitor"
  Identifier "LVDS-1"
  Option "ignore" "true"
EndSection
9.) I can now see PCDM on that terrible wallpaper - 3.82MB? of https://github.com/trueos/pcdm/pull/1/commits/7941547acc19336b03d35027955215680df59b52 doesn't display properly - TrueOS flaming egg again & makes screenshots *huge* which makes moving the images around a pain & your site bandwidth usage unnecessarily high...
https://www.trueos.org/more-on-trueos/ - 1MB ppv just for the image there...

**Comment by TrueBSD** [comment]
Just used SysAdm Update Manager to update the BE from the 09-29 ISO install.
FB_INFO is now reporting the fb resolution correctly as 1200x1600 & the ttyv# therefore is back to proper full-screen utilisation.

Boot is also noted to be far faster.

**Comment by kmoore134** [comment]
Great! Stay tuned, we have some more boot-speed improvements in the works ;)

**Comment by TrueBSD** [comment]
Oddly the above update removes my monitors.conf from the previous BE - still not sure how...
Installing the 10-14 ISO reverts to a broken console - as before, broken install screens - have to launch another pc-installer with geom offset & create the monitors.conf.
None of this was required under 10.3 or 11-CURRENTs - tested until May.

**Comment by artupmorse** [comment]
install linuxmint,,, lol
