### ISSUE TITLE
Intel Centrino Advanced-N 6235 on TrueOS-Desktop-12.0-CURRENT-08-02-2016

### ISSUE THREAD

**Issue by d3xter** [trueos/trueos-core#7]
Tried to boot the TrueOS-Desktop-12.0-CURRENT-08-02-2016-x64-USB-Image on my Samsung Series 9 Ultrabook.
Everything works fine, except WLAN (and LAN) is not detected.

Running **pciconf -lv** prints:

    iwn0@pci0:1:0:0:    class=0x028000 card=0x40608086 chip=0x088e8086 rev=0x24 hdr=0x00
        vendor   = 'Intel Corporation'
        device    = 'Centrino Advanced-N 6235'
        class      = 'network'

**ifconfig -a** only prints _lo0_

**Comment by d3xter** [comment]
dmesg shows only a single row when grepping for _iwn0_:
    
    iwn0: <Intel Centrino Advanced 6235> mem 0xf0600000-0xf0601fff at device 0.0 on pci1

**Comment by kmoore134** [comment]
How did you try to set it up? On -CURRENT FreeBSD ifconfig doesn't list iwn0 devices anymore. If you look at sysctl -a | grep wlan you should see it, then you can add the various rc.conf glue to create a wlan0 device.

**Comment by d3xter** [comment]
Loading the Firmware and setting up wlan0 inside rc.conf did the trick.

**Comment by kmoore134** [comment]
Which firmware did you load? For future ref, might want to include it in TrueOS by default.

**Comment by d3xter** [comment]
Nevermind ^^ Just tried it again with the same image WITHOUT loading any firmware (last time i had iwn6000fw.ko loaded). Configuring wlan0 inside _rc.conf_ & _wpa_supplicant.conf_ is sufficient to get wlan working and connecting
