### ISSUE TITLE
compile issues

### ISSUE THREAD

**Issue by kmoore134** [trueos/trueos-core#70]
_From @q5sys on August 18, 2016 19:0_

make: "/usr/home/q5sys/git/diligent/diligent/Makefile" line 2074: warning: duplicate script for target "moc_mainapplication.cpp" ignored
make: "/usr/home/q5sys/git/diligent/diligent/Makefile" line 980: warning: using previous script for "moc_mainapplication.cpp" defined here

_Copied from original issue: trueos/diligent#3_

**Comment by kmoore134** [comment]
_From @beanpole135 on August 18, 2016 19:2_

Try running "make clean" first

**Comment by kmoore134** [comment]
_From @beanpole135 on August 18, 2016 19:2_

or "make distclean" and qmake && make again

**Comment by kmoore134** [comment]
_From @q5sys on August 18, 2016 19:5_

That's from a fresh git pull.  I did make clean and make distclean and then did qmake $$ make and the error still persists.  The .pro file doesnt seem to have anything wrong, not sure why the makefile is acting the way it is.

**Comment by kmoore134** [comment]
_From @q5sys on August 18, 2016 19:6_

It will continue to compile and the binary will run if started manually from that directory, but 'sudo make install' will fail with the same error and not properly install the binary and additional files to the correct locations.

**Comment by beanpole135** [comment]
Fixed!
The `plugins/qtwebkit/qtwebkit-plugins.pri` was adding a second copy of the mainwindow.cpp file to the SOURCES declaration. I changed it to the non-duplicating addition instead, so it should silence that error now.

https://github.com/trueos/diligent/commit/5961d83acb68063f7f313dd40e047b63ac830f24
