### ISSUE TITLE
Allow PersonaCrypt to be more user-friendly when force is required to import the pool

### ISSUE THREAD

**Issue by kmoore134** [trueos/trueos-core#71]
_From @grahamperrin on August 23, 2016 0:34_

Enhancement request. 

If – for example – a prior use of the PersonaCrypt device did not end with a clean export, then there should be a more user-friendly way of dealing with the subsequent PCDM-based attempt to log in. 

Ideally: do not require command-line use of the zpool command with the force option. 

Too little knowledge can be a dangerous thing, if the user assumes that force will be OK in all import situations (beyond PersonaCrypt). 

There's a companion issue in trueos/pcdm and it probably makes sense to keep this PersonaCrypt issue separate …

_Copied from original issue: trueos/personacrypt#1_

**Comment by pkgdemon** [comment]
@kmoore134 Fixed in https://github.com/trueos/personacrypt/commit/bcb8b32bcfcc853911f8a9fae32e858bc6b9208f
