### ISSUE TITLE
Do not exemplify saving clear text passphrases to a copy-on-write file system

### ISSUE THREAD

**Issue by kmoore134** [trueos/trueos-core#72]
_From @grahamperrin on August 23, 2016 5:52_

For example, from the manual page: 

> The /tmp/mypassword file has the text-passphrase and will be removed after success.

That's reasonable where a file is _not_ on a CoW file system. 

With CoW ZFS, it can never be best practice to include a password or pass phrase in clear text within a file. 

Please improve personacrypt(8) to allow the pass phrase to be entered dynamically at the command line. 

Similarly, it's not ideal to have an `mycrypt.key` file saved, at any time, to ZFS. 

If that file system is non-encrypted and if both `/tmp/mypassword` and `mycrypt.key` were written, then subsequent removal is not (in itself) a guarantee the contents of the files will be non-scavengable, should both that disk and the PersonaCrypt device fall into the wrong hands e.g. theft. 

The file options might remain, but they should be last resorts. 

Side note: yesterday whilst diagnosing bugs I created [a memory-backed memory disk](https://www.freebsd.org/doc/handbook/disks-virtual.html) to save the required file.

_Copied from original issue: trueos/personacrypt#2_

**Comment by kmoore134** [comment]
_From @grahamperrin on August 23, 2016 6:10_

https://forums.freebsd.org/threads/20345/#post-115663 draws attention to 
`/etc/rc.d/tmp` and [mdconfig](https://www.freebsd.org/cgi/man.cgi?query=mdconfig&sektion=8)(8)

> … `tmpmfs="YES"` creates a ramdisk …

**Comment by Mrt134** [comment]
I've long since taken care of the related doc bug - is there anything left we need to do with this one before closing?

**Comment by Mrt134** [comment]
Closed for inactivity - all related issues appear resolved.
