### ISSUE TITLE
The menu of DPI/resolutions should indicate which menu item is effective

### ISSUE THREAD

**Issue by kmoore134** [trueos/trueos-core#76]
_From @grahamperrin on August 30, 2016 16:14_

Enhancement request, complementary to #1 

There should be a tick/checkmark against whatever is active. 

Without that mark: sometimes when I see the menu, I don't intuitively know whether I'm 'at' medium and need to go 'lower'; or whether I'm at something other than medium and need to switch to medium.

_Copied from original issue: trueos/pcdm#5_

**Comment by grahamperrin** [comment]
From https://discourse.trueos.org/t/96/8

> - High (Tries to set 196 DPI)
> - Medium (Tries to set 144 DPI)
> - Standard (Tries to set 96 DPI)
> - Low (Tries to set 48 DPI)

Thanks. I'd like to see those numbers within the menu. 

The 'tries to set' aspect can be covered in the user guide; need not appear within the menu. 

----

(More broadly, I'd like these important options to be upfront, not obscured within a power menu. Food for thought for if/when the PCDM screen is reshaped.)

**Comment by beanpole135** [comment]
Done!

https://github.com/trueos/pcdm/commit/8e2b52d134dadb1ca800182be5c67564f0a1ee26

**Comment by grahamperrin** [comment]
In the context of https://github.com/trueos/trueos-core/issues/192 this is not properly fixed. 

Four resolutions. Changes away from a system-pre-selected resolution are possible, but the menu never changes to show which one of the three is effective (and #192 prevents reuse of the one resolution that was pre-selected).
