### ISSUE TITLE
Inconsistant wording on final screen of installer.

### ISSUE THREAD

**Issue by kmoore134** [trueos/trueos-core#77]
_From @xzovy on September 1, 2016 22:35_

On the last screen of the installer, it tells the user to "Click Finish to reboot." However, there is no "Finish" button, only "Save Config to USB", "Abort" and "Exit". I think standardizing on "Finish" would be best since it implies completion, while "Exit" and "Abort" could be confused.

_Copied from original issue: trueos/trueos-utils-qt5#8_

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/trueos-utils-qt5/commit/86930761657e27bbbfd40d4f8545d68b71ca7b37
