### ISSUE TITLE
Sound setting in Installer - fix interrupts

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/trueos-core#8]
On my 2 Intel NUCs sound plays fine on TrueOS/FreeBSD only with setting: # sysctl dev.hdac.0.polling=1 and dont play with setting by default. May be this is strange situation with interrupts on FreeBSD driver. And I am find the same problem in another FreeBSD hardware users. But no this problem on DragonFly BSD and Linux.

And  in TrueOS Installer, when sound is tested: result --> no sound. May be it is correct to test standart sound mode, but if sound not played, then try to set: # sysctl dev.hdac.0.polling=1 (edit: /etc/sysctl.conf --> dev.hdac.0.polling=1) and if user has listen the sound then make this new setting to /etc/sysctl.conf.

**Comment by pkgdemon** [comment]
Can you provide the output of cat /dev/sndstat, pciconf -lv, and also motherboard information?

**Comment by DmitryPostolov** [comment]
2 pages log: https://yadi.sk/i/8JnXZ8FstzSK4

**Comment by pkgdemon** [comment]
I see where this is valid to set this option when a device is unable to generate interupts.  That appears to be the main purpose of the sysctl.  

http://www.unix.com/man-page/freebsd/4/snd_hda/

I've set it on my system which had working sound, and it has not caused any issues.  I am tempted just to set it default.  Let me discuss further, and see what other options we may have to impliment this.

**Comment by DmitryPostolov** [comment]
> I've set it on my system which had working sound, and it has not caused any issues.

pkgdemon, my NUC DN2820FYKH has no errors on physical console with this setting, but in NUC5PPYH the error message on screenshot. But the sound plays fine with # sysctl dev.hdac.0.polling=1 on both NUCs.

![sound](https://cloud.githubusercontent.com/assets/20837310/18409979/9c3cfe42-7777-11e6-93f8-cb52faa8c5cf.png)

**Comment by pkgdemon** [comment]
We have added an option to enable this sysctl at the services menu post install.  Although it does not provide the user a way to enable it in the mixer settings window it does give a way to enable it for now.  

https://github.com/trueos/trueos-core/commit/c9f188e05ab3ef0204db7fae40279f97c6703b0b
