### ISSUE TITLE
Scfb driver dont works with TrueOS, but works with FreeBSD

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/trueos-core#83]
TrueOS image 2016-09-29. Nettop Intel NUC5PPYH CPU Intel N3700 HD Graphics. If to select in installation menu item "scfb driver", then Installer after few seconds to return to the console installation menu and graphical installer dont starts.

On FreeBSD 11.0-RC3 scfb driver successfully works in UEFI mode with this NUC5PPYH with wiki-settings.

Maybe problem is here: TrueOS works in none-UEFI mode for scfb driver?

**Comment by DmitryPostolov** [comment]
I am sorry for my mistake. This problem with NUCs was that PCs are booted TrueOS installer on none-UEFI mode and I am try to start "scfb" graphic installer in this none-UEFI mode . In UEFI mode "scfb" driver installer successfully works and after reboot I can load TrueOS.

But one problem: on my Intel HD graphics UEFI loader and system starts with by default console resolution "1280x1024" until manually to press ESC in loader and enter a command "mode 0" and "boot". In "mode 0" console and in next graphic resolution is 1920x1080.

How I can add the setting "mode 0" to /boot/loader.conf or another conf loader file for auto load FullHD mode? If to add "mode 0" or "mode set 0" or 'mode="0"' then no result, screen console resolution also 1280x1024.

**Comment by kmoore134** [comment]
where are you entering the 'mode 0' command? In the BSD loader, or EFI loader somewhere? I know EFI has its own 'efivars' settings, might need to go there instead of loader.conf

**Comment by DmitryPostolov** [comment]
I am enter 'mode 0' in BSD loader after press ESC.
![screenshot1](https://cloud.githubusercontent.com/assets/20837310/19331827/c996828c-9108-11e6-94f3-b9d52146fcb3.png)
![screenshot2](https://cloud.githubusercontent.com/assets/20837310/19331835/d0f54162-9108-11e6-9a2b-1a0d457a195a.png)

**Comment by kmoore134** [comment]
Looks like some FreeBSD users having similar issues here:
https://forums.freebsd.org/threads/53150/

I'm not seeing anything obvious on how to set it in loader.conf. Maybe something in /boot/device.hints? I'm going to close this as it seems more of a FreeBSD issue. If you find a solution though, please update the ticket.

**Comment by DmitryPostolov** [comment]
The problem is [SOLVED].

Problem was here: I am installed FreeBSD at GPT (UEFI) mode, this is not by default Installer mode and probably with this setting the problem with auto-setting "mode 0" or "gop set 0" in /boot/loader.rc.local is observed. Now I install FreeBSD with by default setting: GPT (Bios + UEFI) in Installer, then all OK and after add "mode 0" to /boot/loader.rc.local screen resolution is 1920x1080 in auto-mode.

Thanks! Now is all OK!
