### ISSUE TITLE
TrueOS not loading MSI AMD Radeon firmware

### ISSUE THREAD

**Issue by johnnyktester** [trueos/trueos-core#84]
I have tried installing every build since PCBSD11.x and none so far has worked with my MSI AMD Radeon r9 270x hardware.  So below is the dmesg output

~% dmesg |grep radeon
[drm] radeon kernel modesetting enabled.
[drm] radeon: 2048M of VRAM memory ready
[drm] radeon: 2048M of GTT memory ready.
radeon/pitcairn_pfp.bin: could not load firmware image, error 2
radeon/pitcairn_pfp.bin: could not load firmware image, error 2
radeon/pitcairn_me.bin: could not load firmware image, error 2
radeon/pitcairn_me.bin: could not load firmware image, error 2
radeon/pitcairn_ce.bin: could not load firmware image, error 2
radeon/pitcairn_ce.bin: could not load firmware image, error 2
radeon/pitcairn_rlc.bin: could not load firmware image, error 2
radeon/pitcairn_rlc.bin: could not load firmware image, error 2
radeon/pitcairn_mc.bin: could not load firmware image, error 2
radeon/pitcairn_mc.bin: could not load firmware image, error 2
radeon/pitcairn_smc.bin: could not load firmware image, error 2
radeon/pitcairn_smc.bin: could not load firmware image, error 2
[drm] radeon: dpm initialized
radeon/TAHITI_uvd.bin: could not load firmware image, error 2
radeon/TAHITI_uvd.bin: could not load firmware image, error 2
drmn0: failed to load firmware image radeon_TAHITI_uvd_bin
drmn0: radeon_uvd: Can't load firmware "radeon/TAHITI_uvd.bin"
radeon/TAHITI_vce.bin: could not load firmware image, error 2
radeon/TAHITI_vce.bin: could not load firmware image, error 2
drmn0: failed to load firmware image radeon_TAHITI_vce_bin
drmn0: radeon_vce: Can't load firmware "radeon/TAHITI_vce.bin"
[drm] enabling PCIE gen 3 link speeds, disable with radeon.pcie_gen2=0
drmn0: radeon: MSI limited to 32-bit
drmn0: radeon: using MSI.
[drm] radeon: irq initialized.
[drm:0xffffffff82aeccc1s] *ERROR* radeon: ring 0 test failed (scratch(0x850C)=0xCAFEDEAD)
drmn0: fb0: radeondrmfb frame buffer device
[drm] Initialized radeon 2.45.0 20080528 for drmn on minor 0
[drm] radeon kernel modesetting enabled.
[drm] radeon: 2048M of VRAM memory ready
[drm] radeon: 2048M of GTT memory ready.
radeon/pitcairn_pfp.bin: could not load firmware image, error 2
radeon/pitcairn_pfp.bin: could not load firmware image, error 2
radeon/pitcairn_me.bin: could not load firmware image, error 2
radeon/pitcairn_me.bin: could not load firmware image, error 2
radeon/pitcairn_ce.bin: could not load firmware image, error 2
radeon/pitcairn_ce.bin: could not load firmware image, error 2
radeon/pitcairn_rlc.bin: could not load firmware image, error 2
radeon/pitcairn_rlc.bin: could not load firmware image, error 2
radeon/pitcairn_mc.bin: could not load firmware image, error 2
radeon/pitcairn_mc.bin: could not load firmware image, error 2
radeon/pitcairn_smc.bin: could not load firmware image, error 2
radeon/pitcairn_smc.bin: could not load firmware image, error 2
[drm] radeon: dpm initialized
radeon/TAHITI_uvd.bin: could not load firmware image, error 2
radeon/TAHITI_uvd.bin: could not load firmware image, error 2
drmn0: failed to load firmware image radeon_TAHITI_uvd_bin
drmn0: radeon_uvd: Can't load firmware "radeon/TAHITI_uvd.bin"
radeon/TAHITI_vce.bin: could not load firmware image, error 2
radeon/TAHITI_vce.bin: could not load firmware image, error 2
drmn0: failed to load firmware image radeon_TAHITI_vce_bin
drmn0: radeon_vce: Can't load firmware "radeon/TAHITI_vce.bin"
[drm] enabling PCIE gen 3 link speeds, disable with radeon.pcie_gen2=0
drmn0: radeon: MSI limited to 32-bit
drmn0: radeon: using MSI.
[drm] radeon: irq initialized.
drmn0: fb0: radeondrmfb frame buffer device
[drm] Initialized radeon 2.45.0 20080528 for drmn on minor 0

I hope this helps.  This may be the cause that PCDM load the VESA driver for these cards.

**Comment by johnnyktester** [comment]
Adding PCI information about the card.  I am not sure if it will help

ath0@pci0:3:0:0:        class=0x028000 card=0x3112168c chip=0x0030168c rev=0x01 hdr=0x00
    vendor     = 'Qualcomm Atheros'
    device     = 'AR93xx Wireless Network Adapter'
    class      = network
vgapci0@pci0:4:0:0:     class=0x030000 card=0x30331462 chip=0x68101002 rev=0x00 hdr=0x00
    vendor     = 'Advanced Micro Devices, Inc. [AMD/ATI]'
    device     = 'Curacao XT / Trinidad XT [Radeon R7 370 / R9 270X/370X]'
    class      = display
    subclass   = VGA
none1@pci0:4:0:1:       class=0x040300 card=0xaab01462 chip=0xaab01002 rev=0x00 hdr=0x00
    vendor     = 'Advanced Micro Devices, Inc. [AMD/ATI]'
    device     = 'Cape Verde/Pitcairn HDMI Audio [Radeon HD 7700/7800 Series]'
    class      = multimedia
    subclass   = HDA

**Comment by pkgdemon** [comment]
Unfortunately this is a known issue with ATI cards.  Please file a report about this over here:

https://github.com/FreeBSDDesktop/freebsd-base-graphics/issues

This is where we get our graphics stack from that is affecting your ATI setup.  Stock FreeBSD should not be affected by this.
