### ISSUE TITLE
net/vtun

### ISSUE THREAD

**Issue by pkgdemon** [trueos/trueos-core#848]

**Comment by ZackaryWelch** [comment]
https://github.com/trueos/freebsd-ports/commit/0b335ead7133b60482ef85616cbd200780985b8e

**Comment by ZackaryWelch** [comment]
Needs testing.

**Comment by ZackaryWelch** [comment]
https://github.com/trueos/freebsd-ports/commit/98073b4a26bafb9dbcb120e363dbe2a2a19e92bb
