### ISSUE TITLE
Misuse of the word 'zpool' in TrueOS Disk Wizard, in TrueOS Text Install - Edit Menu and in Life Preserver

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#85]
Please do not use the word zpool (a command) to describe a pool. 

Reference: https://github.com/illumos/illumos-gate/commit/c8323d4323a565676ba44883bfeb289d9ed8813e 

> … in the manual page for zpool(1M), one misuse of the word 'zpool' to describe a pool
> Reviewed by: Matthew Ahrens …

A corresponding issue in trueos-docs/issues will draw attention to points where the word is misused. 

Thanks

**Comment by pkgdemon** [comment]
Fix in https://github.com/trueos/trueos-core/commit/b4c92b13eed28ed550bc63257fde758a58489b10

@beanpole135 is taking care of the QT apps this morning.

**Comment by beanpole135** [comment]
Disk manager was fixed in https://github.com/trueos/pc-diskmanager/commit/fa4bfe9d737fcabb0bffc8dae9440b6805be01e3
I could not find any references to "zpool" within the Life Preserver Interface, so I think we should be good to go now.
