### ISSUE TITLE
TrueOS Xorg Fails to Install / Blank Screen on Nvidia GTX 1070

### ISSUE THREAD

**Issue by Proclus1488** [trueos/trueos-core#88]
Both TrueOS and PCBSD 10.2 & 10.3 fail to install on my system with either Nvidia GTX 1070 or GTX 760. A blank white screen appears shortly after the Xorg graphical installer is initiated; the text installer completes without issue but upon startup the white screen appears almost immediately. The issue seems to be related specifically to Xorg's Nvidia drivers as both operating systems install and operate fine under Intel's Integrated Graphics. 

I don't know if there's anything you guys can do to solve the issue but I figure its worth you knowing about and please forgive me if I haven't provided enough information; I don't normally write bug reports and I'm unfamiliar with the proper etiquette in doing so. 

System Specs:
Motherboard: Gigabyte LGA 1150 Intel Z97N Mini ITX
Memory: Crucial Ballistix Sport 16GB 1600 Mhz
CPU: Intel Core i7-4790K
GPU: Nvidia GTX 1070
HDD: Seagate Hybrid Drive ST1000DX001 1TB
Monitor: ASUS PB277 1440p

**Comment by TheDharc** [comment]
Same here with 940m. It's because of Optimus, we don't have bumblebee :/

**Comment by pkgdemon** [comment]
@Proclus1488 When starting the installer with "Auto-detect" do you notice if the detection mentions "Optimus detected", or "Using intel graphics"?

**Comment by pkgdemon** [comment]
Closing due to lack of needed information to further diagnose.

**Comment by TheDharc** [comment]
Where is the auto-detect option?  The installer here always use scfb.

**Comment by TheDharc** [comment]
It starts with modesetting driver. The expected would be intel and/or nvidia, isnt?
