### ISSUE TITLE
brigtness keys stop working after wake (on 2 different laptops)

### ISSUE THREAD

**Issue by tHubig** [trueos/trueos-core#90]
After waking a system which was put to sleep with `acpiconf -s 3`,
the brightness keys no longer function. This was working (on both laptops) up until the last update. ~Sept 29-30, I think. (I test drive Lumina, but mostly use MATE DE.)
Same issue on both Thinkpad X201 Arrandale i7 and System76 i7 Kudu Haswell HD4600 laptops.

sysctl can fix it, however the brightness sometimes is initially maxed out at wake up, regardless of what hw.acpi.video.lcd0.brightness is set to:

> sysctl -a | grep hw.acpi.video.lcd0.brightness
> hw.acpi.video.lcd0.brightness: 6
> sysctl hw.acpi.video.lcd0.brightness=6

The second sysctl command dims the screen, even though it has not changed the value.

**Comment by tHubig** [comment]
I keep both my systems on the bleeding edge. Things have gotten slightly worse. Now the Haswell laptop only sleeps once or twice. On the (usually third) failed attempt, there is intense disk activity and it just stays awake. 

On the thinkpad, sleep still works reliably but brightness is hit or miss. Also, I didn't notice this until a few days ago, but the screen does not switch off when blank...it is black but illuminated still. 

On both systems, sysctl always works and brightness keys stop working after wake up.

I'm accustomed to display power management weirdness and hit-or-miss suspend from years of using Linux, so no big deal.

Nevertheless, I will grasp at a few straws:

Since upgrading from PC-BSD 10.3, I see a lot of signal 10 in dmesg, usually right when applications mysteriously die. Firefox and pc-mixer are the most noticeable.

Sound works on both sytems, but on the Haswell system dmesg has a lot of this:
`hdac0: Command timeout on address 0
  hdac0: Reset setting timeout`

**Comment by kmoore134** [comment]
These kind of issues should be reported upstream to FreeBSD if possible. The sound issue sounds like a possible regression / bug in snd_hda. But as to suspend/resume, that's anybodies guess. We don't particularly have folks in-house to debug that.
