### ISSUE TITLE
xserver/Lumina crash loop after update

### ISSUE THREAD

**Issue by rostwald** [trueos/trueos-core#93]
After updating the system via SysAdm Update Manager (last update/BE @ September 17th), xserver/Lumina won't start. The Screen keeps getting blank and switching off in an endless loop, falling back to console for a fraction of a second before next attempt.

In /var/log/messages the following errors are logged each time:
 `devd: notify_clients: send() failed; dropping unresponsive client`
 `kernel: pid 1475 (PCDM-session), uid 0: exited on signal 6`

In /var/log/Xorg.0.log:
`[    53.357] (WW) config/devd: devd socket is lost`
`[    53.358] (EE) config/devd: fail to connect to devd`

Device section in xorg.conf (auto-generated):
`Section "Device"`
`Identifier  "Card0"`
`Driver      "modesetting"`
`Option      "AccelMethod"               "none"`
`Option      "SWcursor"                  "true"`
`EndSection`

System is a Laptop with Intel i7 4500U (Haswell) / HD 4400 Graphics.

Reverting back to latest BE from September 17th and running updates again reproduces the problem. Updates are applied without reported errors.

**Comment by pkgdemon** [comment]
This should be resolved.  Please try the latest updates, and let us know if it still fails.

**Comment by rostwald** [comment]
Yes, this was resolved with the subsequent wave of updates. Thanks.
