### ISSUE TITLE
trueos/sysadm: personacrypt user creation fail

### ISSUE THREAD

**Issue by Mrt134** [trueos/trueos-core#95]
Using SysAdm User Manager to create a new user with PersonaCrypt results in a message saying "Error: Could not create user". It also fails to adjust a user account (with the same error) previously created without PersonaCrypt.

**Comment by grahamperrin** [comment]
This is reminiscent of https://gitter.im/trueos/Lobby?at=57f8dc8e84f1db0614921d3f , which preceded [the most recent push of packages to udpate servers](https://builds.ixsystems.com/jenkins/view/Push/job/TrueOS%20-%20Push%20Pkgs/27/). 

Please apply updates, restart and then tell whether the bugs are reproducible. Thanks.

**Comment by Mrt134** [comment]
Went back for additional testing, system fully up-to-date. PersonaCrypt appears to be working now. Thanks!
