### ISSUE TITLE
TrueOS Desktop installation fails at the very end.

### ISSUE THREAD

**Issue by muten85** [trueos/trueos-core#97]
[trueos-install-debug.zip](https://github.com/trueos/trueos-core/files/530747/trueos-install-debug.zip)

Hi, it's a bit strange but my installation of TrueOS desktop fails at the very end (during file clean-up or right after). Details are in the attached log file. Can someone shed some light on what's happening? It's very odd since I am using a very "automatic" installation on a standard laptop.

Thank you...

**Comment by pkgdemon** [comment]
Please try a newer installer image, and let us know if this is still happening.  Also if you are trying a USB 3.0 port it may be helpful to try an older USB 2.0 port if was is available.

**Comment by muten85** [comment]
Hello,

Tried the 10-28 USB image and the same happens. I only have 3.0 USB connectors on my computer. Could the issue be related to the software I use to burn the image? (doubt it...)

Anyways I will wait for a new release. Too bad. I was willing to start translating in French.

Thank you...
